### ISSUE TITLE
Intelligent location of Polygon Labels

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1000]
Some of our Natural Earth polygon shapes have text labels.

But, the datasets don't include a location for the label.  We currently just plot the label at the geographic centre of the shape.

QGis has an improved way of doing this.  QGis puts the label at the centre of the currently visible part of the polygon.

In this example, all of Madagascar is visible, so the label is in the centre:
![mad_centre](https://cloud.githubusercontent.com/assets/1108513/5469523/93887d8a-85d4-11e4-8297-c88555bc55ca.png)

In this example, only the Southern tip is visible, so the label is positioned at the centre of the visible portion:
![mad_south](https://cloud.githubusercontent.com/assets/1108513/5469529/9999535c-85d4-11e4-93b9-a8e673f1d7fe.png)

**Comment by pecko** [comment]
The Geotools engine handles this feature correctly. I think we can close this issue.

**Comment by IanMayo** [comment]
Yes, GeoTools is handling it beautifully :-)
