### ISSUE TITLE
Experiment with filtering which ShapeFile features to load according to bounding box

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1014]
(this a performance consideration for when we have got our architecture sorted)

We currently load the whole globe of ShapeFile data (well, we actually trim a little off the edges):
https://github.com/debrief/debrief/pull/1011/files#diff-0e7c793c71cf579c6bcaa313d44a7a57R160

But, instead, we could filter the features according to the currently visible viewport:
Filter filter = ECQL.toFilter("BBOX(the_geom, -10.34, 7.7, -9.33, 7.8)");

We will have to find out if this is a performance improvement or not, according to these factors:
* in the current import, we import the whole earth, and we just do it once
* with a viewport specific import, it *may* be quicker
* but. the GeoTools rendering may only bother plotting the currently visible entities anyway
* plus, if we only import data that is in the restricted view, we may miss some features.

**Comment by IanMayo** [comment]
@pecko  just said:

````
BTW I think that we solve https://github.com/debrief/debrief/issues/1014 
- Experiment with filtering which ShapeFile features to load according to
 bounding box  Geotools handles viewport correctly and the latest commits 
solve this
````

So you *do not* think we need to investigate using a BBOX filter on the features?

**Comment by pecko** [comment]
I think no. Geotools paints only visible part and plot operations are fast when viewport is small.

**Comment by IanMayo** [comment]
I'm sure you're right.

I'd like to keep this open a bit longer until we've done some more playing with the data.  This *could* represent a good performance boost.
