### ISSUE TITLE
Natural Earth - move away from setMap usage

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1016]
The existing GeoTools layers use setMap to trigger loading data, and to add themselves to the parent mapContent.  This only happens once - as the layer is loaded.

In our NaturalEarth implementation we're re-using setMap for each layer refresh.  This may unfortunately cause our existing GeoTools layers (images & shapefiles) to re-load & reconfigure more than is necessary.

So, I think that our NaturalEarth implementation should not overwrite the setMap behaviour, but should use an alternate (or new method).

The new method should probably do something like this:

* are we hidden?
    * yes - return
* find the current scale group
* is it different to the previous one?
    * remove previous features/layers from map
    * loop through new features
    * is it loaded from file?
        * no - load from file
    * add to map

The benefits of this are:
* we leave the logical flow of the existing GeoTools layers unchanged
* we only load each feature from file once
* we minimise adding/removing layers from the GT MapContent

**Comment by pecko** [comment]
The commit https://github.com/pecko/debrief/commit/02a11fc94e35b3e2cfafafd19f0ccbce67e16b82 move away setMap when repainting plot.

Now setMap (configureLayers) is called:

- when opening NELayer first time
- when some property is changed (resolution, show Polygons/Lines/Points/Labels, change color, font ...
We have to reconfigure a layer when style (sld) is changed.

I think that it need a little more reviewing (especially related to disposing; IMO geotools map and layers aren't disposed correctly in old code too), but you can review in the morning.

**Comment by IanMayo** [comment]
@pecko , in my opinion we need to refactor further, since setMap has a hidden behaviour (deciding on what resolution of data to show).

I'll have a play.

**Comment by pecko** [comment]
OK. I will make it that only corresponding layer is reconfigured when a property is changed.

**Comment by IanMayo** [comment]
Now, Debrief configure all datasets within resolution no matter if they are visible.

This seems a mistake, they Bathy datasets are quite large. It's an unnecessary delay to load them if we start with a zoomed out view of the world.

````
Now setMap (configureLayers) is called:

1. when opening NELayer first time
2. when resolution is changed
3. when some property is changed (resolution, show Polygons/Lines/Points/Labels, change color, font
4. We have to reconfigure a layer when style (sld) is changed.
````

This seems wrong. I think we should only call setMap for 1.  The re-configure that we do for 2-4 should be in a separate reconfigure method.  That method will get called from within setMap.

I've just pushed a version with some comments: https://github.com/pecko/debrief/commit/24ea47d682aa387017b8f8b80188908e25a31b4d

**Comment by pecko** [comment]
> This seems a mistake, they Bathy datasets are quite large. It's an unnecessary delay to load them if we 
> start with a zoomed out view of the world.

Geotools will not load/read features until need paint it.

**Comment by IanMayo** [comment]
Geotools will not load/read features until need paint it.

Sure, but we do seem to do a lot of object allocation & generation (lines 162-202):
https://github.com/pecko/debrief/blob/24ea47d682aa387017b8f8b80188908e25a31b4d/org.mwc.cmap.NaturalEarth/src/org/mwc/cmap/naturalearth/wrapper/NELayer.java#L162

**Comment by pecko** [comment]
Let me know that introduce "only corresponding layer is reconfigured when a property is changed". After that we can optimize setMap more.

**Comment by pecko** [comment]
I think we can close this issue.

**Comment by IanMayo** [comment]
closed.
