### ISSUE TITLE
Tidy paint loop 

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1023]
The paint loop currently includes setMap() calls:
https://github.com/pecko/debrief/commit/339f27fafc7965f614cd18b264d4aa9bf0c74639#diff-1b50834cc5eae3de3505f45723dd6206R1352

These calls are intended to allow a Debrief Layer to add/remove itself from the GeoTools MapContent.

We're using them to let the NELayer class change the selected resolution, but that shouldn't be done in the setMap call.

Maybe we use the initial setMap() to store the map as a class field, then the update() method calls another NELayer specific that decides scale and adds/removes layers as necessary.

**Comment by pecko** [comment]
I think that we solve this within https://github.com/debrief/debrief/issues/1016
