### ISSUE TITLE
NE - missing black pixels in Tiff image

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1028]
[Ian has moved this out of #984 ]

Here is a screenshot from 20140602 Stable release:
![juneversion](https://cloud.githubusercontent.com/assets/1108513/5682147/cfc2df36-9815-11e4-90ef-9c4894faf815.png)

Here is a screenshot from the 20141003 release:
![octbuild](https://cloud.githubusercontent.com/assets/1108513/5682355/440044f0-9817-11e4-81a8-a80de189f935.png)

Here is screenshot *with* NE data in the background for the current #984 branch:
![rasterok](https://cloud.githubusercontent.com/assets/1108513/5682161/e1425bf6-9815-11e4-93e3-f47bb1207651.png)

And here is a screenshot *without* NE in the background for the current #984 branch:
![rasterholes](https://cloud.githubusercontent.com/assets/1108513/5682166/ed2589f2-9815-11e4-9bae-bb03a6468fb6.png)

This problem isn't associated with NE.  It's been in Debrief for a few months.  But, it seems significant that the problem goes away when we're displaying an NE backdrop.

**Comment by pecko** [comment]
I think that NE paint borders. It means that NE and TIF projections are correct.

**Comment by IanMayo** [comment]
The change happened between June and October (see first two screenshots).

**Comment by pecko** [comment]
I have seen the issue when using the 20140523_3.0.295 release. Will try to find what is the issue.

**Comment by pecko** [comment]
The issue is Linux specific. I have introduced the issue by fixing #651 
It works fine on Windows and Linux.

@IanMayo Please advice what to do?

I think that we don't need to do anything. The users use Windows and will not face issue and we know what is the problem and painting background in other plots is more important than this issue.

Other solution is revert fix from #651

**Comment by IanMayo** [comment]
"music to my ears". 

If/when we get unix users we'll come back to this.

**Comment by pecko** [comment]
We can add preference so Linux users can control what she/he want: paint background or TIF image.
Anyway, seem minor issue. Agree?

**Comment by IanMayo** [comment]
No, we'll have to do a "big push" if/when we get Linux users.
