### ISSUE TITLE
Need to plot Text labels in points layer

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1029]
Julie extract the ocean and sea labels from Polygon files (110M_geography_marine_polys) into their own Point files.

This was so that we could just have an "Ocean" layer, and not store/draw the Polygons for the named marine polys.  

110M_geography_marine_polys works fine.  But I wish to avoid using it.  I wish to just use the ocean_labels and sea_labels files.  Marine_polys:
![marine_polys](https://cloud.githubusercontent.com/assets/1108513/5682942/c00c9ef0-981b-11e4-8e71-7c46eeaa6a52.png)

But, the rendering for these doesn't seem to work:
![ocean_sea_labels](https://cloud.githubusercontent.com/assets/1108513/5682948/c64111d4-981b-11e4-8c76-b0aa3db12dd0.png)

Could you investigate it?

**Comment by pecko** [comment]
Fixed by https://github.com/pecko/debrief/commit/0a0b77b68f3f59e16a6e2d5eb7d698f594b1d9b2
