### ISSUE TITLE
Small improvements to text labels

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1030]
I've tried to update the styles to match the QGis ones.  My updates are in the issue984_more_styling PR.

Here is the QGis countries:
![qgis countries](https://cloud.githubusercontent.com/assets/1108513/5684039/ef2a6182-9824-11e4-9bf3-b4d399dababb.png)

And here is them in Debrief:
![debriefcountries](https://cloud.githubusercontent.com/assets/1108513/5684044/f356aad6-9824-11e4-8578-bd83da39d0dc.png)

We need to change our style creators to use the color from the Style.  The country names are provided in the 50m_admin_0_countries layer.

I can also see a small white "point" marker in the centre of each country name.  But, I can't see how we delete it.

**Comment by pecko** [comment]
https://github.com/pecko/debrief/pull/7 has been merged.

> We need to change our style creators to use the color from the Style

You mean font color?

Now the bathy datasetsare visible only on some resolutions.

**Comment by IanMayo** [comment]
Yes, the getTextColor() method from the NEFeatureStyle

**Comment by IanMayo** [comment]
Bathy - I've temporarily switched if off for the 50M resolution, to see if that works ok. It will make a great performance improvement.

**Comment by pecko** [comment]
https://github.com/pecko/debrief/pull/8 merged.

> Yes, the getTextColor() method from the NEFeatureStyle

Will check.
We should refactor NEFeatureStyle so it suits better to SLDs.

> Bathy - I've temporarily switched if off for the 50M resolution, to see if that works ok. It will make a 
> great performance improvement.

It works, but it is hard set it so bathy layer is visible when I want that.

**Comment by IanMayo** [comment]
Good suggestions

**Comment by pecko** [comment]
> Yes, the getTextColor() method from the NEFeatureStyle

Fixed with https://github.com/pecko/debrief/commit/06464496e99adfc6072edb355877d070eabd1b4d
Screenshot:
![fontcolor](https://cloud.githubusercontent.com/assets/534584/5684757/ce9f8aa0-9833-11e4-9dd3-c5b8d4799e70.png)

**Comment by IanMayo** [comment]
nice work. getting closer, getting closer...

**Comment by pecko** [comment]
yet one:
![scr](https://cloud.githubusercontent.com/assets/534584/5684898/88382a98-9835-11e4-96d3-1157260893db.png)

**Comment by IanMayo** [comment]
Oh God, my eyes! my eyes!  I'm blinded!

Needs a little more work (next week).
