### ISSUE TITLE
Strange NE lag issue

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1034]
[@pecko - this issue isn't a big deal for me. I'm just creating an issue as a place to store the images.  But, I think what I've experienced may teach us something about GeoTools rendering performance]

I've got a 50M resolution dataset, with just the 50M_Ocean layer visible:
![50m_res](https://cloud.githubusercontent.com/assets/1108513/5707568/c796497e-9a81-11e4-8bf3-f55b5c4dad99.png)

At 10M resolution, with all of the layers visible, the performance is quicker:
![10m_res](https://cloud.githubusercontent.com/assets/1108513/5707571/cceac260-9a81-11e4-9a75-99bf2784d494.png)

As you can see from the screenshots, at 50M we've just got the single set of Ocean polygons to draw.  But, at 10M, we've several layers of Bathy polygons, plus the coastline, plus the land.  That's a lot more data.

But, 10M is showing better performance.

I wonder if the "switched off" 50M layers are still bringing some performance penalty.

**Comment by pecko** [comment]
I think that Geotools optimizes painting in view port. You probably has less features (points, polygons, lines, labels ...) on screen when you see better performance, because geotools filters features out of view port.


In any way, I can see better performance when zooming in.

**Comment by IanMayo** [comment]
Close, OBE.
