### ISSUE TITLE
SATC performance graph is adjacent bars, not stacked bars

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1035]
The performance graph is meant to show stacked bars.  Stacked bars are good for showing the cumulative errors through a solution.

But, sometimes today it is showing adjacent bars:
![screen shot 2015-01-13 at 15 02 11](https://cloud.githubusercontent.com/assets/1108513/5722588/497638ce-9b35-11e4-882a-95dce399a827.png)

**Comment by IanMayo** [comment]
@pecko  - I'll push this to you, please.

If you've forgotten how to get SATC to run, #647 includes some tips.

**Comment by pecko** [comment]
Does it urgent?

**Comment by IanMayo** [comment]
no, not urgent. But, next week sometime would be nice.

**Comment by pecko** [comment]
OK. Hoping will be ready.

**Comment by IanMayo** [comment]
Aah, this is how they should look:
![stacked](https://cloud.githubusercontent.com/assets/1108513/5394739/dd36cf0e-8138-11e4-8490-3062503680cc.png)

**Comment by pecko** [comment]
@IanMayo Could you, please, attach plot file you are using?

**Comment by IanMayo** [comment]
Sure, try using ````thirty_min_earlier_first_turn.dpf````

Open Maintain Contributions, and click on ````121200```` in the Outline view.  The Maintain Conts view will get populated.  Then click on "Calculate Solution" at the top of the Maintain Contributions view.

**Comment by IanMayo** [comment]
D*mn, it's working fine now.  I'll have to wait until I can find a reproducible scenario.

**Comment by pecko** [comment]
There are two issues here:

- the PR https://github.com/debrief/debrief/pull/978 hasn't applied to the master
- the PR only work for two series chart

I have created the new PR (against master): https://github.com/debrief/debrief/pull/1066

**Comment by IanMayo** [comment]
Merged.
