### ISSUE TITLE
NELayer silently failing if folder location unset

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1036]
We've discussed this already.

If we try to add Natural Earth layers without the folder being set in the preferences then Debrief silently fails.  (a message is written to the console, but nothing to the user)

We discussed popping up a message to tell the user. Peco was also going to add a link to the prefs page in the dialog box.

**Comment by IanMayo** [comment]
Hmm, maybe the processing for this could be better.

We need to produce a strategy for how the data is distributed.  If I can, I'd quite like to distribute at least the 110M resolution set with Debrief.

Debrief is currently around 170Mb.  If we can include a useful full set of data for 200Mb, then that would seem ok.  That's a task for me to do within the SLD/styling work.

Maybe Debrief could check which data plugins are present, and offer applicable resolution options.

**Comment by pecko** [comment]
@IanMayo 
I propose that we add all datasets (maybe slds) in a separate github repository. 
After that we can add it to the distribution or download it when a user start Debrief (or NE Layer) first time.
Tycho can handle data from more git repositories.

The proposal is here because the Debrief is almost too big repository on github

**Comment by IanMayo** [comment]
Aah yes, of course - build size.

Unfortunately the online download option isn't available to us, since my users don't normally have an Internet connection.

We'll have to continue to distribute the data separately to Debrief.  Well, until Travis include the build memory.

**Comment by pecko** [comment]
We just need to be care when adding bigger files to the Debrief repository.

**Comment by IanMayo** [comment]
Yes.  But, where is the memory limit hitting us?

* the total size of the Git repo
* the size of the zip files that we build in the final stages.

**Comment by pecko** [comment]
There are two constraints (IMO, they are disk constraints):

- github repository (I think 1GB)  
- travis overall disk space (there is a constraint, but isn't exactly specified; IMO, it is cca 3-4GB)

We are close for both constraints although we haven't face github constraint yet.

**Comment by IanMayo** [comment]
Problem avoided with new NE strategy.
