### ISSUE TITLE
Refactor NELayer to use more GeoTools standard processing

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1043]
Our initial Natural Earth integration has focussed on importing the data and letting Debrief plot the data.  We've also styled the data using Debrief, to avoid having to write SLD to Debrief transformation code.

But, we had troubles accessing the data, and associated rendering performance.

So, letting GeoTools do the data management and rendering has proven more effective.

We have been letting Debrief handle the NE Layer features, with us instructing GeoTools in how to style the data.  

It now seems more logical to use SLD files for styling the NE data, and letting GeoTools "just get on with it".

This issue is for Peco to refactor our NELayer implementation so that:
* we have one NELayer object, which has a number of NEFeature child objects
* each NEFeature object just has "Visible" and "Names" properties
* we just persist the list of features and if each is visible or not
* the location of the NE data is set using Debrief/cmap preferences

In the future we look forward to integrating an SLD editor: #1031   But, once we do that, we'll have to persist the detail of the SLD styling for each feature.

**Comment by pecko** [comment]
I have finished the first phase.
The commit: https://github.com/pecko/debrief/commit/705e101975709e4009348e0789c3fc3a152b2417
The branch: https://github.com/pecko/debrief/tree/issue984_gtrenderer_refactor

Now, the NELayer loads Geotools layers in the following way:

- check the DATA FOLDER from property
- walks all directories in DATA FOLDER
- if there are *shp files, add that to NEFeatureStyle; one NEFeatureStyle can has more *shp files; they will be separate Geotools layer (batty is example)
The NELayer will check if there is SLD file: the same name as *shp file, but with *sld extension. If such file exists, it will use it. Otherwise will use default styles from NaturalEarthUtil. These default styles are only for testing.
- if there is a directory adds it as group and walks that (currently there isn't any group)

I have also remove all unnecessary code. Now, the code is much simpler.

TODO

- create some SLDs
- create Natural Earth github repository in order to easier tracks datasets and slds
- fix a bug related to the Outline properties (currently no one property is shown)

**Comment by pecko** [comment]
Another commit: https://github.com/pecko/debrief/commit/3899a49c11e1f14ab491e68ee2d3bb4caf661c4a

We don't need propertychange listener anymore.

**Comment by pecko** [comment]
I have created a new github repository: https://github.com/pecko/debrief-naturalearth
We can use it as Natural Earth datasets. The SLD files will be added to the this repository.

**Comment by pecko** [comment]
I have added a few slds from the issue984_gtrenderer_filesld branch. The commit: https://github.com/pecko/debrief-naturalearth/commit/c6a59c769959a05e0630fba1f864e0dee8176d24

**Comment by pecko** [comment]
A XML example:

```
<NaturalEarth>
	<NEStore Name="Natural Earth" Visible="true">
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/ne_10m_admin_0_boundary_lines_land/ne_10m_admin_0_boundary_lines_land.shp"
			Name="ne_10m_admin_0_boundary_lines_land" Visible="true" />
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/ne_10m_admin_0_boundary_lines_maritime_indicator/ne_10m_admin_0_boundary_lines_maritime_indicator.shp"
			Name="ne_10m_admin_0_boundary_lines_maritime_indicator" Visible="true" />
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/ne_10m_admin_0_countries/ne_10m_admin_0_countries.shp"
			Name="ne_10m_admin_0_countries" Visible="true" />
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/ne_10m_bathymetry_all/ne_10m_bathymetry_E_6000.shp,/home/snpe/projects/debrief-naturalearth/ne_10m_bathymetry_all/ne_10m_bathymetry_B_9000.shp,/home/snpe/projects/debrief-naturalearth/ne_10m_bathymetry_all/ne_10m_bathymetry_J_1000.shp,/home/snpe/projects/debrief-naturalearth/ne_10m_bathymetry_all/ne_10m_bathymetry_F_5000.shp,/home/snpe/projects/debrief-naturalearth/ne_10m_bathymetry_all/ne_10m_bathymetry_L_0.shp,/home/snpe/projects/debrief-naturalearth/ne_10m_bathymetry_all/ne_10m_bathymetry_G_4000.shp,/home/snpe/projects/debrief-naturalearth/ne_10m_bathymetry_all/ne_10m_bathymetry_A_10000.shp,/home/snpe/projects/debrief-naturalearth/ne_10m_bathymetry_all/ne_10m_bathymetry_H_3000.shp,/home/snpe/projects/debrief-naturalearth/ne_10m_bathymetry_all/ne_10m_bathymetry_I_2000.shp,/home/snpe/projects/debrief-naturalearth/ne_10m_bathymetry_all/ne_10m_bathymetry_C_8000.shp,/home/snpe/projects/debrief-naturalearth/ne_10m_bathymetry_all/ne_10m_bathymetry_D_7000.shp,/home/snpe/projects/debrief-naturalearth/ne_10m_bathymetry_all/ne_10m_bathymetry_K_200.shp"
			Name="ne_10m_bathymetry_all" Visible="true" />
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/ne_10m_geography_marine_polys/ne_10m_geography_marine_polys.shp"
			Name="ne_10m_geography_marine_polys" Visible="true" />
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/ne_10m_geography_regions_points/ne_10m_geography_regions_points.shp"
			Name="ne_10m_geography_regions_points" Visible="true" />
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/ne_110m_admin_0_boundary_lines_land/ne_110m_admin_0_boundary_lines_land.shp"
			Name="ne_110m_admin_0_boundary_lines_land" Visible="false" />
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp"
			Name="ne_110m_admin_0_countries" Visible="false" />
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/ne_110m_geography_marine_polys/ne_110m_geography_marine_polys.shp"
			Name="ne_110m_geography_marine_polys" Visible="false" />
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/ne_110m_geography_regions_points/ne_110m_geography_regions_points.shp"
			Name="ne_110m_geography_regions_points" Visible="false" />
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/ne_110m_land/ne_110m_land.shp"
			Name="ne_110m_land" Visible="false" />
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/ne_110m_ocean/ne_110m_ocean.shp"
			Name="ne_110m_ocean" Visible="false" />
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/ne_110m_populated_places_simple/ne_110m_populated_places_simple.shp"
			Name="ne_110m_populated_places_simple" Visible="false" />
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/ne_50m_admin_0_countries/ne_50m_admin_0_countries.shp"
			Name="ne_50m_admin_0_countries" Visible="false" />
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/ne_50m_coastline/ne_50m_coastline.shp"
			Name="ne_50m_coastline" Visible="false" />
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/ne_50m_geography_marine_polys/ne_50m_geography_marine_polys.shp"
			Name="ne_50m_geography_marine_polys" Visible="false" />
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/ne_50m_geography_regions_points/ne_50m_geography_regions_points.shp"
			Name="ne_50m_geography_regions_points" Visible="false" />
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/ne_50m_land/ne_50m_land.shp"
			Name="ne_50m_land" Visible="false" />
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/ne_50m_ocean/ne_50m_ocean.shp"
			Name="ne_50m_ocean" Visible="false" />
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/ne_50m_populated_places_simple/ne_50m_populated_places_simple.shp"
			Name="ne_50m_populated_places_simple" Visible="false" />
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/ne_50m_ports/ne_50m_ports.shp"
			Name="ne_50m_ports" Visible="false" />
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/ocean labels/ocean labels.shp"
			Name="ocean labels" Visible="true" />
		<NEFeature
			Filenames="/home/snpe/projects/debrief-naturalearth/sea labels/sea labels.shp"
			Name="sea labels" Visible="true" />
	</NEStore>
</NaturalEarth>
```

**Comment by pecko** [comment]
@IanMayo You can see that the bathy feature contains a lot filenames separated by comma.

**Comment by IanMayo** [comment]
Two items of feedback:
1. We don't store lists in an XML attribute - you naughty, naughty man :-)
2. I would prefer it if we just stored the layer name.  An analyst may pass a file to another user who may have the NE data in a folder in a different path.   If we just store the layer name the data will still load.

**Comment by pecko** [comment]
You are right. We needn't filenames because we can searches that. Will update shortly.

**Comment by pecko** [comment]
> But, if the user then adds the 50M dataset, we no longer want the 110M coastline feature to be seen - > we want Debrief to display the 50M coastline feature.

> How do we resolve this if we just rely on the Feature scale parameters?

We have to change (add) the min/max scaledenominators properties in corresponding SLDs

**Comment by pecko** [comment]
XML without Filenames:

```
<NaturalEarth>
	<NEStore Name="Natural Earth" Visible="true">
		<NEFeature Name="ne_10m_admin_0_boundary_lines_land"
			Visible="true" />
		<NEFeature Name="ne_10m_admin_0_boundary_lines_maritime_indicator"
			Visible="true" />
		<NEFeature Name="ne_10m_admin_0_countries" Visible="true" />
		<NEFeature Name="ne_10m_bathymetry_all" Visible="true" />
		<NEFeature Name="ne_10m_geography_marine_polys" Visible="true" />
		<NEFeature Name="ne_10m_geography_regions_points" Visible="true" />
		<NEFeature Name="ne_110m_admin_0_boundary_lines_land"
			Visible="false" />
		<NEFeature Name="ne_110m_admin_0_countries" Visible="false" />
		<NEFeature Name="ne_110m_geography_marine_polys" Visible="false" />
		<NEFeature Name="ne_110m_geography_regions_points" Visible="false" />
		<NEFeature Name="ne_110m_land" Visible="false" />
		<NEFeature Name="ne_110m_ocean" Visible="false" />
		<NEFeature Name="ne_110m_populated_places_simple" Visible="false" />
		<NEFeature Name="ne_50m_admin_0_countries" Visible="false" />
		<NEFeature Name="ne_50m_coastline" Visible="false" />
		<NEFeature Name="ne_50m_geography_marine_polys" Visible="false" />
		<NEFeature Name="ne_50m_geography_regions_points" Visible="false" />
		<NEFeature Name="ne_50m_land" Visible="false" />
		<NEFeature Name="ne_50m_ocean" Visible="false" />
		<NEFeature Name="ne_50m_populated_places_simple" Visible="false" />
		<NEFeature Name="ne_50m_ports" Visible="false" />
		<NEFeature Name="ocean labels" Visible="true" />
		<NEFeature Name="sea labels" Visible="true" />
	</NEStore>
</NaturalEarth>
```

**Comment by pecko** [comment]
> We don't store lists in an XML attribute

You are right that we needn't filenames, but why we don't store lists in an XML attribute? I'm just curious.

**Comment by IanMayo** [comment]
For well designed XML, we use XML to store lists of things.  So, there would be child elements instead of a list.

**Comment by pecko** [comment]
The Filenames attribute has been removed from XML. We just searches for *shp/*sld files in the dataset's directory.

**Comment by IanMayo** [comment]
"Phase 1" - simpler implementation working ok.
