### ISSUE TITLE
New NE Layers - need to specify sort order

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1044]
I'm having problems with the order of SLD layers.

Some layers (such as "10m_admin_countries") have to sit above other layers (such as "10m_geography_marine_polys").

Just looping through folders won't give us this order.

We "could" give a sort order in the SLD. Another strategy would be to specify the sort (display) order in a extension-point, under the older strategy.

**Comment by pecko** [comment]
> We "could" give a sort order in the SLD. Another strategy would be to specify the sort (display) order in 
> a extension-point, under the older strategy.

We can introduce a file, for instance 0.order, 1.order in directory where shp file exist. I will use that to add valid order.

If we use ext point we will miss advantage to configure NE without changing the code.

**Comment by IanMayo** [comment]
Sure.  The 0.order strategy sounds fine.

**Comment by pecko** [comment]
Could you please update order on debrief-naturalearth and I will update the code.

**Comment by IanMayo** [comment]
I'd like to produce a reduced set of layers.  Can you suggest how I do that?  Do I delete SHP files for layers I don't need?

**Comment by pecko** [comment]
You can remove the directory or *shp file. It should be a separate branch in debrief-naturalearth. Right?

**Comment by IanMayo** [comment]
haven't been in branch. will switch to branch now.

Ian Mayo
PlanetMayo Ltd
- New technologies, implemented well

**Comment by pecko** [comment]
I think that we need full set too. Right?

**Comment by IanMayo** [comment]
No, we won't need a full set.  It seems some data is duplicated across multiple features.

**Comment by pecko** [comment]
Then you probably doesn't need a branch.

**Comment by IanMayo** [comment]
too late. But, if I continue in a branch, when you process the PR you'll see the detail of what I've changed.

**Comment by pecko** [comment]
No problem. We can merge it.

**Comment by IanMayo** [comment]
@Peco - I've finished in that branch.  The maps are looking quite nice, but we need the Bathy datasets, and the support order support.

If you include the Bathy data you'll need the order support.   IIRC, 0 has to be rendered first, 200 on top of it, and so on.  If you include support order files for these, tomorrow I can continue to implement the support order files for the other layers.

**Comment by pecko** [comment]
Will do it. You just ensure that file name is <number>.order (or it will be 0).

**Comment by pecko** [comment]
I will implement bathy ordering based on bathy names. It is simple file ordering.

**Comment by pecko** [comment]
Implemented by https://github.com/pecko/debrief/commit/62472ae10ede154c4b32ff9d6855a2e18c265e87

The directories within some groups (or root of datasets) are sorted based on *.order file in the directory. *shp files within the bathy folder are sorted by *shp filenames.

**Comment by pecko** [comment]
Added some ordering based on old ordering:

The commit: https://github.com/pecko/debrief-naturalearth/commit/18c7309531c1cfa6b27e9802a7b582643b48e76e

**Comment by IanMayo** [comment]
Sort order working fine.
