### ISSUE TITLE
Need to support High Volume and Low Volume NE datasets

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1045]
If we can overcome the build-size, I look forward to distributing Debrief with some very high level NE data - maybe just ocean names, sea names, 110M coastline, 110M sea.

1. If this is the only data that is loaded, then it will need to be viewed at all resolutions - there will be no "min" resolution.

2. But, once the user loads in more data, Debrief will need to know to switch off 110M data, and switch on 50M then 10M as the user zooms in.  It "normally" knows this beacuse of a scaleMin value on the 110M coastline data.

These two requirements clash.  The best solution I can think of is this:
1. distribute Low Volume data in Debrief (~250Kb) - with no scale limits present in SLD. If no "NE data" prefs folder is supplied, use this.  
2. if Debrief finds a data-folder supplied, it will use this instead.  This data-folder comes from the "NE data repo",  it includes the 110,50,10M datasets - with each SLD having scale min and scale max specified.

**Comment by pecko** [comment]
We probably can add 250K without any issue. Also we could remove unnecessary files from o.m.c.NaturalEarth/test/data from repository cache.

**Comment by IanMayo** [comment]
Sure. Will finish "full set" of data for the other repo, then work on the trimmed down version.

**Comment by pecko** [comment]
We can remove o.m.c.NaturalEarth.test from github history complete. It tests nothing now. We can add really test later that will use out datasets. The plugin is about 10MB so it will enable to add some bigger dataset.

**Comment by IanMayo** [comment]
@pecko  - have moved the "low volume" dataset into the top-level of the NE plugin.

I did a test run by setting the prefs to this folder, and it works fine.

I think that to support low/high processing we just have to set the "data" NE sub-folder as the default value for the Natural Earth prefs property.

When initially loaded, Debrief can just use this.  When the users add more data (or get it on the network) they can over-write the preference with the actual value.

**Yes, we can delete the test plugin**

**Comment by pecko** [comment]
> Yes, we can delete the test plugin

The plugin is removed from my fork. You will have to pull the branch.

**Comment by pecko** [comment]
I have create the PR https://github.com/debrief/debrief/pull/1050 in order to test travis.

**Comment by pecko** [comment]
The commit: https://github.com/pecko/debrief/commit/9b2d1fd7b036afdd5a59f90113b998e1aa5dc6e5

It works as follows:

If DATA FOLDER isn't set or isn't directory select o.m.cmap.NaturalEarth/data as data folder.
I have to set this plugin as unjared because we can't use folder from a jar file.

**Comment by pecko** [comment]
I have tested the distribution. It works.

**Comment by IanMayo** [comment]
Working fine, thanks.
