### ISSUE TITLE
New NE Layers - don't offer user edits for Phase One

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1046]
I've decided we should split delivery of NE into two phases.

Let's just offer user editing (even layers on/off) in the second version.

For my testing it's useful to switch layers on and off, but further down in implementation we should remove this ability. Let's just have the single NE LAyer object in the Outline window.

Let's still persist the layers to file - so that the data-files work correctly once we do activate layer editing.

Significantly, I think this means that it will be OK to re-use our NE Features across plots - since the data is the same for each plot.  Hopefully there aren't any GeoTools problems.

**Comment by pecko** [comment]
You mean Outline, but not the Overview view. 
Does it mean that we suppress even the visibility property?

**Comment by IanMayo** [comment]
Yes, let's even suppress the visibility property in Phase One.   As I choose which layers to provide, some of them *depend* on other layers being visible.

**Comment by pecko** [comment]
OK. Will implement it when you create a set.
We probably can remove NE groups. Right?

**Comment by IanMayo** [comment]
Ok, let's remove the NE Groups.

When users saw NE features it was useful to group them,  Now that we're hiding NE features we don't need them.

**Comment by pecko** [comment]
> For my testing it's useful to switch layers on and off, but further down in implementation we should 
> remove this ability. Let's just have the single NE LAyer object in the Outline window.

> Let's still persist the layers to file - so that the data-files work correctly once we do activate layer 
> editing.

I think that we don't need NEFeatureStyle, NEStore or XML pesistence stuff. The XML persistence in this case can be handled by old Debrief Geotools stuff (we need to know that NELayer exist)

I will not remove the code related to NE stores, groups, styles or XML persistence, but it will not be used.

**Comment by IanMayo** [comment]
Yes, very sensible.

**Comment by pecko** [comment]
Fixed by https://github.com/pecko/debrief/commit/74024a1ac64af60dccff7c75b07e4135f2ecb97e

The user see only the Natural Earth entry and can add/delete/show/hide it. Will add bathy slds and create a screencast.

**Comment by IanMayo** [comment]
Initial edit functionality removed (it was only superficial anyway)
