### ISSUE TITLE
Need key for Bathy

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1047]
Once we show Bathy data, we'll need to show a key.

I propose that this be drawn using normal Debrief Java calls in the NELayer paint() event.

**Comment by pecko** [comment]
What is a key?

**Comment by IanMayo** [comment]
It's a table/grid that shows what each color represents.

Our Bathy data shades areas in the particular color for that depth.  We need to let the users know what depth is what color, so they can look at a color on the map and interpret what the depth is at that place.

**Comment by pecko** [comment]
Where I can find this grid?

**Comment by IanMayo** [comment]
We have to generate it.

The color for each layer is in the fill property of the SLD.  We'll have to hard-code  these colors, or pull them from the SLD property of the feature.

We then just draw the 13? boxes, fill the box appropriately, and put the relevant depth value as text into that box.

**Comment by pecko** [comment]
OK. Do you add SLDs for bathy?

**Comment by IanMayo** [comment]
No, I think they're in the Java code for the first NE version.

**Comment by pecko** [comment]
We have had colors, font height, style ... in old NEFeatureStyle. Now it is just some defaults.

**Comment by IanMayo** [comment]
You can find the original set of colors here:
https://github.com/pecko/debrief/blob/issue984_gtrenderer/org.mwc.cmap.NaturalEarth/src/org/mwc/cmap/naturalearth/Activator.java#L191

(I think)

**Comment by pecko** [comment]
I know. Would you like me to create SLDs for bathy based on that code?

**Comment by IanMayo** [comment]
Yes please.  Oh, I was thinking that we'd need some Java structure to handle the Bathy.  But, we just copy the bathy files into the relevant folder now.  I see.

Yes, please add the bathy data to the repo - and stick in some SLDs.  The SLD for 10m_ocean is probably useful.  

(Note: I'm not actually using the 10m ocean layer - it's really slow.  So I renamed the .shp to .shpx)

**Comment by pecko** [comment]
OK. Will also do it when you create a set.

**Comment by pecko** [comment]
I have added some batty slds. The commit: https://github.com/pecko/debrief-naturalearth/commit/91e864d98dfa2a7308f501c9469716518cb7d532

It (only bathy) as follows:

![bathy](https://cloud.githubusercontent.com/assets/534584/5810300/43a6636a-a044-11e4-9d9f-5bb0acac6cab.png)

**Comment by pecko** [comment]
The followin *shp files still doesn't have SLD:

ne_50m_populated_places_simple/ne_50m_populated_places_simple.shp
ne_50m_geography_marine_polys/ne_50m_geography_marine_polys.shp
ne_110m_populated_places_simple/ne_110m_populated_places_simple.shp
ne_110m_geography_regions_points/ne_110m_geography_regions_points.shp
ne_110m_geography_marine_polys/ne_110m_geography_marine_polys.shp
ne_110m_land/ne_110m_land.shp
ne_50m_coastline/ne_50m_coastline.shp
ne_110m_admin_0_boundary_lines_land/ne_110m_admin_0_boundary_lines_land.shp

**Comment by pecko** [comment]
A screenshot shows the depth from bathy dataset:

![bathykey](https://cloud.githubusercontent.com/assets/534584/5824271/c3e5f2e4-a0e3-11e4-8472-de2af3ea849d.png)

**Comment by IanMayo** [comment]
@pecko  the key is shown at the side of the plot, it doesn't mean labelling the contours themselves.  But, what you have one is *really impressive* - well done.

Here is an example of a key:
![map one](http://www.gridovate.com/wp-content/uploads/2010/03/Heat-Map-of-Cornwall.jpg)

And here is another:
![map two](http://www.bozemanrealestatereport.com/images/765_US_Foreclosure_Map_June_2011.jpg)

I picture the key being shown as a vertical table/grid at the bottom-left of the screen.

**Comment by pecko** [comment]
>  the key is shown at the side of the plot, it doesn't mean labelling the contours themselves. But, what 
> you have one is really impressive - well done.

OK. Will try to add a new layer when there is some bathy dataset. Would we somehow show/hide that (maybe via preference for now).
I suppose that we need show the depth property and fill color. Right?

Would you like me to commit labeling I show you? We couldn't hide that without editing SLD.

**Comment by IanMayo** [comment]
Yes, I do like the labelling. Let's keep it, but switch it off.

I do hope that we can provide the Bathy Key without another Layer.  I hope we can just implement the NLayer.paint(CanvasType dest) method.  This method will check if the layer is visible, and if Bathy data is present.  If it is, it will draw key.

**Comment by pecko** [comment]
> Yes, I do like the labelling. Let's keep it, but switch it off.

We can't switch them off currently, but I will add slds (*sld.label) for record.

> I do hope that we can provide the Bathy Key without another Layer. I hope we can just implement 
> the NLayer.paint(CanvasType dest) method. This method will check if the layer is visible, and if 
> Bathy data is present. If it is, it will draw key.

OK.

**Comment by pecko** [comment]
@IanMayo  Do you mean something like the following:

![bathykey1](https://cloud.githubusercontent.com/assets/534584/5841359/938e98c6-a19c-11e4-8dee-82c92aef528f.png)

**Comment by IanMayo** [comment]
Yes, looks great.  The numbers should be right-hand justified, please.

Oh - and as you can see.  Bathymetry isn't visible in the the screenshot you provided.  I don't know if you can tell from the feature if it's currently visible, or if you need to do a scale-test using the maxscaledenominator from the SLD.

**Comment by pecko** [comment]
Need scaletest

**Comment by pecko** [comment]
I have committed the bathy key.
The commit: https://github.com/pecko/debrief/commit/623dbc5e1cf2503cc36ae2d053bfb1fb22934975

**Comment by pecko** [comment]
I have put bathy labels to separate branch in my fork of ref_data: https://github.com/pecko/ref_data/tree/bathylabels

**Comment by pecko** [comment]
I have enhanced calculating scale. Screencast: http://www.snpe.rs/bathy.ogv

**Comment by IanMayo** [comment]
Done.
