### ISSUE TITLE
Tidy the NE data repository

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1048]
I think we can do some tidying to the NE repository:

* delete any features that don't have a SHP and SLD file
* push the tidy repo into the Debrief organisation repo:  https://github.com/debrief/ref_data

**Comment by pecko** [comment]
The commit: https://github.com/pecko/debrief-naturalearth/commit/89f83a013d88f08558058aba4ecd953a6b2dd105

All directories without SLD are removed.

**Comment by pecko** [comment]
> push the tidy repo into the Debrief organisation repo: https://github.com/debrief/ref_data

Done by https://github.com/debrief/ref_data/commit/6bf60cc9811682c711f961981f6d6f93bd570164

**Comment by IanMayo** [comment]
Great, thanks.
