### ISSUE TITLE
Need to force Tif images above NE

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1051]
If we load NE, then a GeoTiff - all works fine.

But, if we load a GeoTiff, then add NE, then NE will be shown above the GeoTiff image.

Could you investigate to see if we can force NE to always go to the bottom of the GeoTools layer stack?

**Comment by pecko** [comment]
You want TIF (or other geotools layer as coastline) be always in front of NE layer?

**Comment by IanMayo** [comment]
yes, please.

**Comment by pecko** [comment]
Fixed by https://github.com/pecko/debrief/commit/7f3eab3f536032cd614ec95adef548b69f84c08b

**Comment by IanMayo** [comment]
Sure, working fine.
