### ISSUE TITLE
Don't include GND in the build

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1053]
@pecko - the GNDManager is a legacy experiment.

I would like to retain the source code in the Debrief repo, but I no longer want to integrate it with Debrief or to include it in the distribution.

I've made a simple change in the feature.xml to exclude it, but you also make any MVN/build-related changes to remove it from the build - and keep the size down.

My first changes are in this PR: https://github.com/debrief/debrief/pull/1054

**Comment by pecko** [comment]
@IanMayo Could you merge your PR? I will create the PR to remove that from tycho.

**Comment by IanMayo** [comment]
merged

**Comment by pecko** [comment]
Reopened in order to add tycho part.

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1057

**Comment by IanMayo** [comment]
Done.
