### ISSUE TITLE
Provide importer for NMEA AIS data

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1061]
It's of value for me to show a "Worked Example" or "Test case" in Debrief.

To do that, we need to read in some external data.

Here is a description for the NMEA AIS data format:
http://catb.org/gpsd/AIVDM.html

A sample data-file is provided on this site:
http://www.aishub.net/nmea-sample.html

Here are some decoded lines, to verify the import:
http://fossies.org/linux/gpsd/test/sample.aivdm

Here's an online AIS converter:
http://ais.tbsalling.dk/

**Comment by IanMayo** [comment]
@pecko - thanks for the tidying.

As you'll hopefully see in the code I submitted, we have to listen out for a Message4 in order to find the actual date & hours/mins.

That means we may not know the time for a Message1 until we get the next Message4.

We *could* store up Message1 entries until we get a Message4, and then retrospectively create the stored positions.

But, I will be happy if we ignore any positions before we get a Message4.  We don't *actually* know the time they relate to - so it's equally *invalid* to either deduce the time, or ignore them.  

Since it will give us a tidier implementation, I'm happy to ignore any Message1 items before we have a Message4.

**Comment by pecko** [comment]
I will implement this feature today later.
I have to create an new example since current examples contains only message 1 (2 or 3), but nmea-sample is to big (> 9000 userIds/tracks and >80000 positions).

**Comment by IanMayo** [comment]
Back at my desk in 20 mins. Will look for better example.

**Comment by pecko** [comment]
It would be great, but maybe nmea-sample is fine. I have made nmea1.ais and nmea2.ais based on this file, but filter only message1. Will make some example with message 1 and 4.
Would we look at message 2 and 3 too (they are position message too)?

**Comment by IanMayo** [comment]
Ok, feel free to filter the nmea_sample file.  

Yes, let's import messages 2 and 3 (though I'm not quite sure what they represent. I'll have to read up on it).

**Comment by pecko** [comment]
1, 2 and 3 are similar and described in the same paragraph.
Re message4 there is the description:

> This message is to be used by fixed-location base stations to periodically report a position and time reference.

It looks that we have more these messages (with position) for userId. I'm not sure if (how) they are related to message 1 (2,3).

**Comment by pecko** [comment]
> Ok, feel free to filter the nmea_sample file.

I have reviewed this file. There are 2-3 userid from 9631 userIds with message type 4. 

However there are 2045 userIds with message type 5. Message type 5 has ETA (ETA: Estimated time of arrival; MMDDHHMM UTC). Maybe we would use this messages. The AisTrack project (https://github.com/dma-ais/AisTrack) uses the message type 5. It doesn't include year.

Also, I have tried to handle AisPacket (include timestamp) instead of AisMessage, but all packet's timestamp are -1.

Seems we still need better example. I have tried run the AisTrack project, but the live server which they using isn't accessible (IP=10.*.*.*).

**Comment by IanMayo** [comment]
no, we can't use ETA as the base for the current time, since it's a time in the future ;-)

 I will have a look at the large dataset tomorrow.

**Comment by pecko** [comment]
> no, we can't use ETA as the base for the current time, since it's a time in the future ;-)

Then, we probably have to use AisPacket.getTimestamp(), but it isn't included in nmea-sample.

**Comment by IanMayo** [comment]
@pecko  - sorry to bother you.  If/when you get chance, could you help me out with a quick question?

I can't find the branch where these AIS changes were made.  I can see your commits,  but I can't find the branch that contains them:
https://github.com/pecko/debrief/commit/d679ca2f9bfd0121964763f894e4f72370df8cbd?diff=unified

Cheers,
Ian

**Comment by IanMayo** [comment]
fixed in newer branch
