### ISSUE TITLE
Updated paste image to Clipboard

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1073]
I'd like to switch how we user Ctrl-C to copy images.

Now that we have Natural Earth, I believe it's more important to capture bitmap images rather than WMF.

Also, if we switch to bitmaps, I hope we can provide a multi-platform copy to clipboard solution.

This would also really help me in preparing some Debrief demo presentations.

If possible, I would favour a multi-format Copy operation - where we put both WMF and bitmap (PNG) onto the clipboard.  Then the user can use "Paste Special..." to select which format to paste.

Could you investigate this @pecko ?

Aaah, I'm also concerned that the JavaClipboard.dll may be 32-bit only, since it Debrief just failed to do a WMF export on a 64Bit Win 8 Virtual Machine.

**Comment by pecko** [comment]
You want to put bitmap onto the clipboard for all OSes and bitmap/WPF for Win 32bit ((if it's possible; I'm not sure for that;have to check).

> Aaah, I'm also concerned that the JavaClipboard.dll may be 32-bit only, since it Debrief just failed to > do a WMF export on a 64Bit Win 8 Virtual Machine.

I will check if there is source for JavaClipboard.dll. If so, we could try to recompile it for Win 64bit. 
Now, Visual Studio should be open source: http://blogs.msdn.com/b/somasegar/archive/2014/11/12/opening-up-visual-studio-and-net-to-every-developer-any-application-net-server-core-open-source-and-cross-platform-visual-studio-community-2013-and-preview-of-visual-studio-2015-and-net-2015.aspx
Firstly, have to check multi-format Copy.

**Comment by IanMayo** [comment]
Yes, both your understanding and your plan sound fine.

**Comment by pecko** [comment]
https://github.com/pecko/debrief/commit/336323e822c3f40122eddcdb255a4018fa3bf42c is first step.

It includes the following:

**copy WMF flavor on Windows 32-bit and image on other platforms**

AFAICS, Java clipboard supports multi-format, but have to check WMF format on Windows.

@IanMayo Do you have source for ./org.mwc.cmap.core/libs/WMFWriter.jar (including native JavaClipboard.dll)?

**Comment by IanMayo** [comment]
**UPDATED REQUIREMENT**

I've just met with users onsite.  Now that we have implemented Natural Earth, they only expect to transfer plots as BitMaps.

So, we can make:  *Ctrl-C will copy as bitmap across all platforms*.

As you'll remember we already have the multi-platform "copy as WMF inside RTF" menu option.  So, that will provide fallback support for any users that really to want to copy a WMF.

I guess this also means we will not require the 64bit version of JavaClipboard.dll

**Comment by pecko** [comment]
Fixed with https://github.com/pecko/debrief/commit/62d17ca51678535f0f25947a58b901b05b18f470

> I guess this also means we will not require the 64bit version of JavaClipboard.dll

The Export WMF action (the File menu) still uses JavaClipboard.dll and works only on Windows 32-bit.
I suppose that we don't need this action as well as 32-bit dll.

**Comment by IanMayo** [comment]
@pecko - at the demonstrations yesterday I discussed the improved export with some existing users.

This body of users only use a Natural Earth backdrop for a "zoomed out" overview diagram at the start of their report.  They won't use Natural Earth backdrops for zoomed in diagrams showing tracks.  

But, "copy PNG" will give a black/grey image.   So, they still require WMF export.

Actually, maybe the 32bit-only dll isn't such a problem.  Whilst most users are using a 64bit operating system, I'm pretty sure it's the JRE that is 32-bit specific.  So, even on 64bit MS Windows, if they use a 32 bit JRE they will still be able to copy the WMF to clipboard.

Does that sound right?

If it is right, maybe there is another, tidier strategy that we can follow:
* Have a "Export PNG to clipboard <ctrl-C>" item in the file menu
* Have a "Export WMF to clipboard <ctrl-shift-C>" item in the file menu. This would be disabled if it's a non-32 bit JRE

How does that sound?

**Comment by pecko** [comment]
> But, "copy PNG" will give a black/grey image. So, they still require WMF export.

You mean CTRL-C? I get the following when CTRL-C in Debrief and paste to here:
![image](https://cloud.githubusercontent.com/assets/534584/6089848/af26a856-ae69-11e4-999b-f89580b67516.png)

**Comment by IanMayo** [comment]
The "black background" issue is when they have NE switched off.  As you remember, with WMF export, we don't show a background shade - so it is always a transparent image, with any tracks / labels drawn over it.

With the bitmap export, they would get a black background (if that's the current background color).  But, if the backdrop is changed to White, PNG export looks quite poor.

So, I now realise that users sometimes users want a PNG image - when they're showing a zoomed out "overview" image that shows where in the world the exercise happened.  They also require a WMF export for when they are showing a a zoomed in image with close-in view of some tracks, but no NE.  

As you know, WMF is vectored - which is best suited to showing the lines, text, shapes like tracks.   And PNG is best suited for large blocks of color - like NE.

RE: the DLL.  For now, let's just have 32 bit export to clipboard - using the existing DLL.  We can have 64-bit export as a feature in the future.

I hope all that's clear - we can talk in Chat if it needs further clarification/explanation.

**Comment by pecko** [comment]
> With the bitmap export, they would get a black background (if that's the current background color). But, > if the backdrop is changed to White, PNG export looks quite poor.

Will try to create transparent bitmap Image.

> I hope all that's clear - we can talk in Chat if it needs further clarification/explanation.

We have CTRL-C (Copy) that copy a plot to clipboard as bitmap Image (will try to enhance it with transparent background) at all platforms. That is "Export PNG to clipboard".

I think that we should only add the "Export WMF to clipboard" action on Windows 32-bit. Agree?

**Comment by IanMayo** [comment]
No, don't worry about transparent background in bitmap. 

Yes, only enable export as WMF on 32 bit windows.

**Comment by pecko** [comment]
> Yes, only enable export as WMF on 32 bit windows.

Fixed with https://github.com/debrief/debrief/commit/4c139ef3a253416cff1e9f4386418fcdae2a06b8
I have tested on Win 7 64-bit using 32-bit JDK and 32-bit Debrief.

**Comment by IanMayo** [comment]
@pecko - do we have "copy as bitmap" available under Win32 builds?  I can't see the command.

**Comment by pecko** [comment]
We have that in the issue984_naturalearth branch. In this branch, CTRL-C do "copy as bitmap", bu separate the "Export WMF to clipboard" copy WMF to clipboard and it's visible only on Win 32-bit.

**Comment by IanMayo** [comment]
Aah, of course - thanks.
