### ISSUE TITLE
Natural Earth background - DirectLayer isn't disposed correctly

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#1081]
When closing a plot with NE we get the following message:

Jan 30, 2015 12:15:23 PM org.geotools.map.Layer dispose
SEVERE: Layer preDispose was not called prior to calling dispose
Jan 30, 2015 12:15:23 PM org.geotools.map.Layer dispose
SEVERE: Layer preDispose was not called prior to calling dispose

**Comment by IanMayo** [comment]
Yes - thanks for recording it.

Once we've got this data projection issue resolved I think we can give the NE branch a good tidy.  I'd also be interested in you doing some performance analysis - just to check we haven't missed something.

**Comment by pecko** [comment]
Fixed.
@IanMayo I will close this issue and you can open a new one related to performance analysis.
