### ISSUE TITLE
Exporting WMF to clipboard under 64Bit MS Windows

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1083]
The export to Clipboard is failing under 64 bit MS Windows.

It works under 32bit - I guess this is because of the DLL.

I think it would be valuable to see if it's possible to export WMF from Java to the System clipboard without the DLL.  Then we'll have a platform-independent solution.

We now have a number of clipboard export issues:  #1073 #1064  #417

**Comment by pecko** [comment]
Based on #1073 I think that we can close this issue.
