### ISSUE TITLE
XY Plots don't show in OSX

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1089]
A couple of days ago I found out that XY Plots don't open under OSX.  An error message is displayed instead.  When I googled the error message, it appeared to indicate that I needed an extra property line in the startup arguments.

![screen shot 2015-02-07 at 10 04 49](https://cloud.githubusercontent.com/assets/1108513/6091703/d4b58b7c-aeb0-11e4-9d21-4410213110fe.png)

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1090

@IanMayo Could you, please, test. I can't test because I haven't some Mac. It should be work with newer JDK 7.

**Comment by IanMayo** [comment]
No, the experiments don't work.  Googling suggests always switching to the newest version.  

But, that hasn't worked either.

I see that JFreeChart does include a SWT.jar file.  I don't think we use that, I think we use the earlier SWT_AWT utility.

Would you mind building a version that uses the JFreechart SWT jar?  Maybe that will fix the osx issue.

**Comment by pecko** [comment]
> I see that JFreeChart does include a SWT.jar file. I don't think we use that, I think we use the earlier 
> SWT_AWT utility.

We use the swt plugin from Eclipse 3.8 distribution (our target platform). I can't check jfreechart because sourceforge is currently down

I can't test the issue because I don't have any Mac.
You can try to run mentioned swt snippet (or some swt_awt snippet) with our swt plugin as well as with swt.jar from jfreechart.

**Comment by IanMayo** [comment]
Hmm, it does look like the only achievable fix is to create an OSX build in a newer version of Eclipse, since the plots "just work" in Luna.


@pecko - Is it very difficult to change the build so that the OSX version of the app is build on Luna? 

Or, can you suggest an alternative strategy to provide an OSX Luna build?

**Comment by pecko** [comment]
> Is it very difficult to change the build so that the OSX version of the app is build on Luna?

We should create a separate target platform for Luna. It isn't to hard - we already had Juno target. This would be good to test future builds with E4.

> Or, can you suggest an alternative strategy to provide an OSX Luna build?

We could check what is changed in SWT on Luna. The main issue is that I don't have some Mac to test.

**Comment by IanMayo** [comment]
Separate target platform - would this target platform still get build automatically by Travis?

**Comment by pecko** [comment]
I think that we can set it so it builds with E3 and E4.
I suppose that there are some difference on E4 (additional toolbar/menu actions we have to remove from UI, for instance), but it would be good to check/test that.

**Comment by IanMayo** [comment]
Works perfectly in Luna!

We're not committed to moving the normal builds to Luna, but it's great that it's a way of getting a working OSX instance for demo-ing.

**Comment by pecko** [comment]
We can keep luna branch for OSX, for now.

**Comment by IanMayo** [comment]
Yes, cool.  I should be able to pull future Master branch updates into it,
shouldn't I?

Ian Mayo
PlanetMayo Ltd
- New technologies, implemented well

**Comment by pecko** [comment]
Right. We just need rebase the luna branch to the master branch periodically.
