### ISSUE TITLE
XYPlot: "Copy to Clipboard" doesn't plot labels

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#1095]
The same issue is with the "Export to WMF" action (exports image to a wmf file).

**Comment by IanMayo** [comment]
Oh dear, the normal export plot to WMF isn't plotting labels, right?

That would be bad.

**Comment by pecko** [comment]
Right, but I think that I found the issue... checking...

**Comment by pecko** [comment]
This s a bug in JFreeChart 1.0.16. The issue doesn't happen wit JFreeChart 1.0.19.

So, the PR https://github.com/debrief/debrief/pull/1094 fixes this issue too.

**Comment by pecko** [comment]
> Oh dear, the normal export plot to WMF isn't plotting labels, right?

I have tested only action within XY Plot viw in this issue.

**Comment by pecko** [comment]
Fixed by the PR: https://github.com/debrief/debrief/pull/1094
