### ISSUE TITLE
Java Clipboard DLL not found when run from IDE

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1096]
I'm just doing some MS Windows testing, but I can't copy to clipboard when I run from the IDE.  I get this error message:
````
!ENTRY org.eclipse.ui 4 0 2015-02-18 09:25:36.331
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.UnsatisfiedLinkError: no JavaClipboard in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
````

Is there a command/text that I need to include in the Run Configuration?  I've looked in our product definition, but can't see any Windows-specific commands.

I'm running Win8, with 32 bit Java 1.8 (java version "1.8.0_31"

**Comment by pecko** [comment]
The easiest way is to add JavaClipboard.dll to working (current0 directory of your IDE session. You can find the current directory if open your launch configuration, select the Arguments tab

![image](https://cloud.githubusercontent.com/assets/534584/6255275/32c2417c-b7af-11e4-97e4-83bc54d1dcdc.png)

**Comment by IanMayo** [comment]
Ok, resolved. Thanks.
