### ISSUE TITLE
Natural Earth WMF write performance issue

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1108]
If we have Natural Earth loaded, but not visible, there is a lengthy (10 secs) delay when we try to write to WMF.

This is in the GeoTools rendering, not the Debrief code.

When we actually delete the Natural Earth layer the performance lag disappears.

Unfortunately, the only obvious fix for this is to override the setVisible behaviour, and add/remove the GeoTools layer from the GeoTools map as appropriate.

**Comment by pecko** [comment]
I can't reproduce the issue. CTRL-C and/or Export to WMF works fine on my local Win 7 64bit with 32-bit Debrief/JRE. How you see delay? Eclipse freezes?
@IanMayo  can you reproduce on some your computer? Maybe, it's also network issue.

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1153

The problem was that the SWChart tests all geotools layers, but not only visible layers.

**Comment by IanMayo** [comment]
Great - well spotted. Thanks/
