### ISSUE TITLE
Color coded Narrative entries

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1114]
Users may find it quicker to navigate the narrative listing if the rows were somehow color-coded according to the platform name.

Note: implementation would have to support using a non-present platform name in instances where the narrative comes from a non-participant.

To be resolved:
* does the color get updated if the track color changes?
* how do we tidily display the color.  I don't think we can use it as the foreground or background, for troubles with contrast.  We could have a "marker" column that is either solid that color, or contains a circle shaded in the relevant color.  Or, we could use a very washed out version of the color as the background shade to each row.  **Washed out color is Ian's favourite**.

Yes, the color should get updated if the track color changes.  One solution to this is that at the start of the table repaint event it gets the colors for the Tracks (Sources) contained in the table - and uses those colors. Note: this shouldn't fail if the track isn't found.

Solution started in branch: 1118_color_narratives

Steps to reproduce:
* load track ````boat1.rep````
* load track ````boat2.rep````
* load file ````narrative.rep````
* Window/Show View  - **Narrative Viewer**

We need to introduce some per-row coloring for the narratives data, to show which vessel the narrative relates to.

**Comment by IanMayo** [comment]
Solution started in branch: 1118_color_narratives

Steps to reproduce:
* load track ````boat1.rep````
* load track ````boat2.rep````
* load file ````narrative.rep````
* Window/Show View  - Narratives

We need to introduce some per-row coloring for the narratives data, to show which vessel the narrative relates to.

**Comment by pecko** [comment]
Where is the 1118_color_narratives branch?

**Comment by IanMayo** [comment]
sorry - will check it right away, maybe I didn't push.

**Comment by IanMayo** [comment]
Pushed: https://github.com/debrief/debrief/tree/1114_color_narratives

**Comment by pecko** [comment]
I don't understand the requirements in this issue.
We have the NELSON track in boat1.rep and COLLINGWOOD in boat2.rep, but we have nothing in the Narrative view when some of these plots are active. When narrative.rep is active we have NELSON and COLLINGWOOD entries in the Narrative view, but not sure how to find corresponding track's color (search all open editors, maybe?)
Not sure what to reproduce by opening these files in the 1114_color_narratives branch?

> Washed out color is Ian's favourite.

What is this?

**Comment by IanMayo** [comment]
Aah,  I see your problem. You need to load all of those files into the same plot -then you see multiple tracks and narrative entries.

Washed out color:  this is my thinking about how to show the colors.  We could make the foreground text the track color, but yellow (or other light shades) won't be visible against the white table background.  An altternate way of using the color is to shade the background of the cells in the relevant color.  Solid color would be too dense.  But, a "washed out" shade would be more attractive. By "washed out" I mean a more faint version of the shade. Something like 1/2 way between each of the R,G,B shades and 255.

**Comment by pecko** [comment]
Trying ...
When a track couldn't be found we wouldn't have change a background. Right?

**Comment by IanMayo** [comment]
Correct.

**Comment by pecko** [comment]
I have added the commit https://github.com/pecko/debrief/commit/795e947d3112a4828e4c85a80a29dd8c76858e38 to the 1114_color_narratives_branch branch (https://github.com/pecko/debrief/tree/1114_color_narratives)

The commit changes background color according track's color. There are two solutions:

- background color is the same as track's color

screencasts:

yellow (nelson), blue(collingwood)

![issue1114a](https://cloud.githubusercontent.com/assets/534584/6931958/aa4faaac-d813-11e4-9f93-ab125d5929c6.png)

red (nelson), blue (collingwood)
![issue1114b](https://cloud.githubusercontent.com/assets/534584/6931973/dd3666ae-d813-11e4-974f-9408bfd1fd4c.png)

- washed color (see org.mwc.cmap.NarrativeViewer.NarrativeViewerModel.getWashedColor(Color)

screencasts:

![issue1114c](https://cloud.githubusercontent.com/assets/534584/6931984/f0988664-d813-11e4-894e-9cbe3a2cfff7.png)

![issue1114d](https://cloud.githubusercontent.com/assets/534584/6931990/029dd972-d814-11e4-8a19-1a9d1fe43067.png)

**Comment by IanMayo** [comment]
Hi there, I've pushed a change that uses an even more washed shade of background color.

But, I've come across a problem.  In the **sample.dpf** data-file, Debrief loads the narratives before it loads the tracks - so it doesn't know the color.

I guess the solution to this is to provide an NarrativeViewerModel getBackground() method implementation that:
* if the entry has a color, use that color
* if the entry doesn't have a color, look it up the relevant track from the Layers object, then assign that color to the entry.  If the track isn't found leave the background as white.

This will defer looking for the color until the narrative viewer gets rendered.

**Comment by IanMayo** [comment]
Hmm, I suspect that my users will expect the narrative color to change if they change the color of a track.

Currently, they would have to close and then re-open the plot to refresh the color.  (But, they probably won't think of doing that).

Could we change the implementation so that we retrieve the track color each time we render the table?

Or, maybe the Narrative Viewer should register as a property change listener, so it knows to re-set the rendering colors each time the track changes color.

Hmm, maybe the Viewer could have a HashMap of track name vs color.  On a Layers.formatted() event, the NarrativeViewer would re-populate the track-color HashMap.

**Comment by pecko** [comment]
> Hi there, I've pushed a change that uses an even more washed shade of background color.

I get the following (very low contrast):

![image](https://cloud.githubusercontent.com/assets/534584/6948464/3ffcc374-d8ae-11e4-9f34-d44aab26df27.png)

**Comment by IanMayo** [comment]
It did look a little deeper for mine, but I'm sure it's the same thing.

I discussed this issue with a user this evening.  Since we mostly have a limited set of track colors in Debrief, we could devise a custom set of background shades for those (light gray for dark colors, dark gray for light colors, or something like that).

I will try to use oDesk to get a graphic designer to devise a color scheme for us.  We will "hide" the lookup list in the getWashedColor() method. So, the getWashedColor() logic can remain unchanged.

But, I would like you to consider the improved logic that lets the narrative view table change color if a track color is changed.

**Comment by pecko** [comment]
> But, I would like you to consider the improved logic that lets the narrative view table change color if a 
> track color is changed.

I'm working on this.

> Or, maybe the Narrative Viewer should register as a property change listener, so it knows to re-set the 
> rendering colors each time the track changes color.

IMO, this would be the best solution, but I don't sure where to add property change listener. Checking...

**Comment by IanMayo** [comment]
ok.

If it gets tricky I'm happy to help out in the morning - just leave me questions here, or in code comments

**Comment by pecko** [comment]
I have created the PR: https://github.com/debrief/debrief/pull/1159

It fixes all issues. See https://github.com/pecko/debrief/commit/2b63e1d16cca4d9ac29234c45cb59e76d5f15a17


> But, I would like you to consider the improved logic that lets the narrative view table change color if a 
> track color is changed

Fixed using Layer's data listener. The listener already exists in NViewerView.
I have keep shade factor 0.9, for now.

**Comment by IanMayo** [comment]
@pecko  - all of our shades should work against a white background now. So, could you check your PR works for the new shades. We should be able to use the track color as the font, with a white background.

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1223

The screenshot:
![image](https://cloud.githubusercontent.com/assets/534584/7525164/7f753930-f507-11e4-9e72-d316f3ecbaeb.png)

**Comment by IanMayo** [comment]
I don't know why, but the text in the narrative window looks really, really crisp. 

It looks just great.
