### ISSUE TITLE
Hide media player buttons from main toolbar

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1121]
I don't have any users that currently engage with the media player.

Now that we have the 24px icons on the toolbar, they occupy more space.

So, I would like us to remove the media player buttons from the main toolbar.  The media menu can stay there though.

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1134
The PR will also reset perspective.

**Comment by IanMayo** [comment]
Done.
