### ISSUE TITLE
Export graph to clipboard text wrong

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1124]
I've had trouble recently copying headings too weird via the clipboard (in MS Windows)

If I remember correctly, the text was the wrong size, and while the y axis text should have been rotated, it wasn't when it was pasted.

Could you have a look?

If there isn't an easy WMF later trick, I think we should switch to exporting a bitmap image.

**Comment by pecko** [comment]
@IanMayo What action (view) you are using?

**Comment by IanMayo** [comment]
When I did it, the rest for the labels was too large, and the axis label which should have been vertical was horizontal.

**Comment by pecko** [comment]
How you "copying headings to clipboard"? CTRL-C, Export to WMF  or ...

**Comment by IanMayo** [comment]
XY plot, then use drop down menu to copy to clipboard

**Comment by IanMayo** [comment]
@pecko  - here's an example of a xy plot copied to MS Word.  Note that the Y axis label isn't rotated, and there's a box around the graph title.
![xyplot](https://cloud.githubusercontent.com/assets/1108513/6657571/3529751e-cb48-11e4-867a-d1842d2db297.PNG)

**Comment by pecko** [comment]
I have already seen this issue. It is probably the easiest switch (or add) the "Export as  Bitmap" action.

**Comment by IanMayo** [comment]
Sure, let's replace wmf for the bitmap option.

**Comment by pecko** [comment]
OK. Currently working on #1122

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1152

- the action text "Place a WMF image of the graph on the clipboard"  replaced with "Place a bitmap image of the graph on the clipboard"
- the action works on all OSes

Screenshot:
![image](https://cloud.githubusercontent.com/assets/534584/6887720/757b29a2-d668-11e4-90ba-5a71102e8dd4.png)

**Comment by IanMayo** [comment]
Merged.

I did some investigating, and it did look like the WMF library was able to support rotated text - it's just that we haven't connected it correctly.

I'll put "support for rotated text" into a separate ticket.

**Comment by pecko** [comment]
There are two classes for WMF. MetafileCanvas supports rotated text, but the class used by XYPlot doesn't support it. Since we have more issues with this class, I replace it with bitmap that works perfectly.

**Comment by IanMayo** [comment]
Yes, you did the right thing :-)
