### ISSUE TITLE
E4 test builds

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1133]
We have an unsolveable issue related to OSX Charts #1089 

We intend fixing it by switching to Luna builds for OSX.

This issue is to progress creating an E4 target for OSX.

Note: one set of users are struggling with the JFreeChart problem where the plot freezes on resize. I would like a win32 test build to see if it fixes the xy chart bug on their machines.

**Comment by pecko** [comment]
I have created the issue_luna_1133 branch and the PR https://github.com/debrief/debrief/pull/1151 . The PR isn't ready to apply. I suppose that we will not apply that than create separate branch for Luna target (at least for now).
The remaining issue with Luna Debrief is that there are some unnecessary toolbar actions. See screenshot. I suppose that we can test these issues.

![image](https://cloud.githubusercontent.com/assets/534584/6883483/f249c87c-d5ae-11e4-8312-3505087f869e.png)

**Comment by pecko** [comment]
Closed by mistake.
