### ISSUE TITLE
Put new Debrief icon into Windows launcher

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1137]
The MS Windows launcher .exe is using old Debrief icons.

We should update it to use the new ones.

IIRC, the launcher needs a composite bitmap containing the icon at a range of resolutions.  The various resolutions are available in this repo:
https://github.com/debrief/debrief-icons

**Comment by kumarbabu** [comment]
Hi,
Could you please help me to convert the debrief_icon.ico file, I am not able to find  16X16, 32X32,  48X48, 256X256 debrief_icon files inr https://github.com/debrief/debrief-icons repository.

Regards,
Kumar

**Comment by IanMayo** [comment]
16px: https://raw.githubusercontent.com/debrief/debrief-icons/master/16/icon.png
48px: https://raw.githubusercontent.com/debrief/debrief-icons/master/48/icon.png

No, we don't have 32px or 256px versions.  I'll ask the designer to create them.  Or I guess you *could* try re-sampling other icon sizes:
24px: https://raw.githubusercontent.com/debrief/debrief-icons/master/24/icon.png
533px: https://raw.githubusercontent.com/debrief/debrief-icons/master/others/533x533.png

**Comment by kumarbabu** [comment]
Hi,

I have generated  32X32, 64X64, 256X256 derief png iconswith help of existing png icons, please see the attached generated one.

![debrief_32](https://cloud.githubusercontent.com/assets/835065/6808410/cd451a00-d279-11e4-9cb3-efd35edc9102.png)
![debrief_64](https://cloud.githubusercontent.com/assets/835065/6808411/cd483230-d279-11e4-9a23-48ba66915f2f.png)
![debrief_256](https://cloud.githubusercontent.com/assets/835065/6808440/fdbf5f6a-d279-11e4-93a2-bc5ed4db4e1e.png)

**Comment by IanMayo** [comment]
Ok. Those images look like you *scaled up* a small icon.  The images would look better if you produced them by *scaling down" from the nearest larger icon.

**Comment by kumarbabu** [comment]
Hi,

I have used http://image.online-convert.com/convert-to-png web site to produce the images.

**Comment by IanMayo** [comment]
Sure - but the largest 256px image looks like a scaled up version of 16px image.  If you scaled-down the this 533px image (link below) it would look a lot more crisp.

 https://raw.githubusercontent.com/debrief/debrief-icons/master/others/533x533.png

**Comment by IanMayo** [comment]
Kumar, here's a 533px image shrunk down to 256px:
![256x256](https://cloud.githubusercontent.com/assets/1108513/6914414/09d81096-d782-11e4-97c5-8233d3830b82.png)

I'm sure you can see that it's better than the one that is upscaled from the 16px icon.  I suggest you produce the 32 and 64 px images by down-scaling and up-scaling the 48px icon.  Tell you what, let me have a go for you :-)

32px:  ![32x32](https://cloud.githubusercontent.com/assets/1108513/6914447/87e510d8-d782-11e4-810a-959d9b763344.png)

64px: ![64x64](https://cloud.githubusercontent.com/assets/1108513/6914448/90f110dc-d782-11e4-8b21-11f31db82b67.png)

**Comment by IanMayo** [comment]
Ok Kumar, back to you to put those images into the app startup executable.

**Comment by kumarbabu** [comment]
Thanks Ian, I will use these Images to produce the debrief Icon.

**Comment by IanMayo** [comment]
Kumar, sorry I missed you last night. Could you give me a progress update when you get chance?

**Comment by kumarbabu** [comment]
Hi Ian,

I have reproduce the debrief launcher ico icon and updated the same in debrief.product, apart from that I have updated other debrief windows images/icons in product itself. I am able to run the debrief product from the source code and able see all update windows icons/images mainly. 

However when I tried to build the debrief package through MAVEN build, I am getting following error and then produced debrief build with default eclipse launcher icon.

oducts) @ product ---
Error - 7 icon(s) not replaced in C:\Users\Ammu\AppData\Local\Temp\p2.brandingIr
on7319609204002677662\launcher.exe using C:\Users\Ammu\Documents\GitHub\debrief\
org.mwc.debrief.product\target\products\DebriefNG\org.mwc.product\icon.ico
Error - 7 icon(s) not replaced in C:\Users\Ammu\AppData\Local\Temp\p2.brandingIr
on3355053502948735886\launcher.exe using C:\Users\Ammu\Documents\GitHub\debrief\
org.mwc.debrief.product\target\products\DebriefNG\org.mwc.product\icon.ico
[INFO]

Could you please help to resole the issue.

Regards,
Kumar

**Comment by IanMayo** [comment]
@pecko  - Kumar is having trouble with the build.  Do you know the MVN build step that injects the icons into the app launcher?  Can you give any pointers?

**Comment by pecko** [comment]
Debrief includes Windows icon file org.mwc.debrief.product/icon.ico. This file contains 7 icons in different resolution as required by Eclipse build engine. It isn't tycho/maven specific; Eclipse Windows build stuff always worked this way. 
I have created icon.ico with gimp. I think that we need repeat this procedure with new icons.
We can also use 7 different files for different resolution, but it will require a little change in debriefng.product.

**Comment by IanMayo** [comment]
Ok, @Kumar - if you're able to produce that multi-resolution *.ico* file, just put it into your PR, and I'm happy to test the build under Linux.

**Comment by pecko** [comment]
I can also test build as well as review icon file(s).

**Comment by kumarbabu** [comment]
Hi,

I have created debrief launcher icon with help of GIMP tool as suggested by @pecko . find the same.

![debrief ico2](https://cloud.githubusercontent.com/assets/835065/7074864/54b3dafa-df1b-11e4-837f-aa43ba4d8dac.JPG)

**Comment by pecko** [comment]
The PR https://github.com/debrief/debrief/pull/1175 seems correctly. It builds on my local machine as well as on travis (https://travis-ci.org/debrief/debrief/builds/57849738).

**Comment by IanMayo** [comment]
Great = well done Kumar, thanks for persevering.
