### ISSUE TITLE
Maintain Contributions - missing fields warning

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1141]
We have "missing fields" warnings in text-boxes the Maintain Contributions View.  The warnings relate to "Both max/min values must be supplied"

But, the warnings only disappear when the focus leaves the cell. This has confused users - since once they have entered text the warning stays visible.

Could we change the behaviour so that the check happens as text is typed, instead of when the cursor leaves the box.

I think the specific problem happened with a "Composite Straight Leg Forecast", in the Course fields.

Aah, another confusion is that the error highlight also shows over the "estimate" box, even though the estimate remains optional.
![erroricons2](https://cloud.githubusercontent.com/assets/1108513/6729947/6528df68-ce2f-11e4-974c-600367d5f22b.png)

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1164
Now, all validations are done separately and when typing something in the field.

**Comment by IanMayo** [comment]
Sadly the PR introduces a fresh problem.

The PR makes the min/max fields compulsory.   They aren't compulsory.  The only "essential" is that if one of min/max is present, then the other one must be supplied aswell.

Currently the error warnings are displayed for empty min/max, but it is acceptable to have both min **and** max empty.

Aah, but the new implementation does update the error validity as text is typed - and that is an improvement.

**Comment by pecko** [comment]
I didn't know it. Will fix today.

**Comment by pecko** [comment]
I have updated the PR according your suggestions.

**Comment by IanMayo** [comment]
Great, thanks.
