### ISSUE TITLE
Update DebriefNG.aip with new Debrief icons

### ISSUE THREAD

**Issue by kumarbabu** [debrief/debrief#1144]
Our icon designer are designed new icons for Debrief application, so better to modify the MSI Adv Installer script with latest debrief icon.
DebriefNG.aip file exist in "org.mwc.product" plug-in.

The latest designed various resolutions icons are available in this repo: https://github.com/debrief/debrief-icons

**Comment by IanMayo** [comment]
Forget about it, we don't use AIP.
