### ISSUE TITLE
New JFreeChart errors

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1147]
We've been stuggling with JFreeChart hanging when showing an XY Plot.

In recent weeks, the Bearing Residuals plot has also been hanging.

Investigate if/when we upgraded the JFreeChart library in use - and see if a new .jar version has introduced this problem.

Alternatively, it would be interesting to see if an E4/Luna build suffers from this problem.

**Comment by pecko** [comment]
@IanMayo I'm starting to create Luna build (#1133). 
Could you please let me know how to reproduce this issue? 
Does it always reproducible?
When you tell "hanging", you mean "Eclipse freezes or crashes" ?

**Comment by IanMayo** [comment]
For one group of users (Win 7 64bit, JRE 7 32 bit), the first time a JFreeChart chart opens (XYPlotView, SATC or Bearing Residuals) the area containing the chart stays white for about 20 seconds, then the chart will appear. 

Hmm, they did only suffer it with the XYPlotView - SATC was fine (we think).  If I remember correctly,  SATC was using a private copy of JFreeChart.jar until a few weeks ago - when it adopted the org.cmap.jfreechart.  I suspect that SATC's private version worked ok, but version in org.cmap.jfreechart was somehow incompatible with the usr setup.  But, now that SATC is using the common version (at least, I think it is), the problem appears in SATC.

No, I can't reproduce it on any of my machines.  But, I see it happen every time on the user network.

It is possible to produce the error by:
1. open **sample.dpf**
2. ctrl-select the **Nelson** and **Collingwood** tracks in the **Outline** window
3. right-click, select **View XY Plot** from the popup menu
4. Select **Course** as the attribute to view
5. The RCP View will open, but the graph area will be a blank space.  Debrief will remain responsive.

**Comment by pecko** [comment]
> No, I can't reproduce it on any of my machines. But, I see it happen every time on the user network.

What is on network: Debrief installation, sample.dpf, workspace or ...?
You claim that it happens in recent weeks. Right?
Seems as network issue. I can't reproduce it too.

**Comment by IanMayo** [comment]
I think Debrief, workspace, and data is across network.

But, JFreeChart is the only component that causes this behaviour.  JFreeChart.jar is only 1.6Mb, so it wouldn't take *very* long to download.

**Comment by pecko** [comment]
I'm not sure, but RE SATC we have changed the way to load jfreechart. I was in local plugin, but now we load a new plugin. Since, you claim that it's happen only first time I suppose this.
Question: when you start a chart in XYPlot view first time and after that start another chart in SATC, does SATC's chart has also 20 secs delay first time?

I doubt that version of jfreechart make trouble, but we can try to downgrade for testing. SATC used 1.0.14 and we now use 1.0.19.

**Comment by IanMayo** [comment]
I'm going to try a Luna build on Weds AM.  

But, will also perform your SATC test when I'm there.

**Comment by IanMayo** [comment]
After installing today's (non-Luna) release the charts were working perfectly, in XY Plot View, Bearing Residuals View, and SATC.

I'm not in again for a couple of weeks. I expect to take in a new release then, and will see if the issue is still resolved.

It does look like its something outside Debrief that has fixed the issue.

**Comment by IanMayo** [comment]
[BTW - the charts also worked perfectly under LUNA, though the pressure to upgrade to Luna is off.]

**Comment by pecko** [comment]
> It does look like its something outside Debrief that has fixed the issue.

It's possible that there is some classloading issue in some JDK. We have changed the way how to load JFreeChart (as a new plugin instead of a jar) and JDK's version (upgrade to Java 7.
My question:

> Question: when you start a chart in XYPlot view first time and after that start another chart in SATC, 
> does SATC's chart has also 20 secs delay first time?

is related to classloading. If there is only one delay for all views then we have probably a classloading issue

**Comment by IanMayo** [comment]
Hopefully one of the changes you described resolved the problem. But, I did think I experienced the JFReeChart pause since the changes.

But, today I experienced no delays at all - so the SATC test became irrelevant :-)

**Comment by pecko** [comment]
Seems good.
Do you change something: Java version, some network places ...?

**Comment by IanMayo** [comment]
Switch to SWT JFreeChart has overcome these problems
