### ISSUE TITLE
Aesthetic color scheme for tracks

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1160]
In my Open Source maritime analysis application we use colored lines to show the paths where different vessels have travelled:

![introshot](https://cloud.githubusercontent.com/assets/1108513/6962635/203f7e0c-d92e-11e4-86e4-445088fd5d78.png)

We have 10 standard track colors in Debrief.
![image](https://cloud.githubusercontent.com/assets/1108513/6962394/081b452e-d92c-11e4-8c18-c195e7161f98.png)

The 10 specific colors used are shown in the screenshots at the end of this posting.

These colors are used for both displaying vessel tracks (routes) on the map, and in UI listings.

Vessel route:
![routes](https://cloud.githubusercontent.com/assets/1108513/6962423/4525af5e-d92c-11e4-811e-3bcd9f8a7fdd.png)

Listing:
![narrativelist](https://cloud.githubusercontent.com/assets/1108513/6962431/55b3b6a4-d92c-11e4-9aba-ad5fa15cb468.png)

Unfortunately some of these shades have poor contrast against a white UI backdrop, or a white/light-gray map backdrop.   Within our chosen technologies it is possible to use custom shades as a backdrop for the lighter shades, but not on the map backdrop.

The shades also lack coherency.  Ideally it would be possible to devise a series of color shades that complement each other.  Diagrams exported from the software will typically be used in government or industrial technical reports, so the colors cannot be to "garish".

This two-stage task includes the following:
* design 10 new color shades.  A, B, and C will remain as some shade
 of Blue, Green and Red (resp).  But the other 7 shades may be created as fresh shades/colors.  The 10 shades should remain legible and clear against Black, White, Gray and Blue-Ocean shades (see the sample images posted below).
* for lighter shades, devise complimentary background shades (possibly gray) to be used in UI listings, to retain the legibility of lighter-shade text.

Note 1: Users will frequently copy/paste the chart images into MS Word-style documents, where the image will always have a white backdrop.
Note 2: The Debrief application has recently had a UI makeover, where two particular shades of Blue and Red have been used extensively RGB(00,00,51) and RGB(204,0,51).  If aesthetically possible, I would be interested in the designer investigating use of these specific shades for Blue and Red.

**The deliverable for this task will be 10 foreground and a number of background shades, presented in RGB color format**

Gray backdrop:
![graybackdrop](https://cloud.githubusercontent.com/assets/1108513/6962528/204e3664-d92d-11e4-9e52-fc62b87d04fb.png)

Black backdrop:
![blackbackdrop](https://cloud.githubusercontent.com/assets/1108513/6962531/205084d2-d92d-11e4-865b-e71e3eb3e2e8.png)

Ocean-shade backdrop:
![seabackdrop](https://cloud.githubusercontent.com/assets/1108513/6962529/204e96ae-d92d-11e4-8a16-bbf57bf21d88.png)

White back-drop:
![whitebackdrop](https://cloud.githubusercontent.com/assets/1108513/6962530/2050683a-d92d-11e4-8898-493f7298e63f.png)

**Comment by IanMayo** [comment]
We've now got a tidy set of track colors:
![trackcolors](https://cloud.githubusercontent.com/assets/1108513/7348956/9173d99c-eced-11e4-96d0-4cffbbb3a80a.png)

Now we need to:
* [ ] Use them as the standard Debrief colors
* [ ] Include the above diagram in the user guidance

**Comment by IanMayo** [comment]
Hi there @pecko  - once we're on top of the current "dragging" issues, could you make this your next ticket?

We're going to swap the existing set of Debrief colors for this new set.  We'll override the set of colors in ImportReplay.initialiseColors().   The first three colors (red, green, blue) should keep their letters from the existing set, but the others can be in any order.

We also need to override them in ColorPropertyEditor.java

Actually - it would be tidier if we could combine these two lists.  I guess the list in "cmap.legacy" should be the single set of colors (since debrief.legacy depends on cmap.legacy).

**Comment by pecko** [comment]
We have 12 colors in ImportReplay.initialiseColors and 17 colors in ColorPropertyEditor. This list contains only 10 colors. 
Would I keep missing colors (white, black, magenta, light grey, dark grey, gold ..) as is?

**Comment by IanMayo** [comment]
Yes - let's use the new colors first, and then the remaining unused colors after that.

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1220
Hoping you want that.

**Comment by pecko** [comment]
@IanMayo I have added the code to your TODO marker.

The PR: https://github.com/debrief/debrief/pull/1222 includes also two your commits.

**Comment by pecko** [comment]
You don't need apply "Revert issue #1160 ...". You should apply the PR #1222
