### ISSUE TITLE
English language property names

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1161]
For years and years we've presented the Java Getter/Setter method names to users, both in the properties window (below), and in right-click context menus.

![propertynames](https://cloud.githubusercontent.com/assets/1108513/6964031/432b4e6e-d93d-11e4-9602-34365f1e7f52.png)

It's probably time to switch to properties that use proper english language & spaces.  I propose we modify the prop() and expertProp() methods to introduce another String parameter. This String will be presented to the user.

The UI logic will use this String, not the raw property name.

We'll use mixed case, not all capitals - so "LineThickness" above will be represented as "Line thickness".

Eclipse will help us do this, by highlighting all instances using <ctrl-G>.  There's a chance that the methods have already been overloaded with extra String parameters - so be sure to start with the longest signatures, then work on the shortest signatures.

An example of how the properties are declared is in SensorWrapper.SensorInfo class.  The Editable methods called ultimately create PropertyDescriptor objects. I think the current implementation relies on the PropertyName to determine the read/write methods. So, I believe our code will have to use the longer PropertyDescriptor method that explicitly provides the read/write methods.

**Comment by IanMayo** [comment]
Here's an example of where you will introduce the new english-language name:
SensorWrapper.SensorInfo

It's the PropertyDescriptor object that we're affecting.  We're currently using the Bean name - so that PropertyDescriptor can determine the bean getter/setter methods.

But, we'll use an English name.  So, I expect our "prop(" method will still have to receive the bean name, but it will have to determine the getter/setter methods, and explicitly provide these to the PropertyDescriptor.

OR, we could extend the PropertyDescriptor class to include a new attribute ("Display Name").  Maybe it would be called "NamedPropertyDescriptor".

When we build the UI to edit properties,  we check for NAmedPropertyDescriptor.  If it is a named property descriptor we provide the DisplayName to the user, else we provide the existing (Bean) name.

Here's an example of where we access the bean data to build the UI:
RightClickSupport.generateListEditorFor()

In there you'll see what PropertyDescriptor objects we access.

**Comment by pecko** [comment]
@IanMayo Thanks.
Will try just to solve #1163

**Comment by IanMayo** [comment]
@pecko - you have a queue of issues, so I've given this fairly straightforward one to Kumar.

**Comment by pecko** [comment]
OK. I don't seen that.

**Comment by kumarbabu** [comment]
Hi,

I understood that we have to maintain  Properties View table labels (i.e. LineThickness, PlotArrayCentre, etc. ) in "message.properties" resource  file, these values defined by users in that resource file. Debrief reads this file and display in "Properties View".

Regards,
Kumar

**Comment by IanMayo** [comment]
No.  We don't use a properties resource file.  The names via intro-spection from method names in the relative classes.

So, in the TrackWrapper class, methods are provided for getLineThickness and setLineThickness.  A TrackWrapperInfo class gives a list of which properties are provided.

**Comment by IanMayo** [comment]
@pecko - Kumar couldn't get the hang of what we were doing here. 

Could you take over?

**Comment by pecko** [comment]
The PropertyDescriptor class already has the displayName property. This property is used in the Properties view and context menu. Currently, we have the same valuse for the name and displayName property.

I suggest that we create a new methods: prop(...), expertProp(...) ...as follows:

- name of method will be displayProp, displayExpertProp ...
- method will have one additional parameter - displayName in regard to corresponding method

After that we just need update the EditorType class for different editable.
I have created example in the  issue1161 branch. The patch in this branch (commit: https://github.com/pecko/debrief/commit/8bb77049e265e59d6d17a489f3fa1fda70f1f493) solves this issue for tracks and sensors.
@IanMayo If you agree I will fix other objects.

BTW
I don't make compile errors because you can easily see what is changed in commit (4 classes only).

Screenshot:

![image](https://cloud.githubusercontent.com/assets/534584/7754924/a2d819d0-fff0-11e4-88a3-4324c8dd725a.png)

**Comment by IanMayo** [comment]
Looking great, thanks Peco.

**Comment by pecko** [comment]
I will continue to fix other objects ...

**Comment by pecko** [comment]
I have created the PR: https://github.com/debrief/debrief/pull/1251

The subclasses of the MWC.GUI.Editable.EditorType class has been updated.

**Comment by pecko** [comment]
I have added the org.mwc.debrief.editable.test plugin that try to test all Editable class.
The following is implemented:

- environment that includes tested classes
- finding classes in hierarchy
- test for class

TODO
Some classes have to be instantiated in specific way (require non-null parameters). I have implemented some of that, but not for all.

**Comment by IanMayo** [comment]
Some classes have to be instantiated in specific way (require non-null parameters). I have implemented some of that, but not for all.

Please use a TODO marker for the difficult ones - I'll create the test objects first thing on Monday morning.

**Comment by pecko** [comment]
See https://github.com/pecko/debrief/blob/0c49565bc0c094c0444bac28f306db60fda0ad34/org.mwc.debrief.editable.test/src/org/mwc/debrief/editable/test/EditableTests.java#L291#L290
in order to see how I have created some classes.
The classes which can't be instantiated are in travis output:

https://travis-ci.org/debrief/debrief/builds/64654230
lines 3500-3553

**Comment by pecko** [comment]
I have updated the PR.
Now, all editable classes are instantiated and tested for property method names. Actually, we just call getPropertyDescriptors, but Java create descriptor and check names. Main task was to instantiate a lot different classes.

**Comment by pecko** [comment]
Trying to fix the tycho build. Since we test the asset classes we have to add the asset plugin to build (they will not be included to the distribution, of course).
The asset plugins needed some fixes.

**Comment by pecko** [comment]
Travis build (https://travis-ci.org/debrief/debrief/builds/65181562) is fine. Finally.

**Comment by pecko** [comment]
I have checked PDE, local on my machine and travis build. The travis build tested only 109 classes. 
PDE and my local build tests 246 classes.
I think that we could apply the patch (it is enough reliable), but I will check this difference.

**Comment by pecko** [comment]
Travis build (https://travis-ci.org/debrief/debrief/builds/65301570) is fine too. There are 200+ tested classes. It is possible that there are some difference via my repository because my repo maybe contains some old plugins.

**Comment by IanMayo** [comment]
Fixed in #1251
