### ISSUE TITLE
Strange UNDO problem on opening plot

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1163]
It appears that UNDO only works after the cursor has left, then returned to the plot.

Steps to reproduce:
1. Start Debrief
2. Open boat1.rep  (select Over the Ground if asked)
3. Right-click on track, and go into "Nelson" drop-down menu, and select "Color" / "Green".
4. Click on Undo menu, and select "Undo color for multiple items"
5. The operation doesn't undo.
6.  Select the *Navigator* view, then select the plot (*boat1.rep*) again
7. Click on Undo menu, and select "Undo color for multiple items"
8. Undo will have worked this time.
9. Undo will continue to work.  The problem will only re-occur when a fresh file is opened in a new plot.

Note that after step 4., the event isn't removed from the Undo Buffer - so something is *rejecting* the undo operation.

**Comment by pecko** [comment]
I can't reproduce the issue.
See http://www.snpe.rs/issue1163.ogv.
How I can reproduce the issue described at https://github.com/debrief/debrief/issues/1156?

**Comment by pecko** [comment]
> 4. Click on Undo menu, and select "Undo color for multiple items"

I suppose you mean "Click on Edit menu, ..."

**Comment by pecko** [comment]
There is a problem when opening two (or more) plots. I have tried boat1.rep and boat2.rep and Undo/Redo operation are sometime done in wrong editor (non active editor). I'm not sure if this issue is related.

**Comment by pecko** [comment]
Debrief uses one undo context for all plot editors (defined statically in CorePlugin). This is wrong and we will have different issues when using more plots or open/close some editor.
I will try to fix it, but, please, let me know how to reproduce the issue from #1156.

**Comment by IanMayo** [comment]
Hi there,
tomorrow morning I'll switch to another PC and produce another test case.  But, on my linux PC the steps above worked every time.

**Comment by IanMayo** [comment]
Aah, I can't reproduce it on my Mac.  Undo works correctly on there.

I'm certain the #1156 is the same error as this - the undo event gets ignored.  This issue was generated as an easier-reproduce version of the same issue.  It's unfortunate that the problem is hard to reproduce.  

I guess our best way ahead is to first fix the "single undo history", then for me to see if that resolves the issue.

**Comment by pecko** [comment]
OK.
There is certainly issue when editing more files or open/close one file.

Test case:
- open a plot file
- make some editing so there are a undo/redo actions
- open second file
The undo/redo action are present in another editor (wrong) and do nothing or do something in first (inactive editor)
- close all files
- open some plot editor
the undo redo actions are present (wrong).

I will try to fix this today.

**Comment by pecko** [comment]
I have created the PR: https://github.com/debrief/debrief/pull/1171
@IanMayo please try your cases.

**Comment by IanMayo** [comment]
Aah, I've found a screen recorder that seems to work without crashing my system

[Compressed.mov | uploaded via ZenHub](https://files.zenhub.io/5526428d0a4d65f74b34a451)

You'll see that although the Undo color change action is offered it doesn't work.  When I re-open the Edit menu, the Undo color change action is still offered.  This time it works ok.

**Comment by pecko** [comment]
You have reproduced the issue with included the PR: https://github.com/debrief/debrief/pull/1171?

**Comment by IanMayo** [comment]
I'm pretty sure it was in this branch.  But, to be sure, I made a fresh recording, using this branch.

[Compressed2.mov | uploaded via ZenHub](https://files.zenhub.io/55264e140a4d65f74b34a481)

It does seem significant that after the first Undo fails, the focus moves from the Editor window to the Navigator window.  Then, when the editor takes focus, the Undo works again.

Here's another experiment.  I make the color change, then switch focus a couple of times. After doing this, the undo works perfectly.  I repeat the test without switching to demonstrate the issue is still present:

[Compressed3a.mov | uploaded via ZenHub](https://files.zenhub.io/55264f630a4d65f74b34a49d)

**Comment by pecko** [comment]
What OS you are using?

**Comment by pecko** [comment]
> It does seem significant that after the first Undo fails, the focus moves from the Editor window to the 
> Navigator window. Then, when the editor takes focus, the Undo works again.

I think so, but can't reproduce the issue on Ubuntu 14.04.
Could you try to reproduce the same issue with simple text editor (in Debrief on the same OS)? Just create some *.txt file, open it, type something, undo it...

**Comment by IanMayo** [comment]
Ubuntu  14.04

**Comment by pecko** [comment]
Do you use Ubuntu unity menus?

**Comment by IanMayo** [comment]
Nice thinking.  I remember us discussing it.  I believe I have the *standard* menus that don't include icons.

**Comment by pecko** [comment]
This issue is reproducible with unity menus. It is Linux Ubuntu specific.
Could you try the following:

export UBUNTU_MENUPROXY=0

after that start Eclipse/Debrief and try to reproduce the issue.
The issue isn't related to menus without icons.

**Comment by IanMayo** [comment]
Aah, I have to start eclipse from the same Terminal.

Yes, that fixes it.

But, this is a Ubuntu-specific fix.   I won't be able to find out more about if #1156 is the same problem as this. Well, it can't be, since they're on Win7.  But, their lack of "Undo" for shear operations does seem related.

I propose we still continue with this branch (correcting the Undo contexts).  But, we'll have to handle undo operations triggered from:
* changes from the Outline view (right-clicking or hide/reveal from view toolbar)
* changing the viewed area from the Chart Overview
* properties window

**Comment by pecko** [comment]
> But, this is a Ubuntu-specific fix.

This issue happens only on Ubuntu.

>  I won't be able to find out more about if #1156 is the same problem as this. Well, it can't be, since 
> they're on Win7. But, their lack of "Undo" for shear operations does seem related.

It is different issue. Not sure how to reproduce it.

> I propose we still continue with this branch (correcting the Undo contexts)...

Agree.

**Comment by pecko** [comment]
I have created the commit: https://github.com/debrief/debrief/commit/1a103431abd8b91a9737f2f35c9d863964902675 that adds undo/redo actions when the Outline view is active. It fixes the following:

> Users would make an edit from the Outline view, then not be able to undo it until they gave focus to 
> the editor. They found this non-intuitive.


> If I remember correctly, the previous behaviour was implemented so that "Undo" would work when a 
> view (not the editor) had focus.

Undo/Redo worked only when a editor has focus. Adding these actions to the Outline/Properties view isn't trivial. Eclipse editor's (as xml editor) doesn't have these actions in Outline/Properties View. There are very old Eclipse bug related to this issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=124495

**Comment by pecko** [comment]
I have added Undo/Redo to the Properties view too. @IanMayo please review.

**Comment by IanMayo** [comment]
Fixed, thanks @pecko !
