### ISSUE TITLE
Fixes to RCP layout in Maintain Contributions View

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1166]
I've added some controls to the Maintain Conts View, but it has spoiled the layout.

Here is the previous layout:
![neatbmcv](https://cloud.githubusercontent.com/assets/1108513/7026364/26d86d5c-dd41-11e4-9838-6b58dd6b6b52.png)

But, since adding some controls, the layout has been spoiled:
![untidybmcv](https://cloud.githubusercontent.com/assets/1108513/7026370/2e83b16a-dd41-11e4-86cd-990610ec02ff.png)

Note how the layout must now be wider to accomodate the top sliders being further right.

You can get data into the Maintain Conts view by opening **thiry_min_one.dpf** and selecting 121200.00 in the Outline view.

**Comment by pecko** [comment]
You have added a few widget right to Error/MDA in Analyst Contributions. Right?

**Comment by IanMayo** [comment]
Yes, that's right.

**Comment by pecko** [comment]
Did you mean something like the following;

![image](https://cloud.githubusercontent.com/assets/534584/7102129/40f790bc-e077-11e4-9f9c-ee0b63f21da4.png)

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1176

**Comment by IanMayo** [comment]
@pecko  - almost. Would it be possible to move the **Name** and **Dates** fields left a little more, to remove the whitespace between the label and the controls.

I guess another column needs to be removed - of something like that.

**Comment by pecko** [comment]
Name and Dates controls would be aligned, but they wouldn't be aligned with slider.Right?

**Comment by IanMayo** [comment]
Well spotted. Yes, it would be acceptable for them to not align with the slider.  Well, hopefully the right sides would align. But, the left sides do not need to.

**Comment by pecko** [comment]
OK. Will try to solve today.

**Comment by pecko** [comment]
Something like this:

![image](https://cloud.githubusercontent.com/assets/534584/7117120/080c217e-e1f7-11e4-8c81-665c4ffcb3aa.png)

**Comment by pecko** [comment]
The PR has been updated

**Comment by IanMayo** [comment]
Perfect :-)
