### ISSUE TITLE
Use of Nebula chart widget instead of JFreeChart

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1169]
We're facing JFReeChart troubles of ranging complexity on some user machines.

Specifically we're using the SWT_AWT bridge to show the AWT JFreeChart control in the SWT environment.

Nebula widgets provides a native SWT graph control:
https://eclipse.org/nebula/widgets/visualization/visualization.php

Step one would be to integrate the nebula graph control into the build (prob a task for Peco), then for Peco or Ian to try replacing one or more JFreeChart controls with the nebula equivalent.

The two graphs at the foot of the Maintain Contributions View are candidates for being tried first.

**Comment by pecko** [comment]
The PR #1177 implements step one - integrate the nebula graph control into the build.

BTW We would probably test pure SWT JFreeChart as follows: http://alvinalexander.com/java/jwarehouse/jfreechart/swt/org/jfree/experimental/chart/swt/demo/SWTTimeSeriesDemo.java.shtml
It doesn't use SWT_AWT bridge.

**Comment by IanMayo** [comment]
Hey - the pure SWT JFreeChart would be better - since it's certainly the minimum API change.

**Comment by pecko** [comment]
OK. Will try to implement that in MaintainContributionView tomorrow.

**Comment by pecko** [comment]
The PR https://github.com/debrief/debrief/pull/1184 uses JFreeChart in MaintainContributionsView without AWT bridge.

I think that it is possible to use this technique in XYPlot, but we have to implement the StepperChartPanel class in SWT.

**Comment by IanMayo** [comment]
Works fine for Ubuntu. Will check for OSX.

**Comment by IanMayo** [comment]
WORKS FINE IN OSX!  That's great news.

Would you mind starting the steps to implement StepperChartPanel?

I'm pretty sure we should use a JFreeChart ValueMarker instead of our custom line drawing. That should make it simpler.

**Comment by pecko** [comment]
OK. will try.

**Comment by pecko** [comment]
I have added new PR: https://github.com/debrief/debrief/pull/1190

I have tested timing (stepping from the Time Controller view) and XVPlotView's actions. Some actions are required adapting (export WMF to file, export bitmap to clipboard).

Please test.

**Comment by IanMayo** [comment]
> Some actions are required adapting (export WMF to file, export bitmap to clipboard).

Do you mean they still need to be fixed?

**Comment by IanMayo** [comment]
No, all seems to work.

Are the two 1169 branches ready for merging (they both work perfectly in OS X :-)  )

Aah - have found some more locations where we need to switch to the new SWT chart:
* Bearing Residuals View
* Frequency Residuals View

Actually, I'm pretty sure it's worth searching for all instances of JFreeChart - and replacing them all with the new construct.

**Comment by pecko** [comment]
> Do you mean they still need to be fixed?

No, It has already fixed.

> Are the two 1169 branches ready for merging (they both work perfectly in OS X :-) )

Yes, they are ready.

> Actually, I'm pretty sure it's worth searching for all instances of JFreeChart - and replacing them all 
> with the new construct.

I will check if we have AWT_SWT bridge yet and fix it in a new branch (PR).

**Comment by IanMayo** [comment]
I'd like to pause adopting the Nebula chart widget.  It does look like the SWT JFreeChart is an improvement (its certainly better under OSX).  When I next visit my client site I will test the new charting.

**Comment by pecko** [comment]
OK.

**Comment by IanMayo** [comment]
My users will find great value in the 3rd of the above commits (Bearing/Frequency Residuals).

But, the commit isn't working - the graph doesn't appear.

The graph can be "driven" by loading **midflow2.dpf**.  Then select "Drag track segment" in the toolbar. The Bearing Residuals View should open.  Now, when you start to drag a track, the dots on the graph should move.  You may need to ensure that "Only draw dots for visible data points" is un-selected.

It's probably worth having a go at this in the Master branch before this development branch - just to see the expected behaviour.

**Comment by pecko** [comment]
> You may need to ensure that "Only draw dots for visible data points" is un-selected.

Fixed by the PR: https://github.com/debrief/debrief/pull/1212

> But, the commit isn't working - the graph doesn't appear.

I'm not sure wat you expect (some graph when opening the view?)

The screencast:

http://www.snpe.rs/issue1169d.png

**Comment by pecko** [comment]
I have just seen that you haven't applied the PR https://github.com/debrief/debrief/pull/1191
The issue can be reproduced when try this PR.
Trying to solve ...

**Comment by pecko** [comment]
Fixed showing graph with the commit: https://github.com/pecko/debrief/commit/cb530632c974241858312d529529da8a6675b5de

The PR: https://github.com/debrief/debrief/pull/1191 has updated (and rebased)

**Comment by pecko** [comment]
I think that we can close this issue. If we face some new issue we can enter a new issue entry.

**Comment by IanMayo** [comment]
Closed - SWT JFreeChart did the job
