### ISSUE TITLE
Additional symbology codes

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1186]
To speed up the process of customising the display of tracks and annotations to create an aesthetically pleasing and clear display 3 new terms (for a total of 5) could be added to the symbology code in the rep file format. These would be used to to set line type, line thickness and fill / transparency options. For legacy support a rep file with just the original 2 terms could still be loaded as normal using default values for line and fill options.

* Line Type:
    * @ : SOLID
    * A : DOTTED
    * B : DOT_DASH
    * C : SHORT_DASHES
    * D : LONG_DASHES
    * E : UNCONNECTED
* Line Thickness:
    * 0 : Hairwidth  
    * 1 : 1 pixels  
    * 2 : 2 pixels  
    * 3 : 3 pixels  
    * 4 : 4 pixels  
    * 5 : 5 pixels  
* Fill style
    * 0 : no-fill
    * 1 : solid fill
    * 2 : semi-transparent fill

The line thickness and fill style will apply to shape annotations.

The line type and line thickness will apply to individual positions (Fixes)

**Comment by IanMayo** [comment]
(have updated index for line types, to match existing ```ImportReplay.replayLineFor()````

**Comment by pecko** [comment]
I'm reviewing this issue...

> ImportReplay.replayLineFor()

You mean ImportReplay.replayLineStyleFor(). Right?

> Note 2: extra symbology attributes have been added to the shapes.rep file in the branch 
> 1188_dynamic_shapes

I suppose you mean extra attributes in CIRCLE type, that is, shape annotations.
Could you made some example for:

> The line type and line thickness will apply to individual positions (Fixes)

**Comment by IanMayo** [comment]
> You mean ImportReplay.replayLineStyleFor(). Right?

Yes.

> I suppose you mean extra attributes in CIRCLE type, that is, shape annotations.

Yes.

> Could you made some example for:
> > The line type and line thickness will apply to individual positions (Fixes)

Have just pushed two commits that add styling to individual positions.

**Comment by pecko** [comment]
> Have just pushed two commits that add styling to individual positions.

There is styling/thickness for track (TrackWrapper), but there isn't styling/thickness for individual positions  (FixWrapper).

I have created commit (PR) that updates shape annotations (style, thickness, fill) and whole track.
For track, the last symbology will be used (in your example @CA20)
The commit are separated so you can check.

The PR: https://github.com/debrief/debrief/pull/1192

**Comment by IanMayo** [comment]
Great, thanks. Will be on it tomorrow morning.

**Comment by IanMayo** [comment]
Fixed in #1192
