### ISSUE TITLE
Hi-res sensor arcs

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1187]
Add an enhancement to debrief to allow the depiction of sensor arcs.
The sensor arc would be linked to a track name and time referenced (in the same way that sensors currently work) and they would be input by a replay file via a new annotation format.
Once loaded they would be displayed in the objects menu below their host platform and would be hidden by default (in the same way that sensors currently work). All bearings given are relative to the platform head.
Multiple sensor arcs could be associated with each track and toggled as required for analysis or presentation.
The arc would take a colour from the symbology attribute assigned in the rep file and potentially also line style and fill options. The arcs descriptive name would be specified in quotes at the end of the data line and this would be used to group together multiple track entries.
The arc would be specified as a series of pairs of bearings (left of arc, right of arc) and ranges (inner, outer) which would be combined to describe the arc as illustrated below:

*For clarity the DTG, track name, symbology attributes etc are omitted in the following simplistic examples.*

![arc1](https://cloud.githubusercontent.com/assets/1108513/7142145/40f81ff6-e2ce-11e4-9429-f80dd9847407.png)
![arc2](https://cloud.githubusercontent.com/assets/1108513/7142146/40fc1106-e2ce-11e4-9cca-c341dbc42110.png)
![arc3](https://cloud.githubusercontent.com/assets/1108513/7142147/40fc80aa-e2ce-11e4-9c40-5d892b32828d.png)

This format would be flexible, a simple arc could be specified with just a few parameters while multiple segments could be ‘stacked’ in each data line to create a complex shape if required (e.g. multiple convergence zones with fwd and stern blind arcs).

Use cases (all cases could be data from trials / excursuses or ODIN model runs):
* Displaying torpedo sonar beams, which vary at different phases of the weapon run
* LFAS convergence zones
* Arcs for various sonars in SUBTACEX
* Arcs for trainable sensors (such as EO/IR sensors)
* Buoyfield probable detection ranges, highlighting buoys in contact

### Import from REP
A new ```ImportSensorArc``` class will be created.  ImportReplay will check for nwe instances of SensorArc elements being read in. When they are read in, they will be added to the relevant track via ```theTrack.add(newSensorArc)```

The TrackWrapper object will add the sensor arc to the new _sensorArcs object.

### Painting - Normal Mode & Snail Mode

Any visible sensor arc element will be plotted at the current time value.

The TrackWrapper method will need to implement the DynamicPlottable interface, as described in #1188  When the paint(dest, time) method is called, the  TrackWrapper will paint as normal, but it will also paint any visible SensorArc objects.

## Overview Manager Support

The list of sensor arc objects will be exposed in the same way that the list of sensors are.

From the properties window it will be possible to edit the string that represents the set of arc values.  Thus this class will need to support a two-way to/from text flow.

### Reading from & writing to DPF

A new HandleSensorArcs class will be registered in HandleTrack for reading and saving to XML (DPF)

**Comment by pecko** [comment]
@IanMayo Could you please create a simple rep file for testing (similar to shapes.rep from #1188)?

**Comment by IanMayo** [comment]
@pecko - I've gone back to the analyst to clarify the role of DTG (time) in the Sensor Arcs.  I hope to give you an example in a couple of hours.

**Comment by IanMayo** [comment]
Sample data-file included in this commit:
https://github.com/debrief/debrief/commit/b90225d8386ce0a5927d0051492fbe488bb00309

The plan is that you will load boat1.rep and boat2.rep, then drag in this sensor_arcs.rep file to test the support for sensor arcs

**Comment by pecko** [comment]
I have pushed a few commits to the https://github.com/pecko/debrief/tree/issue1187 branch. They implement importing from REP and adding to track (showing in Outline).

Will try to implement painting sensor arc...

**Comment by pecko** [comment]
I have added a new commit that paints sensor arcs as specified. It requires more examples to testing.

Screenshot:

![image](https://cloud.githubusercontent.com/assets/534584/7338834/bfda1ebc-ec58-11e4-895e-8d7215e5d568.png)

**Comment by pecko** [comment]
TODO:

- test painting more
- exporting to DPF

**Comment by IanMayo** [comment]
Ok, early feedback:

* the arc should only be displayed during its "valid time period" - between the start & end markers.  So - this is now similar to the DynamicShapes behaviour.
* Where the arc as start/end angle, this angle is relative to the current ship course.  So, in the screenshot above, the Yellow "pie slice" should be facing to the West, so it's like a "search-light" in front of the ship.
* We don't need the grey circles & lines - they were just used by the analyst to help draw the shape.
* we need PropertyEditor support - so that it's possible for the user to edit the shape. This would be supported by providing the "format string" as a "Arcs" String parameter. The string would contain the series of min/max angle/range values as in the REP format.

**Comment by pecko** [comment]
> Where the arc as start/end angle, this angle is relative to the current ship course. So, in the screenshot 
> above, the Yellow "pie slice" should be facing to the West, so it's like a "search-light" in front of the ship.

I'm not sure that I understand this. Could you sketch (paint) how should look: the Yellow "pie slice"

**Comment by IanMayo** [comment]
Sure, here's a very poor illustration:
![westpie](https://cloud.githubusercontent.com/assets/1108513/7348655/3c7aace2-
eceb-11e4-8eb2-32eec84987fe.jpeg)

The sensor angles aren't to be measured against North (0 degrees). They are to be measured against the current ship's course/heading/direction of travel (so they are *relative* angles, not *absolute* angles).  The diagrams at the top of this page are all drawn as if the ship is travelling North.  In the sample data, the ship is travelling west - so they need to be rotated 90 degrees anti-clockwise.

**Comment by pecko** [comment]
OK. Although I can't see your image (forbidden), I think that I understand that.

Two other questions:

1) Seancor Arc starts with ;SENSORARC. Would it be ;SENSORARC: (with colon at the end according to other types)?
2) I use arcs radius as 4000 yards (hardcoded), Would we use some arc's value (maybe fourth outer value)?

**Comment by IanMayo** [comment]
1) yes, there should be a colon
2) the "CZ Ring" raduses are 500 and 1000.  So we don't need hard-coded values. (actually the spec doesn't say, but they are in yards)

**Comment by pecko** [comment]
Clear. Will start a little later.

**Comment by pecko** [comment]
I forget. Would we use symbology as specified in #1186 ?

**Comment by IanMayo** [comment]
Symbology - yes. The color will be the fill/outline, and we'll need to use the filled/semi-transparent setting.

**Comment by pecko** [comment]
Recapitulation:

Implemented:

* the arc should only be displayed during its "valid time period" - between the start & end markers. So - this is now similar to the DynamicShapes behaviour.
* We don't need the grey circles & lines - they were just used by the analyst to help draw the shape.
* I expect users will wish to "tune" the arcs in Debrief. So, we will need to support "exportThis()" in ImportSensorArc.java
* Aaah, one last item. In the Outline View, we should call them "Coverage Arcs", not "Sensor Arcs".
* ;SENSORARC replaced with ;SENSORARC: 
* arcs radius isn't hardcoded anymore

todo:

* Where the arc as start/end angle, this angle is relative to the current ship course. So, in the screenshot above, the Yellow "pie slice" should be facing to the West, so it's like a "search-light" in front of the ship.
* we need PropertyEditor support - so that it's possible for the user to edit the shape. This would be supported by providing the "format string" as a "Arcs" String parameter. The string would contain the series of min/max angle/range values as in the REP format.
* users will also need to be able to edit the start/end time for each sensor arc object
* export to DPF

**Comment by pecko** [comment]
How I can get "the current ship course" (I suppose from track object)?

**Comment by IanMayo** [comment]
* there's a problem where two arcs are visible at 0512. This is because one finishes at 0512, and the second starts at 0512.  We'll have to handle this by the end time being exclusive.  

So, an arc is visible if the time is "greater than or equal to" the start time, and "less than" the end time.
* When I replay through the data I only see first two arcs for the "FWD Dynamic" set of arcs.
* You're going to retrieve the current course from the track. Possibly using something like getNearestTo(), then getCourse().    You will also have to retrieve the position:  the arc shape is plotted at the vessel location at that time.  If an arc extends over one hour - it will "move along" the vessel track during that hour.   So,
when you retrieve the current course (to rotate the arc shape) you will also need to retrieve the current location (to position the arc shape).
* The arc shapes need to be transparent - the "CZ Arc" currently obscures the track behind it:
![arccoverage](https://cloud.githubusercontent.com/assets/1108513/7365068/aeccbf30-ed84-11e4-8d2d-3290a62bab3b.png)

**Comment by pecko** [comment]
> So, an arc is visible if the time is "greater than or equal to" the start time, and "less than" the end time.
> When I replay through the data I only see first two arcs for the "FWD Dynamic" set of arcs.

Fixed

**Comment by pecko** [comment]
> The arc shapes need to be transparent - the "CZ Arc" currently obscures the track behind it: 

I have fixed this so paint sensor arcs firstly and after that track's shapes. See commit: https://github.com/pecko/debrief/commit/fb962ea13289617eebe4c8df76d3c71c4a93c156

Screenshot:

![image](https://cloud.githubusercontent.com/assets/534584/7398258/2f2de026-eeae-11e4-934a-723e53a8c81d.png)

**Comment by pecko** [comment]
> You will also have to retrieve the position: the arc shape is plotted at the vessel location at that time. If 
> an arc extends over one hour - it will "move along" the vessel track during that hour. So, when you 
> retrieve the current course (to rotate the arc shape) you will also need to retrieve the current location 
> (to position the arc shape).

The position (origin) has been calculated in the Debrief.Wrappers.SensorArcContactWrapper.getCalculatedOrigin(WatchableList) method.
The code is based on SensorContactWrapper.getCalculatedOrigin

**Comment by IanMayo** [comment]
Transparent arcs: Sorry, that solution won't work if there is a background (like natural earth) or of there are other shapes or tracks underneath.

**Comment by IanMayo** [comment]
Origin: you just need to use the Watchable(0) object that you used to retrieve the current course. It also has a get location() method.

**Comment by pecko** [comment]
> Transparent arcs: Sorry, that solution won't work if there is a background (like natural earth) or of there 
> are other shapes or tracks underneath.

Screenshot with Natural Earth (it works because I have changed order only within track wrapper's elements; it isn't related to another layers):

![image](https://cloud.githubusercontent.com/assets/534584/7398851/0920cc28-eeb2-11e4-8a97-4dd838f4336a.png)

**Comment by pecko** [comment]
> Origin: you just need to use the Watchable(0) object that you used to retrieve the current course. It also > has a get location() method.

Trying ...

**Comment by IanMayo** [comment]
Transparent arcs - but the centre of the circle in your image is grey - it should be blue with Natural Earth.

**Comment by pecko** [comment]
> Transparent arcs - but the centre of the circle in your image is grey - it should be blue with Natural Earth.

You are right. Will try to find solution. It isn't to easy because we have cover beam, not only concentric circle (donut)

Screenshot with beams and dark background (incorrectly):

![image](https://cloud.githubusercontent.com/assets/534584/7399560/021a3bd0-eeb7-11e4-96a1-0aaeb3135236.png)

**Comment by IanMayo** [comment]
Yes - I think you need to do "shape subtraction" to get just the shaded area. You then paint this shape.

Or, we create a polygon to represent the shape.  The polygon will only have straight lines. But, if we break a circle down into e.g. 16 segments it will still look like a nice circle.

**Comment by pecko** [comment]
I hope that I understand it. Will try.

**Comment by IanMayo** [comment]
it's ok to leave that shape rendering until last.  If you handle the other functionality I may get chance to "step in" for this rendering.  I've done similar things in the past.

**Comment by pecko** [comment]
OK.
IMO, Remaining feature is only "Export to DPF". Will try do it tonight...

**Comment by pecko** [comment]
I have added the "exporting to DPF" feature and create the PR: https://github.com/debrief/debrief/pull/1207

IMO, we should review the PR and apply.
Other features/issues (as transparent arcs, fixing DPF schema ...) can be solved in separate issues.

Notice: We should probably fix DPF schema for this export as well as dynamic shapes.

**Comment by IanMayo** [comment]
Have done lots of refactoring - the code was carrying a lot of unnecessary functionality.

I've posted an oDesk fixed-price task to produce code to plot the donut/donut-slice.

Once that's in we're practically done.

Aah, there is one other thing.  We need the shapes to appear when stepping through in "Snail Mode".

Would you mind investigating that?  As before: you load *boat1.rep*, *boat2.rep*, *sensor_arcs.rep*. Then you switch to Snail Mode in the Time Controller.  At each step - the relevant Sensor Arc(s) should be displayed.

**Comment by pecko** [comment]
I will review/test Snail Mode. If I have more time will also try donut/donut-slice.

**Comment by IanMayo** [comment]
Aah - I'd also appreciate you updating the Plot File schema, if you get chance.  You can leave the comments/descriptions to me, if you like.

**Comment by pecko** [comment]
I will update schema, of course. Maybe, we could create a separate issue because this one is very big (also we have to change schema because dynamic shapes).

**Comment by IanMayo** [comment]
Yes, let's move schema updates to another issue.

I'd like to defer closing/merging this one until we have working sensor arcs.  I don't want to put it in master with the current broken plotting.

**Comment by pecko** [comment]
Clear. Will try fix plotting during day.

**Comment by pecko** [comment]
I have implemented plotting in Snail mode and transparent arcs using the PlotDonutFrame example.

@IanMayo Please review... I have commented some your code.

**Comment by pecko** [comment]
Screencast (Snail mode):

![image](https://cloud.githubusercontent.com/assets/534584/7425988/232597a6-efbc-11e4-8f03-5efff77816d7.png)

**Comment by IanMayo** [comment]
Closed in #1207
