### ISSUE TITLE
Moving shapes  (dynamic annotations)

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1188]
Add an enhancement to debrief to allow the depiction of moving shapes.
The moving shape would be listed as a shape in the objects list, but would have additional time / position data in the same way as a track object.
Three new annotations would be added to achieve this; Circle, rectangle and polygon (;CIRCLE_TRACK, ;RECT_TRACK, ;POLY_TRACK).The shape would take a colour from the symbology attribute assigned in the rep file and potentially also line style and fill options. The shapes name would be specified in quotes between the DTG and position terms of the data line and this would be used to group together multiple shape entries into a single track.

To speed up the process of customising the display the additional symbology parameters suggested in earlier proposal (#1186) should be adopted.

Use cases (all cases could be data from trials / exercises or ODIN model runs):
* Displaying wakes and other signatures
* Growing furthest on circle / target uncertainty areas
* Displaying ping front and echo front
* Moving and expanding op areas

## Example

**Existing circle**
```
;CIRCLE: @@ DD MM SS.S H DDD MM SS.S H YYY XX.XX 
;; symb, centre lat, centre long, radius (yards), label 
```
**New circle track**
```
;;format
;CIRCLE_TRACK: @@@@@ YYMMDD HHMMSS "NAME" DD MM SS.S H DDD MM SS.S H YYY XX.XX 
;; symb, date-time, parent track name, centre lat, centre long, radius (yards), label 
;CIRCLE_TRACK: @@011 151212 143000 "Circle Track A" 54 05 12.1 N 4 0 12.4 W 1000 At time 1430 
;CIRCLE_TRACK: @@011 151212 143100 "Circle Track A" 54 05 14.1 N 4 0 12.1 W 1100 At time 1431 
```

## Implementation
We will introduce a new shape wrapper class, **DynamicShapeLayer**.  This will store a series of shape objects.  The Shape objects do not need to be of the same style: they may be rectangles, circles, or polygons.

The DynamicShapeWrapper will be a top-level layer in Debrief, sitting alongside Tracks and other layers.

### Import
When reading in an instance of CircleTrack, RectangleTrack or PolygonTrack the importer will first test to see if it has an object of that name ("Circle A" above).  If the object doesn't exist then a new DynamicShapeWrapper of that name will be created.

If the object does exist, then the shape will be added to that dynamic shape wrapper.

### Painting - Normal mode

A new interface, DynamicPlottable will be created. This will have a single method:
```
  /** paint this object to the specified canvas
   */
  public void paint(CanvasType dest, long time);
```

DynamicAnnotations will not respond to the paint() event. They will just respond to the paint(dest,time) event.  If time is -ve, nothing will be painted.

The DynamicShapeWrapper will receive newTime events - so it is always aware of the current time.

The DynamicShapeWrapper entity will have a *PlotAllShapes* boolean attribute. Its default will be false.

When the paint() method is called, processing will depend on the value of the PlotAllShapes attribute.

If true, all shapes will be plotted.

If false, the DynamicShapeWrapper will find the shape entity on or immediately after the current time.  This is the shape that will be painted.

### Painting - Snail mode

In snail painting mode - only the shape entity on or immediately after the current time will be plotted.

### Persist to PDF
The HandleDynamicShapeLayer handler will have to be registered as an importer in DebriefLayersHandler.

When the plot is saved, a new HandleDynanicShapeWrapper class will be used. This will cycle through all child shapes, exporting them to XML using the relevant methods from HandleCircleTrack, HandleRectangleTrack and HandlePolygonTrack classes.

### Read from PDF

The HandleDynamicShapeLayer handler will have to be registered as an exporter in DebriefLayersHandler.

The handler will register child handlers fro HandleCircleTrack, HandleRectangleTrack and HandlePolygonTrack

**Comment by IanMayo** [comment]
@pecko  - I think this one is also ready to start.  I've put some test data into "Shapes.rep" in the 1188_dynamic_shapes branch.

**Comment by pecko** [comment]
> We will introduce a new shape wrapper class, DynamicShapeLayer. This will store a series of shape objects. 
> The Shape objects do not need to be of the same style: they may be rectangles, circles, or polygons.

You probably mean DynamicShapeWrapper, but not DynamicShapeLayer. Right?

**Comment by IanMayo** [comment]
Aah yes, that was confusing.

Since the element will sit at the top level in the Outline, I think **Layer** is the better term to use.  Plus, it will contain a series of shape wrappers - which is more like a layer.

Do you have any thoughts?

**Comment by pecko** [comment]
No, I just reviewing this issue for now.

**Comment by pecko** [comment]
> The moving shape would be listed as a shape in the objects list, but would have additional time / position data in the same way as a track object.

The ShapeWrapper class already has startDTG/endDTG attributes. I suppose that we should just use them. Right?

**Comment by pecko** [comment]
> Persist to PDF/Read from PDF

Do you mean DPF (Debrief xml format)?

**Comment by IanMayo** [comment]
Oh, that's a complication.

For the new version, the user will just provide a single date-time.  So, I think we will have to just provide the startDTG and leave the endDTG blank.

When the parent class (DynamicShapeLayer) renders itself it will find the shape with a startDTG on or immediately after the current TimeController time.

**Comment by pecko** [comment]
I hope that I understand it. Will try to implement ...

**Comment by IanMayo** [comment]
@pecko  - I've just updated the shapes.rep file in the 1188_dynamic_shapes branch to include updated data from your "more symbology" branch.

**Comment by pecko** [comment]
I think that there is a little issue in shapes.rep related to POLY_TRACK. I have created the PR: https://github.com/debrief/debrief/pull/1196. It is against the 1188_dynamic_shapes branch.

**Comment by pecko** [comment]
I have created step 1 of this issue: importing dynamic shapes. The PR: https://github.com/debrief/debrief/pull/1197

Notices: 

1) ";POLY:" type already recognize startDTG/endDTG. However, I have created a new importer (ImportPolygonTrack) that is similar to ImportCircleTrack and ImportRectangleRect

2) 
> A new interface, DynamicPlottable will be created. This will have a single method:
> public void paint(CanvasType dest, long time);

There is already the DynamicPlottable interface with the following method:

```java
public boolean visibleBetween(HiResDate start, HiResDate end);
```

I think that it isn't used, but regardless, we should use some other interface (maybe MovingPlottable).

Question:
 paint(CanvasType dest, long time); would be implemented in the following way:

Debrief paints a layer by calling:

```java
org.mwc.debrief.core.editors.painters.TemporalLayerPainter.paintThisLayer(Layer, CanvasType, HiResDate)
```

It calls only the method:

```java
theLayer.paint(dest);
```

We will check if a layer implement MovingPlottable (that is, our new interface) and HiResDate != null and call a new method:

```java
public void paint(CanvasType dest, long time);
```

Do you agree?

**Comment by pecko** [comment]
Question 2:

When we call 

```java
public void paint(CanvasType dest, long time);
```
we will paint a shape depending on method parameter time (maybe we would use HiResDate here) and shape's startDTG. Will we use some tolerance or we paint shape only when time = startDTG?

**Comment by IanMayo** [comment]
Question 1: 
> We will check if a layer implement MovingPlottable (that is, our new interface) and HiResDate != null and call a new method. Do you agree?

Yes.

Question 2:
> Will we use some tolerance or we paint shape only when time = startDTG?

We can't know tolerances - some data is 0.1sec intervals, some data is 15 minute intervals.  So we will paint the shape when **time >= startDTG**.

**Comment by pecko** [comment]
I have added the commit: https://github.com/pecko/debrief/commit/de12d2809f120aaa277e9d04b352cc4e3853e505 that implements painting.

Screencast:

http://www/snpe.rs/issue1188.ogv

Will continue on export/import from/to DPF.

**Comment by IanMayo** [comment]
Hi there, looking nice.

One comment on painting: we plot the **first** shape on or after the time.  We don't plot **all** shapes on or after the time.

**Comment by pecko** [comment]
I will adapt.

**Comment by pecko** [comment]
I have added painting and importing/exporting to DPF files. I have also tried to paint as you suggested in previous mail.
IMO, now it is whole this issue ready to apply.

@IanMayo Please review ...

**Comment by IanMayo** [comment]
Fixed.
