### ISSUE TITLE
Improve hover text when dragging track

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1204]
When dragging a manual TMA track, we show a hover box that displays the course and speed for the solution.

This box gets increasingly difficult to read over a cluttered plot.

Analysts would like the box to be made easier to read, by making it a solid box, shown above the data. 

Reproduce this by opening **midflow2.dpf**.  Then click on **Drag Track Segment**, then start to drag one of the red track segments (from the end point).

You will see the popup hover box appear.  In Ubuntu/64Bit Java 8 - the text isn't legible at all.

**Comment by pecko** [comment]
I can't reproduce the issue on Ubuntu 64-bit 14.04 (JDK 1.8.0_25 or JDK7). I suppose that you have some specific ubuntu (or Eclipse) theme/font settings. 
Could you, please, create a screenshot (or screencast)?

**Comment by pecko** [comment]
I suppose you mean the following popup:

![image](https://cloud.githubusercontent.com/assets/534584/7446465/bb13049e-f1d9-11e4-9aed-db477901c494.png)

**Comment by pecko** [comment]
Try to fix (will create the PR tomorrow if it's correct):

http://www.snpe.rs/issue1204a.png

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1214 fixes the issue as shown in second screencast.

**Comment by IanMayo** [comment]
http://www.snpe.rs/issue1204.ogv - Yes - it clearly works on your machine.

On my machine I just get a white rectangle:
![draghighlight2](https://cloud.githubusercontent.com/assets/1108513/7470022/50b9e8d6-f311-11e4-9976-7624632136dc.png)

**Comment by pecko** [comment]
It's weird. I'm using the same OS (Ubuntu 14.04 64-bit)
Could you try the PR: https://github.com/debrief/debrief/pull/1214?

**Comment by IanMayo** [comment]
Yes, it's weird.  The image was produced using the PR #1214 

There's another strange behavior: when I measure range and bearing under Linux I don't see the measured text on the plot.  I see the "elastic line" that represents the range/bearing being measured - but not text (just the set of measurements displayed down in the status bar):
![dragrangebearing](https://cloud.githubusercontent.com/assets/1108513/7474486/b1d5610e-f339-11e4-84cf-6f0994e368c6.png)

So, it looks like for "Range and Bearing" and "Drag Track Segment" - the dragging behaviour can display the line, and the shaded rectangle.  But - it doesn't display text.

**Comment by pecko** [comment]
I think that you have some specific Linux settings (theme, font or similar), because text is shown fine on my machine.
I just look at http://www.snpe.rs/issue1204a.ogv. It is weird to that you can't see it. You can't download it or you can open the file?

**Comment by IanMayo** [comment]
I've got a Win7 VM, and the text shows properly there:
![rangeshown](https://cloud.githubusercontent.com/assets/1108513/7475037/2b0eaa5a-f33d-11e4-80bf-7b148cbcae58.png)


I've captured the 2 config files, to see if they hold any clues (attached).

[XORText_NotShown.txt | uploaded via ZenHub](https://files.zenhub.io/5548d64a8fd825ae6d3e0cc1)

[XOR_text_shown.txt | uploaded via ZenHub](https://files.zenhub.io/5548d64a8fd825ae6d3e0cc2)

**Comment by pecko** [comment]
You use JDK 1.8.0_45 and Debrief distribution (not stating Debrief as  PDE from Eclipse). Right?

**Comment by IanMayo** [comment]
The "XOR Not shown" is running from Eclipse.  The "XOR text shown" is from a distribution.

Let me try a Linux distribution.

**Comment by pecko** [comment]
I'm running Debrief from Eclipse on Linux and it looks fine.

**Comment by IanMayo** [comment]
No, when I run the Linux version from standalone it still fails to show XOR text.

**Comment by pecko** [comment]
Do you change some Linux settings? Theme, Fonts ... Do you use standard Ubuntu 14.04 (or 14.10) 64-bit?

**Comment by IanMayo** [comment]
Sure.  My users are using Win7/32Bit Java, and they don't get the text shown.  Hmm, maybe they do see it, but the pixels are scrambled.

The original issue requests that the text be shown against a solid background. Your video shows the text shown against a solid background.  So - it looks like we don't need a new feature, we just need to get this feature working properly on my Linux & their Win7.

I know it's hard to investigate if you can't reproduce it :-(  Let me have a play with the rendering on my machine.

**Comment by IanMayo** [comment]
Here's my config:
![sysconfig](https://cloud.githubusercontent.com/assets/1108513/7475388/32191e32-f33f-11e4-92ab-9f697694be7a.png)

**Comment by pecko** [comment]
> So - it looks like we don't need a new feature

The PR creates popup background without XOR. It looks better when there is a painting bellow popup.
So, I think that we would probably apply the PR.

I will check Win 64-bit and 32-bit.

**Comment by pecko** [comment]
Just resume:
You can reproduce the issue on Linux Ubuntu 14.04 64-bit and Windows 7 32-bit with JDK 8 (you test JDK not JRE). Right?

**Comment by IanMayo** [comment]
Sorry Peco, have to break.

Yes I can reproduce the issue on Linux.  IIRC the onsite users have Win 7 64 bit with 32 bit Java.  They're certainly using JRE not JDK. I can't remember if they're using JRE 7 or JRE 8.

On my personal machine I have a Win 7 64 bit with 32 bit Java 8 JRE.  The rendering works perfectly on that.

**Comment by pecko** [comment]
OK. Will check ...

**Comment by pecko** [comment]
I have updated the PR https://github.com/debrief/debrief/pull/1214 so it doesn't use XOR mode at all.
See commit: https://github.com/pecko/debrief/commit/5fa6c551a761fd462ba82f3736afbff93df97179

@IanMayo Could you please try it?

Notice: It probably isn't ready to applying because change the DragFeature (setColor) that cann affect some other feature. ... Also it will not fix the issue related to "Measure rangebearing". ... but just to test XOR mode

**Comment by IanMayo** [comment]
Yes, the fix works perfectly for me :-)

![fixeddrag](https://cloud.githubusercontent.com/assets/1108513/7489167/a21ccd96-f3cb-11e4-9fe6-ddb7e71f0c95.png)

That's a relief.  

I've had a play with dragging other features (using the shapes.rep) file - and all worked fine.  I've also tried splitting and dragging track sections (to test the "TrackSegment" parent class) - and that worked fine too.

**Comment by pecko** [comment]
Do the "Measure range bearing" action work?

**Comment by IanMayo** [comment]
No, I still don't see any text for Measure Range & Bearing

**Comment by pecko** [comment]
You see a line. but don't see any text. There are the same issue on some Win 32-bit. Right?

**Comment by IanMayo** [comment]
Correct, I see a line, but not any text.

Afraid I can't remember if the users (32 bit Win) see any text or not. I'm next onsite on Monday.

**Comment by pecko** [comment]
Could you, please, try JDK7 on your machine?

**Comment by IanMayo** [comment]
You mean try JDK7 on my Linux dev machine?  

I could download and install it, but what would I do with it then?

**Comment by pecko** [comment]
You would extract it in some directory, add it as Installed JRE in Eclipse and start Debrief from Eclipse using this JRE. Eclipse uses term JRE, but you would download JDK.

You also can start distribution (Eclipse or Debrief) with adding the following in eclipse.ini (or DebriefNG.ini):

-vm
/usr/local/jdk1.7.0_71/bin/java

the -vm and /usr/local/jdk1.7.0_71/bin/java are two lines in *ini file

(I suppose that you extract JDK7 to /usr/local/jdk1.7.0_71.

**Comment by IanMayo** [comment]
@pecko  - can we talk in Google Hangouts?  I've just sent a screenshot.

**Comment by IanMayo** [comment]
Ok, checked "Master" branch onsite on MS Windows machines this morning.

The new "black text on white background" fix works perfectly on target machines.

I propose we apply the same fix to #1225.
