### ISSUE TITLE
Update Debrief Plot Schema

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1209]
We've introduced two new types of data (dynamic shapes, and dynamic track shapes).  We've also introduced some more symbology attributes.  I guess the symbology attributes may have resulted in changes to what is stored to XML.

The Debrief XML schema should be updated to reflect these changes.

**Comment by pecko** [comment]
I have created the PR: https://github.com/debrief/debrief/pull/1213

The PR includes:

- xsd definition for DynamicShapeSet
- fixing definition for the vector element
- add 2 files to sample_data (DynamicShapeSetTest.dpf and shapes.dpf) in order to test schema with TestPlotXsdFiles

**Comment by IanMayo** [comment]
Great - thanks for extending the test file.
