### ISSUE TITLE
XStream fails under JDK 8

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1217]
I forced Debrief to start under Java 8 - to investigate the track dragging text problem.

But, now I find I can't save or load XStream data (SATC dataset is stored using XSTream).

When I switched Java back to 7, it worked fine.

There are a couple of newer versions of XStream available, but the new versions don't seem to mention a Java version fix.

Could you investigate?  

You can reproduce the issue by using **Run Configuration** to change the execution environment to **JavaSE-1.7 (java-8-oracle)**, then trying to open **SATC/CompositeStraightTest.dpf**.  The file will open, but the SATC data won't be loaded - and errors are shown on the console.

Similarly, if I open a normal data plot (without SATC), then generate some SATC data, Debrief isn't able to store it.

Switching back to **JavaSE-1.7 (java-7-oracle)** works ok for me.

I'd like us to be able to read/store SATC data under Java-7 or Java-8 - I expect the first step is to try the newest version of XStream.

**Comment by pecko** [comment]
Fixed with replacin xstream 1.4.4 with new 1.4.8 version. The PR: https://github.com/debrief/debrief/pull/1219

BTW
The satc.core plugin includes some Geotools (8.0M4) libraries that it doesn't use. They should be removed.
Also, this plugin uses own version of jfreechart library (1.0.14). Now, we have common the jfreechart plugin (1.0.19). IMO, we should use common plugins everywhere.

**Comment by IanMayo** [comment]
Ok, could you do a new PR that removes unused libs?

**Comment by pecko** [comment]
Ok. Will create a new PR. Will I make it that use common jfreechart plugin too?

**Comment by IanMayo** [comment]
Yes please - the common jfreechart plugin

**Comment by pecko** [comment]
OK. Please apply this PR (it is simple and I have tested it). I will create a new PR just after that.

**Comment by IanMayo** [comment]
Merged

**Comment by pecko** [comment]
I have added new PR: https://github.com/debrief/debrief/pull/1221

**Comment by pecko** [comment]
I think that this issue is fixed.
