### ISSUE TITLE
Display of range/bearing text in Rng Brg Measurement tool

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1225]
This worked, then it didnt. 

It isn't working right now (64 bit JRE7, Ubuntu 14.04)

When I use the measure range/bearing tool, I don't see a displayed text.

I guess we need a fix similar to the one we used for #1204

**Comment by pecko** [comment]
What is your background? Could you save you current plot and attach them here?

**Comment by IanMayo** [comment]
It fails with light or dark backgrounds. 

This is with **sample.dpf**:
![screenshot from 2015-05-08 15 44 00](https://cloud.githubusercontent.com/assets/1108513/7538624/3a0d0890-f599-11e4-8189-dfa422a2c0ac.png)

**Comment by pecko** [comment]
You mean: It fails with sample.dpf from the master branch. Right?

Do you agree with the following solution: create text always as black on white background regardless plot's background. It would enable us to avoid XOR mode.

**Comment by IanMayo** [comment]
Yes - it fails with sample.dpf from the master branch.  It isn't visible in any plot I open.

Yes - your solution is satisfactory.  But, does it trigger a whole plot repaint?

(using XOR was a way of avoiding plot repaints during drag operations).

**Comment by pecko** [comment]
I'm not sure. Have to try. I would like to reproduce the issue. Have to some idea when/why it happens?

**Comment by IanMayo** [comment]
I get it every time I try to measure range/bearing - for every plot.

**Comment by pecko** [comment]
... but yesterday it worked fine. Right?

**Comment by IanMayo** [comment]
Yes - during our screen sharing. But I did have a suspicion that we rolled back one or more commits from that version.

**Comment by pecko** [comment]
You reproduce the issue with current master?

**Comment by IanMayo** [comment]
Yes

**Comment by pecko** [comment]
Trying ...

**Comment by pecko** [comment]
what eclipse version you are using?

**Comment by IanMayo** [comment]
3.8.2

**Comment by pecko** [comment]
I can't reproduce. I'm using Debrief master, JDK 1.8.0_45, Eclipse 3.8.2 (from target platform), Ubuntu 14.04 64-bit...
Could you try to reproduce it with Debrief distribution: https://github.com/debrief/debrief/releases/download/Stable_20150508_3.0.323/DebriefNG-Linux64Bit.tar.gz (I will also try it).

**Comment by IanMayo** [comment]
Sure. Will not be able to try it for a few hours - sorry.

**Comment by pecko** [comment]
np :)

**Comment by pecko** [comment]
The Debrief distribution works perfectly on my machine (as well as Debrief PDE from Eclipse)

**Comment by pecko** [comment]
@IanMayo Could you please also try the PR https://github.com/debrief/debrief/pull/1226
It will paint text with background. The PR is constrainted on Linux, because I think that there isn't this issue on Windows, but you will check it at Monday.

**Comment by pecko** [comment]
Second PR: https://github.com/debrief/debrief/pull/1227
This PR avoid XOR mode for painting text. The text is always painted as white on black (using DebriefColors white and black).
The PR is also limited on Linux.

**Comment by IanMayo** [comment]
Check user machines this morning, using new Master build (3.0.323).

The measured range and bearing is shown in mangled XOR text.  It's not possible to read the text when it passes over lines underneath.

I think this needs the fix that we applied to #1204

**Comment by pecko** [comment]
I have updated #1227 so it works similar #1204 (avoid XOR mode and work for all platforms). Only difference is that the font in #1204 is increased. Do you want me to increase font for range bearing too?

BTW #1225 is closed.

**Comment by IanMayo** [comment]
Nice work, thanks.
