### ISSUE TITLE
Can't editsensor arcs

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#1229]
The issue has been introduced with some new commit.
We can edit properties of sensor layer, but not for sensor arc entries.

The error log:

!MESSAGE Exception caught:Possible problem collating properties for:951212 053000-951212 054000 (class Debrief.Wrappers.DynamicTrackShapes.DynamicTrackCoverageWrapper)

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1230

**Comment by IanMayo** [comment]
One day in the future, when we use annotations to declare editable properties, we won't have this problem.

**Comment by IanMayo** [comment]
Fixed in #1230
