### ISSUE TITLE
Investigate replacing Tutorial & User Manual front-page in Travis

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1242]
I've got a task to design a more attractive front page for the User Manual.

It's a nightmare to do it with DocBook.  But, it's easy to design a new front-page as a 1-page PDF.  On our development machines it's then easy to replace the front-page in the user manual with my pretty one (prob using the pdftk command line tool)

But, we'd need to do this in Travis.   

Here's a new (dummy) title page:
https://github.com/debrief/debrief/commit/94de0bd33382a825f4047af9fad009a7555588d3

Could you experiment with swapping the PDF front page for this one, both in our local build and in the Travis build?

**Comment by IanMayo** [comment]
Ok, we have two new front page documents, one for the [user guide](https://github.com/debrief/debrief-materials/blob/master/userguide_cover/UserGuide_FlattenedForViewing.pdf), and one for the [tutorial](https://github.com/debrief/debrief-materials/blob/master/tutorial_cover/Tutorial_FlattenedForViewing.pdf).

These document are in the build process, both from Maven locally and in the Travis build.

**Comment by IanMayo** [comment]
@pecko  - I'd like you take on this issue next, please. But, if there isn't a straightforward fix then let's discuss the strategy.

**Comment by pecko** [comment]
@IanMayo 

> I've found on the Internet that there are command line routines that are able to swap pages in/out. 

What routines you mean here?

**Comment by IanMayo** [comment]
I'd appreciate you investigating a way that works for Travis - if there is one. 

But, there are two more important issues: #1263 then #1203

**Comment by pecko** [comment]
I will check pdftk. 
I understood this issue is priority. Will solve it shortly and try to fix another two (via weekend I hope)

**Comment by IanMayo** [comment]
No, the other two are priority. They're broken. This is nice to have.

**Comment by pecko** [comment]
I understand now, but, IMO, this one is almost solved. Just test travis build.

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1265
@IanMayo Travis build (https://travis-ci.org/debrief/debrief/builds/65639173) looks fine. Could you please check If I create pdfs that you want.

**Comment by IanMayo** [comment]
Brilliant - well done :-)

**Comment by pecko** [comment]
Thanks!
You should maybe write that build requires pdftk (sudo apt-get install pdftk on ubuntu) to some wiki or manual. o.m.d.help builds only on Mac and Linux.

**Comment by IanMayo** [comment]
Sure, good advice.

**Comment by pecko** [comment]
I think that this issue can be closed.
