### ISSUE TITLE
Introduce toolbar toggle to hide/reveal symbols in XY Plot

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1247]
It's possible to use the properties window to make symbols visible/not visible in an XY Plot.

It is really common that analysts wish to change the symbol visibility.  

Include an XY Plot View toggle button to hide/show symbols.

I suggest we have a toggle button that uses the two object hidden/revealed icon images from the Outline view.

**Comment by pecko** [comment]
I have prepared this fix, but will make a PR when you apply https://github.com/debrief/debrief/pull/1251 because possible conflict.

**Comment by IanMayo** [comment]
ok, #1251 merged

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1259

**Comment by IanMayo** [comment]
Fixed in #1259
