### ISSUE TITLE
Add boolean option for XY Plot View show legend

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1248]
Sometimes the XY Plot View legend isn't necessary.

We should add a property to the XY Plot View properties window that allows a user to switch the graph legend on and off.

If there is just one series displayed, I suggest that the legend is off by default.  But, it should be displayed by default if more than one series is present.

**Comment by pecko** [comment]
I have prepared this fix, but will make a PR when you apply https://github.com/debrief/debrief/pull/1251 because possible conflict.

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1260

Screenshot:
![image](https://cloud.githubusercontent.com/assets/534584/7991418/42b91c76-0af8-11e5-906b-42f1a426b04d.png)

**Comment by IanMayo** [comment]
Fixed in #1260
