### ISSUE TITLE
Wrong icon in About dialog

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1252]
The About dialog lists loaded features (or something like that).

But, it is showing the old Debrief icon, not the new one:
![aboutdialog](https://cloud.githubusercontent.com/assets/1108513/7863099/2cc02d5c-0552-11e5-9a70-67dd0d528737.png)

When I click on the Debrief icon, the Debrief NG Features panel opens up.  This also uses the wrong icon.

We need to switch to using the new icon.  If you tell me the required size, I can find you a correctly sized icon to use.

**Comment by pecko** [comment]
Where is a new icon placed?

**Comment by IanMayo** [comment]
We have a range of icons in the debrief-icons project:
https://github.com/debrief/debrief-icons

But, if you tell me what size is required I can give you a link to the correctly sized icon.

**Comment by pecko** [comment]
Currently, it is 250X64, but we can choose any size <= 250X300.

**Comment by IanMayo** [comment]
Hmm, I'm sure it's a square icon - so the height & width would be equal.

**Comment by pecko** [comment]
This is the current icon: https://github.com/debrief/debrief/blob/master/org.mwc.debrief.core/icons/DebriefNGlogoSmall.png

**Comment by IanMayo** [comment]
Aah, I haven't explained properly.  The "wrong" icon is the square "D" in the list of features - below the icon you're referring to.

**Comment by pecko** [comment]
What new icon you want? You can show me any size for starting...

**Comment by IanMayo** [comment]
Here's a 48px version:
https://github.com/debrief/debrief-icons/blob/master/48/icon.png

**Comment by pecko** [comment]
I have shown on about image/icon, but if you mean on feature icon, it has to be 32x32 and currently it is
https://github.com/debrief/debrief/blob/master/org.mwc.debrief.core/debrief_icon32.gif

**Comment by pecko** [comment]
I think I can scale 48 point icon to 32 point. Right?

**Comment by IanMayo** [comment]
Yes - please scale it.

**Comment by pecko** [comment]
OK. Will do it just after solving #1161. 
What about the About image/icon? We would keep current image?

**Comment by IanMayo** [comment]
The "Debrief" icon at the top of the About Dialog is the correct icon.

**Comment by pecko** [comment]
OK.

**Comment by IanMayo** [comment]
@pecko  - here's a crisp 32px icon:

![32x32](https://cloud.githubusercontent.com/assets/1108513/7866110/26a2e834-0565-11e5-92b7-3c30e454e8c0.png)

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1254
I'm using icon you attached above.

Screenshot:

![image](https://cloud.githubusercontent.com/assets/534584/7883467/04f9cd62-0617-11e5-98d0-36f1292969a2.png)
