### ISSUE TITLE
Put "Export to WMF" into an Eclipse job

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1277]
The "Export to WMF" job takes about 4 seconds on my machine.  I believe that for a very complex plot it can take almost a minute on user machines.

The first problem is that Debrief freezes during this process.  It would be great if we could avoid this.  But, I appreciate that we don't want the plot to change mid-way through the painting operation.

I'd also like to make a request - to put the export operation into an Eclipse job, so we get the progress monitor visible in the status bar, labelled as "Exporting to WMF". 

Finally, one small change.  I've currently got an invalid WMF export location - it's trying to export to "/d3__59_54.wmf" - but cant' because I'm not logged in as admin.  But, Debrief doesn't find out until the end of the export process (after a few seconds).  It would be better if we did this check at the start of the export, not the end.

**Comment by pecko** [comment]
the PR: https://github.com/debrief/debrief/pull/1289

**Comment by IanMayo** [comment]
Have given some feedback.  @pecko  - once we have a method of showing the progress bar without the background app freezing, could you apply the same method to the other WMF export process (export WMF embedded in RTF), please?

**Comment by pecko** [comment]
I will to solve it during day. The action requires UI thread, but we could separate this part.

**Comment by pecko** [comment]
@IanMayo  I have updated the PR with fixes for your suggestions. Please review!

**Comment by IanMayo** [comment]
@pecko  - could you also put the "Export image as WMF embedded in RTF"  (**ExportRTF.java**) operation into a similar progress dialog?

Note, I've pushed a commit that fixes a minor typo. So please *Pull* before you commit.

**Comment by pecko** [comment]
@IanMayo I have added the "Export image as WMF embedded in RTF" operation to a dialog. Your commit saved.

**Comment by IanMayo** [comment]
Yes, working fine.
