### ISSUE TITLE
Move PDF Front pages out of root_installs folder

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1280]
We insert our PDF front pages onto the tutorial & user guide.

That's working well.

But, we shouldn't have the front-pages in the root_installs folder, since they get installed on the user PCs.

I've put copies of the covers into a front_covers sub-folder.

We need to change the pdftk_title.sh script to use these versions, then delete the front covers from the root_installs folder.

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1287
