### ISSUE TITLE
Let Eclipse support Local History for DPF & REP files

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1292]
Eclipse provides Local History support for recognised file types (I just played with an XML file, and it worked perfectly):
http://www.aaronwest.net/blog/index.cfm/2007/3/23/Do-You-Know-About-Eclipses-Local-History

But, this isn't supported for DPF files.  Maybe we have to register them. 

@pecko - could you investigate if/how we would add this support for DPF & REP files?

**Comment by pecko** [comment]
The plot editor saved a file out of Eclipse. The PR https://github.com/debrief/debrief/pull/1297 fixes the issue.
It should be tested in network environment, because I only tested local file system (FileEditorInput).

**Comment by IanMayo** [comment]
thanks. got other things on today & tomorrow - will test on Weds morning.

**Comment by IanMayo** [comment]
1]  I've got the History window open, and **sample.dpf**, have right-clicked on a previous version, then selected "Get Contents" - "Do you wish to override contents".

The file gets overwritten, but the plot doesn't update.  I guess we can only update the plot to use the earlier version if we close then re-open the plot, right?

[I'm not asking for any implementation here, just your thoughts on the subject]

2]  With no plot open, when I right-click on an earlier version and select *Open in Debrief* I get this error:
````
!ENTRY org.mwc.cmap.core 4 0 Not expected file type:org.eclipse.team.internal.ui.history.FileRevisionEditorInput@7165b6002015-07-09 06:06:28.119
!MESSAGE data source for PlotEditor not of expected type:org.eclipse.team.internal.ui.history.FileRevisionEditorInput@7165b600
````

But, if I select *Open in text editor* I get the normal XML text contents.  Do we need to add support for the FileRevisionEditorInput type?

**Comment by pecko** [comment]
1) Right.
The Plot editor doesn't implement reloading when their input (file) is changed.

2) Right.
I think we should convert file content to Debrief plot (import it)

**Comment by IanMayo** [comment]
1).  Ok, let's leave that.

2).  Yes, I'd like you to investigate how to handle these files of type FileRevisionEditorInput. Please.

**Comment by pecko** [comment]
Of course.

**Comment by pecko** [comment]
I have fixed both issues.

1) It just close and open plot. I think that it is better to do it otherwise a user could have screen that isn't according to the plot file.
2) implement FileRevisionEditorInput

**Comment by IanMayo** [comment]
Great - working fine.
