### ISSUE TITLE
Format dragged track according to residual error

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1294]
Analysts face the challenge when dragging solution track legs of optimising the track on the plot the stacked dots, and viewing the current course/speed values for the solution (See the "single sided reconstruction" [tutorial](http://debrief.info/library/DebriefNG_TMA_Tutorial.pdf) ) .  This means that have to watch 3 parts of the screen at once.

We may be able to combine the information on the residuals plot with the spatial plot by color coding the points in the solution track according to the size of the error.  So,  we make an error of 5 degs green, and an error of 0 degs yellow, we can color code each point on the solution track according it's residual error. 

The error colors would only be shown whilst the track is being dragged - the real colors would return once the track leg is dropped.

When a track is being dragged, we currently draw the line in plain white.  An alternative strategy (that still allows for white-only track) is to draw a ring around each track point that is proportional to the error.  I guess the ring could be error * 3 pixels in radius (with the error trimmed at 5 [15 pixels] ).

This capability can be investigated using the **midflow2.dpf** test file.

**Comment by IanMayo** [comment]
@pecko - I look forward to you implementing this, but I think I first have to find a way to get the "error" value into drag-paint operation.

**Comment by pecko** [comment]
OK. Will try.

**Comment by IanMayo** [comment]
I've a suspicion it need me to tidily glue the numbers together before you handle the screen updates, but you're welcome to have a look.

**Comment by pecko** [comment]
Test PR: https://github.com/debrief/debrief/pull/1307
I have tried to get "error" and set color according that.

Notice: We have selected the white color carefully in order to fix dragging for different plot background.

**Comment by IanMayo** [comment]
Ok - I'm going to do some more work in this branch.  You're right about the reasons behind the track color.  I'm going to experiment with marker radius instead of color-code to show the error.

**Comment by IanMayo** [comment]
Ok.  I'm going to trial this with the users.  If they like the behaviour then I'll need to give  @russcrowley sufficient background to include the new behaviour in the tutorial and/or the user guide.
