### ISSUE TITLE
Remove viewing-in-3d from user guide

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1296]
We had to drop support for viewing in 3d a couple of years ago.  I did think that we should add a note explaining this, but we should probably both include the note *and* remove the 3d content.

**Comment by IanMayo** [comment]
@pecko - this isn't related to  #1281.  Did you mean to link from #1281 to another issue?

**Comment by pecko** [comment]
I'm not sure. Maybe to https://github.com/debrief/debrief/issues/1299.
