### ISSUE TITLE
Allow filled background & custom font for Scale Painter

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1308]
A user is having trouble viewing the Scale with a Natural Earth backdrop - since it's difficult to select a Scale color that can be seen both against blue sea and yellow land.

So, he would like to be able to switch on a filled background for the scale. He would also like to be able to choose the background fill color.

Lastly, he would also like to be able to change the Font used for the scale (both family and size).

These new capabilities will require changes to the Debrief plot schema.  We should use property names that match those we use for the Time Display object.

**Comment by pecko** [comment]
I suppose you mean Chart Features>Scale. I will add the following properties:

- Fill Background (boolean, default no)
- Background (Color, default white)
- Font (Font, default Arial, Plain 12 - current)

RE font, a user will be able to change family, size and style in the standard way.

**Comment by IanMayo** [comment]
Yes, correct changes. But let's be sure the new handling is backwards compatible.

**Comment by pecko** [comment]
I will set default values as current state in the code as well as plot xsd schema.

BTW I will add the Semi Transparent property. Not sure if you seen that.

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1310

The screenshot:

![image](https://cloud.githubusercontent.com/assets/534584/8687680/19d337a0-2a93-11e5-9824-07059500e0f8.png)


The plot xsd schema has been also updated.

**Comment by IanMayo** [comment]
Thanks for the implementation.

But, the semi-transparent fill doesn't seem to work.  With semi-transparent switched off, we see the correct fill.  With semi-transparent switched on, we just see a black background.  Here's an example with semi-transparent off (correct behaviour):
![notsemitransparent](https://cloud.githubusercontent.com/assets/1108513/8698317/ef04d4b8-2af4-11e5-9a1a-4bc3d1b818cd.png)

And here's one with semi-transparent on:
![semitransparent](https://cloud.githubusercontent.com/assets/1108513/8698319/f2b407b4-2af4-11e5-8aad-e3563c68eaf6.png)

**Comment by pecko** [comment]
I will check later.

**Comment by pecko** [comment]
I have updated the PR, so semi persistent works almost the same as TimeDisplayPainter. The issue you noticed happens because the scale widget is placed to the Chart Features layer. This layer is buffered and creating transparent swt image in this case doesn't work correctly.

I think that we should solve it in another issue.

**Comment by pecko** [comment]
Screenshot when the Chart Features layer isn't buffered (both, scale and time display has green background and semi transparent properties):

![image](https://cloud.githubusercontent.com/assets/534584/8703459/7824445e-2b1d-11e5-89f9-4d754f787330.png)

**Comment by pecko** [comment]
I'm just set the Chart features layer as unbuffered to create the screenshot. It isn't changed in the code.

**Comment by IanMayo** [comment]
Closing - buffering issue moved to #1313

**Comment by pecko** [comment]
Really closing :)
