### ISSUE TITLE
Upgrade travis

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#1312]
We should upgrade legacy Travis to container-based infrastructure:

http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

We have to adapt our sudo command.

**Comment by pecko** [comment]
It really start in seconds.
Testing if it will install our required package ...

**Comment by pecko** [comment]
The first version doesn't work :(

**Comment by pecko** [comment]
We need really exotic package. It isn't on white list and building require GCJ, GJAR ...

**Comment by pecko** [comment]
@IanMayo  I have sent mail to travis support and cc you.

**Comment by IanMayo** [comment]
So do we need to build our own binary, then upload it to Amazon S3?

**Comment by pecko** [comment]
We could, but we don't know what travis run (probably ubuntu, but now it is docker and very hard to estimate). 
I'm trying that and we will se what will they answer. Maybe it will be just some permission (adding pdftk to whitelist).

**Comment by pecko** [comment]
Seems we just need pdftk. Will try update it on my server and we will where we will really host that.

**Comment by pecko** [comment]
starting travis https://travis-ci.org/debrief/debrief/builds/71318141

**Comment by pecko** [comment]
The pdftk binary from my ubuntu (14.04 64-bit) doesn't work. Installing from source is hard because it requires gcj-jdk that also doesn't exists on travis. We will see what their support tell.

BTW builds start immediately and they are slight faster.

**Comment by pecko** [comment]
We got correct answer from support. The pdftk package is added to whitelist and this PR is valid now.
You can check created pdf's, just in case.

**Comment by pecko** [comment]
The build really start very fast and takes 7-8 minutes. See https://travis-ci.org/debrief/debrief/builds/71479759

**Comment by IanMayo** [comment]
great news :-)

On 17 July 2015 at 22:14, Haris Peco <notifications@github.com> wrote:

> The build really start very fast and takes 7-8 minutes. See
> https://travis-ci.org/debrief/debrief/builds/71479759
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/debrief/debrief/issues/1312#issuecomment-122419859>.
>



-- 
Ian Mayo
Deep Blue C Technology Ltd
- New technologies, implemented well

**Comment by pecko** [comment]
No, we don't. We just need apply the PR :)

**Comment by IanMayo** [comment]
@pecko - just looked at the Travis build. There's a warning about sudo:
https://travis-ci.org/debrief/debrief/builds/71763464#L119

Do we still run a mvn script that includes sudo?

(just wondering)

**Comment by pecko** [comment]
> Do we still run a mvn script that includes sudo?

No, we don't use it directly as before, but seems travis uses it when running our addons - installing pdftk (see https://github.com/debrief/debrief/blob/master/.travis.yml#L6).
It works fine because we face the "pdftk isn't found" when run o.m.d.help plugin before travis team adds pdftk to whitelist. I think that warning doesn't have any effect. It's just warning now.
Anyway, you could check if pdf files are correctly in a new build (first page replaced as required in https://github.com/debrief/debrief/issues/1280)

**Comment by pecko** [comment]
This issue has been solved.
