### ISSUE TITLE
Drop in performance for dragging tracks since March build

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1318]
I was with a user today, showing off the new "show bearing error via scaled circles" capability (#1294).

But, when we tried to drag his track, it was really slow.  We moved back through some previous versions, and found that a build from 16th March worked perfectly ( https://github.com/debrief/debrief/releases/tag/Stable_20150316_3.0.317 )

Just in case we need to reproduce the problem, here are the specifics of the data:  
* 8 hours of ownship data, with positions on the minute
* 980 sensor cuts, spanning 8 hours
* 3 legs of target track, roughly 2 1/2 hours each

The significant changes since then seem to be:
* switch to JFReeChart-SWT  #1169 
* switch from JFreeChart scaling up beyond a certain size to always rendering at native scale
* change to ensure we display the solution's course and speed #1204 

Steps to reproduce:
* load sample_lots_of_sensors.dpf
* under the Osprey track, switch on the Sensor titled **Sensor:sensor:0 (1505 items)**
* right-click on that sensor, and select **Generate TMA solution from all sensor cuts**
* from the wizard, click on **Next**, then **Finish**
* a new track will appear in the Outline view: **Track:TMA_120532.02**
* make this track the Secondary track (select it, then click on the "2" in the Outline toolbar)
* switch to **Drag track segment** view
* start to drag the new red track, you'll see it moves really, really slowly.

Hopefully you'll be able to reproduce the above performance problem, and identify that it doesn't occur in the March builds.

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1323

I have used "Sensor 3:94 (5454 items)", have created a track and dragging the segment is pretty slow.
IMO, main reason is the BearingResidualsView.getValueAt(HiResDate) method that searching time using loop for all positions in time series.

Enhancements in the PR:

- using TimeSeries.getIndex(RegularTimePeriod) that optimizes above mentioned searching (I think that it is main enhancement)
- avoid creating Double object and Date object as well as unnecessary Double->double>int conversions (We call this method very often when dragging, so creating object can be significant)

I have added another enhancement (not related to speed):
- when getValueAt doesn't find any value it return 0. It is used to paint and Debrief paints nothing. I have changed so Debrief uses standard height=4 for this case.

After this changes, I can't see some difference when comparing with a build from 16th March. However, it is possible that there are a difference when dragging a track with much more positions. If you face such case, please try to uncheck the "Show the error when dragging" button in order to locate reason for slowing. If it is good when the button is unchecked then this method is yet slow.

**Comment by IanMayo** [comment]
@pecko  - I've had a play, but the performance is still too slow on my machine, though release 3_0_317 also seems slow. 

I expect to visit the relevant user tomorrow, I hope to double-check what the "lots of errors" plot-file performance is like on his machine.

**Comment by pecko** [comment]
@IanMayo I'm not sure what you claim:

You test using your steps above and there is still big performance difference between release 3_0_317 and this PR. Right?

Do you see that the PR enhances performance?

**Comment by IanMayo** [comment]
Hmm, when I run 3_0_317 on my machine it's running slowly.  When I run the PR, it's also running slowly.  The processing in both is so slow that any difference/improvement is hidden from me.

**Comment by pecko** [comment]
What you test? What happens when you try the master without the PR?

I can't reproduce too bad performance, but the PR improve performance and it is similar as release 3_0_317.

**Comment by IanMayo** [comment]
When I follow the steps at the start of this ticket, it takes about two seconds to redraw the line as I try to drag it.  This two second delay effectively means it can't be dragged.

I'll investigate more later, and try on a user (MS Windows) machine tomorrow.

**Comment by pecko** [comment]
OK. I will test again later. Suppose you mean that it is almost same in release 3_0_317, master (with and without patch).

**Comment by pecko** [comment]
I have tested again.
I use your test, but I select Sensor:1 (3904 items) instead of Sensor:0 (1505 items) because it contains more items and work slower.

You can test in the following way:

- uncheck the "Show the error when dragging" button 

The performance will be the same as in release 3_0_317

- check the "Show the error when dragging" button 

The performance will be slower than in release 3_0_317, but not too much.

If you try the same without patch, you will see bigger difference.

Using TimeSeries.getIndex(RegularTimePeriod) instead of whole loop have to increase performance. Other changes will also improve performance, but not too much as indexing.

**Comment by IanMayo** [comment]
I tried the user machine this morning.  He's using version 3.0.327.  When he tries to drag the "Sensor:0" track there is at least a 1-second pause before the dragged track gets redrawn.

When he closes the "Bearing Residuals" view the performance is instantaneous.  I now remember that when I first encountered the problem I thought it may have been related to how we changed JFReeChart from scaling the image to plotting at native resolution.  It is now plotting a lot, lot, more pixels.

When he clicks on "Drag feature" then back to "Drag track segment", then Bearing Residuals view opens, the performance slows down again.

I hope to experiment with your suggested performance test this afternoon or tomorrow.

**Comment by pecko** [comment]
What happens when you uncheck the "Show the error when dragging" button?

**Comment by IanMayo** [comment]
Ooh, I wish I'd thought of that when I was in there :-(

**Comment by pecko** [comment]
I don't understand. It is important how checking/unchecking of this button affects performance because we will know if the BearingResidualsView.getValueAt(HiResDate) method is main culprit (I think that it is).

**Comment by IanMayo** [comment]
Yes. You're right. It was important to check that.  I was focussing on "does the user experience the problem in our sample data in addition to his real data?"

**Comment by pecko** [comment]
IMO, showing error is the biggest difference between version 3.0.327 and current version. 
I'm pretty sure that it is main bottleneck. 
The performance will be worse when we check showing error, but this PR enhance that pretty good.

**Comment by pecko** [comment]
> I tried the user machine this morning. He's using version 3.0.327. When he tries to drag the "Sensor:0" track there is at least a 1-second pause before the dragged track gets redrawn.

This is weird for whatever version. This sensor drags quickly on my machine (not too fast: ASUS k52J, Intel i3 , 4gb RAM).
What machine you test?

**Comment by IanMayo** [comment]
My machine is 6-core AMD, 24Gb.

But, if you don't click on "Set Secondary", there is no performance delay, since it only does all the calcs if the new TMA track is set as secondary.

I'm back on this on Thursday morning (tomorrow I have meeting in AM, then I have to review user tutorials in PM). There is no immediate hurry on this.

**Comment by pecko** [comment]
I forget "Set Secondary". Will check later...

**Comment by pecko** [comment]
Clicking "Set Secondary" on the track doesn't change the performance for me. 
I have created screencast: http://www.snpe.rs/516.ogv

I probably skip something.

**Comment by IanMayo** [comment]
*finally* had chance to play with your branch again.

I see there are no performance problems in your video.  But, suspect it isn't doing the calculations (particularly since no data gets shown in the Bearing Residuals view).

Here's a video of the performance I get using your branch:
[DragPerformance.ogv | uploaded via ZenHub](https://files.zenhub.io/55d1db7d4bea290a348bea18)

You'll see that it's really, really slow.

**Comment by IanMayo** [comment]
Hmm, here's the 317 performance on my machine - it's also slow:
[317_perf.ogv | uploaded via ZenHub](https://files.zenhub.io/55d1dfc44bea290a348bea4d)

**Comment by pecko** [comment]
I can reproduce the issue. It is necessary to set Sensor:0 visible. The fix enhances the issue when the "Show the error when dragging" button is checked, but dragging is slow when it is checked or not.
The issue exists a long time ago. It is just more visible when showing the error.

Will try to enhance it.

**Comment by pecko** [comment]
I have added the commit: https://github.com/pecko/debrief/commit/454f5b5b9abee259d1476742eb010f5c7f1ec2d4 to the PR: https://github.com/debrief/debrief/pull/1323

Debrief updates the Bearing Residuals view too aggressively, that is, after each drag move. If view's calculation is longer it will slow down UI thread and mostly calculation will not be significant (visible).
The PR do two tricks:
- updates the Bearing Residuals view asynchronous
- wait if there is some calculation in progress

This way, dragging operation has priority in UI thread and run quickly. You will notice that updating (redrawing, calculating ...) in the Bearing Residuals view is a little delayed.

I hope that is acceptable solution.

**Comment by IanMayo** [comment]
@pecko - when you get chance, could you record a video to compare dragging before and after applying the change.

[I can't see a difference, but I may be looking for the wrong thing]

**Comment by IanMayo** [comment]
@pecko - this is my highest priority for you next, please.

**Comment by pecko** [comment]
I'm working on that. Just rebased it.

**Comment by pecko** [comment]
Screencast 1: http://www.snpe.rs/perfwithpatch.ogv
With patch. I made two tracks with Sensor 0 (1900+ items) and Sensor  (3900+ items).
You can see that painting in the Bearing residuals view has delay, but dragging is fast.
I will prepare the screencast without patch asap:

**Comment by pecko** [comment]
Screencast 2 (without patch): http://www.snpe.rs/perfwithoutpatch.ogv

**Comment by pecko** [comment]
Conclusion: 
with patch - dragging work as expected, but painting in the BR view is delayed

**Comment by IanMayo** [comment]
Ok - I see the benefit.  I'll have a play.

**Comment by pecko** [comment]
> Have removed the lazy screen update fix - it was making small/simple dragged tracks slower, with intermittent updates.

I think that you removed main enhancement.
Namely, (when the Bearing Residuals view is opened) Debrief will recalculate the plot for each drag event. It will significantly slowing down dragging when there are a lot sensors (calculation point). It is often calculated unnecessarily (user already drag to a new position, but Debrief still calculate old, finish old unnecessarily and calculate a new position).
With "lazy screen update", dragging has priority and "calculating" will not slowing down (lock) dragging. The calculation (JFreeChart plot) will be always done, but with some delay. It is more important that dragging works smoothly; user will see plot (maybe with delay, but it isn't too important. 

Also, this issue existed in all versions of Debrief. It isn't regression.

I have seen your comment:

>  +		final Display display = Display.getCurrent();
> +		long waitTimeMillis = 5 * 60 * 1000;
> @pecko - doesn't this mean 5 minutes? Surely that's too long for a timeout.

It is just in case. If some plot calculation takes more than 5 minutes it will be stopped. It won't happen in real cases. Even, if it happens, it just means we skip a big JFreeChart calculation. It isn't big issue. Will be recalculated on next drag.
Anyway, it will not block dragging. In current, it could be happen.

So, I suggest that you test this commit yet once.
