### ISSUE TITLE
Cheat Sheet generation - bookmarks

### ISSUE THREAD

**Issue by russcrowley** [debrief/debrief#1324]
When the cheat sheet pdf's are generated, is it possible to generate book marks as part of the process? This aids navigation, structure, etc.

It only takes a few minutes to add them manually, but it would be great if this was generated from Heading 1 - 3's. If it isn't possible, may I suggest sending them across to me to be added manually, and then added to the distribution zip(s). It will enhance the user experience enormously.

![pdf_bookmarks](https://cloud.githubusercontent.com/assets/10422030/8898951/d8b2be7a-3457-11e5-8ebd-9a04fe926fff.PNG)

**Comment by IanMayo** [comment]
Good suggestion Russ.

The engineer in me dreads having anyone naturally insert the links for each update, but I am hopeful we can configure our build process to generate the bookmarks.

**Comment by russcrowley** [comment]
Thanks Ian,

Further to this, if it's possible, I'd also recommend setting the pdf 'Initial View' properties, to:
* Navigation tab: 'Bookmarks Panel and Page'
* Page layout: 'Single Page'
* Magnification: 'Fit Page' 
* Open to Page: '1'

Please see attached. I have actions set up in Acrobat to do this automatically for me, and it's far more visually appealing than being zoomed in at 167% on the image. It'd be great if we could automate this as well.

![pdf_properties](https://cloud.githubusercontent.com/assets/10422030/8922110/dd2b6a86-3508-11e5-89fd-ce814e192c71.PNG)

**Comment by pecko** [comment]
I think that we add this feature by https://github.com/debrief/debrief/issues/1343
