### ISSUE TITLE
VectorLabelVisible property in planning segment

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#1326]
The UI contains this property, but it isn't persisted to xml (*dpf).
The fix will require adding it to debrief plot schema (https://github.com/debrief/debrief/issues/516).

@IanMayo  I will fix it when you apply the fix for #516: https://github.com/debrief/debrief/pull/1325

**Comment by IanMayo** [comment]
great, thanks.

**Comment by pecko** [comment]
Fixed by commit: https://github.com/pecko/debrief/commit/3d08941e94f2289f82f7755bae6ad153613992e7 within the PR: https://github.com/debrief/debrief/pull/1325

**Comment by pecko** [comment]
Now, the commit https://github.com/debrief/debrief/commit/3d08941e94f2289f82f7755bae6ad153613992e7 is applied in the master.
