### ISSUE TITLE
Command line processing to insert PDF bookmarks.

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1336]
As you know, we're switching to PDF tutorials.

But, our toolchain from Google Drive to PDF doesn't produce the index that shows like a side-bar based table of contents.

Here is a PDF where the index has been created by hand: 
![tutorialwithindex](https://cloud.githubusercontent.com/assets/1108513/9526030/046fc496-4cdf-11e5-8e89-995c210adf09.png)

But,  the PDF produced from Google Drive doesn't include these headings.

I'd like you to investigate to see if pdftk can automatically create an index of h1 & h2 paragraphs.

**Comment by IanMayo** [comment]
Here's a raw file for you to experiment with:


[TutorialWithoutIndex.pdf | uploaded via ZenHub](https://files.zenhub.io/55df37c5ac61d2626d5ceab7)

**Comment by pecko** [comment]
> Here is a PDF where the index has been created by hand: 

How you do it "by hand"? Could you attach the file with indexes?

**Comment by IanMayo** [comment]
"By hand" - my author freelancer uses Adobe Acrobat Pro to select paragraphs and then select "add to index" (or something like that).

Here's an article showing how the bookmarks are created:
http://www.w3.org/TR/WCAG20-TECHS/PDF2.html

The article shows that they're actually "Bookmarks", not an "Index".

**Comment by pecko** [comment]
I think that it's possible, but not sure if pdftk can do it. Will review it more tomorrow.

**Comment by IanMayo** [comment]
@pecko  - I'm looking at the pdftk man-page:
http://manpages.ubuntu.com/manpages/utopic/man1/pdftk.1.html

It looks like *Outline* levels can be produced using the *dump_data* command, then these can be inserted back into the pdf using *update_info*

**Comment by pecko** [comment]
Seems, it's possible. Do you have the pdfs with bookmarks (indexes) or want me to create such pdfs?

**Comment by IanMayo** [comment]
There's a PDF for you to experiment with higher up in this issue **TutorialWithoutIndex.pdf**

**Comment by pecko** [comment]
OK. You want me to add bookmarks here, extract them with dump_data and use extracted file(s) to add bookmarks to final pdfs. Right?
I can also experiment with current pdfs.

**Comment by IanMayo** [comment]
Note quite:

    Reads a single, input PDF file and reports various statistics, metadata, bookmarks (a/k/a outlines), and page labels to the given output filename or (if no output is given) to stdout

I'm hoping that when dump_data finds "outlines", that these are the h1, h2, etc headings from the PDF.  When we export a document to PDF from MS Word, it automatically goes through the document and creates bookmarks from the content - to give a set of bookmarks like in the screenshot at the top of the page.  But, when we export from Google Drive - it doesn't create these heading contents.  We're trying to use pdftk to do this for us.  So, pdftk will provide the list of document headings, then pdftk will insert those headings as bookmarks.  Fingers crossed...

**Comment by pecko** [comment]
I will try it today later.
I think that the dump_data command will dump existing bookmarks (outlines), but will check ...

**Comment by IanMayo** [comment]
Sure - no rush.

**Comment by pecko** [comment]
The pdftk's dump_data will export a bookmark only if it exists, so we have to create bookmarks and put them with upload_info. I think that MS Word/LibreOffice works in this way too - we have to create a table of contents in order to insert a bookmarks.

I have created the bookmarks manually and created the files (nbtutbook.txt and ngtmabook.txt for our tutorial and tma pdfs). Unfortunately, these files have to be updated if we change the structure of our pdfs.
The pdftk_title.sh script has been updated so it inserts bookmarks.
The PR: https://github.com/debrief/debrief/pull/1338

New pdfs:

http://www.snpe.rs/DebriefNGTutorial.pdf
http://www.snpe.rs/DebriefNG_TMA_Tutorial.pdf

**Comment by IanMayo** [comment]
Hmm, it isn't acceptable to require the text files to be manually updated.

I'd like us to explore an alternative strategy:
* produce a PDF direct from Google Docs (pdf-1)
* download as "rtf" from Google Docs
* open the rtf in LibreOffice (or similar)
* export the rtf to PDF (pdf-2)
* use pdftk to extract the table of contents text file from pdf-2
* use pdftk to insert this table of contents into  in pdf-1

Note: we're not using the LibreOffice exported PDF since it "mangles" much of the formatting.

@pecko - could you try this?

**Comment by pecko** [comment]
I don't sure if I or you understand pdftk possibilities. 
If your pdf-1 contains bookmarks, we have to do nothing.
If it doesn't contain bookmarks, pdftk can't produce it.

pdftk can extract some bookmarks only if the bookmarks exists. Of course, in this case we have to extract/insert nothing.
It also can insert bookmarks from txt file in specific format, but can't produce this txt file from pdf without bookmarks.

IMO, it is the same if you use MS Word or something else. We have to create table of contents manually (similar our bookmark txt file).

I'm not sure if there are some software that will recognize some pdf formatting and create bookmarks. pdftk (and jpdfbookmarks) that I use for creating bookmark manually) can't do it.

Maybe, I don't understand the issue. You can try:

```
pdftk <some_pdf> dump_data output report.txt
```

if '<some_pdf>' doesn't contain bookmarks, report.txt doesn't contain it too.

**Comment by IanMayo** [comment]
Yes - it was difficult to explain.

PDF-1 won't contain bookmarks, since they're not present in Google to PDF.  But, PDF-2 will contain bookmarks, since MS Word/LibreOffice to PDF does include bookmarks.

But, PDF-2 will be badly formatted.  So, we take the bookmarks from PDF-2 and inject them into PDF-1.

Hopefully that is more clear.

**Comment by pecko** [comment]
Sorry, I still don't understand.
Where I (tycho build) would start?

**Comment by IanMayo** [comment]
Yes, it's a bit twisted.

I suggest you perform steps 1 to 4 by hand - to give you two PDFs. Then you perform 5 and 6 at the command line using tycho.

If this results in a correctly formatted PDF that has page number index, we can try to automate it in tycho.

**Comment by pecko** [comment]
We can try if you can provide some pdf-1 example.
IMO, pdftk will do nothing in steps 5 and 6. It will extract existing bookmarks and put the same one.
Beside that, I'm not sure what we will get if we do 1-4 manually. It is the same as creating bookmarks how I do it. I have used JPdfBookmark; you can review it (java -jar jpdfbookmark.jar) - http://sourceforge.net/projects/jpdfbookmarks/

**Comment by IanMayo** [comment]
IMO, pdftk will do nothing in steps 5 and 6. It will extract existing bookmarks and put the same one.

Aah, there's the magic. We're extracting bookmarks from pdf-2 (which contains them) and inserting them into pdf-1 (which doesn't contain them).

Performing steps 2-4 manually gives us pdf-2, a PDF document that contains bookmarks. We're going to put these bookmarks into pdf-1.

**Comment by pecko** [comment]
OK.
It's just way to create bookmarks. I do it with jPdfBookmark (it is GUI) and you propose steps 1-4. In any way we will have hard-coded (bookmarks create manually).
... or you mean that we can anyhow automate steps 1-4 too.

**Comment by IanMayo** [comment]
"bookmarks create manually"

No, in my method we don't create them manually.  MS-Word/LibreOffice create them automatically - we then re-use them.

**Comment by pecko** [comment]
When I tell manually, I mean: "tycho don't do it"
I just do the following:

- make bookmarked pdf-1 as described in your step 1-4, but using jPDFBookmarks. It is GUI, not editing txt files and it is certainly easier than your steps 1-4
- create ngtutbook.txt and ngtmabook.txt by pdftk extracting (dump_data) - step 5
- create a script to enter these txts (bookmarks) to new pdfs - step 6

> MS-Word/LibreOffice create them automatically

What you mean. It will takes our pdf and create bookmarks? If so, how to do it?

**Comment by IanMayo** [comment]
>>     MS-Word/LibreOffice create them automatically

>     What you mean. It will takes our pdf and create bookmarks? If so, how to do it?

When Word/LibreOffice produces a PDF, it scans through the headings and produces bookmarks for those headings.

But, Word/LibreOFfice mangle the layout.  So, we can't use the exported PDF. 

So, I'm proposing that we use the extracted ToC files from Word/LibreOffice export, and inject those ToC files into the correctly laid out pdf-1 files.

**Comment by pecko** [comment]
> But, Word/LibreOFfice mangle the layout. So, we can't use the exported PDF.

OK. You mean we will extract bookmark from pdf-1 (invalid layout) and put them to pdf-2 (valid layout, but without bookmarks) and create pdf-3 with valid layout and bookmark.
If so, question is: How to create pdf-1? I don't know do it.

**Comment by IanMayo** [comment]
> OK. You mean we will extract bookmark from pdf-1 (invalid layout) and put them to pdf-2 (valid layout, but without bookmarks) and create pdf-3 with valid layout and bookmark.

Exactly

> If so, question is: How to create pdf-1? I don't know do it.

Hmm, I'll share a Google Drive document with you.  I'd like you to try "export as RTF", then open the .rtf in a Word Processing application. Then export the document as PDF - and check if the bookmarks have *magically* been inserted.

If that works, then you have your pdf-1.

**Comment by pecko** [comment]
OK. Will try ...
We will repeat creating pdf-1 (bookmarks) when changing our pdfs. Right?

**Comment by IanMayo** [comment]
Sadly we may have to repeat creation of pdf-1 and pdf-2.  But, at least we won't have to generate every single bookmark by hand.

**Comment by pecko** [comment]
Question:

Let's tell that I have pdf-1 now. Since it isn't some as some our pdf, I also need pdf-2. It will be exported as pdf on Google Drive. Right?

**Comment by pecko** [comment]
> Sadly we may have to repeat creation of pdf-1 and pdf-2. But, at least we won't have to generate every single bookmark by hand.

Please try jPDFBookmarks. It generates pdf bookmarks with GUI and we will need just update it when updating our pdfs. 
I think that it will be easier than Google drive/LibreOffice ....

**Comment by pecko** [comment]
I have tried the following:

1) export 01a_Tutorial_WorkingwithDebrief as pdf

It creates pdf-1 without bookmarks 

2) export 01a_Tutorial_WorkingwithDebrief (Google Docs) as *.odt, import it to LibreOffice and create a pdf

It creates pdf-2 (steps 2-4) that contains bookmarks

3) extract metadata (including bookmarks) using pdftk from pdf-2
4) insert metadata (including bookmarks) created in previous step to pdf-1

So, it works as you expected.

The PR replicates this procedure in the following way:

- it contains the 2 pdf files with bookmarks: DebriefNG_TMA_TutorialIndexed.pdf and DebriefNGTutorialIndexed.pdf
We have to create these files (with Google Docs, jPDFBookmarks or however ...)
They are your pdf-2 files

- the org.mwc.debrief.help plugin will create pdf-1 files without bookmarks:  DebriefNG_TMA_Tutorial.pdf and DebriefNGTutorial.pdf

- updated pdftk_title.sh will extract metadata/bookmarks from pdf-2 (indexed) files and insert them to corresponding pdf-1 files. 

Final pdfs (DebriefNG_TMA_Tutorial.pdf and DebriefNGTutorial.pdf) will contains bookmarks as they defined in DebriefNG_TMA_TutorialIndexed.pdf and DebriefNGTutorialIndexed.pdf

Hoping, I finally understood what you wanted.

**Comment by pecko** [comment]
This isn't necessary after fixing #1343
