### ISSUE TITLE
Remove right-click "Properties" from JFreeChart

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1339]
User can create XY-plots of calculated or measured data (range, course, speed, etc).

We use the "standard" Debrief property editor to let the user customize these charts.  Debrief remembers the changes.

But, JFreeChart also provides a property editor (accessed by right-clicking on an XY Plot).  This is unnecessary, and may cause confusion.

Is it very difficult to remove the "Properties" from the right-click menu?

**Comment by pecko** [comment]
It's pretty simple :) . The PR: https://github.com/debrief/debrief/pull/1340
