### ISSUE TITLE
Time marker missing from XY Plots

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1341]
We can create an XY Plot (such as a graph of the range between two tracks).

When we move forwards and backwards in time (via the Time Controller), a vertical marker should move backwards and forwards through the XY Plot.

This marker is missing from the current version.

**Comment by pecko** [comment]
It works in some older version (when we use swing chart composite). Will explore tomorrow (today later).

**Comment by pecko** [comment]
The problem was redrawing in swt chart composite.
Fixed by the PR: https://github.com/debrief/debrief/pull/1347

**Comment by IanMayo** [comment]
@pecko  - could you explain how the fix works?

The new code is quite different to the previous code:
https://github.com/debrief/debrief/pull/1347/files

**Comment by pecko** [comment]
The old code was my trick  to refresh _plotControl. Unfortunately, it doesn't refresh time stepper :( . The new code is copied from JFreeChart's swt chart composite (not sure exactly where I found it, but I already used it in a mouse event). It refreshes complete chart properly.
I'm not sure if you want me to investigate deeply, that is, to investigate how exactly JFreeChart notification work.

**Comment by IanMayo** [comment]
No, don't worry about investigating further.  Your explanation is fine.
