### ISSUE TITLE
Switch to manually generated PDF tutorials

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1343]
We've reluctantly moved away from eclipse cheat sheets for the tutorials.

PDFs for the two tutorials are now generated externally.  We will no longer build them within Debrief.

Could you change the build control so that we no longer generate the PDFs from cheat sheets.  

Note: *this also means removing the pdftk ToC generation you created last week*.

Also, please replace the computer-generated PDFs in root_installs with the attached/linked versions:

[DebriefNGTutorial.pdf | uploaded via ZenHub](https://files.zenhub.io/55f28fdb94d876d2311a76a3)

[DebriefNG_TMA_Tutorial.pdf | uploaded via ZenHub](https://files.zenhub.io/55f28fdb94d876d2311a76a2)

**Comment by pecko** [comment]
Does it mean that we can remove skip the o.m.d.help plugin?

**Comment by IanMayo** [comment]
We still need to produce the User Guide from the DocBook ng_help.xml (including all the FOP/XSL processing) in **collate_docbook.xml**.

But, we don't need to do the **cheat_transform.xml**

**Comment by pecko** [comment]
OK. Will to remove unnecessary stuff.

**Comment by pecko** [comment]
I have removed all stuff related to cheat_sheets.
The PR: https://github.com/debrief/debrief/pull/1346

**Comment by IanMayo** [comment]
There seems a problem here: it looks like the XSL generated cheat sheets are still being included in the dist.  But, it's our manually generated version that is in [the repo](https://github.com/debrief/debrief/blob/master/org.mwc.cmap.combined.feature/root_installs/DebriefNG_TMA_Tutorial.pdf).  So, it looks like the manually generated one is being overwritten.

**Comment by pecko** [comment]
I'm not sure what I should to do here.

We would keep cheat sheets part, just comment it. Right?

**Comment by pecko** [comment]
The PR https://github.com/debrief/debrief/pull/1346 updated.

**Comment by IanMayo** [comment]
@pecko - spotted a problem with this issue.

The change has prevented the PDF Title page being added to the normal Debrief user guide.  

We were meant to drop PDF transformation of the tutorials, but we also cancelled the step where we add the "flattened" front page to the Debiref user guide.

So, the first couple of lines of pdftk_title.sh still need to be run.  We also need to declare pdftk in our travis.yml build file.

**Comment by pecko** [comment]
@IanMayo 

Please review the PR: https://github.com/debrief/debrief/pull/1356

**Comment by IanMayo** [comment]
great, thanks.

**Comment by pecko** [comment]
checking travis yet...

**Comment by pecko** [comment]
It's OK. Ready to apply.

**Comment by IanMayo** [comment]
Working fine.
