### ISSUE TITLE
SensorArc shading

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1410]
FD said:
Also I have been playing with SensorArcs and note that I cannot turn the shading off, i.e. just have the line of the arc. The help suggests I can have the values of 0 (non-filled), 1 (transparent), 2 (semi- transparent) in the rep file but 0 doesn’t seem to do anything and from within the GUI there is no non-filled option.

**Comment by helenayele** [comment]
Hey @saulhidalgoaular, would you please put the steps to verify this issue?
