### ISSUE TITLE
Split long narrative lines

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1413]
FD said: 
I also think in the more recent versions something has happened to the Narrative window. Previously if my narrative line was long (i.e.it would not fit within the window) there was an option to split it with a new line but I cannot seem to do that now.

**Comment by IanMayo** [comment]
FD gave new input:
In previous versions if you had narrative text that went beyond the window you could select ‘Clip to visible space’ and it would show the remaining text on a new line. In the latest version (and several versions before this, at least a year) it literally does just clip the text meaning that there is no way of seeing the additional narrative text.

**Comment by IanMayo** [comment]
@theanuradha  - I'd like you to take this "Narrative" item on too, please.

If there aren't any lines in "narrative.rep" that introduce the need for a line-wrap, you'll have to make them longer.

**Comment by theanuradha** [comment]
@IanMayo  I can reproduce issue. this section of  code use  Old KTable Source code not sure why it added there at that time ? it is old  code and coped Ktable [**de.kupzog.ktable**] source in to project.

Do you have any idea why it used Ktable is there issue on SWT Table view that cover by Ktable ?

**Comment by IanMayo** [comment]
KTable - hey, I think that's all that was available when we created the Narrative Viewer - I think it was before SWT Table :-)

I don't think this issue justifies porting to SWT Table, so let's keep KTable.  Ok?

**Comment by theanuradha** [comment]
Sure I will try to workaround ! :-)

**Comment by theanuradha** [comment]
![image](https://cloud.githubusercontent.com/assets/535713/18174716/22dca79c-708c-11e6-8795-dc468c3364e9.png)
I have work around for issue but maybe when we got time we should get rid of KTable as code is nasty down there ;-)

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/1870

**Comment by IanMayo** [comment]
Fixed in #1870
