### ISSUE TITLE
Command line version of DIS library, for automated testing

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1420]
The ODIN development team would like to verify their DIS output, and extend this testing to verify Debrief's DIS reading processing.

So, we'll develop our DIS reader in a library that can be run from command line or integrated into our UI.  The command line interface will export read DIS messages to CSV file.  These files can then be used in automated testing.

The will benefit the long term maintenance of Odin.  It will also help our developmental stages - where the Odin team can verify that we're correctly reading & understanding the DIS messages.

** Update: 22nd Jan **

I've started a testing app, to meet their requirements.  It's called **HeadlessDISLogger**

Could you create new build steps to we package this & its dependencies as a minimal-size jar?

I guess the built jar should go into our libs folder.

** Update: 11th Feb **

Our Debrief release process is producing an org.mwc.debrief.dis jar file.  This jar file contains the DIS libs, plus our DIS code.  It should be possible to start the Debrief logger direct from this jar file.

But, the logger is down deep in the namespace - resulting in a fairly long class URL.  So, maybe provide an "easy-access" class at the top of the namespace that in turn passes the call to the real Debrief logger.

**Comment by pecko** [comment]
I'm not sure that I understand. 
You want to create a jar that includes HeadlessDISLogger with dependencies. It is OK, I will find way to do it.
I'm not sure why we need include a separate jar in libs, since we already have it (including dependencies) in the dis plugin jar. If you need a separate jar with this class for some reason, we would create it in maven standard way (the target folder). Maybe, I would understand better if you explain why it is needed.

**Comment by IanMayo** [comment]
The Odin team wants to include some of the Debrief processing in their Jenkins.

They don't want the Debrief UI, or any of the Debrief processing. They just want a jar that will read from the relevant network socket/port, and write the messages to CSV file.

Then they can check that the simulation data is correctly packed into DIS format at their end, and that the Debrief code is correctly unpacked. 

So, I want to give them a standalone jar.  If this ends up in the target folder, then that is fine.

Does that make more sense?

**Comment by pecko** [comment]
OSGi jar (Eclipse plugin) can be used for that purposes. It is just simple jar with some structure described in manifest. They can ignore UI, but we also can separate UI to a new plugin (it is even recommended). I can help them in order to use it on Jenkins.

**Comment by IanMayo** [comment]
As long as the OSGI jar can be run from the command line, then I think it's fine.  They don't want or need UI.

**Comment by pecko** [comment]
If HeadlessDISLogger (or some other class) contains the main method, it can be configured and run from command line.

**Comment by IanMayo** [comment]
Working fine, included in #1507
