### ISSUE TITLE
DIS Listener view

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1428]
For the DIS support, we need an RCP View (DIS Listener in the following diagram) for the user to control the integration:

![DIS mockup](https://docs.google.com/drawings/image?id=sNn-TlZXNZotVIU_bptFqtw&rev=838&h=567&w=601&ac=1)

The functionality will follow, but it would be good to have a UI (with a good MVC model behind it).

**Comment by IanMayo** [comment]
@pecko - I've added some layout/resize details to the UI design.  I'd be grateful for you making a start at this over the weekend, if you get chance.

**Comment by pecko** [comment]
@IanMayo 
I will start certainly via weekend (not sure for today). I will firstly review the DIS protocol and after that let you more.

**Comment by IanMayo** [comment]
Don't worry about the protocol, I'll take the lead for that. This issue is just producing the "dumb" RCP view. I'll fill in the implementation.

**Comment by pecko** [comment]
OK. I have to know at least base concepts (very short description would be perfect). We will pull some data format via some URL and have to set its preferences. These data will be converted to Debrief (or Debrief-Limpet) format. Right?

**Comment by IanMayo** [comment]
Yes, but we will not implement that yet. Maybe in 10 days time. This issue is just the ”inactive " UI.

A simulator will multicast events to us, we will hear them, and create events on the Debrief plot.

We will also send commands back to start/restart the simulator.

**Comment by pecko** [comment]
OK. Fine.

**Comment by snpe2** [comment]
I will create a new plugin: org.mwc.debrief.dis

**Comment by pecko** [comment]
I will create a new plugin: org.mwc.debrief.dis

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1437
We need view icon, I have used icon of XY Plot view.
"Server prefs" opens the DIS preferences page.
The view includes the ChartComposite object, but it is empty.
Screenshot:
![disview](https://cloud.githubusercontent.com/assets/534584/12383445/6a8892e8-bda6-11e5-8d67-02c3c05c7d0c.png)

**Comment by pecko** [comment]
The PR: #1437
We need view icon, I have used icon of XY Plot view.
"Server prefs" opens the DIS preferences page.
The view includes the ChartComposite object, but it is empty.
Screenshot:
![disview](https://cloud.githubusercontent.com/assets/534584/12383475/f1d7c55c-bda6-11e5-8bc4-b2cc7bce57d0.png)

**Comment by IanMayo** [comment]
Closed in #1437
