### ISSUE TITLE
Prevent user creating project in home folder

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1434]
The IT security policies at a user establishment are happy with Debrief storing preferences in USER.HOME/.debriefNG.

But, they do not want users to store Debrief plots in that folder.

So, when the user runs the "New Project" wizard, the IT staff would like users to be forced to choose "Alternate Location" - if possible.

Alternatively, we need to replace the "New Project" wizard with one that creates the project by default on a pre-assigned drive.

## Update: 10th June 2016

At a visit yesterday we devised a new strategy. Here is the current wizard:
![createprojectwizard](https://cloud.githubusercontent.com/assets/1108513/15963299/bdaf8926-2f08-11e6-9410-13d2ecd0a2af.png)

We will modify this so that instead of entering a Project Name, the user has to use the System File Browser to an existing (or new) folder.  

The wizard will then check if this folder already contains a project. If it does, it will import the project.  If it doesn't, Debrief will create a project in the specified folder.

After the user has selected the target folder, if it's an existing folder I'd like the UI to be updated to reflect the fact that Debrief is "importing" the Project folder, rather than creating a new one.

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/1787
