### ISSUE TITLE
Add limpet to Debrief target platform

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#1441]
The Limpet update site is required by Limpet Integration (#1430)

**Comment by IanMayo** [comment]
Note: for development I've been importing the relevant limpet projects into the workspace - since I'm frequently editing sources in both repos.

**Comment by pecko** [comment]
It's OK. The target platform is obliged for build only.
I will also work with imported Limpet plugins mostly.

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1443

Possible issue: Debrief and Limpet uses different version of the org.geotools plugin. We uses Debrief's version here, but Limpet part could have a issue. We should update version of geotools in Debrief.

@IanMayo 

Now, you can build Limpet integration branch from cmd line (after applying this PR and rebasing Limpet integration branch. You also can use this target (eclipse38.target if import org.mwc.debrief.targetplatforms) when developing. It will use the same plugins as build.

Don't forget build target once.
```
cd org.mwc.debrief.targetplatforms
mvn clean install
```

**Comment by IanMayo** [comment]
Yes, please update GeoTools in Debrief, if necessary.

**Comment by IanMayo** [comment]
Sorted.
