### ISSUE TITLE
Fix travis build for DIS

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1444]
Peco,
my DIS branch is failing, I'm pretty sure it's since the DIS sources aren't included in the mvn build.

Could you fix the build, with a branch taken from my branch? 

Oh, in case you don't want to build from the sources - the *.jar* is in the *libs* folder - so we can build on that, instead.

**Comment by pecko** [comment]
I have to rebase your branch. It will include the dis plugin as well as a new target platform (#1441).

**Comment by IanMayo** [comment]
sure, that's fine.

**Comment by pecko** [comment]
Could you please apply https://github.com/debrief/debrief/pull/1442 (it will be applied to your limpet branch)?

**Comment by IanMayo** [comment]
[tomorrow morning]

**Comment by pecko** [comment]
OK. I will try to rebase it too.

**Comment by pecko** [comment]
You talk about the issue1440_initial_DIS branch. Right?

**Comment by IanMayo** [comment]
yes.

**Comment by pecko** [comment]
I mixed with the limpet branch (rebasing will be harder for it).
The dis plugin is included, but the target isn't important for this branch. 
The problem happens because you added a new source directory (dis-src). Tycho (and maven at all) don't like multiple source directories. I suppose that it's possible, but my proposal below is better solution.

I propose that we move it to a new plugin (edu.nps.moves). We should also create a new test plugin (otherwise we will not be able to run tests on Travis). Agree? If so, I will prepare the PR now (be ready for you tomorrow morning).

**Comment by IanMayo** [comment]
hmm, no - let's just use the *.jar*.  We'll only use sources if we need to edit them.

**Comment by pecko** [comment]
OK. I will add jar to dis plugin and remove source directory (we can attach source for debugging). 
Notice, if we use jar in another plugin, we should use the dis plugin or create a separate plugin for jar. If we add the same jar in different plugins we will have maintenance issue (when upgrade version, we have to remember to upgrade it in multiple place) similar as we already have with jfreechart, geotools ... In other words, adding jar to plugin isn't recommended; jar(s) should be in own separate plugin similar as Eclipse Orbit do it.
Where is jar?

What about test? If we want to run test on Travis (or some other CI) they have to be in separate plugin.

**Comment by pecko** [comment]
> We'll only use sources if we need to edit them.

You can only edit it in 
- another plugin with source folder
- another java project with this source, edit, create jar, replace jar ... (to complicated)

**Comment by IanMayo** [comment]
No, we won't need to call it from another plugin. No, I do not expect to edit DIS code. We will come up with a new strategy if we need to edit DIS code.

**Comment by pecko** [comment]
OK. Please let me know where I can find jar and will I separate test in a new plugin.

**Comment by pecko** [comment]
I have look at https://sourceforge.net/projects/open-dis/. DIS requires a lot libraries (hibernate with dependencies, jta, lucene, a jdbc driver ...).
Maybe we could move the files from dis-src to src and create a test plugin, for now. Agree?

**Comment by pecko** [comment]
I'm trying to solve tycho part without changing the structure of plugin. You can decide later about the tests.

**Comment by pecko** [comment]
FYI - comment from Vector3Float.java

> Jaxb and Hibernate annotations generally won't work on mobile devices. XML serialization uses jaxb, and
> javax.persistence uses the JPA JSR, aka hibernate. See the Hibernate site for details.
> To generate Java code without these, and without the annotations scattered through the
> see the XMLPG java code generator, and set the boolean useHibernateAnnotations and useJaxbAnnotions 
> to false, and then regenerate the code

I suppose that we will not use Hibernate (maybe JAXB too), so we would maybe use the code without that.

**Comment by pecko** [comment]
The PR https://github.com/debrief/debrief/pull/1445 (against the issue1440_initial_DIS branch) fixes tycho/Travis build (https://travis-ci.org/debrief/debrief/builds/103975941).

@IanMayo 
Please advice what to do with tests. Currently, DIS tests will not be run on Travis.

**Comment by IanMayo** [comment]
Ok.  I do want *our* DIS tests to run on Travis, but I don't need the *OpenDIS* tests to run on Travis.

So, I guess we could move the tests into the main src folder, or create a tests plugin.

Let's create a plugin to host our DIS tests.

**Comment by IanMayo** [comment]
Oh, and the OpenDIS jar is in the libs folder of our new plugin: **open-dis_4.08.jar**

**Comment by pecko** [comment]
> Ok. I do want our DIS tests to run on Travis, but I don't need the OpenDIS tests to run on Travis.

See #1452 

> Oh, and the OpenDIS jar is in the libs folder of our new plugin: open-dis_4.08.jar

I have seen that, but you added all dependencies (the libs directory). Maybe we should exclude hibernate.
Also, we don't use libs/open-dis_4.08.jar (it isn't in classpath or distributed dis plugin; it just exists on the debrief repo)

**Comment by IanMayo** [comment]
#1452 - great,

The sources are just for development, to help debugging.  I expect to switch to the .jar once things are stable.

I'm sure our Maven build can just refer to the .jar file.

**Comment by pecko** [comment]
> The sources are just for development, to help debugging. 

You can attach source container to jar for debugging. I debug geotools, jfrechart ... without any issues. However, it's OK if this is easier for you.

> I'm sure our Maven build can just refer to the .jar file.

You are right. Maven Tycho can do almost all PDE build do (and something more), but separating jar(s) in its plugin is good for us (maintenance). I agree to postpone that.

You can remove libs/open-dis_4.08.jar.

**Comment by pecko** [comment]
IMO, we solve main request in this issue (Travis build pass). We can solve other problems in a separate issue(s).

**Comment by IanMayo** [comment]
Your plan sounds fine.

**Comment by IanMayo** [comment]
Closed.
