### ISSUE TITLE
Update geotools plugin

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#1446]
Debrief and Limpet uses different version  (12.1 and 14.0)of the org.geotools plugin.
We should update Debrief's plugin to 14.0.

BTW the latest stable release of geotools is 14.1
We could create a separate (common) github project and update site for common plugins (especially if we introduce more common plugins).
Minimal (fastest) solution is update Debrief's geotools plugin (this ticket).

**Comment by IanMayo** [comment]
For now, let's just update Debrief. If/when we have more shared labs we can consider a shared libs repo.

**Comment by IanMayo** [comment]
Close. Replaced by #3878
