### ISSUE TITLE
Provide sensor time period in Properties View

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1447]
An analyst has a range of sets of sensor data.  

He wants to find the data that represents a particular time period - and he can only currently do that by opening up the Outline folder and scrolling to the start/end of that data.

He suggested we provide a read-only Property that shows the time period.

This is a great suggestion.  We may also consider it for other Debrief items that show as folders in the Outline view.

**Note**: This problem would also be eased by having more Limpet support for existing Debrief items - so the time period & coverage would be visible in the Limpet Analysis View.

**Comment by IanMayo** [comment]
Example UI:
![sensorcoverage](https://cloud.githubusercontent.com/assets/1108513/12811455/73aa38a0-cb24-11e5-912c-afec062e97c5.png)

**Comment by IanMayo** [comment]
Assigning to Russ, for documentation (probably just a small entry in the user guide)

**Comment by russcrowley** [comment]
Added to chapter 11, 11.1.2 Viewing Sensor Data Time Period.
