### ISSUE TITLE
DIS graph layout issue

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1448]
We have a chart composite in the DIS Listener view.

But the layout is wrong. It doesn't stretch to fill the space available.

Could you fix this?

**Comment by pecko** [comment]
I test this issue on the issue1440_initial_DIS branch. Is it OK?

**Comment by IanMayo** [comment]
Yes.   

I you want to see it update,  you can press "Play" and then "Attach" and you should see points appear on the graph.

**Comment by pecko** [comment]
Where is "Attach"?

**Comment by IanMayo** [comment]
Aah, maybe it's "connect"

**Comment by pecko** [comment]
Do I need set Server Preferences (IP, port ..)?

**Comment by IanMayo** [comment]
If I remember correctly, they now default to the ones for CustonEspduSender.

But, you can edit them, if you need to.

**Comment by pecko** [comment]
I can't set it to see points, but it's maybe isn't important. You want that the graph occupy all space in chart composite. Right?

**Comment by IanMayo** [comment]
Agreed, it isn't important. Yes, I want the chart to fill the whole composite.

**Comment by pecko** [comment]
trying ... chart composite layout  seems weird.

**Comment by pecko** [comment]
It seems that the ChartComposite doesn't work properly for some layouts. I have fixed it by reflection in Debrief. I think that it's stable (JFreeChart team will not change the canvas field).

The PR: https://github.com/debrief/debrief/pull/1455

Screenshot:

![dislayout](https://cloud.githubusercontent.com/assets/534584/12542093/250076d6-c31f-11e5-96f2-14f39f5379c4.png)

**Comment by pecko** [comment]
> Could you refactor the code/layout so that JFreeChart "just works", the way it does in our other uses?

@IanMayo 
I will try. I have checked and JFreeChart doesn't released a new version From  Jul, 2014 (https://sourceforge.net/projects/jfreechart/files/1.%20JFreeChart/1.0.19/), so I'm not sure if they will accept the patch. Maybe, we can use patched version.
I think, this case is different because we have other widgets within dialog/view. Have to test...

**Comment by IanMayo** [comment]
Working fine. Acceptable for now
