### ISSUE TITLE
Fix starting processes in new threads

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1449]
In two occasions I wish to start processes in new threads.

On DISListenerView.play() and in NetworkDISProvider.attach()

I've only been able to create these in background threads by using RCP Jobs - but they appear in the RCP Progress View.

Can you fix these so that they just fire off as background threads?

Oh, the UI also terminates these threads - so you need to allow this, please.

**Comment by pecko** [comment]
How you want to terminate them: separate command/dialog, preferences pages...?
They can be terminated in the Progress view, but you want remove them from it.

**Comment by IanMayo** [comment]
The listener UI has commands to terminate the processes: *detach* and *stop* should trigger the stop.

I'd like the processes to be "invisible" from the UI.

**Comment by pecko** [comment]
I understand that. It can be set to be "invisible" from the UI. However, I don't understand how it will be detach/stop if it isn't visible from UI. Do you think that you will detach/stop it without user's interaction?

**Comment by IanMayo** [comment]
when the user presses "attach" in the listener UI, the thread should start, and should run until the user presses "detach" on the listener UI.

So, the user doesn't see the thread/process itself - the user is just starting and stopping it.

**Comment by pecko** [comment]
OK. Clear. You just that it isn't shown in the Progress view. Will solve it.

**Comment by IanMayo** [comment]
Fixed, all seems fine now.
