### ISSUE TITLE
Package CustomEspduSender as .jar file

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1450]
Eventually, analysts will specify the path to their simulation executable.

I wish to mock having this executable.  I wish to do this by packaging CustomEspduSenser into the minimum possible jar (including all dependencies).

Could you do this?  I guess we will include the jar in the libs folder.

**Comment by pecko** [comment]
The best way to do it is creating a plugin that start main in Activator method (similar as #1420)
Another option is to use antrun plugin to create jar as you want.
You don't want that it be included in Limpet distribution. Right?

**Comment by IanMayo** [comment]
Correct, I don't need it to be included in the limpet distribution.

I'm hoping that I can distribute it as a single .jar file, with the main class specified in the manifest. 

Once we have the build working, I'll start on command line configuration options for it.

**Comment by IanMayo** [comment]
Hmm, it looks like the .jar file produced by our release process is sufficient to use for this.

**Comment by pecko** [comment]
@IanMayo 
I hope I will start tomorrow. Will check, maybe you are right. We just have to configure classpath in a script and call the main method.

**Comment by IanMayo** [comment]
No rush @pecko .  I was worried about creating the .jar files automatically. But, now that it seems that they get produced already, including their dependencies, it all looks fine :-)

Aah.  The OSGI plugin has dependencies on Debrief.  But, the "headless" tests we want to call from the .jar don't have Debrief dependencies.  So, I do hope that they can be called from the command line.

Maybe we do need a plugin that contains the non-Debrief code - just the code to parse/extract the DIS messages.  But, let's only create it if we need to.

**Comment by pecko** [comment]
OK.

**Comment by IanMayo** [comment]
Closed, in #1507
