### ISSUE TITLE
Trouble with Debrief trunk build

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1462]
Hi there,
a branch I've just taken off the master branch build is failing:
https://travis-ci.org/debrief/debrief/builds/105221878

It looks like it's dependent on **info.limpet.ui**

We haven't merged in the Limpet branch, so I don't think our builds should depend on that.

I need to deliver a new Debrief release early next week - so would appreciate you resolving this dependency so that a Debrief release doesn't rely on Limpet.

[yes, in the future we may require it - but we're a few weeks/months away from that right now]

It looks like this is the commit that introduced the dependency:
https://github.com/debrief/debrief/commit/0b4baaf069d91bddfbbf2852297262c8d830256a

**Comment by pecko** [comment]
I will look at that immediately.

**Comment by pecko** [comment]
The problem happened because Travis builds some old Limpet before splitting rcp and ui features.
We have added the Limpet update site to target platform although we don't use it yet.
The fix is rebuilding the Limpet master on Travis in order to create valid update site.

Currently, there is one failure in org.mwc.debrief.test2. Testing ...

**Comment by pecko** [comment]
The Limpet target platform has been added with #1441 , but it isn't an issue. It is better that we test it earlier. If you want we can remove it, but I don't think that it helps.

**Comment by IanMayo** [comment]
Ok, but I need the Travis build to complete - so I can do the release.

**Comment by pecko** [comment]
Failed test is
```
Failed tests:   testOrientation(Debrief.Wrappers.FixWrapper$testMe): correct orient expected:<0> but was:<2>
```
I suppose it is introduced with fixing #1459. The master branch builds correctly: https://travis-ci.org/debrief/debrief/builds/103774222
We can try to fix failed test or skip it temporary.

**Comment by pecko** [comment]
The failed test happens in the 1459_default_label_location branch.

**Comment by pecko** [comment]
It looks ok now.

BTW Limpet uses version 0.23.1 of tycho and debrief version 0.21.0. We should probably upgrade both project to tycho 0.24.0 (the latest version).

**Comment by IanMayo** [comment]
yes, I broke the build :-D  Fix pushed.

**Comment by pecko** [comment]
It's normal. The problem was because Travis run some old build in the same time.
