### ISSUE TITLE
Outline view not hearing about all updates

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1515]
When we change multiple items in the Outline view, only the first one gets cosmetically refreshed.

Eg:
* load **boat1.rep**
* load **boat2.rep**
* right-click on both in *Outline* view
* go into *Multiple items*
* change *Color* to *Green*
* Only the **Collingwood** track goes green in the Outline (though both get updated on the plot).

Expect this bug is related to optimising layer updates - triggered from *FireReformatted*

**Comment by helenayele** [comment]
Verified.
