### ISSUE TITLE
DIS - More a suggestion on functionality than an issue

### ISSUE THREAD

**Issue by russcrowley** [debrief/debrief#1633]
When running the DIS Listener and viewing data in the console view...

Given that we can already **clear console**, it would be a good addition if, while **Scroll Lock** was enabled, we could select messages/data using the mouse/keyboard and delete them. That way, the analyst can filter out what isn't needed and hone in on that required.

**Comment by IanMayo** [comment]
Good suggestion - and thanks for questioning the status-quo.

But, the Console is beyond our control. It's an off-the-shelf component.  We can send lines of text to it, but that's about the limit.

Well, Eclipse (which Debrief sits above) is Open Source, so we could change the underlying code - but that's a can of worms that I've managed to avoid so far.

Closing this - but please keep the thoughts coming.
