### ISSUE TITLE
Replace usage of standard Java colours with Debrief colours

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1644]
In lots of places we're still using Java colours (**java.awt.color.Red**)

Instead, we should be using Debrief colours (**MWC.GUI.Properties.DebriefColors.RED**)

This will be resolved by:
* updating your fork, to reflect Master (*Pull*)
* create a branch, titled *issue1644_colors*
* search for all uses of Java.awt.color.red (plus blue, yellow, green, etc)
* where there is a Debrief alternative, use the Debrief color instead
* create a Pull Request for the change

Please be careful not to re-format the files - the only changes in the PR should be ````java.awt.color.red```` to ````MWC.GUI.Properties.DebriefColors.RED```` (and the other colours)

**Comment by IanMayo** [comment]
@kumarbabu  - please start on this when you get chance. Be sure to update your repo, and take a branch off **Master**

**Comment by kumarbabu** [comment]
Hi Ian,

I am replacing the java.awt.color.* to MWC.GUI.Properties.DebriefColors.RED in org.mwc.debrief.xxxx plugins.

Please correct me, if there any thing wrong.

Regards,
Kumar.

**Comment by IanMayo** [comment]
No, they're not all going to Red.  We don't want Blue to change to Red.  We want to go to the relevant color.

Please make the change in all org.mwc.* code in the repo.

**Comment by kumarbabu** [comment]
Here, I am assuming that, java.awt.Color.lightGray ==> DebriefColors.LIGHT_GRAY similarly other colors also. Because Color also have TWO different Variables like "lightGray"  and "LIGHT_GRAY".
Both are representing same values.

**Comment by IanMayo** [comment]
Sure, that's a good presumption. Please highlight (list) any instances that don't match up.

**Comment by IanMayo** [comment]
Done.
