### ISSUE TITLE
outline view is missing Icon 

### ISSUE THREAD

**Issue by theanuradha** [debrief/debrief#1676]
on Outline View Has red box indicate it is missing icon.

**Comment by theanuradha** [comment]
<img width="169" alt="outline" src="https://cloud.githubusercontent.com/assets/535713/14583340/9d3c3262-043c-11e6-810d-05ace0d569cb.png">

**Comment by IanMayo** [comment]
Thanks for that.

Problem introduced in: e22dca0caedb4430fd797008449efb9badda9418

Icon reinstated in: 514b53fa3d035f71e1745125d8bb33214d53755d
