### ISSUE TITLE
Tutorial: boat1.rep Change Line to "long dash" not updated on editor.

### ISSUE THREAD

**Issue by theanuradha** [debrief/debrief#1679]
Steps :
1. Open boat1.rep 
2. select outline view and expand **120500.00 (402 items)** 
3. right click "L​inestyle a​nd select​ Long dashes". 
4. It never change to line style on editor  as of tutorial.

**Comment by theanuradha** [comment]
[mac]

**Comment by theanuradha** [comment]
@IanMayo this is also covered  by https://github.com/debrief/debrief/pull/2015

**Comment by IanMayo** [comment]
Great, thanks.
