### ISSUE TITLE
Multi line text editor enhancement

### ISSUE THREAD

**Issue by sambireddyt** [debrief/debrief#1686]
Text editor is not intuitive for name/description. Implement 
multi-line editor without scrolling.

![text editor](https://cloud.githubusercontent.com/assets/1883173/14621511/639071bc-0591-11e6-8621-70ff401e8d8b.png)

**Comment by IanMayo** [comment]
A user experienced this confusion today.

If we can't replace the inline editor with a taller one (3 lines tall?), then we should provide a popup editor  with a multi-line input area.


@sambireddyt - Could you describe some options for me?

**Comment by sambireddyt** [comment]
@IanMayo : I think quick window to accept value will  be easier to use. take a look at these options show in picture. last option is as mentioned, new popup dialog editor. I also think all color/font dialog should be popped up where user actually clicks to activate the editor, not in the middle of the screen. so that user doesn't have to move mouse cursor a lot.

![editor_poc](https://cloud.githubusercontent.com/assets/1883173/14696809/114ac3aa-074c-11e6-8893-ee6c4ac54ca7.png)

**Comment by IanMayo** [comment]
Fixed in #1740
