### ISSUE TITLE
Show Context info in Properties view

### ISSUE THREAD

**Issue by sambireddyt** [debrief/debrief#1688]
Property editor doesn’t show which object properties are shown. I think it should show some context information about current selection.

ex:
![properties_context](https://cloud.githubusercontent.com/assets/1883173/14621607/1bfe1948-0592-11e6-9efc-6e14a42df0d3.png)

**Comment by theanuradha** [comment]
<img width="532" alt="context_1" src="https://cloud.githubusercontent.com/assets/535713/14949469/dc4e6632-1067-11e6-81fd-0854a471765b.png">

**Comment by theanuradha** [comment]
Multi-Select 

<img width="520" alt="context_multi_1" src="https://cloud.githubusercontent.com/assets/535713/14949473/e22841ea-1067-11e6-821b-1f931183fa25.png">

**Comment by sambireddyt** [comment]
is it not possible to use empty space on view toolbar to add title?

**Comment by theanuradha** [comment]
@sambireddyt so far not found way to get to toolbar space. Even Current impl was found after deep dive in to eclipse source how they build Properties View via Adaptors. :-) highly welcome give any directions on possibility to add on action toolbar space

**Comment by IanMayo** [comment]
Fixed in #1737

**Comment by IanMayo** [comment]
@russcrowley - the Properties window now shows the name of the item(s) being edited.    I've added a comment in tutorial 2 suggesting where it could be described:
https://docs.google.com/document/d/16h1-iKQ-oJswhUlA381xbWsaKfsMkYCVEt7rewzQATE/edit#

**Comment by russcrowley** [comment]
Done.
