### ISSUE TITLE
Minor paint issue when color editor is activated

### ISSUE THREAD

**Issue by sambireddyt** [debrief/debrief#1691]
It has minor paint issue when color editor is activated.
![color_editor_paint](https://cloud.githubusercontent.com/assets/1883173/14621761/1193d4ec-0593-11e6-8924-ff4812565211.png)

**Comment by IanMayo** [comment]
@sambireddyt - could you give a bit more detail about what the *minor paint issue* is?

thx :-)

**Comment by sambireddyt** [comment]
@IanMayo : if you look at the attached image, blue icon was underneath activated editor. I think editor should stretch to cell width.

**Comment by theanuradha** [comment]
@IanMayo  PR created with a workaround.

**Comment by IanMayo** [comment]
Fixed in #1736
