### ISSUE TITLE
Properties editor : activate when selected

### ISSUE THREAD

**Issue by sambireddyt** [debrief/debrief#1694]
When drop down editor is activated, user doesnt have to click on  "drop down arrow"  to make available options visible. Show available options when editor is activated. It reduces one extract mouse click.

![dropdown](https://cloud.githubusercontent.com/assets/1883173/14621879/fa7441e2-0593-11e6-8310-3ff25da128e2.png)

**Comment by IanMayo** [comment]
Fixed in #2071
