### ISSUE TITLE
JRE/Execution Environment need to update to 1.7 in project 'org.mwc.debrief.legacy'

### ISSUE THREAD

**Issue by theanuradha** [debrief/debrief#1697]
Project 'org.mwc.debrief.legacy' has incorrect JRE/Execution Environment (1.6) while source has usage of 1.7 eg **java.nio.file.Path  **. 

Project need to be updated to 1.7 JRE/Execution Environment.

**Comment by IanMayo** [comment]
Fixed in #1698
