### ISSUE TITLE
Delete Key doesn't work in outline view

### ISSUE THREAD

**Issue by sambireddyt** [debrief/debrief#1703]
Add delete shortcut key (Key bindings) in outline view to remove drawings/shapes.
Similarly  other actions copy/paste...etc. 

![delete_short_cutkey](https://cloud.githubusercontent.com/assets/1883173/14661016/59272e9a-0678-11e6-9825-ab63898462ae.png)

**Comment by theanuradha** [comment]
@IanMayo I investigate in to **RightClickCutCopyAdaptor**.DeleteItem and found out there is where plot editor and outline view copy,cut/paste & delete defined. issue is none of action setup keybinding.

I setup it with setActionDefinitionId(ActionFactory.DELETE.getCommandId()); and it works!.

now  Copy,Cut ,Paste all missing so I went ahead and added those as well.

**Comment by theanuradha** [comment]
<img width="633" alt="context" src="https://cloud.githubusercontent.com/assets/535713/14875146/17e540e4-0d25-11e6-9716-1ac7579de461.png">

**Comment by IanMayo** [comment]
Fixed in #1741
