### ISSUE TITLE
DIS Preference page improvements

### ISSUE THREAD

**Issue by sambireddyt** [debrief/debrief#1716]
1. Path should be valid. do file extension validations. user can't select any file as executable.
2. Provide IP address format help. When validates, show correct message that " IP address format should w.x.y.z"
3. Provide port range if applicable
4. "Discover" button should be enabled only when IP and port info are in valid format.

![prefs](https://cloud.githubusercontent.com/assets/1883173/14729604/5414b81e-080d-11e6-9d80-62e90a99521e.png)

**Comment by IanMayo** [comment]
There is a newer version of this UI in the **issue1440_initial_DIS** branch. 

Here is the updated UI:
![disprefs](https://cloud.githubusercontent.com/assets/1108513/14739978/4805eedc-0883-11e6-9baa-cb6e7dae7ae2.png)

Feedback on this newer version is welcome.

**Comment by IanMayo** [comment]
Done.
