### ISSUE TITLE
Tycho Update version Goal fail   [mvn org.eclipse.tycho:tycho-versions-plugin:update-pom]

### ISSUE THREAD

**Issue by theanuradha** [debrief/debrief#1718]
When running **mvn org.eclipse.tycho:tycho-versions-plugin:update-pom** locally throw error.

Error seems related to tycho version miss-match as I have Tycho 0.25 in my local maven repo. where tycho 0.25 only compatible eclipse 4.3 or higher.   

`[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 33.361 s
[INFO] Finished at: 2016-04-22T11:01:16+05:30
[INFO] Final Memory: 97M/684M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-versions-plugin:0.25.0:update-pom (default-cli) on project parent: Execution default-cli of goal org.eclipse.tycho:tycho-versions-plugin:0.25.0:update-pom failed: A required class was missing while executing org.eclipse.tycho:tycho-versions-plugin:0.25.0:update-pom: org/eclipse/tycho/model/IU
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.eclipse.tycho:tycho-versions-plugin:0.25.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
`

**Comment by IanMayo** [comment]
Fixed in #1719
