### ISSUE TITLE
Auto save files feature

### ISSUE THREAD

**Issue by sambireddyt** [debrief/debrief#1744]
I think providing auto save feature helps users and don't have to remember saving work. May be we can enable  "auto save" feature by preference.

**Comment by IanMayo** [comment]
Valid suggestion.

But, one body of users conduct "experiments" with their data - particularly the TMA data you've been working with. They only "save" when they're happy with the current plot.

I won't implement it until there is a "ground-swell" of users that would value it.

**Comment by IanMayo** [comment]
Discussed with users. They fear their "good copies" of plot being over-written.
