### ISSUE TITLE
Radio state drop down menu is not visible properly

### ISSUE THREAD

**Issue by sambireddyt** [debrief/debrief#1745]
"Normal" selection is not visible properly.  I think  having check image or sort of will be more visible. 

![image](https://cloud.githubusercontent.com/assets/1883173/15064810/822ce068-1326-11e6-99bb-0576b1d8690e.png)

**Comment by IanMayo** [comment]
Ok, our struggle is fitting the representation into a 16px icon.

Sadly, a check image wouldn't convey the meaning.  I'm open to suggestions.

**Comment by IanMayo** [comment]
Closing, users content with strategy.
