### ISSUE TITLE
Boolean property descriptions not appearing in Status Bar

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1752]
The Properties that are edited in Debrief all have supporting descriptive text.

The text is shown in the Status bar:
![tracklabel](https://cloud.githubusercontent.com/assets/1108513/15359905/4d8452b0-1d03-11e6-9e34-d7778f2facd6.png)

But, it isn't shown for some properties, including Boolean ones:
![booleanproperty](https://cloud.githubusercontent.com/assets/1108513/15359909/50034870-1d03-11e6-9f02-a789cf2818b0.png)

It does look like the descriptive text is briefly shown then it disappears.

(actually, today I can only reproduce it for boolean editors, yesterday I thought it was missing for others too)

**Comment by theanuradha** [comment]
@IanMayo  https://github.com/debrief/debrief/pull/2019

**Comment by theanuradha** [comment]
@IanMayo as we merge #2019 we can close this
