### ISSUE TITLE
Debrief Build failing, possibly due to Limpet dependencies

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1756]
The Debrief build is failing:
https://travis-ci.org/debrief/debrief/builds/131634560#L230

Debrief hasn't changed recently - so it's probably due to how we've incorporated new features (ecore) in the Limpet build.

As your main priority, @theanuradha - could you investigate and resolve this?

**Comment by IanMayo** [comment]
@sambireddyt - could you add @theanuradha as a collaborator on your repo?  Then, if he has to make a change to the Debrief target platform, he can make changes direct to your branch, rather than creating a new one.

thanks :-)

**Comment by sambireddyt** [comment]
Added @theanuradha  as collaborator on my repo.

**Comment by theanuradha** [comment]
@IanMayo  I make sure to build valid again by temporarily removed  limpet-update site,
 limpet-update site need layout change to move emf-related libs to separate feature to avoid version conflicts.

I will make this change on limpet project one it do will re-add limpet-update site and create PR under this issue. 


NOTE: build is valid again https://travis-ci.org/debrief/debrief/builds/131771878

**Comment by IanMayo** [comment]
Ok, resolved.

**Comment by IanMayo** [comment]
Hmm, @theanuradha - it looks like the Master build is still failing:
https://travis-ci.org/debrief/debrief/builds/132494113

Could you investigate again?

**Comment by IanMayo** [comment]
New fix works.
