### ISSUE TITLE
Outline View should support "collapse all" keyboard shortcut

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1757]
I've just learned that Eclipse has a "collapse all" keyboard shortcut: **ctrl-shift-keyboard_divide**

Our outline view has a "Collapse all" view toolbar button, but, it doesn't respond to this standard keyboard shortcut.

Could you "connect up" this button.

**Comment by IanMayo** [comment]
Done.

**Comment by IanMayo** [comment]
@russcrowley - the Outline view toolbar has a **Collapse all** button.   There is now also this keyboard shortcut.

I don't have a strong opinion about whether we include the shortcut in the tutorial (particularly since I've been pushing to remove keyboard shortcuts).  But, the icon does provide a quick way of collapsing all the layers in the outline view, and getting back to the top-level view.

It's of value to include use of this button, though it doesn't *have* to come at the start.  If there isn't a better location, then section 1.3.4 of Tutorial 4 may be suitable - since the user will probably have to collapse some layers to find the new track.   Hmm, but some users may not get this far - tutorial 4 only relates to a small pool of users.  Maybe there's an earlier location where the user needs to collapse some layers.

**Comment by russcrowley** [comment]
Added to Tutorial 03, page 2, following 'Hide whole layer'.
