### ISSUE TITLE
Introduce extension ability - for third-party plugins to add buttons to Track Tote

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1768]
For the "View Stacked Charts" capability, I'd like to add a button to the toolbar of the Track Tote view.

I expect that for this capability, TrackTote *may* have to declare an extension point - then process any such extensions during createPartControl().

I'd like this button to be defined in the **org.mwc.debrief.limpet_integration** plugin.xml, and implemented by the **ShowTacticalOverview** handler.

The feature is being developed in the **1309_initial_tactical_overview** branch in your repo.

This is a Debrief feature. So, you'll have to pull the above branch.  Then you'll have to *import* these limpet plugins from your Limpet repo (from the **stacked_charts_poc branch**):
![imports](https://cloud.githubusercontent.com/assets/1108513/15568238/b505fe50-2322-11e6-8630-16e339f292a7.png)

**Comment by theanuradha** [comment]
@IanMayo  for add Actions for a given View no need to create sparare extension eclipse already support it with **org.eclipse.ui.menus**. I have push my change please take a look 


https://github.com/theanuradha/debrief/commit/85466e64b2c47a7fc1343993d89a9f24d9e67d26

![image](https://cloud.githubusercontent.com/assets/535713/15572673/a0dca252-235f-11e6-9646-cdadd60fd321.png)

**Comment by IanMayo** [comment]
Sorted.
