### ISSUE TITLE
Outline view drag support, like with Limpet

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1778]
I next need to implement the Debrief version of IStackedAdapter.

I've made a start.  But, "Track" objects aren't draggable. Only items within layers.

The "test case" for this is the **sample.dpf** file.  

Once this file is open, the *Show tactical overview* button is available from the **Track Tote**. This will open the Stacked Charts view.  You can then try to drag/drop a Track (*Nelson*) onto an axis of the  Stacked Chart editor.

Ok, we seem to have these challenges:
* expand set of object types that can be dragged (via DragDropSupport.dragStart() )
* prevent some of these item types from being drag/dropped into a plain layer (mark them with **NotInBaseLayer**)
* provide the translation steps necessary to present Debrief data as Stacked Overflow model

**Comment by IanMayo** [comment]
Ok, have pushed work.

You can now drag a Track item onto an AxisEditPart. You will be given a choice of what attributes to plot.

**Comment by theanuradha** [comment]
@IanMayo  updated to new limpet version and removed direct dependency

**Comment by theanuradha** [comment]
https://github.com/theanuradha/debrief/commit/9c9a43b347fe3368e6db61fc73b9185b50ff195a

**Comment by IanMayo** [comment]
Working fine, have recently added support for dragging Sensor data
