### ISSUE TITLE
Missing Debrief icon

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1791]
FD said:
[Bug - Debrief Icon] – In the latest version (3.0.352) both the toolbar and taskbar Debrief icon has disappeared.

**Comment by IanMayo** [comment]
I believe this user is running 32-bit MS Windows version.

**Comment by IanMayo** [comment]
@theanuradha - would you mind investigating this?

**Comment by theanuradha** [comment]
@IanMayo  I will take a look

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/1835

**Comment by IanMayo** [comment]
Fixed in #1835
