### ISSUE TITLE
ETOPO Key grid marker incorrect

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#180]
*[Migrated from Assembla ticket [180](https://www.assembla.com/spaces/Debrief/tickets/180) - reported by @IanMayo on 2009-11-18 15:43:13]*

The key that's displayed for ETOPO data shows a line marker for any visible contours.

It's displayed against different values (background colors) when displayed vertically vice horizontally.

Check the problem, fix the algorithm.

**Comment by IanMayo** [comment]
We're going to deprecate ETOPO fairly soon, so let's not worry about this.
