### ISSUE TITLE
Multipath analysis view not showing

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1802]
There has been some interest in the multi-path view.

I just tried it.  It doesn't show at all on Linux.  The graph doesn't show on MS Windows.

Investigate.

## Steps to reproduce
* Open Debrief
* Open **MultiPath** folder in **sample_data**
* Open file **GapsTestTrack.dpf**
* Open **Multipath analysis** View
* Drag **GapsTestIntervals.csv** file onto **Intervals** placeholder
* Drag the **Depth** slider until the two graphs lie over each other

**Comment by IanMayo** [comment]
@theanuradha  - I've just tried to open part of Debrief that I suspect hasn't been opened in a few years.

Nothing was shown on screen for the "MultiPath Analysis" view.  You won't have played with this before, but hopefully the above steps are sufficient to reproduce the problem.

cheers,
Ian

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/1803

**Comment by IanMayo** [comment]
Working under MS Windows/OSX, failing under Linux:
![blankmultipath](https://cloud.githubusercontent.com/assets/1108513/16191250/400dc1d8-36db-11e6-8ea4-0f8cbe88e95f.png)

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/1804

**Comment by IanMayo** [comment]
@theanuradha - have a remaining layout problem. Could you sort it out?
