### ISSUE TITLE
Finish off Export to WMF 

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1809]
I've made a start at exporting a Tactical Overview to WMF.  But I got horribly stuck.

We do have some WMF export libs in the Debrief project, but they proprietary.  I'd like to move to an Open Source equivalent, exporting either EPS or WMF.  Apache Batik appears to be the best supported library to offer this.  But, the FreeHEP library also exports to EMF (and it has a Graphics2D driver).  [Here](https://community.oracle.com/message/5363358#5363358) is an example of exporting a JFreeChart to WMF on the clipboard via FreeHEP.

The *so far* code is in **ExportStackedChartsToWMF**.  That is currently sitting in the Debrief project, in case we end up using Debrief's legacy WMFGraphics2D libraries.

**Comment by theanuradha** [comment]
https://github.com/debrief/limpet/pull/376#issuecomment-233037704

**Comment by IanMayo** [comment]
Here is the note I put in the Limpet PR:

````
Ok, could you try to make a platform-specific change?

For Windows, continue to use EMFGraphics2D

For OSX & Linux, could you use PDFGraphics2D?

I'm pretty sure you'll need to change the transfer mime type.

Actually, it would be good to wrap the two behaviours into their own class. 
Then we can allow the choice of both exports on Windows platforms.

thanks :-)
````

Would you mind investigating Non-Windows support (via PDF) ?

**Comment by theanuradha** [comment]
I have setup Linux and tested on inkspace works fine now 
![image](https://cloud.githubusercontent.com/assets/535713/17505452/e1a3c456-5e1e-11e6-9e4a-44d1101e698e.png)

**Comment by IanMayo** [comment]
Great, look forward to having a play tomorrow morning.
