### ISSUE TITLE
Stacked Chart - zig zag graph lines for infill

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1813]
Infill segments look wrong in stacked charts:
![sharktoothline](https://cloud.githubusercontent.com/assets/1108513/16450342/4a3064c0-3df4-11e6-8c12-20167fce4da2.png)

Here is the same data in Debrief's normal XY Plot:
![xy_plot](https://cloud.githubusercontent.com/assets/1108513/16450403/a5990df8-3df4-11e6-88bf-59059277ca36.png)

Investigate how we're passing the data to the Stacked Charts renderer.

Steps to reproduce:
* open plot **midflowa.dpf**
* open the **Track Tote** view
* click on the **Show tactical overview** button

Steps to reproduce XY Plot, using plot in state produced above:
* select both tracks (TMA_xxx & NONSUCH)
* right-click on both tracks, select **View XY Plot**
* select **ATB** from drop-down list in dialog, then **OK**
* select **Track:TMA_xxx** from drop-down list, then **OK**

**Comment by theanuradha** [comment]
@IanMayo  can you give steps to generate X Y View Data.

**Comment by IanMayo** [comment]
Steps to produce XY data added to issue.

**Comment by IanMayo** [comment]
Ok, it's because we weren't interpolating, and we have a lot fewer secondary positions than on the primary.

Switching on interpolation has resolved this.

**Comment by IanMayo** [comment]
Fixed in #1822
