### ISSUE TITLE
Add "Create Debrief Project" to navigator right-click editor

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1819]
Whilst we've added the "New Debrief Project" capability, it isn't visible when right-clicking in the blank Navigator pane.

We should either remove the **New Project** menu item, or ensure that **New Debrief Project** appears before it.

**Comment by theanuradha** [comment]
@IanMayo  I look into this. As ResourceNavigator class has hard coded "New" & "New Project" action only option is we have to add Wizard for Create project and register it on Perspective. Is this accepted solution ?

**Comment by IanMayo** [comment]
Could you conduct a trial in a PR?

**Comment by theanuradha** [comment]
@IanMayo Sure

**Comment by IanMayo** [comment]
Fixed in #1821
