### ISSUE TITLE
Narrative - data is white if source missing

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1866]
If an analyst loads narrative data for which there isn't a track present, the default color is white.

Stupid!

**Comment by IanMayo** [comment]
@theanuradha -  I can't reproduce it. Entries for a missing track appear in Red.

I'll push the mangled file (narrative2.rep) to your branch, so you can test under MS-Windows. Reproduce by loading ````boat1.rep```` and ````boat2.rep````, then ````narrative2.rep````.  Then ask to view the **Narrative Viewer**, and see what color the 3rd, 4th, 5th entries are.

**Comment by theanuradha** [comment]
@IanMayo this can be close now

**Comment by IanMayo** [comment]
Sorted.
