### ISSUE TITLE
Switch Narrative viewer from KTable to JFace table

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1871]
The narrative viewer was introduced before the JFace Table was introduced, if I remember correctly.

If it's not too complex a task, I'd like us to switch the view to use a JFace table control.

These parts of the UI functionality should be present in the new implementation - please indicate if any aren't possible:
* [ ] double-click on *Source*** or **Type** header to open dialog to filter on that field
* [ ] entries color coded according to the narrative entry color
* [ ] optional word-wrap
* [ ] two-way sync, select row according to current time, set current time when row double-clicked

**Comment by theanuradha** [comment]
![image](https://cloud.githubusercontent.com/assets/535713/18318334/f146f7de-753e-11e6-9127-df519a1e55ca.png)
@IanMayo  First version With some toDo to support all features

**Comment by IanMayo** [comment]
Well done.

**Comment by theanuradha** [comment]
- [x] double-click on Source** or Type header to open dialog to filter on that field
- [x] entries color coded according to the narrative entry color
- [x] two-way sync, select row according to current time, set current time when row double-clicked
- [ ] optional word-wrap

**Comment by theanuradha** [comment]
@IanMayo  https://github.com/debrief/debrief/pull/1878

**Comment by IanMayo** [comment]
Thanks for this progress. The word-wrap remains a really important feature.  Can we copy some of the word-wrap functionality from the KTable implementation?

**Comment by theanuradha** [comment]
@IanMayo there are some workarounds will try those

**Comment by theanuradha** [comment]
@IanMayo I manage to get Wrap working I have issue on when wrap switch off it never go to original row height Im working on it  

![image](https://cloud.githubusercontent.com/assets/535713/18444526/33503752-7937-11e6-8278-97914f3925e7.png)

**Comment by theanuradha** [comment]
also trying to only expand given row than all the rows will try on this changes

**Comment by IanMayo** [comment]
I'm on Linux.  Just the relevant row gets taller for me.  Is it broken for you?

![narrative](https://cloud.githubusercontent.com/assets/1108513/18471678/fbbdf1b6-79aa-11e6-8ebd-3394bdaf006b.png)

**Comment by theanuradha** [comment]
ON mac and windows Both have issue on all items get bigger and when wrap switch off it not going back to original. there is open bug in eclipse for this. there are coupe of hacks to get around this Im trying out those Also Will try to use Nebula Grid as seems it have inbuilt wrap  support. 

https://bugs.eclipse.org/bugs/show_bug.cgi?id=154341
https://bugs.eclipse.org/bugs/show_bug.cgi?id=148039

**Comment by IanMayo** [comment]
Existing bugs.  Grr, that's a pain.  I really like the new implementation. Good luck with the workaround.
