### ISSUE TITLE
Regexp to extract suitable integers.

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1872]
I have sentences like the ones below.  I wish to extract the 3 digit integer.

````
Some text FF654 and some more
Blah K343 and more blah
Y543 and more blah
````

The three digit integer will always one or more characters before it.

I need a regexp to extra the 3 digit integer from each sentence.  So, running the regexp on the three sentences will return 654, 343, 543

**Comment by theanuradha** [comment]
`public static void main(String[] args)
  {
      String [] texts= new String[]{
      		"Some text FF654 and some more",
      		"Blah K343 and more blah",
      		"Y543 and more blah"};
      
      for (String string : texts)
      {
        Pattern p = Pattern.compile("\\d+");
        Matcher m = p.matcher(string);
        while(m.find()){
        System.out.println(m.group());
        }
      }
  }`

**Comment by theanuradha** [comment]
@IanMayo If u use **"\\d{3}"** it will only get 3 digit

**Comment by IanMayo** [comment]
But I only want the match if there are one or more characters before the number.

**Comment by IanMayo** [comment]
Hmm, this seems to work for this problem 
````
\S{1,4}\d\d\d
````

Could you check it in an IDE?

**Comment by IanMayo** [comment]
ta-da!

\S{1,4}(\d\d\d)

The round brackets indicate it's the numeric part that we're after :-)

**Comment by theanuradha** [comment]
@IanMayo 


```
 public static void main(String[] args)
  {
      String [] texts= new String[]{
      		"Some text FF654 and some more",
      		"Blah K343 and 334 more blah",
      		"Y543 and more blah"};
      Pattern lead = Pattern.compile("\\S{1,4}(\\d{3})");
     
      for (String string : texts)
      {
        
        Matcher m = lead.matcher(string);
        while(m.find()){
        	String group = m.group(1);
        	System.out.println(group);
        }
      }
  }
```

**Comment by theanuradha** [comment]
this works :-)
trick is ask for **m.group(1)**

**Comment by IanMayo** [comment]
Could you show me the output?

**Comment by theanuradha** [comment]
![image](https://cloud.githubusercontent.com/assets/535713/18344993/2703f0f0-75d7-11e6-8ee2-9e8e7dc876f9.png)

**Comment by IanMayo** [comment]
Perfect :-)

This one is done.
