### ISSUE TITLE
Regexp to extract significant phrases

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1873]
I wish to extract pairs of certain values from a sentence, if they're present.

````
Improve TY765 blah blah blah M345
Improve blah blah UY234 blah blah M65
Improve blah blah UY123 blah blah M45 blah Improve blah blah PP126 blah blah M21
````

The significant items are:
* the sentence will start with **Improve**
* there will be a composite element with one or more characters, followed by a 3 digit integer
* later in the sentence there will be a **M** followed by an integer of unknown length
* the *triplets* could appear more than once in the sentence.  So, for the last one I would expect to return an array of pairs:  [[123,34],[236,21]]

**Comment by IanMayo** [comment]
Ok, this matches the first occurrence, returning the two integers:
````
Improve.*?\S{1,4}(\d{3}).*?M(\d{1,3})
````

But, I need to allow it to return multiple sets of the above

**Comment by IanMayo** [comment]
It looks like just putting ````/g```` on the end will let it run multiple times.

Could you check this works in Java code?

**Comment by theanuradha** [comment]
@IanMayo 


```
	public static void main(String[] args) {
		String[] texts = new String[] { 
				"Improve TY765 blah blah blah M345",
				"Improve blah blah UY234 blah blah M65",
				"Improve blah blah UY123 blah blah M45 blah Improve blah blah PP126 blah blah M21" };
		Pattern lead = Pattern.compile("Improve.*?\\S{1,4}(\\d{3}).*?M(\\d{1,3})");

		
		List<Object> result = new ArrayList<Object>();
		
		for (String string : texts) {

			Matcher m = lead.matcher(string);
			while (m.find()) {
				int [] sub_result = new int [2];
				sub_result[0] = Integer.parseInt(m.group(1));
				sub_result[1] = Integer.parseInt(m.group(2));
				result.add(sub_result);
			}
			
		}
		
		for (Object is : result) {
			System.out.println(Arrays.toString((int [])is));
		}
	}
```

**Comment by theanuradha** [comment]
![image](https://cloud.githubusercontent.com/assets/535713/18345385/dd364ea8-75d8-11e6-871b-d54753b87ae3.png)

**Comment by IanMayo** [comment]
Hooray, great team!
