### ISSUE TITLE
Search field in narrative viewer

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1874]
Once we've moved the narrative to the new control, it would be good to introduce a search facility that does a free-text search through all the entries.

This issue will just cover a basic search - where rows that match the search string are selected/highlighted.

**Comment by theanuradha** [comment]
@IanMayo As part of Port Jface I have use Inbuilt Filter Component as prototype 


![image](https://cloud.githubusercontent.com/assets/535713/18359042/a937de4a-7615-11e6-8c18-f9160971d5e0.png)

**Comment by theanuradha** [comment]
@IanMayo this component used any many eclipse views if this works let me know if not will revert it

**Comment by theanuradha** [comment]
first version done part of https://github.com/debrief/debrief/pull/1878

**Comment by IanMayo** [comment]
I'd like to have a look at the filter code, could you tell me where I can find it?

**Comment by IanMayo** [comment]
@theanuradha  - screenshot added to original comment.

**Comment by IanMayo** [comment]
@theanuradha - I just had a play with your filtering code, but now realise it's SWT code, and we're not using SWT table/tree - we're using Nebula Grid.  So, I guess we'll need fresh code.

This looks like a start point:
http://stackoverflow.com/a/20215936/92441

**Comment by theanuradha** [comment]
@IanMayo yes
also filter support you mention is not limit table to match rows. we highlight and allow navigate will work on this tonight

**Comment by IanMayo** [comment]
Great, thanks @theanuradha .  Look forward to playing with it tomorrow.

**Comment by theanuradha** [comment]
@IanMayo 
ui coming along nicely fully functioning version will be ready by tomorrow.


![image](https://cloud.githubusercontent.com/assets/535713/18645134/a8800a74-7ec9-11e6-8c5f-3eda1a6faeb4.png)

**Comment by IanMayo** [comment]
Cool, could you Push before you finish fit the night?

**Comment by IanMayo** [comment]
@theanuradha - I've simplified this issue.

We'll put off the advanced search until we've got the highlighting sorted #1885

**Comment by theanuradha** [comment]
@IanMayo I'm doing the cleanup should be ready soon

**Comment by theanuradha** [comment]
![image](https://cloud.githubusercontent.com/assets/535713/18663838/cdd03ec4-7f3d-11e6-8b49-33024008f370.png)


I push the basic version

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/1902

**Comment by IanMayo** [comment]
Fixed in #1902
