### ISSUE TITLE
Highlighting text in narrative viewer

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1885]
When the user conducts a search of the narrative viewer, it would be good to highlight the matching phrase.  I guess a pale yellow background would be fairly standard UI.

Also, it would be good to allow a set of "stock" phrases that get highlighted. A default set would be delivered with some phrases/words, but the user would be able to edit this in the Preferences page.

For this initial development, hard-coded values of ***important***, ***urgent*** and ***track*** should be highlighted.  **CHANGE**: let's have it user configurable.  We can commit to this now that we know the highlighting works well.

We will have a preference titled "Highlight phrases" in the preferences group "Narrative viewer".  This will contain a series of comma-separated phrases.  We will highlight those phrases in a background color that cycles through these shades
* 178 180 255
* 147 232 207
* 232 205 167
* 255 192 215

That will leave 238 255 176 (yellow) to be used for the search string:
![shades](https://cloud.githubusercontent.com/assets/1108513/18988150/38b5d106-86fd-11e6-94c4-120a6878aefe.png)

Oh, and support for RegExp would be a neat additional capability.

Here's an article on formatting parts of text:
http://stackoverflow.com/questions/26173834/highlight-particular-string-in-swt-tree-node

## Note:
The above swt-tree article is irrelevant. We can't use swt-tree, since it can't show different height rows on MS-Windows.

## Note 2:
I've attached a code snippet that *may* cover styling cells.
[demo_style.txt](https://github.com/debrief/debrief/files/475027/demo_style.txt)

## Note 3:
Actually, a good first implementation could be to highlight text that matches the current search phrase, as entered in the existing basic search interface.

## Note 4: 
the view drop-down menu should include an Action to *Edit highlight phrases*. This should open the preferences page.

**Comment by theanuradha** [comment]
![image](https://cloud.githubusercontent.com/assets/535713/18869570/816c82bc-84ca-11e6-8a6a-10f42243d954.png)


I got it working there are some bugs I need to sort soon as done will push

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/1922

**Comment by IanMayo** [comment]
Hi there, have had a play.  Have this feedback:
* [ ] when we do "Clear" after a search, the previous highlight is shown
* [ ] when a new search is conducted, the highlight remains visible if it is in a different column. E.g. search for "Nelson". Then clear search, then search for "comment 3". "Nelson" and "N" remain visible.  I guess we have to "clear" formatting as we loop through in a search
* [ ] if we close the current plot, then re-open another one, the highlight remains.  E.g. Open *sample.dpf*, search for "Nelson" in the narrative.  Now close the plot, and open *boat1.rep*.  Now drag in *narratives.rep*.  "Nelson" will already be highlighted.

**Comment by theanuradha** [comment]
@IanMayo  all of the issues in feedback are done!

**Comment by IanMayo** [comment]
@theanuradha - have more feedback based on today's playing:

* [ ] It's not possible to search for "B-"  Is this because it's being treated as a RegExp?  I've pushed a new sample.dpf to the branch that includes a "B-" entry
* [ ] when we have a filter running (either filter-by-type, or filter-by-search string) the time-sync isn't working. E.g. load *sample.dpf*, then search for *comment*.  As you move the time slider, the nearest narrative entry should be shown. But, sometimes there isn't a row selected. This is when the control has tried to select a row that's currently filtered out.

**Comment by theanuradha** [comment]
- [x] It's not possible to search for "B-" Is this because it's being treated as a RegExp? I've pushed a new sample.dpf to the branch that includes a "B-" entry

@IanMayo on second issue we may should not remove records but just highlight only ? as when it removed from visible list it is not possible to add it back when selection made .

**Comment by IanMayo** [comment]
Closing this. Remaining issue moved to #1924

**Comment by IanMayo** [comment]
Re-opening, since this issue also includes set of stock phrases.

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/1927

**Comment by IanMayo** [comment]
Note added regarding view menu command to open preferences page.

**Comment by theanuradha** [comment]
@IanMayo Done!

![image](https://cloud.githubusercontent.com/assets/535713/19019119/d21fd44a-8897-11e6-92ad-6a8623013df3.png)
