### ISSUE TITLE
Experiment with SWT.Virtual (or other) virtual grid mode.

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1892]
[*renamed from "Pause on loading large quantity of narratives"*]

As we load 12k narrative entries they appear instantly in the Narrative Viewer.  But, there is a pause of several seconds before the viewer will scroll.

Investigate what is causing the delay, and see if it can be avoided.

**Comment by IanMayo** [comment]
Ok, the pause is while the Nebula Grid component re-calculates the cell height for the 12k rows.  Actually, it does it for each cell in the table.

Have pushed some fixes directly to master that improve the performance a little, but the real fix for a 10k+ entry narrative is to move to a virtual table, like NatTable.  This only renders rows that are currently visible.

**Comment by theanuradha** [comment]
@IanMayo Seems Nebula Grid support **SWT.Virtual**   lazy loading of data.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=222402

BTW I check on NatTable seems it also has issues on **WRAP** 
https://www.eclipse.org/forums/index.php/t/545892/

SO will try Nebula Grid SWT.Virtual support first

**Comment by IanMayo** [comment]
Yes - that virtual support would be great.

There is a file called **narrative_bulk.rep** in the sample_data folder, for you to experiment with.

But, @theanuradha  - I'd like to put the Search capability & custom highlighting in front of that experiment, please.

**Comment by IanMayo** [comment]
Ok, I've done some googling.  There is an Eclipse bug that discusses SWT.Virtual:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=222402

But, an article linked from that bug gives more detail on a solution that uses range-checking (only provide a few rows at a time - simulating SWT.VIRTUAL), including demo code:
https://tomsondev.bestsolution.at/2011/10/07/jface-viewer-and-eclipse-databinding-with-10-000-objects/

**Comment by theanuradha** [comment]
@IanMayo I think we can close this

**Comment by IanMayo** [comment]
Fixed.
