### ISSUE TITLE
Line Style not working for line widths > 1

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1906]
We allow line style for tracks and some annotations (especially line annotations).

But, line style gets ignored if the width is > 1.

(I think line styles don't work at all under Linux, I'm seeing this behaviour under OSX).

Line Styles should work with line widths > 1.

To reproduce:
1. Open **sample.dpf**
2. Right-click on the the green line _Barrier Charlie_
3. Change the line style to **Long Dashes**
4. Observe that the line rending changes
5. Right-click again, and change the width to 3px
6. Observe that the line is now solid.

Yes, this problem may be beyond our control.

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/2015

**Comment by theanuradha** [comment]
@IanMayo after long debug session seems I found a workaround on issue I will test on linux as well

**Comment by IanMayo** [comment]
@theanuradha - did this work under Linux?  Can you remember if you tested it under Linux?

**Comment by theanuradha** [comment]
@IanMayo I think I did but will do it again

**Comment by theanuradha** [comment]
@IanMayo  works perfectly on linux

**Comment by IanMayo** [comment]
Great, thanks for checking.
