### ISSUE TITLE
Toggle button for narrative search field

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1913]
Sometimes the user may wish to recover the space occupied by the Search field.

We should use a toggle button in the Narrative Viewer toolbar to control whether the search field is displayed.

Here is an icon to use:
![search](https://cloud.githubusercontent.com/assets/1108513/18746611/46ffe78a-80c0-11e6-807a-755a7042f4f3.png)

**Comment by IanMayo** [comment]
@theanuradha -  this seems a nice quick one, for when you're next waiting for me.

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/1927

**Comment by IanMayo** [comment]
Fixed in #1927
