### ISSUE TITLE
Refactor narrative filter

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1924]
We're currently applying filtering in two places:
* one for source/type
* another for search text

But, there's an issue:
when we have a filter running (either filter-by-type, or filter-by-search string) the time-sync isn't working. E.g. load sample.dpf, then search for comment. As you move the time slider, the nearest narrative entry should be shown. But, sometimes there isn't a row selected. This is when the control has tried to select a row that's currently filtered out.

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/1925

**Comment by IanMayo** [comment]
Fixed in #1925
