### ISSUE TITLE
Narrative viewer performance

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1928]
@theanuradha  - I think we still have a rendering performance problem:
![stack](https://cloud.githubusercontent.com/assets/1108513/19032874/15f805b8-8954-11e6-8924-ae6171d33f2a.png)

I added **narr_12k.rep** to **sample.pdf**, then moved the time slider around.  We can see that **17** different time updates were sent.  For each new time we want to highlight the relevant row in the narrative viewer.    But, we see this results in 43076 calls to computeSize() - even when the size of the columns & rows have not changed.

Could you see if we can overcome this problem?

The excessive computeSize() calls don't have an impact for short narratives, but they do on long ones.

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/1930

**Comment by IanMayo** [comment]
Fixed in #1930

**Comment by IanMayo** [comment]
A performance problem remains.  Steps to reproduce:

1. Open **sample.dpf**
2. Open Narrative Viewer  (note: if it's not visible in *Window/Show* View you need to do a _Reset Perspective_.
3. Drag in **narrative_bulk.rep**

The progress slider takes about 5 seconds to load the 12k entries, but then the _busy cursor_ appears and runs for a couple of minutes.

**Note:** if steps _2_ and _3_ are reversed in the above sequence there is no performance delay.


Hmm, I've got an idea - I think this is about a long queue of "new entry added" screen updates. Let me do an experiment.
