### ISSUE TITLE
Import NMEA wizard

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1937]
I've written code to allow import of a new data-type.

But, before it starts, I wish to ask the user two questions - each is answered by selecting an item from a  a combo-box.  

* [ ] Could you create a SWT Dialog form to get the answer?  
* [ ] I expect it will sub-class TitleAreaDialog.  
* [ ] The dialog will return a status on dialog.open(), with a status of ListDialog.CANCEL if the user has cancelled. 
* [ ] The dialog will support getOwnshipFreq() and getThirdPartyFreq(),returning the specified long value.

![nmea import dialog 1](https://cloud.githubusercontent.com/assets/1108513/19127910/f2b026c6-8b38-11e6-8c5d-b63898652fe2.png)

The NMEA logo is here:
http://www.volvopenta.com/SiteCollectionImages/VPC/Accessories/Inboard/280x/NMEA.jpg

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/1938

**Comment by IanMayo** [comment]
Hi there @theanuradha  , any chance of a screenshot?

**Comment by theanuradha** [comment]
I did not connect it any where. I can get Screenshot without Icon as I run with main method 
![image](https://cloud.githubusercontent.com/assets/535713/19148004/6be37d82-8bd8-11e6-880c-7d6338b7f1a7.png)

**Comment by IanMayo** [comment]
great, thanks.
