### ISSUE TITLE
Change font size in narrative viewer

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1942]
It would be good if the user could choose the font size for the narrative viewer.

I *guess* we could include this in the preferences page.  Or, just via a popup font selection dialog.

Yes, that's better.  A "Font-size" command in the drop-down menu that lets the user choose a new font size.  The font-size should be stored in the Eclipse settings for the next session.

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/1951
