### ISSUE TITLE
Add resample frequency to import dialog

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1953]
When a REP-file is loaded, we ask the user what mode to use (unless they've specified a default):

![image](https://cloud.githubusercontent.com/assets/1108513/19192603/ae014dc2-8c9e-11e6-8965-73d298b74503.png)

I'd like to extend this to include the resample frequency.

Could you modify this dialog (SelectImportModeDialog.java) to include a "Sample frequency" drop-down that is similar to the one you did for the NMEA Import dialog?

**Comment by IanMayo** [comment]
@theanuradha - I could do with this for Monday, if you get chance.

**Comment by theanuradha** [comment]
@IanMayo  i'm on it

**Comment by theanuradha** [comment]
![image](https://cloud.githubusercontent.com/assets/535713/19229739/7ef7f494-8eed-11e6-9bc3-91f83f51043b.png)

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/1955
