### ISSUE TITLE
No simple way to find the length of a track

### ISSUE THREAD

**Issue by ed-butcher** [debrief/debrief#1969]
There is a requirement to calculate the length (over ground) of a track.

It might be sensible to use the 'filter to period' within the time controller to allow user to calculate the distance traveled in a particular time period as well as for the whole track.

**Comment by IanMayo** [comment]
Working solution developed:
![menu_item](https://cloud.githubusercontent.com/assets/1108513/19278772/7e1994d0-8fd6-11e6-87d8-a27e50392008.png)


![length_dialog](https://cloud.githubusercontent.com/assets/1108513/19278777/80b272de-8fd6-11e6-9962-0bd4be7dd898.png)

**Comment by IanMayo** [comment]
Will work on support for adding button to copy length to system clipboard.

**Comment by IanMayo** [comment]
Copy to clipboard working:
![new_dialog](https://cloud.githubusercontent.com/assets/1108513/19279792/c067acc4-8fda-11e6-8c48-ba7f2a159756.png)
