### ISSUE TITLE
Export to GPX silently fails

### ISSUE THREAD

**Issue by ianrenton** [debrief/debrief#1980]
When I right-click a Track and select "Export Track to GPX", nothing seems to happen. I am not prompted for a file name to export to, and no GPX file is created in my project folder. Am I missing something or is this a bug?

**Comment by IanMayo** [comment]
Yes, it's a bug.  It looks like there's a .jar file missing from the build.  I'll work on it tomorrow.

Cheers,
Ian

**Comment by IanMayo** [comment]
Issue resolved in #1994, available for download here:
https://github.com/debrief/debrief/releases/tag/20161014_3.0.376

**Comment by IanMayo** [comment]
@ianrenton  - I think I've worked out where you are at the moment.  If I can be of any further help during the challenge please feel free to ping me directly via ian at DeepBlueC.com

**Comment by ianrenton** [comment]
I think you might be right! Thanks for the quick fix, I'll test it out tomorrow.
