### ISSUE TITLE
Narrative viewer re-calculating height on column width change

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1989]
When we resize the narrative columns, we sometimes get vertical whitespace.
![whitespce](https://cloud.githubusercontent.com/assets/1108513/19346406/0c84040c-913b-11e6-809f-63b64d14fb53.png)

To reproduce:
1. Load sample.dpf
2. Show Narrative Viewer
3. Resize narrative viewer to be tall & narrow
4. Make the **Entry** column wider, until the extra whitespace is seen.

I guess we need to call some re-calculate method on column width change

**Comment by theanuradha** [comment]
@IanMayo  https://github.com/debrief/debrief/pull/1991

**Comment by IanMayo** [comment]
Fixed in #1991
