### ISSUE TITLE
Force input dialogs to be shown on top

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1992]
When users drag in .REP (or .DPF) files in MS-Windows, the Import dialog is frequently shown behind the MS Windows Explorer where the drag operation started (particularly on twin monitor machines).

Beyond that, the progress bar shown when importing .REP files is sometimes shown behind Debrief.

Could you investigate a way of forcing the dialog to be shown above others.

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/1996

**Comment by IanMayo** [comment]
I haven't had chance to test this under MS-Windows. 

But, there is a remaining problem.  On Linux the dialogs appear at the top-left of the display(s).  On a multi-monitor setup, they're appearing on another monitor. It looks like Debrief has hung.

@theanuradha - Is it possible to force the dialog to open at the centre of the Debrief Window?

**Comment by theanuradha** [comment]
@IanMayo  Import dialog ?

**Comment by IanMayo** [comment]
@theanuradha  - I'm referring to the dialogs that you've worked on in this issue: the ones that appear when dragging in a REP file, or a NMEA .LOG file.

**Comment by theanuradha** [comment]
got it will make sure always Center

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/2004

**Comment by theanuradha** [comment]
@IanMayo this can be close now
