### ISSUE TITLE
Excessive Narrative Viewer GUI updates on Time Change

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1993]
I've been using YourKit Java Profiler to look at Narrative Viewer updates.

Here's a call tree:
![perf_image](https://cloud.githubusercontent.com/assets/1108513/19384909/f28870aa-9203-11e6-9f2e-721b37ac4001.png)

I loaded **narrative_bulk.rep** onto **sample.dpf**, and then opened the Narrative View.  Then I clicked on "_Jump forward large step_" in the Time Controller.

As you can can see in the image, one call of NarrativeViewer.setEntry() results in 9k calls to updateElement and 38k calls to getFont() etc.

Could you investigate what's happening here?

As a side-point, I've learned more about SWT_Virtual.  I did think that it only tried to render/handle a "window" on the overall data. But, I now think it doesn't do that, I now think it's just a lazy loader. So, by the time we've viewed the last row in the Narrative Viewer the control has loaded (and must render) all 12k entries.

**Comment by theanuradha** [comment]
I made a fix seems have big improvement (will create a branch )

without fix
![image](https://cloud.githubusercontent.com/assets/535713/19391100/966735f0-9248-11e6-9a8d-18b43643a0bc.png)


**With fix**
![image](https://cloud.githubusercontent.com/assets/535713/19391071/7cc47b8a-9248-11e6-9c5b-35f37d4876e9.png)

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/1997

**Comment by IanMayo** [comment]
The fix in #1997 has made an improvement.

But there's still a pause/freeze when we move to time beyond the Narrative rows that have already loaded.

Note: I've pushed a modified version of **sample.dpf** to your branch.  This file has the "current time" at the start of the time period.

With this data, pressing "large step forwards" in the time controller introduces a long time delay - as the Viewer loads/renders more rows.

I'm keen to overcome this issue - and happy to discuss options.  The following spring to mind:
* resolve any bottlenecks in loading/rendering these rows
* load/render the rows in a background thread after the narrative viewer is loaded (maybe after displaying the first 20 - just to populate the panel).
* investigate a "Windowed Grid" - where the control only does the rendering for rows that are actually currently visible.

**Comment by theanuradha** [comment]
@IanMayo  I will go over tonight

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/1998

**Comment by theanuradha** [comment]
@IanMayo I follow on with 

> "resolve any bottlenecks in loading/rendering these rows"

 and seems made some progress no with updated **sample.dpf** jump made with **~1** sec please try on ur end as well I will continue to look for where we can gain

**Comment by theanuradha** [comment]
@IanMayo we can merge #1998 as it bring in improvement.

> "load/render the rows in a background thread after the narrative viewer is loaded (maybe after displaying the first 20 - just to populate the panel)."
 
I will look on possibility but im afraid as  SWT only allow to update ui in Display Event Thread  it will start to freeze the ui. 

Yes I went trough SWT code on **AbstractTableViewer**
they have interesting comment on following method 

> // Now go through it again until all is done or we are no longer
>             // virtual
>             // This may create all items so it is not a good
>             // idea in general.
>             // Use #setSelection (int [] indices,boolean reveal) instead


```

	private void virtualSetSelectionToWidget(List list, boolean reveal) {
		int size = list.size();
		int[] indices = new int[list.size()];

		Item firstItem = null;
		int count = 0;
		HashSet virtualElements = new HashSet();
		for (int i = 0; i < size; ++i) {
			Object o = list.get(i);
			Widget w = findItem(o);
			if (w instanceof Item) {
				Item item = (Item) w;
				indices[count++] = doIndexOf(item);
				if (firstItem == null) {
					firstItem = item;
				}
			} else {
				virtualElements.add(o);
			}
		}

		if (getContentProvider() instanceof ILazyContentProvider) {
			ILazyContentProvider provider = (ILazyContentProvider) getContentProvider();

			// Now go through it again until all is done or we are no longer
			// virtual
			// This may create all items so it is not a good
			// idea in general.
			// Use #setSelection (int [] indices,boolean reveal) instead
			for (int i = 0; virtualElements.size() > 0 && i < doGetItemCount(); i++) {
				provider.updateElement(i);
				Item item = doGetItem(i);
				if (virtualElements.contains(item.getData())) {
					indices[count++] = i;
					virtualElements.remove(item.getData());
					if (firstItem == null) {
						firstItem = item;
					}
				}
			}
		}
```

**Comment by IanMayo** [comment]
Ok, if we don't have an alternative, then I think the "tidy" solution is to popup a progress bar and populate the Narrative Viewer all in one go.  We know how many rows there are, so we can roughly indicate the correct process.

Note: we don't do this as part of file-load.  We do it as part of NarrativeViewer.setInput().  So, this delay only happens if the user has the Narrative Viewer open.

How does this sound?

**Comment by theanuradha** [comment]
@IanMayo  ok so effectively we take out **VIRTUAL**  and add load progress I will try it!

**Comment by IanMayo** [comment]
Yes, let's do that. But, let's cover it with a Progress Dialog. The message will be **Loading 12548 narratives into viewer**.

Ooh, if we can, let's update the counter in the message, so it's **Loading 345/12548 narratives into viewer**.  I know this will effectively make it longer, but it will manage the users' expectation better.

Hmm, I'm sure we need to switch off viewer UI updates when it's running.

**Comment by theanuradha** [comment]
I have added Progress Dialog but we can not show progress and we have no way to get load progress from Viewer  on how it loading data at least I did not found a way yet. but after load it navigate really well now.

**Comment by theanuradha** [comment]
@IanMayo  I have added Small **hack** to get notification out of **Viewer**  please review and rename interface and method names as needed.

**Comment by theanuradha** [comment]
![image](https://cloud.githubusercontent.com/assets/535713/19488273/bf994380-9583-11e6-9d31-671ac5306d19.png)

**Comment by theanuradha** [comment]
I have change code to update progress on every 500 to speed up data loading

**Comment by IanMayo** [comment]
I've made a comment against the PR ( [here](https://github.com/debrief/debrief/pull/1998#issuecomment-254779077)  ).

But, I'll carry on the conversation here.  I'm starting to think that it's unachievable to support 12k entries using the Nebula Grid.  Supporting 12k entries isn't a core requirement for my analysts, it's a nice to have.

I'm tempted to create a new PR that doesn't include the dialog, but does include the other optimisation steps.

Then, as a longer term background task I/we could investigate the use of Nebula NatTable - since it introduces a virtual "Window" on the data.  The data is all in the background, but only the current window is rendered.

How does this sound @theanuradha  ?

**Comment by theanuradha** [comment]
@IanMayo  Sure Sounds better . Shall i go at NatTable right away or it can wait ?

**Comment by IanMayo** [comment]
Close this.  Issues we encounter after NatTable can be captured in another issue.
