### ISSUE TITLE
Show Error Log View is new item added in narrative import

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2013]
We're using the Error Log to give feedback if something screwy happens during a narrative import.

But, not all users will know to look at the Error Log for feedback.

So, if an error is logged from the ImportNarrativeDocument class, reveal the Error Log View

**Comment by IanMayo** [comment]
Done some code tidying.

Aah, hold on.  The issue only requires the Errors view to show when we encounter an error from *ImportNarrativeDocument*.   There is lots of assorted logging in Debrief.  We only need the view to be forced to open if it's from ImportNarrativeDocument - else lots of log entries will be shown.  I'll add a flag to indicate if the Errors Log should be shown.

**Comment by IanMayo** [comment]
Ok, API updated.  ImportNarrativeDocument now sends a flag to indicate the LogView should be displayed.  But, we need to amend the method in DebriefToolParent so that we use the UI thread (since getActiveWindow() is currently returning null).

Could you do that @theanuradha ?

**Comment by theanuradha** [comment]
@IanMayo Sure

**Comment by theanuradha** [comment]
@IanMayo done!

**Comment by IanMayo** [comment]
Closed in #2028
