### ISSUE TITLE
Preparatory work for Zone Chart

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2017]
In the next week I'm going to need a new chart.  I'm going to be using it in several places.

I'd like you to make a start on it, please.  So we can get a working version ready more quickly.

The horizontal axis will be a time axis. This new functionality is all about letting the user view/specify time periods.

Two instances of the chart will be used at the bottom of the bearing residuals view:
![leg interface mockup](https://cloud.githubusercontent.com/assets/1108513/20598878/26769644-b243-11e6-8082-a531b2aefc84.png)

We need the user to be able to:
* [x]  drag the centre of the blue (or red) time period markers to "pan"
* [x] drag the edge of the time zone markers to expand/shrink the period "zoom"
* [x] cursor change to show the user when the mouse is in the right position to pan/zoom the zone
* [x] a button to add a new zone. Once in "add mode" - the user will click on an area where there isn't a zone, and a zone will be created that is 1/3 of the available free time, centered in that free time 
* [x] a button to remove a zone.  Once in "remove mode" - when the user clicks on a zone it will be removed

I guess the above requirements mean we will have 4 cursors:
* [x] a hand for "pan"
* [x] a pair of resize arrows for "zoom"
* [x] a plus for "add mode"
* [x] a minus for "remove mode"

JFreeChart doesn't implement drag/drop of data. So, you're going to have to write your own listeners.

A few years ago a developer added drag/drop to JFreeChart in support of Debrief's grid editor (http://www.debrief.info/tutorial/GridEditor.html)

Here are my thoughts on the layout:
![zonechart 2](https://cloud.githubusercontent.com/assets/1108513/20883148/7dd79176-badc-11e6-95af-8b4e3f29890a.png)

API:
````
class Zone{
	long start;
	long end;
}

interface ZoneListener{
	void deleted(Zone zone);
	void added(Zone zone);
	void moved(Zone zone);
}

class ZoneChart{
	void create(Zone[] zones, long[] times, long[] values);
	void addListener(ZoneListener listener);
	void removeListener(ZoneListener listener);
	Zone[] getZones();
}
````

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/2020

**Comment by theanuradha** [comment]
- [x] drag the centre of the blue (or red) time period markers to "pan"
- [x] drag the edge of the time zone markers to expand/shrink the period "zoom"
- [x]  cursor change to show the user when the mouse is in the right position to pan/zoom the zone

**Comment by IanMayo** [comment]
Hey, nice work. Thanks.  I don't think the finger pointing is the correct cursor, we need a "grab hand" rather than a finger pointing.

**Comment by theanuradha** [comment]
@IanMayo  done! removed system cursor and used custom cursor with grab mode!

**Comment by IanMayo** [comment]
@theanuradha - have updated the diagram, and expanded the API description.

I see that you still need to implement the Add/Remove mode buttons - to allow adding & removing zones.  I've also extended the API to include support for a ZoneListener interface.

**Comment by theanuradha** [comment]
@IanMayo  I have added new **MODE** to **ZoneChart** than adding buttons

so we have

```
 public enum EditMode
  {
    MOVE, ADD, REMOVE
  }
```

this way we do not hardcode buttons in to ui keep flexibility of how we change the mode.

so New API 

```
class ZoneChart{
	void create(Zone[] zones, long[] times, long[] values);
	void addListener(ZoneListener listener);
	void removeListener(ZoneListener listener);
	Zone[] getZones();
      
        EditMode getMode()
       void setMode(EditMode mode)
}
```

**Comment by theanuradha** [comment]
@IanMayo  BTW ADD mode not complete yet **REMOVE** works now

**Comment by theanuradha** [comment]
@IanMayo I have added Test Toggle buttons 

![image](https://cloud.githubusercontent.com/assets/535713/20916297/091fdf66-bbb1-11e6-90cd-4cb74e2bf7f9.png)

**Comment by IanMayo** [comment]
Nice work :-)

* [ ] could we switch to icons on the buttons?  Then we can have +, -, hand-drag as toggle modes, plus command button with diagonal "fit to window" icon, and one with a calculator icon, to "auto generate".  I'll find some icons.

**Comment by theanuradha** [comment]
@IanMayo  sure as I mention Buttons are out of ZoneChat class so we have flexibility  where we want to place them and how we do that

**Comment by theanuradha** [comment]
- [x] I'm looking at the buttons. Actually, I'd like them to be embedded in the ZoneChart. So, this may mean ZoneChart has to move to being a Composite that contains a ChartComposite (plus the button panel). This is because MaintainContributions UI will contain at least two ZoneCharts - so I want the buttons "hidden" inside the ZoneChart composite control.

**Comment by IanMayo** [comment]
* [ ] Layout of Zone Charts in Base Stacked Dots View.  I've put two charts onto this view, so that I can start playing with numbers.  But, the layout is poor.  So, I'd like you to put the two charts into panel that is collapsible.  A "header bar" will go at the top of the panel, with the title "Leg Detections", and a triangle icon for expand/collapse. This lower panel will be resizable, so I guess it needs to be a "sash form".  So, I guess the UI is two vertical sash forms. The top one contains the existing graphs, plus the control bar. The lower one contains the zone charts.  The control bar expand collapse buttons make the lower sash visible/not visible

**Comment by theanuradha** [comment]
- [x]Drag/stretch logic. We switch to "extend" rather than "pan" when the cursor is in the first/last quarter of the zone. But, once we zoom in, this 1/4 may fill the screen. So, we need to test using screen pixels rather than time period. So, I think the resize test needs to convert the zone start/end into screen coords then check if we're within (e.g.) 5 pixels of it.

@IanMayo last commit cover this now we use pixel base dnd then convert to domain value

**Comment by IanMayo** [comment]
* [ ] issue with dragging zones. The mouse is drifting away from the zone when we drag to move/resize a zone.   https://www.youtube.com/watch?v=7ccwgiuHSYI  This looks fiddly, I hope you can overcome it.

**Comment by IanMayo** [comment]
* [ ] I've realised we can simplify the processing a little. I've realised that "-" mode only works over a zone, and "+" only works in a space.  So, I think we could replace them with a "edit" mode.  In this mode, if we're over a zone then the remove cursor is shown, and if it's over a blank space then the add cursor is shown.  But, let's defer this until we've got a pen icon.

**Comment by theanuradha** [comment]
- [x] I've realised we can simplify the processing a little. I've realised that "-" mode only works over a zone, and "+" only works in a space. So, I think we could replace them with a "edit" mode. In this mode, if we're over a zone then the remove cursor is shown, and if it's over a blank space then the add cursor is shown. But, let's defer this until we've got a pen icon.

@IanMayo toolbar need update with correct icon now

**Comment by theanuradha** [comment]
- [x] issue with dragging zones. The mouse is drifting away from the zone when we drag to move/resize a zone. https://www.youtube.com/watch?v=7ccwgiuHSYI This looks fiddly, I hope you can overcome it.

**Comment by IanMayo** [comment]
@theanuradha - looks like just one issue left: zone start/finish on a data point. See the following diagram:

![snip4](https://cloud.githubusercontent.com/assets/1108513/20974790/4d26073c-bc95-11e6-9796-2926ecfaddf5.png)

When we're adjusting the start of the first blue zone, as the user moves the cursor the zone start should "lock on" to the nearest red point. Then as the cursor moves to the left, at one point it will "jump" to the previous red markers.

I think this is how it could be handled:
* don't try to change the cursor position
* as we convert to data coordinates, first convert to data coordinates, then loop through the time values to find the nearest time.  It's this time that we use to change the zone/interval start/end time.

Note: we "may" need the original _pure_ convert-to-data-scale function, for doing "hot-spot" detection for if the cursor is over a zone.

Hope this helps,
Ian

**Comment by IanMayo** [comment]
* [ ] Merge mode.  There are cases when the user will wish to merge two zones.  The UI for this will be to select "Merge mode". He will then select two zones. As he selects the second one - the two get merged.  I picture the UI for this to be: Click "Merge" button.  The cursor changes to a "1" when over a zone.  The user then clicks on a zone (to select it). Then as the user hovers over an adjacent zone (before or after the first), a "2" is shown.  When the user clicks on a second zone they are merged.  So, the later one is deleted, and the end time of the earlier one extends to the end of the later one.

I've attached some digit icons.
![numbers-2-icon](https://cloud.githubusercontent.com/assets/1108513/20979106/5c365a20-bca3-11e6-9857-ba09e4e4d18c.png)
![numbers-1-icon](https://cloud.githubusercontent.com/assets/1108513/20979107/5c381748-bca3-11e6-8eba-86cf88b76774.png)

**Comment by IanMayo** [comment]
* [ ] Ok, there are times when I'm struggling to zoom in on the zone chart, because I keep dragging/moving a zone instead.  So, we need to be able to "switch off" the dragging modes.  With the current toggle buttons, it may not be intuitive to "switch off" the modes.  So, instead, we could introduce a "zoom" button. This effectively switches off the other modes, a makes the mouse drag just do a zoom.
* [ ] I've realised there's an simpler drag implementation.  We've combined "add" and "remove". We could also combine "move".  We can drop the ability to "pan" (drag) a zone - since I now realise this will never happen.  Instead of moving a zone to another time, it is more likely (& quicker) that the user will delete one, and drag to select the new zone.  So, in the new "combined edit" mode, when the mouse is in a blank space it will be "add".  When it's near the edge of a zone it will be "extend". When it's in the centre of a zone it will be "remove".   So, in combination with the above "zoom" issue, we will be down to two mouse modes:  "edit" and "zoom".

**Comment by theanuradha** [comment]
@IanMayo I have added "make edit mode also allow to resize zones" I did not yet take out MOVE Mode can u try and see EDIT mode see is this what you expect !

**Comment by IanMayo** [comment]
@theanuradha  - ok, the hover cursor is changing correctly.  But, when I try to drag a start/end zone it deletes the zone.  Could you fix that logic, and then we'll make a decision?

**Comment by theanuradha** [comment]
@IanMayo done please test again

**Comment by IanMayo** [comment]
@theanuradha - great - working fine. Thanks.

**Comment by theanuradha** [comment]
@IanMayo will remove **MOVE** and add **ZOOM** AND **MERGE** can u get a icon [24] for EDIT and MERGE modes

**Comment by theanuradha** [comment]
@IanMayo I have added merge mode please fix merge_2 icon this is an issue with it

**Comment by theanuradha** [comment]
@IanMayo I have pushed **MERGE** mode please review and let me know what we have pending in ZoomChart

**Comment by theanuradha** [comment]
@IanMayo 

> When we're adjusting the start of the first blue zone, as the user moves the cursor the zone start should "lock on" to the nearest red point. Then as the cursor moves to the left, at one point it will "jump" to the previous red markers.

I have added this please check is this what u after 👍

**Comment by IanMayo** [comment]
This won't be popular :-(   

I've realised we need undo/redo support.  The following should be undo-able:
* zoom in/out on the plot
* add a zone
* delete a zone
* merge two zones
* change the end limits for a zone.

I'm happy to discuss the implementation of these, if you think we need to.

**Comment by IanMayo** [comment]
Hi there @theanuradha,
no rush on the undo/redo support (above) - it won't get used in anger until January.

**Comment by IanMayo** [comment]
Closing - moving outstanding items to #2023
