### ISSUE TITLE
Narrative Viewer in NatTable

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2021]
I have a requirement for an Eclipse RCP View that provides a tabular via of logging data.

Here is the existing implementation:
![screenshot](http://www.debrief.info/tutorial/figures/Narr_1.png)

Described in more detail [here](http://www.debrief.info/tutorial/viewing_narratives.html).  And [here](https://www.youtube.com/watch?v=mmGj3G84w64) is a video showing the current version in use.

But, the existing implementation has these shortcomings:
* load and scroll performance is slow with > 12000 entries

[Here](https://raw.githubusercontent.com/debrief/debrief/master/org.mwc.cmap.combined.feature/root_installs/sample_data/narrative_bulk.rep) is an example of such a long file.

My team believe we've reached the limits of what can be done with Nebula Grid, and wish to investigate a Nebula NatTable implementation.  In particular, it is believed that the "virtual table" support will be required to reduce the UI complexity.

The view should include the following capabilities:
* user selection of which columns are visible
* text highlighting of set phrases (such as "URGENT" and "IMPORTANT")
* user filtering of displayed rows, dependent on the presence of some value. More detail [here](http://www.debrief.info/tutorial/viewing_narratives.html#filtering_narrative)
* font-size up and down buttons
* word-wrap toggle button

Where relevant, code for the above capabilities can be copied/reused from the existing implementation.

[Here](https://raw.githubusercontent.com/debrief/debrief/master/org.mwc.cmap.combined.feature/root_installs/sample_data/narrative_large.rep) is a sample of data file. The content looks like this:
````
;NARRATIVE2: 951212 050010 NELSON TYPE_3 congue duis cursus ut ut fames molestie bibendum mus
````
The columns are used as follows:
1. **;NARRATIVE2:** - this can be ignored
1. **951212** - the date, in yymmdd format
1. **050010** -  the time, in hhmmss format
1. **NELSON ** - the name of the vehicle that recorded the log data
1. **TYPE_3** - the type of this log data entry
1. **congue duis cursus....** - the textual log data, running up to the end of line

As the video demonstrated, the control will need to integrated with an external "time now" controller. But, this can be deferred for a future task.

**Comment by theanuradha** [comment]
@IanMayo this is current version we have 

![image](https://cloud.githubusercontent.com/assets/535713/19013652/fa4342f2-87f4-11e6-8bbe-67b8a9e7fcf3.png)

**Comment by IanMayo** [comment]
@theanuradha  - I'd like us to do some preparatory steps, to help this along.

I've created a new GitHub repo to host this development: https://github.com/debrief/bulk_table_viewer

Could you please implement this?

* Create a project with an RCP View that contains a "Load" button and a NatTable control.
* Pressing the "Load" button loads the [text-file](https://github.com/debrief/debrief/blob/master/org.mwc.cmap.combined.feature/root_installs/sample_data/narrative_bulk.rep) into a list of custom objects passed to a ListDataProvider - like the example [here](http://www.eclipse.org/nattable/documentation.php?page=examples)

**Comment by theanuradha** [comment]
@IanMayo sure

**Comment by IanMayo** [comment]
@theanuradha - I've forwarded the working example to you, so you can start a branch that includes the new viewer - to check we can build it properly.

**Comment by IanMayo** [comment]
@theanuradha - I could do with making progress on this, so I/we can provide feedback to Dirk, the developer.

I've created a working PR [here](https://github.com/debrief/debrief/pull/2029) to track our progress.

**Comment by IanMayo** [comment]
Remaining fixes resolved in separate issues
