### ISSUE TITLE
New icons for Zone chart

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2022]
We need a couple of 24px icons for a new control. They should be in Debrief colors.  We need:

* [ ] Add
* [ ] Remove

We already have 16px versions here: ![add](https://cloud.githubusercontent.com/assets/1108513/20923221/7472845c-bba3-11e6-8014-59edd44c119b.png)   and here:  ![remove](https://cloud.githubusercontent.com/assets/1108513/20923235/7e4dd3d2-bba3-11e6-8d65-7e1e35bfb6c8.png)

**Comment by sammy1985** [comment]
Files
