### ISSUE TITLE
Undo/Redo for Zone Chart operations

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2023]
(pulled out of #2017)

It's easy to be in the wrong mouse mode, and create a new zone instead of zooming in.

So, Undo of these operations will be of great value:
* zoom in/out on the plot
* add a zone
* delete a zone
* merge two zones
* change the end limits for a zone

Other parts of the UI may also have to respond to an Undo/Redo - so the ZoneChart should fire the necessary ZoneListener events.

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/2024

**Comment by theanuradha** [comment]
@IanMayo apart from Merge/Zoom rest of the action undoable 

![image](https://cloud.githubusercontent.com/assets/535713/21469994/d587045c-ca99-11e6-91a5-aae2f284a8fb.png)

**Comment by theanuradha** [comment]
undoable zone merge now supported

**Comment by IanMayo** [comment]
Fresh requirement:
* It would be easier to use Undo/Redo if the operation description was shown against the Undo/Redo menu item.
![undo_redo](https://cloud.githubusercontent.com/assets/1108513/21542067/46bd63f2-cdb3-11e6-8efa-16203f5f1cf8.PNG)

I see the *label* parameter is provided to the *AbstractOperation* class, but it isn't being used.

**Comment by IanMayo** [comment]
**Fresh requirement**
Aah, we need undo/redo on the **Fit to window** too (you already mentioned it for "Slice legs").

For **Slice legs** I think we need this:
* **execute** remember existing legs, run operation, remember new legs
* **undo** restore previous legs
* **redo** re-run operation (I *think* this is better than reinstating the previously calculated new legs)

**Comment by theanuradha** [comment]
@IanMayo I have added "Slice legs" undoable but **redo** I make sure use previously calculated new legs. as if not there maybe unexpected errors due to state changes in context. so safe bet is redo is use same state (previously calculated) exactly same to **execute**.

**Comment by IanMayo** [comment]
Fixed in #2024
