### ISSUE TITLE
NAT Narrative Viewer - hide/reveal Source or Type columns

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2043]
@fipro78, our old UI had checkboxes to hide/reveal the Source and Type columns.

Should @theanuradha be concerned about implementing this?  Will the column indices be affected if one column is removed?  (I presume not, since they appear to take a String identifier (*COLUMN_1*)

**Comment by IanMayo** [comment]
With field showing:
![image](https://cloud.githubusercontent.com/assets/1108513/21984069/0e4357f6-dbec-11e6-9b0a-4d67e5f2e8ac.png)


With hidden:
![image](https://cloud.githubusercontent.com/assets/1108513/21984076/174b63fc-dbec-11e6-8503-0daa73dd9482.png)

**Comment by IanMayo** [comment]
Have just tried. Actually our old viewer also had the problem.

**Comment by IanMayo** [comment]
Fixed in https://github.com/debrief/debrief/pull/2029/commits/c3b268f4d66501d9d87d9b24da08a2e2675d7daf

**Comment by fipro78** [comment]
@IanMayo If you use the NatTable ColumnHideShowLayer for hiding and showing columns again, then you don't need to be concerned about the indexes and the labels, as they are based on the basic DataLayer indexes.

Regarding your layout issue, if you are using a GridLayout I think you need to set the visible flag on the control to false and the exclude flag in the GridData for the control to true.
