### ISSUE TITLE
Minimum scale on error residuals axis

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#206]
*[Migrated from Assembla ticket [206](https://www.assembla.com/spaces/Debrief/tickets/206) - reported by @IanMayo on 2010-01-15 09:59:19]*

When the chaps are doing manual TMA, they're trying to minimise the errors on the residuals.  They only aspire to an error of less than a degree or so, but once they're getting close, the residuals plot zooms in to show, for example, 0-0.01 degs.  They don't need this accuracy, and would be happy for the x-axis to never zoom in more than a degree of error.

One route to this is for a user-configurable setting that stops the residuals zooming in closer than a degree.

**Comment by IanMayo** [comment]
Fixed when 5-degree minimum length added for Bob O.
