### ISSUE TITLE
Trouble with drop-down check-box in NatTable (Linux & OSX)

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2067]
On Linux (and I think osx), the selector drop-down to filter the Source/Type columns doesn't render properly.

![image](https://cloud.githubusercontent.com/assets/1108513/22342081/0a1d59ea-e3eb-11e6-8b5f-7504cc68106f.png)

I'm assigning this to @theanuradha , but if it's a problem that's common across NatTable then it's of more interest to @fipro78

**Comment by fipro78** [comment]
It looks like https://bugs.eclipse.org/bugs/show_bug.cgi?id=471465

I was never able to reproduce the issue. Also people that work on Linux I
know could not reproduce this.

I talked to Alexander Kurtakof a while ago about this and he said it might
be related to a Linux theme that does not work well with SWT.

Please let me know if you have any further insights and comment on the
ticket. Feel free to reopen the ticket if there is something we can do.

Am 26.01.2017 18:17 schrieb "Ian Mayo" <notifications@github.com>:

**Comment by theanuradha** [comment]
@fipro78 we have same issue on mac as well

**Comment by IanMayo** [comment]
@theanuradha - could you grab an osx screenshot please?

**Comment by theanuradha** [comment]
![image](https://cloud.githubusercontent.com/assets/535713/22358055/41417ae2-e462-11e6-9474-2ac956be1a40.png)

on mac it has unwanted scroll

**Comment by theanuradha** [comment]
And when we use Fonts Size(increase size )
![image](https://cloud.githubusercontent.com/assets/535713/22358100/94c3a6ea-e462-11e6-82f6-85129633cbe4.png)

**Comment by theanuradha** [comment]
@fipro78 On windows also when use bigger/large fonts 
![image](https://cloud.githubusercontent.com/assets/535713/22371191/b7b82dde-e4bb-11e6-90e4-f8fd61c9d687.png)

**Comment by fipro78** [comment]
I have seen and possibly fixed that particular issue locally already. But I forwarded my fix to another NatTable committer who works on Mac to see if he can fix the issue completely. I think we need to wait a bit for further response.
Thanks for testing and the feedback so far!

**Comment by IanMayo** [comment]
Hi there guys, a developer called Rodrigo helped us with a Nebula rendering issue last year.  If we don't have a fix in place by 13th Feb I'm happy to task him to work on this rendering bug.

Could you keep me updated on the resolution please @fipro78 ?

**Comment by fipro78** [comment]
@IanMayo @theanuradha 
If I prepare and send you a locally updated NatTable version (NatTable Core jar) with a possible fix, would you be able to test locally? Or do you need some SNAPSHOT build for the integration? I checked the implementation and found some layout flaws that might causing the rendering issues. But I can't tell if that fixes the issue on Linux and Mac.
Please let me know what would be possible for you and I can try to prepare something you can test with later.

**Comment by IanMayo** [comment]
Thanks for that @fipro78   I'm sure that if you sent me a jar then I can forward it to @theanuradha for testing under OSX.

That sounds a good solution.  Is your experimental fix in a GitHub PR that we could have a look at? Or is it just a local fix?

cheers,
Ian

**Comment by fipro78** [comment]
At the moment it is only a local fix. But I will push it as Gerrit patch later that day so it is easier to test for others.

**Comment by theanuradha** [comment]
@fipro78 Please send localy build jar file

**Comment by theanuradha** [comment]
@IanMayo @fipro78 patch version of nattable core works great on MAC . @IanMayo  will test on linux

**Comment by theanuradha** [comment]
@IanMayo  on windows drop down issue is fixed. Yet Window 10 64bit not show data on grid it is empty

**Comment by IanMayo** [comment]
@fipro78 patched version works fine on 64-bit Linux Mint too.  No regression problems.
