### ISSUE TITLE
NatTable not showing data in 64-bit MS Windows

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2073]
Hi there @fipro78, we've got an outstanding issue in NatTable running under 64-bit MS Windows.

In 64-bit MS Windows the data appears briefly, then disappears.

@theanuradha is able to reproduce the problem in the initial working demo:

[![Recording of missing data](https://img.youtube.com/vi/ArRboVN6q2Y/0.jpg)](https://www.youtube.com/watch?v=ArRboVN6q2Y)

**Comment by fipro78** [comment]
@IanMayo @theanuradha 
I'm working on Windows 7 aswell as on Windows 10 and don't see that issue. Two questions:

1. Do you have scaling enabled on OS level? Do you use 100% or a higher scaling like 125% which most of the newer notebooks come with by default? Then it could be an issue with the scaling which I hoped to have fixed already.
2. Could you try to resize the window? Does that change anything? Maybe the issue is related to that, as the Entry column looks pretty small.

**Comment by theanuradha** [comment]
@fipro78 I disable scale factor still have the issue even resize  no change

**Comment by fipro78** [comment]
I will test later on my Windows 10 machine if I can reproduce this issue there. While checking I have found another issue with regards to the automatic resizing of the last column. If you resize the window to be so small that the header of the last column would not show the header text completely, a resize is triggered that breaks the percentage sizing. Not sure if this is a possible cause. 

You could try to add the following to the NarrativeViewerStyleConfiguration

`    public NarrativeViewerStyleConfiguration() {
    	AutomaticRowHeightTextPainter p = new AutomaticRowHeightTextPainter();
    	p.setCalculateByTextLength(false);
    	columnHeaderCellPainter = 
        		new BeveledBorderDecorator(
        				new PaddingDecorator(p, 0, 5, 2, 5, true));
	}
`

I'm thinking about adding an additional constructor to AutomaticRowHeightTextPainter to make that configuration easier at creation time.

**Comment by fipro78** [comment]
I did some further investigation on this issue and found out that it is apparently a scaling issue. I suppose you didn't log off and log in again after you changed the scaling in the Windows settings. For SWT this is necessary.

Nevertheless it seems I have found and fixed the issue. 

https://bugs.eclipse.org/bugs/show_bug.cgi?id=511724

Please try the latest SNAPSHOT build to see if it works now for you too. That version also includes the fixes for the NatCombo, so the local NatTable Core jar should be obsolete.

**Comment by IanMayo** [comment]
@theanuradha - can you confirm to @fipro78  that the SNAPSHOT build fixes the issue for you?

**Comment by theanuradha** [comment]
@IanMayo sure will merge to it and check

**Comment by theanuradha** [comment]
@IanMayo @fipro78 
snapshot done the trick and works on more testes but looks good so far. 
https://github.com/debrief/debrief/pull/2077

**Comment by theanuradha** [comment]
@IanMayo works great on linux

**Comment by IanMayo** [comment]
Fixed in #2077
