### ISSUE TITLE
Zone dragging not getting picked up

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2090]
I'm playing with the zone chart.

But, when I drag zones, the events aren't being fired.

I'm pretty sure its the logic in ZoneChart.java at Line 390:
`if (!onDrag && isDelete(dragZone, event.x))`

Steps to reproduce:
* Open **mid_flow.dpf**
* Switch to **Drag track segment** mode
* Open **Zone Chart**
* **Calculate Ownship legs** (top zone chart)
* **Calculate Target legs** (bottom zone chart). Two zones should appear
* Drag finish time of first zone.
* Notice that the first line segment on the plot doesn't change in length for most changes

Here's a video demo:

![https://youtu.be/7AnUBNvAyzs](https://img.youtube.com/vi/7AnUBNvAyzs/0.jpg)

Note: when we drag the zones, the two target legs on the plot should change in length.  Sometimes the events do get fired, but lots of times they don't.

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/2092

**Comment by IanMayo** [comment]
Fixed in #2092
