### ISSUE TITLE
E4 build

### ISSUE THREAD

**Issue by theanuradha** [debrief/debrief#2121]
Debrief is currently built on Eclipse 3.8.2, from December 2012.

After that release Eclipse switched to the 4.x series (called E4).  The first versions of 4.x suffered a performance drop, plus some UI presentation issues.

But, Eclipse 4.5 is widely regarded as stable & polished.  It also includes some minor new capabilities, though few are seen to bring direct benefits to Debrief users (maybe the retina-style rendering for the high resolution monitors used by some Debrief analysts).

It is right for the Debrief project to investigate the transition to E4, to identify any issues that may arise, and de-risk the eventual transition.

E4 did introduce a new UI framework/model, but it still supports the 3.x model, and a hybrid approach where both model are supported.  The project will stick with 3.x model until strong justification for the upgrade arises.

**Comment by IanMayo** [comment]
Got advice from Jonah about using Java 7 in JRE 3.8.2:
````
Perhaps a little off-topic, but AFAIK 3.8.2 functions correctly with
Java 8, the problem is the BREE in the January manifest files? i.e.
you get errors like this:

!MESSAGE Missing required capability Require-Capability: osgi.ee;
filter="(&(osgi.ee=JavaSE)(version=1.8))".

If so, you can patch org.eclipse.osgi to include the 1.8 profile. If
you develop in newer eclipse that will allow you to target eclipse 3.8
and use bundles for Java 8. See this answer
http://stackoverflow.com/a/29717036/2796832 for more info.

(PS it makes me sad to launch old Eclipse because despite all the
other improvements in e4, 3.8 really feels faster)

YMMV but I HTH,
Jonah
````

**Comment by IanMayo** [comment]
Have just sat through an introduction to E4.  

The presenter (Jonas Helming) warned that the 3.x ui elements aren't being maintained any more.  Moving to the e4 compatability layer will actually run modern UI code, that are wrapped to look like 3.x.

**Comment by IanMayo** [comment]
Closing. This task is being covered within #4094
