### ISSUE TITLE
SAX Parsing troubles

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2132]
Here's another challenging one.

I'm loading my new data into Debrief:
![datatree](https://cloud.githubusercontent.com/assets/1108513/23666853/0baa37dc-0354-11e7-8d0e-86a5b8f3a7b6.png)

I'm successfully storing my new data measurements to file:
![image](https://cloud.githubusercontent.com/assets/1108513/23666940/3f0460b2-0354-11e7-9833-391b7b942211.png)

But, when I try to parse the XML, the data all falls into the top level folder:
![image](https://cloud.githubusercontent.com/assets/1108513/23666971/5bcf6796-0354-11e7-9cda-aad376e84a00.png)

This is almost certainly down to the structure of DataFolderHandler.

But, I'm really stuck so far.

**Comment by theanuradha** [comment]
@IanMayo for me I guess Will have a go

**Comment by IanMayo** [comment]
Please, we're still in branch 2116_DataModel

**Comment by IanMayo** [comment]
Fixed in #2133
