### ISSUE TITLE
Classic - Swing slider bar not resizing

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2145]
The app features a couple of slider bars that are used to resize the relevant panes in the application.

The grab handle is shown, but it doesn't work.

Steps to reproduce:
* start Debrief classic `DebriefApp.java`
* Click on `File \ New`, a new pane (session) will open
* Try to grab vertical bar, to change left/right hand side width - can't be grabbed.

The working app is in branch called `2141_legacy_icons`

Aah, I've had a play. I suspect the issue is down to the preferred width for the left-hand side. It wants to jump to quite a wide layout.  It's possible to drag it wider than that, but not smaller.

**Comment by IanMayo** [comment]
Fixed in #2152

**Comment by IanMayo** [comment]
Unfortunately, this isn't fixed on MS Windows.  This is when the app opens a plot:
![beforestretch](https://cloud.githubusercontent.com/assets/1108513/24348023/34dfbb76-12d2-11e7-89d3-3fe15df37870.png)

When I click on the splitter bar, it stretches to this:
![afterstretch](https://cloud.githubusercontent.com/assets/1108513/24348038/3f02c328-12d2-11e7-9ac9-8b1ba3a960db.PNG)

As far as I remember, I didn't get his behaviour under Linux.

**Comment by IanMayo** [comment]
Aah, I'm sure it's related to the Tote Table.  Without the Tote Table the panel resizes freely. Once a track has been loaded, then **Auto generate** tracks clicked, it wants to grow too large.

**Comment by IanMayo** [comment]
Aaah, found a bit more. I'm pretty sure it's because of the buttons that appear:
![totebuttons](https://cloud.githubusercontent.com/assets/1108513/24354397/8a74d4ce-12e9-11e7-82e9-b81d731edb98.PNG)

So. We need to allow these buttons to shrink to fit the available space, not allocate space as required for these buttons.  Or, we could switch to "Remove" and "Copy" icons on the clipboard.

**Comment by theanuradha** [comment]
It's related to Tote panel that use **Gridlayout**

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/2175

**Comment by theanuradha** [comment]
I avoid issue with add missing cut.gif,copy.gif to project

**Comment by IanMayo** [comment]
Fixed in #2175
