### ISSUE TITLE
Classic - Swing layout of Outline view

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2173]
![outline_view](https://cloud.githubusercontent.com/assets/1108513/24331332/cfdb83de-1229-11e7-9b09-18e50a15fac4.png)

It looks like child entries in the outline view are centre formatted. They should be left formatted.  Screenshot shows **sample.dpf**

**Comment by theanuradha** [comment]
@IanMayo https://github.com/debrief/debrief/pull/2189
