### ISSUE TITLE
Consider blue marble integration

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#22]
*[Migrated from Assembla ticket [22](https://www.assembla.com/spaces/Debrief/tickets/22) - reported by @IanMayo on 2009-03-12 09:55:49]*

There's a chance we want to switch to uDig as the plot component, to get access to other underlying datasets.

Alternatively, we could adopt World Wind, since it provides a Java SDK, and looks gorgeous:
http://www.ibm.com/developerworks/java/library/j-wwj/

But, we'd have to establish an offline data source for BMNJ data.  We hold a single-month snapshot of the data (~400Mb iirc), but I suspect uDig and WW expect it to come from WMS.

**Comment by IanMayo** [comment]
Drop this, Natural Earth provides equivalent benefits
