### ISSUE TITLE
D1 Export to new file format

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2912]
As an **analyst** I wish to **export tracks in a new format** in order that I can **share them with analysts in another agency.**

We need to implement a new track export capability.

* Design UI for wizard
* Produce banner image for wizard (Sam)
* Develop registry to handle UI dropdowns.
* Develop export of data in new format

The format will be one track position per row.  But, there are lots of extra rows.  We need to generate a wizard to help fill in this extra information.

[Here](https://docs.google.com/presentation/d/1jNJ8TqeodjLW7oWzj3JLuqCrfwvT0zOYU_AAWSJshLE/edit#slide=id.g3c02f236c2_1_6) is a slideshow that gives mockups for the wizard pages. 

**Note:** in the presentation above, the text in Red is the field name that is used to store/retrieve values from the preferences store.  Where it's a drop-down it's also the column name in the CSV datafile name.

Some of the fields for the wizard will be drop-down lists, with the drop-down values extracted from a .CSV file.  I'll put a demo copy of the file into the **other_formats** sub-folder of the sample_data folder in org.mwc.cmap.combined_feature.

(note: I had to rename the above from `.csv` to `.txt`.  In our implementation it will be a `.csv` file)

The location of the CSV file will be specified in a prefs page.  The prefs page will allow the user to specify a new file location.  But, it will also allow the user to open the .csv file.  This command should open the System Editor for a .csv file, which is normally MS Excel.

The prefs page will also contain a toggle button that controls whether the export command should be made available on right-click - since the export won't apply to most Debrief users.

I'll make a start on this, but then I look forward to @theanuradha  taking over.

**Comment by IanMayo** [comment]
Ok, @theanuradha - I've got this started, in branch **2912_new_export_wizard**

Would you mind doing the code to populate the wizard.

It will need two pages, as provided in the above slideshow.  A class is provided that will provide the contents of the dropdowns.  It's configured from the CSV Export page in preferences.  There's a sample data-file in [here](https://github.com/debrief/debrief/blob/8ddd98596a0ec80c95049adf921ef0a0b8a3d58a/org.mwc.cmap.combined.feature/root_installs/sample_data/other_formats/ExportWizard.csv)

**Comment by theanuradha** [comment]
@IanMayo will work on this

**Comment by IanMayo** [comment]
Still have UI change, and fix date format to ISO 'Basic', not ISO 'Extended'

**Comment by IanMayo** [comment]
Still have UI change, and fix date format to ISO 'Basic', not ISO 'Extended'

**Comment by IanMayo** [comment]
Ok, re-close, following #3074
