### ISSUE TITLE
D2 Investigate why right-clicking in empty space retains selection

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2917]
As an **analyst** I wish to **select empty area of tree when right-clicking** in order that **I can paste into top level  of data structure**

I've got an SWT tree control.  An item is selected.  A user right-clicks in empty space.  But, the context menu for the selected item is shown:
![image](https://user-images.githubusercontent.com/1108513/41711385-eac37790-753f-11e8-8905-3b25561966f9.png)

This means that if I select "Paste" the item on the clipboard gets added to the top-level item, not as a new item at the same level in the hierarchy as the existing item.

But, when right-clicking into empty space, the context menu for the empty space should be shown:
![image](https://user-images.githubusercontent.com/1108513/41711441-072fb74a-7540-11e8-962b-0c891520e212.png)

Steps to reproduce:
* open boat1.rep
* open boat2.rep
* from boat2.rep, right-click on `COLLINGWOOD` in the Outline, and select `Copy`
* switch back to boat1.rep
* Check that `NELSON` is selected
* right-click in whitespace beneath Nelson, it will offer Nelson's popup menu.  It shouldn't it should offer `Paste copy of COLLINGWOOD`.

Note: it's possible to ctrl-click to deselect `NELSON`, and the correct menu will be displayed.  This issue is about why Nelson's popup appears even though the user has right-clicked in whitespace.

**Comment by theanuradha** [comment]
@IanMayo I investigated this issue note that you do not have to Ctrl+Click just left click into empty space deselect the selected node and you can go ahead and right click next.

This is default SWT/Eclipse behavior so we can try to workaround it issue will be we might have to patch all views if we do not find a way to change the default behavior globally.  

Do you want me to go ahead?

**Comment by IanMayo** [comment]
@theanuradha - hmm, I thought the behaviour happened in our Outline View, but not in the Eclipse Navigator view.

I'll have to test again.

No - I don't really want to fight Eclipse behaviour.

**Comment by theanuradha** [comment]
https://debrief-devs.slack.com/archives/DBCUN5YCC/p1532710536000388

**Comment by IanMayo** [comment]
ok - watched the video you posted.  Ok, we aren't going to fix that. Closing.
