### ISSUE TITLE
D1.2 Preferences page for export format

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2934]
As an **analyst** I wish to be able to **edit persistent preferences related to track export** so that **I don't have to type them in every time**

We have a couple of preferences related to this:
* toggle for whether to offer "Export to CSV format" to user (since it only applies to a single group of users.  Ok, one user!)
* location of presets datafile.
* Value of 3 numeric fields:  "Major axis (nm)", "Semi Major Axis (nm)", "Semi Minor Axis (nm)"

The form will also contain a "reload" button.  This will reload the data.  It will also perform these checks:
* [ ] check there at least one entry present for each section
* [ ] check there are no extra sections of data

**Comment by helenayele** [comment]
@IanMayo Is there any help documentation regarding how to prepare this file format please?
