### ISSUE TITLE
D16 Display build date & version number in splash screen

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2987]
_As an_ **Analyst** _I would like to_ **see the Debrief version as it loads** _so_ **I have a feel for how new/old this version is, and avoid mistakenly opening a legacy version**

We have a Splash screen that is shown as Debrief loads:
![image](https://user-images.githubusercontent.com/1108513/42450644-cb27a6ae-837c-11e8-862f-37935638abd8.png)

It would help users to see the build date & version in this screen, particularly when the two Ian's are doing acceptance testing.

The build date & version should _somehow_ be extracted from the `Debriefng.product` file (or other runtime source), and displays as black text at the bottom-left of the Splash screen.

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/3047
