### ISSUE TITLE
M1.6.2.0 View Map in Debrief Lite

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2993]
As an **analyst** I wish to **view a map of the area of interest** in order to **understand what happened in a exercise**.

## Status
This is the first step in the creation of Debrief-Lite.  Sprint 1 will be developing a bare-bones application.  The original strategy was to develop this based upon the DebriefApp.java class.  But, a more streamlined approach would be to base it upon the GeoTools Swing-based editor that's described below:
http://docs.geotools.org/stable/userguide/tutorial/quickstart/eclipse.html

## Strategy
Produce a barebones application using the above quickstart guidelines.

## General testing
* Application starts
* User able to load ShapeFile
* User able to pan & zoom around plot

## Sample data
In the Debrief organisation repo is a project called NaturalEarth:
https://github.com/debrief/NaturalEarth

This contains datasets formatted for use in Debrief.  The shapefile in this directory should be used for testing Debrief-Lite map rendering:
https://github.com/debrief/NaturalEarth/tree/master/ne_50m_admin_0_countries

**Comment by helenayele** [comment]
Verified.
