### ISSUE TITLE
M1.6.1.2 Load/View REP data-file for Debrief Lite

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2994]
As an ***analyst*** I wish to be able to ***load and view track data*** so that I can ***subsequently analyse what happened***.

## Status
So far we just have a bare-bones spatial mapping app.  In this stage we introduce track data, structure(s) to store that data, and code to render that data.

## Strategy
The main Debrief object for storing data is the `Layers` object.  We'll need to create one of those.  Next we need to load a track (in a `*.rep` file). That's performed using the `ImportReplay` class.  It will need a call to `setLayers` to tell it where to load new data.

The next step is to load the .rep file.  Let's add drag/drop file support to the parent class.  So, when a .rep file is dropped onto the new plot, we'll load the track data into the Layers object.

Lastly, we need to display the track on the screen.  The Layers object has a `paint()` method - call that to paint onto a destination.  Note - the legacy DebriefApp used a `SwingCanvas` control as the backdrop. We won't have this - since we're basing our app on the GeoTools Swing component.  So. a wrapper class will be required that wraps the GeoTools Swing component, to make it look like a `CanvasType` that the `Layers.paint()` method expects.

## General testing
* Drag a non-rep file onto Debrief-Lite.  Warning dialog opens, to explain file not found
* Drag a .rep file onto Debrief-Lite.  A progress bar is shown while the file loads.  Once file is loaded, Debrief-Lite map control rescales to show all loaded data (this bounds is obtained via `Layers.getBounds()`

## Source data
In the `org.mwc.cmap.combined.feature` plugin is `root_installs\sample_data`. In that folder is a track file called `boat1.rep`. That file should be used.

**Comment by helenayele** [comment]
Verified
