### ISSUE TITLE
M1.6.3.1 Export .png

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2996]
As an **analyst** I wish to **export a copy of the plot as a `.png` file** so that I can help my audience understand what happened in the exercise.

## Status
We now have a bare-bones app that looks _something_ like an analysis application.  To test the full _cradle to grave_ analysis flow, we need to output some data.  So we need to add a button to the interface (or ctrl-c key listener) that will place a bitmapped copy of the current plot on the clipboard.

## General strategy
The Full Debrief method to do the above is in `CorePlotEditor` action called `copyClipboardAction`. Elements of that can be re-used.  Ideally, the non-Swing elements of the above would be moved to a class in `org.mwc.debrief.legacy` in order that the same code be available to Debrief-Lite and full Debrief.

## Testing
* open Debrief-Lite
* load shapefile coastline
* load track data
* zoom in on some portion of the track
* copy plot to clipboard
* paste to MS Word - verify image matches that in Debrief.

## Implementation

* Create image same dimensions as map
* Tell map to render to image
* Integrate ctrl-C shortcut*
* Add menu option to copy to clipboard
* Put PNG file onto clipboard
*  Acceptance: perform copy operation, Paste into MS Word. Verify it matches the displayed map

**Comment by IanMayo** [comment]
Aah, I see this is incomplete.  

I have this plot open (note the `Collingwood` track):
![image](https://user-images.githubusercontent.com/1108513/51533590-43265480-1e3b-11e9-9a08-3df574588e53.png)

Copying it to MS Word gives us this (note that `Collingwood` is missing:
![image](https://user-images.githubusercontent.com/1108513/51533622-55a08e00-1e3b-11e9-9c31-6a90daee4e21.png)

I can understand what's happened.  We've invited the GeoTools map control to draw itself to an image.  But, once the GeoTools rendering is complete we need to ask our own Painters to draw onto the image, too.

Assigning to @unnivm - the map-wizard.

**Comment by helenayele** [comment]
After launching D-lite, I zoomin the track like this : [![Image from Gyazo](https://i.gyazo.com/2ab40a19962939e978eb9a9db4a0cf09.png)](https://gyazo.com/2ab40a19962939e978eb9a9db4a0cf09) 
and tried to trigger 'Copy Plot to PNG' action. And I tried to paste it to word docuument and looks like this [![Image from Gyazo](https://i.gyazo.com/1b3aed1dfca1fe5a071f40862f14b09d.png)](https://gyazo.com/1b3aed1dfca1fe5a071f40862f14b09d)
and when I paste it to paint , it looks like 
![image](https://user-images.githubusercontent.com/31482729/52279977-d008fc00-296b-11e9-8883-b9bb5d565056.png)

**Comment by helenayele** [comment]
still reproducible @saulhidalgoaular.

**Comment by saulhidalgoaular** [comment]
Hi. I have tested it on Windows, and now it looks good. Please, test it and tell me how it goes in your computer @helenayele

**Comment by helenayele** [comment]
Verified
