### ISSUE TITLE
M1.7 Debrief Classic not starting under MACOS

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2997]
On MACOS, the DebriefApp application silently dies when started from Eclipse.  I know it runs on Windows ok - but not on MACOS.  I'd appreciate @theanuradha investigating this.

**Comment by theanuradha** [comment]
![image](https://user-images.githubusercontent.com/535713/42892318-2b2bb050-8acf-11e8-9cb4-d2c8ad8d65fc.png)


look at bootom option UNCHECK it

**Comment by theanuradha** [comment]
![image](https://user-images.githubusercontent.com/535713/42892393-59227e80-8acf-11e8-884e-d05fcd99e26f.png)

**Comment by IanMayo** [comment]
Fixed, with above setting.
