### ISSUE TITLE
M1.6.2.2 View / Control Time

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3006]
As an **analyst** I wish to **view and control the current time** in order to **understand the context of events unfolding, and to focus on specific events**.

## Status
We need a time control for Debrief-Lite.  It _may_ look like the one in full Debrief.

In addition to controlling time, we need to highlight the location of particular participants at any time. Traditionally this is through one of two display modes: normal (rectangle) and snail.

## Strategy
The SwingStepControl should contain large parts of the logic we need for the Time Controller.

Debrief Classic included SnailPainter and TotePainter classes. Hopefully these will meet the main requirements of normal/snail painting.

### Existing data-files
* Open Debrief-Lite
* Open boat1.rep file
* Open boat2.rep file
* Check that time slider range matches the start/end time of these data-files
* Check that time control value is the first time recorded for either track
* Move the time slider, check that a marker moves along both tracks
* Switch to snail mode, check that the tracks switch to snail mode

### One track within another
* Produce cut-down version of boat2.rep file, to be named boat2_short.rep file. It should just contain the central 50% of the data, remove approx 25% from start/end
* Open Debrief
* Load boat2_short.rep
* Check the time slider show the range of this new shortened track
* Load boat1.rep
* Check the time slider has expanded to show the full range of boat1.rep

### Non-overlapping tracks
* Repeat the above, but create a very short boat1_short.rep file, that finishes before boat2_short starts.  So, they don't overlap
* Once both files are loaded, check the time period goes from the start of the earliest to the end of the latest
* Move forward in time for the normal and snail painters, check that both tracks appear/disappear s appropriate.

**Comment by IanMayo** [comment]
@helenayele - could you check that the `General testing` bits above are correct?

**Comment by helenayele** [comment]
sure

**Comment by helenayele** [comment]
@IanMayo  will you attach boat2_short.rep please, can't find in existing sample_data folder.

**Comment by IanMayo** [comment]
@helenayele - it doesn't exist.  But, the testing steps explain how to create it.
> Produce cut-down version of boat2.rep file, to be named boat2_short.rep file. It should just contain the central 50% of the data, remove approx 25% from start/end

Please have a go at producing it - but clearly I help out if you get stuck.

**Comment by helenayele** [comment]
Verified.

**Comment by helenayele** [comment]
General testing goes without any issues, hence closing.
