### ISSUE TITLE
Dynamic combo-box in Frequency Residuals View

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3053]
I've got a UI challenge.

I need to add a combo box (or drop-down menu) to the toolbar in the Frequency Residuals View.  But, the combo must by dynamic.  I can only get it to run once, as the View opens.

I've introduced my code that initially populates the combo:
https://github.com/debrief/debrief/pull/3052/commits/f40def528eec81407375092d5afa2e14778781bc

Steps to reproduce:
* Open Debrief
* Open mid_flow2.dpf
* Open `Frequency Residuals` view, via `Window / Show View...`

To demonstrate that the combo is being generated dynamically, in the working version, a random number of drop-down items will be produced each time the combo opens.

![image](https://user-images.githubusercontent.com/1108513/43462293-a1cec2bc-94cd-11e8-97bb-42688cfe39f6.png)

**Note:** this _may_ have the answer: http://git.eclipse.org/c/platform/eclipse.platform.swt.git/tree/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet67.java

It's relevant since we could re-populate the menu items in the listener event.

**Comment by theanuradha** [comment]
` IContributionItem comboCI = new ControlContribution("Acoustic Source")
    {
      protected Control createControl(final Composite parent)
      {

        final Button item = new Button(parent, SWT.FLAT | SWT.ARROW | SWT.DOWN);
        final AtomicReference<String> selection = new   AtomicReference<String>(null);
        //@IAN -> you can set Icon if you need on Button
        item.addListener(SWT.Selection, new Listener()
        {
          @Override
          public void handleEvent(Event event)
          {
            final Menu menu = new Menu(parent.getShell(), SWT.POP_UP);
            
            //----------- MENU populate -----
            int numItems =  2 + (int) (Math.random() * 6d);
            for (int i = 0; i < numItems; i++)
            {
              final MenuItem mitem = new MenuItem(menu, SWT.RADIO);
              mitem.setText("Item " + i);
              mitem.setSelection(mitem.getText().equals(selection.get()));
              mitem.addSelectionListener(new SelectionAdapter()
              {
                @Override
                public void widgetSelected(SelectionEvent e)
                {
                  selection.set(mitem.getText());
                }
              });
            }
            //-------------------------------
            
            //menu location  
            Rectangle rect = item.getBounds();
            Point pt = new Point(rect.x, rect.y + rect.height);
            pt = parent.toDisplay(pt);
            menu.setLocation(pt.x, pt.y);
            menu.setVisible(true);
          }
        });
        return item;

      }
    };
`

**Comment by theanuradha** [comment]
@IanMayo  
Added support with track selection as well

**Comment by theanuradha** [comment]
![image](https://user-images.githubusercontent.com/535713/43500009-021c08fc-956c-11e8-9b14-85e4b1a634a4.png)

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/3054

**Comment by IanMayo** [comment]
Fixed in #3054
