### ISSUE TITLE
M3.11 Refactor export to PPT to allow use in Debrief-Lite

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3067]
In the future, we will wish to introduce Export to PPT to Debrief-Lite.   Lots of work in this capability is performed by the CoordinateRecorder class.

This class contains lots of SWT/RCP related code that won't be useable in Debrief-Lite.

So, I believe there is merit in refactoring CoordinateRecorder.  I guess there are at least two approaches to this:
1.  Use an MVC style approach where CoordinateRecorder is the Controller, and it receives a View object that implements the UI capabilities (SWT in the current instance, Swing in Debrief-Lite)
2. Refactor CoordinateRecorder to be an abstract CoreCoordinateRecorder, that has abstract UI methods.  These would be implemented in SWTCoordinateRecorder (or SwingCoordinateRecorder).

I'm interested in hearing your perspective on the above choices, and am happy to listen if you're able to suggest anything else.  

We're not under any time pressure for this, so you're welcome to choose the option that seems to have the most architectural merits.

**Comment by ayeshare** [comment]
Refactored to create a corecoordinaterecorder in debrief.legacy and retained the remaining code in coordinaterecorder in the timecontroller plugin.

**Comment by IanMayo** [comment]
Solved, in #3056
