### ISSUE TITLE
D12.2 Reproduce getting started tutorial in RCPTT

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3078]
As a first set of UI regression testing, we should aim to reproduce the getting started PDF document in RCPTT.

As we go through it we'll learn lessons about RCPTT testing, and how we validate the data currently loaded in Debrief.

Note: we can defer this until we have RCPTT running in the automated build.

**Comment by IanMayo** [comment]
This is done.

**Comment by helenayele** [comment]
@IanMayo did we complete producing getting started  PDF document? if so please locate me.
