### ISSUE TITLE
[RCPTT] Rcptt returns No editing support for tree column viewer

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3148]
### Issue 1 - Can't click checkbox in Outline View

Context: we're trying to test that it's possible to hide/reveal items from the Outline View.

When RCPTT tries to select checkboxes under outline view, it logs java.lang.RuntimeException: No editing support for tree column viewer with attached stack traces.
[No editing support.txt](https://github.com/debrief/debrief/files/2411214/No.editing.support.txt)
Steps to reproduce :
1. Open “ sen_tracks.rep” file from sample_data project ,If the Import dialog appears, select Over The Ground (OTG) for both tracks.
2. Drag “ sen_ssk_sensor.dsf” SSK sensor data file onto the plot
3. Drag  the “ sen_frig_sensor.dsf” frigate sensor data file onto the plot.
4. Go to outline view and check the visibility of these checkbox for the 5 sensor data on during recording. 
From the Debrief UI this works perfect manually, but when rcptt tries to replay selecting/checking these checkboxes , it throws exception. (In another word, recording the above all steps is working perfect, but replaying the recorded scripts throws the above exception while it tries to select these check-boxes(at Step 4).

### Issue 2 - can't verify visibility checkbox
The other issue observed is , rcptt can select the visibility from properties view without any issues, but after we change the visibility of these sensor data from properties view and check it from outline view, rcptt is reading then as not-checked. But they are seen on the outline view as checked. See this Screenshot:
![image](https://user-images.githubusercontent.com/1108513/45962915-e98f5400-c019-11e8-9e0b-e77136a5fffd.png)

(From here: https://gyazo.com/fbc5d8fb987a5cb05c174b2d6ec0e852 )

See the getChecked property returns false here.

**Note:** Ian believes the above issue is because RCPTT is returning the isChecked() attribute for the visibility _row_ (in column one), not the checkbox that's in column two.

**Comment by helenayele** [comment]
Issues 1 happens when we replay the recorded scripts. Not happening while recording. 
Issue 2 is during recording. It doesn't show the current selected/checked state of the control. as we can see , it is seen like checked/seen from outline view/properties view but , when we record its state in rcptt, it is showing as not checked/not selected.

**Comment by IanMayo** [comment]
We have a workaround for Issue 2:

> instead of testing the state of the checkbox, select the item, then verify the state of the two (hide/reveal) checkboxes in the Outline toolbar
