### ISSUE TITLE
M11.4 Re-use primary track Sensor Arcs

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3166]
Sensor Arcs have a great relevance to the Unit Centric View.

When plotting the primary track, we should check if the primary track has a sensor arcs object (dynamic shapes).  If/where present, they should be plotted around the primary track marker.

~~We'll need a toggle button in the Unit Centric View toolbar to indicate if the sensor arcs should be plotted.~~

Drop need for toggle button, until specific use case arises.

**Comment by helenayele** [comment]
We still didn't implement a toggle button in the Unit Centric View toolbar to indicate if the sensor arcs should be plotted. So re-opening..

**Comment by IanMayo** [comment]
Close issue.  The value of the toggle button has been reduced.
