### ISSUE TITLE
M11.11 Error dialogs when playing with no primary

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3173]
If we haven't got a primary track assigned, a popup dialog is shown when the plot is re-rendered.

If we press **Play** when in this scenario a steady stream of modal popup dialogs are shown, and the user can get trapped.

Really, we should only show the dialog once in such circumstances.  One way to do this would be to store the time the dialog was last popped up.  If it has been shown in the last 10 seconds, we don't need to show it again.

**Better solution:** only show the dialog as the View is opening.  Don't show dialog if primary is missing on UI updates.

**Comment by IanMayo** [comment]
Fixed in #3216

**Comment by helenayele** [comment]
Verified
