### ISSUE TITLE
M3.17 Take time labels from time controller

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3177]
We show a label for current time in the PowerPoint export.

But,  it doesn't show seconds.  On very short runs it looks like the time isn't changing.  We won't know how to format the label, since we don't know how long the scenario will run for.  But, the analyst will have formatted the `TimeController` time to suit what they're looking at:
![image](https://user-images.githubusercontent.com/1108513/46192454-07e3a100-c2f3-11e8-9e53-09eb020a78ba.png)

For the labels that we display in PowerPoint, we should take them directly from the TimeController - since the analyst can apply formatting to them.

I suggest we have a new method in TimeController that returns a String representing the current label displayed (without the `REC` indicator).  We'd store these labels in a modified `TrackData` object.

Hmm, we have a decision to make.  Do we continue to maintain both Python _and_ Java implementations of the algorithm?  If @saulhidalgoaular found it easier to debug what's happening from Python then Ian is happy that Python is worth maintaining.

**Comment by saulhidalgoaular** [comment]
Good morning @IanMayo . I think we have done this in this commit. https://github.com/debrief/debrief/commit/5a31d25fd30638aaaab8c0d18efb51848c13e108
If that is correct, we may close this issue.

**Comment by IanMayo** [comment]
Yes, @saulhidalgoaular  - agreed.
