### ISSUE TITLE
M19.8 Allow .WMV to be dragged in

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3180]
`.wmv` files aren't in included in the list of allowable file types, but if the analyst switches to `*.*` then they can be opened.

We should add `.wmv` to the list of supported types.  This list of types _may_ apply both to the file-open dialog, and whether we offer `View in video player` in the context menu for that item in the Navigator pane.

**Comment by helenayele** [comment]
@IanMayo  Can I get the list of allowable file types?

**Comment by helenayele** [comment]
Okay thanks, Verified for
 .flv.
 .avi, 
.mp4
.mp3,
 file types
