### ISSUE TITLE
M9.9 Respect existing time in Stopwatch

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3181]
The stopwatch icon lets the user specify the start time for the video recording.

It is always pre-populated with the current _real world_ time (I think).

It would be better if it was pre-populated with the time at the start of the TimeController - since that's probably the correct month and year, at least.

But, once the user has provided a time, he may need to move it forwards/backwards by a couple of minutes.  It will be frustrating if the dialog is populated with a different time.

So, if the user has provided a start time, that's the time that should appear in the dialog.

**Comment by IanMayo** [comment]
Close. Can't reproduce.

**Comment by helenayele** [comment]
@IanMayo I was trying to reproduce but am afraid that I can't guess where can I get the StopWatch icon, Would you give me some hint please?

**Comment by helenayele** [comment]
Works as expected.
