### ISSUE TITLE
M19.10 Formalise support for audio

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3182]
Ian made a conscious decision not to support audio.

While it's possible to interpret video at the time steps specified in the TimeController (just like fast-forwarding through a movie), this doesn't work for audio.

Audio can only be interpreted in _real time_.   Ian thought that an analyst would never analyse an engagement in real time.

Ian was wrong. While an analyst may not want to analyse a whole engagement in real time, he may want to explore every data source available for a particular short period in time, including an audio recording.

_Luckily for Ian_, the Video player supports audio files _out of the box_.   So, we should acknowledge this support, through:
1. renaming the view as `Media player`
1. doing some testing of what audio formats are supported
1. providing these formats in the dialog, and use them when adding `Play in media player` for a file's context menu in the navigator view.

**Comment by helenayele** [comment]
Verified.
