### ISSUE TITLE
D25 Import UK CSV file format

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3204]
We've introduced the ability to export to the UK CSV exchange format.

Analysts can only review what's in the file by opening in Excel, and producing a scatter diagram of the lat/long columns.  Sadly, lat and long equate to y and x, so the x and y axes are exchanged when looking at the image.

I would be easier to review the content if it could be loaded into Debrief

I _think_ we already have a CSV import capability (in a different format).  We need to introduce an extra CSV Import handler, that checks for the relevant phrase on the opening line: `# UK TRACK EXCHANGE FORMAT, V1.0`

## Expected behaviour
1. Open Debrief
1. Open `sample.dpf`
1. Right-click on `Nelson`, select `Export track to CSV text format`.  Fill in any old values into the fields, export to known location.
1. Rename the `Nelson` track to `Nelson - Original`
1. Drag the exported `.csv` file back into Debrief. Check that `Nelson` and `Nelson - original` are identical
1. View an XY Plot of both of their speeds - the plots should be identical
1. Repeat the above for course, then depth. All should be identical.

**Comment by helenayele** [comment]
@IanMayo trying to follow these steps 

1. Open sample.dpf
2. Right-click on Nelson, select Export track to CSV text format. But I can't find export tracl to csc text format context menu - [![Image from Gyazo](https://i.gyazo.com/18517c1ae55fa2f3429b69e1b9c7471e.png)](https://gyazo.com/18517c1ae55fa2f3429b69e1b9c7471e)

And also tried to right click on Nelson plot and found only these ctx menus - [![Image from Gyazo](https://i.gyazo.com/96d3ff45642a5a22d6f7665eaaa979c0.png)](https://gyazo.com/96d3ff45642a5a22d6f7665eaaa979c0)

**Comment by IanMayo** [comment]
Sure, it's an option that's really rarely used.  So it's switched off by default.  It's in the preferences window - in a tab called **CSV Export Wizard**.
