### ISSUE TITLE
D26 - More robust handling of CSV export

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3205]
We accidentally deleted the CSV file containing the drop-down lists.

When we tried to export a track to CSV format, Debrief silently failed.  

The error log indicated that the fault lay at `CSVExportPage1.java#148` . It was a NPE caused by the input data not being found.

The export process really shouldn't get that far, an error dialog should be offered as soon as the user tries to do the export.

## Steps to reproduce
1. Open Debrief
1. Go into `Window > Preferences > Maritime Analysis > CSV Export Wizard`
1. Click on `Browse`, and navigate to `sample_data\other_formats\ExportWizard.csv`
1. Open `Sample.dpf`
1. Right-click on `Nelson` track
1. Select `Export track to CSV text format`
1. Fill in wizard steps, check `.csv` file has been created

Ok, that's the intended behaviour. Now let's break it:
1. Navigate to the `sample_data\other_formats` folder
1. Rename `ExportWizard.csv` to `ExportWizard_RENAMED.csv` (or similar)
1. Go through the export process again,  observe that the export wizard doesn't appear.

The desired behaviour is that at the previous step, a popup appears, saying:
**Title:** Export to CSV Text format
**Message:** Please provide the path to the Export Wizard drop-down list, in the preferences window.

**Comment by helenayele** [comment]
Following exact steps . after modifying the ExportWizard.csv to ExportWizard_RENAMED.csv trying to export to csv format will export normally as if the file is not renamed. It recognazes the renaming of the file when we restart debrief. is this expected? and the dialog looks like [![Image from Gyazo](https://thumb.gyazo.com/thumb/200/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpbWciOiJfMWZkZDI3MDI0MzVlNTc4NTZjOTVjNjI0ODFjNDE1ZDUifQ.IkKA0LUxMsb4O-Po9BTkXF21VnOrEx-o3lsdprK20Sw-png.jpg)](https://gyazo.com/2124b746b5a72d7a26f2320b58f51194)
