### ISSUE TITLE
M3.23  Narratives not going to PPT

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3227]
We have a sample data-file that includes some narrative data.  See the file here:
https://github.com/debrief/debrief/blob/develop/org.mwc.cmap.combined.feature/root_installs/sample_data/sen_tracks_with_narrative.dpf

But, when it goes to PowerPoint, only the first narrative entry is shown.  See it in the video here:
https://youtu.be/qEBB-Umju6U

We should start off by verifying:
1. that the entries are being stored in the track data object
1. that the data is being sent to XML
1. what's happening to the data in PowerPoint

**Comment by helenayele** [comment]
I tried to record like this [![Image from Gyazo](https://i.gyazo.com/b982ad74c300e8c60964c1a1d5e52e56.gif)](https://gyazo.com/b982ad74c300e8c60964c1a1d5e52e56)

And the exported ppt looks like 
[DebriefExport-030319_1.PPTX](https://github.com/debrief/debrief/files/2575295/DebriefExport-030319_1.PPTX) , as can be seen , the narrative data are not properly shown.
Hence re-opening...

**Comment by helenayele** [comment]
The narrative entry is displayed according to the play time of the recording and this seems right to me.   And also the recording icon is shown properly.So closing this issue.
