### ISSUE TITLE
M19 - Video/Audio sync-After closing track plot video player is still playing

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3230]
When we close the track data , the video continues playing.
Steps to reproduce :
1. Open Sample.dpf file
2. Drag 19951212_103415.avi file on to the opened plot from other_format folder
3. Play a little and close the Sample.dpf file

See that  the video player is still playing
Expected Result:
The video player should stop playing.

**Comment by ayeshare** [comment]
cannot replicate this with the steps given above.

**Comment by helenayele** [comment]
Ian and Aysha stated "The user may be watching video that isn't related to plot. Let's let the video continue playing when plot is closed." so based on this the issue is expected and so closing..
