### ISSUE TITLE
After opening and playing a video player, trying to open a fresh empty video player is not possible

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3231]
**M19 - Video/Audio sync**
After playing a video and closing it , trying to open a fresh empty video player is not possible. It will open the previous played video.
Steps :
1. Open Sample.dpf file
2. Drag 19951212_103415.avi file from other_formats folder on to the opened plot.
3. Play a little and stop the player and close the video view.
4. Open video player from Window > Show Views > Video player

See that the video file opened at step #2 is opened in the newly opened video player.

Expected Result 

An empty blank video view should be opened whenever it is invoked from Window > show views > Video Player

**Comment by ayeshare** [comment]
I see the expected result after trying out all the steps given above. cant replicate this issue now

**Comment by helenayele** [comment]
I can't no more reproduce it, so closing
