### ISSUE TITLE
Sometimes duplicate toobar buttons are seen on time controller view

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3239]
Sometimes Duplicate toobar buttons are seen on time controller when we put focus on already opened editor while Workbench launches for the first time 
Video : https://gyazo.com/43b54074691dbfc356955d5fda440c9c

### Steps to Reproduce:
1. Open sample.dpf file
2.  start Debrief from eclipse
3. As soon as it launches and open TimeController view and  try to put the cursor inside the opened plot or  try to close the editor by clicking the close (X )button in the editor area. 

### Expected Result
No duplicate toolbar buttons should be seen

**Comment by saulhidalgoaular** [comment]
Good morning @helenayele .
I have tried, but I was unable to reproduce it. I've ran on Linux and Windows, resizing Debrief, maximizing it, etc. Could you please give more details about how to reproduce it, please?

**Comment by helenayele** [comment]
Unable to reproduce myself as well and I Have agreed to close it with @Ian
