### ISSUE TITLE
M22-Paste REP from clipboard -Debrief doesn't recognize invalid data while pasting

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3243]
Debrief also doesn't recognize some invalid data.
### Steps to Reproduce
1. Open boat1.rep file in text editor
2. Change the month in the second row to 00 , OR change the date to 33
3. Save copy only some of line like till line 10 
4. Open a plot and try to paste it ,  now Debrief goes to not-responding state again

### Expected Result:
It should validate the data and shouldn't provide the option to paste if the data is invalid.

**Comment by IanMayo** [comment]
@helenayele - when I reproduce this, I get an error dialog indicating the problem:
![image](https://user-images.githubusercontent.com/1108513/46751413-62490e00-ccb2-11e8-91c8-53e111ab594a.png)

Could you double-check that you aren't getting that dialog?

**Comment by helenayele** [comment]
I am still getting Debrief turned to not responding state  while pasting invalid data to new plot am not getting the dialog you are seeing.
 https://gyazo.com/3374702577f238721a6a8bc156763b49 . 
it logs also 
java.text.ParseException: Unparseable date: "950012 050300"
	at java.text.DateFormat.parse(Unknown Source)
	at MWC.Utilities.TextFormatting.DebriefFormatDateTime.parseThis(DebriefFormatDateTime.java:288)
	at MWC.Utilities.TextFormatting.DebriefFormatDateTime.parseThis(DebriefFormatDateTime.java:355)
	at Debrief.ReaderWriter.Replay.ImportFix.readThisLine(ImportFix.java:211)
	at Debrief.ReaderWriter.Replay.ImportReplay.readLine(ImportReplay.java:2230)
	at Debrief.ReaderWriter.Replay.ImportReplay.importRep(ImportReplay.java:1545)
	at Debrief.ReaderWriter.Replay.ImportReplay.importThis(ImportReplay.java:1493)
	at org.mwc.d........

**Comment by helenayele** [comment]
The problem now seems intermittent, only happening on some plots
### Steps when it fails to show error dialog:
1. Open new plot - with no track data
2. Paste some invalid data in outline view
####  OR
1. Open sen_tracks.rep file
2. paste some invalid data in outline view

In both cases debrief turns to not -responding state.

### Steps when it shows the error dialog
1. Open sample.dpf file
2. Paste some invalid data in outline view
This time it shows the error dialog

**Comment by IanMayo** [comment]
@helenayele - Ayesha has reported fixing this.  Could you see if the issue is still there?

**Comment by helenayele** [comment]
I tried to re-test all the above scenarios and it is working as expected. It popups the dialog whenever I try to paste invalid data.  So closing...
