### ISSUE TITLE
Put NMEA tracks into named folder

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3258]
When we import NMEA tracks, we import them as heavyweight tracks, putting them into the top-level folder.

We should load them as lightweight tracks, and put them into a `NMEA Contacts` folder.

**Comment by helenayele** [comment]
@IanMayo  Would you please tell the location where we can get those NMEA tracks please?

**Comment by IanMayo** [comment]
I'm pretty sure we don't think we have any sample ones.
