### ISSUE TITLE
Can't change TMA start time

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3267]
> I have a TMA leg from 0730 – 0830, before 0730 the track was in the stern, 
> so I opened up the TMA leg and changed the start time in the outline view to
> 0710 to DR back as CPA was before 0730.
> 
> When I changed the time the TMA name was changed the solution on the plot
> jumped to another position but still showed 0730 as the start time.

I was able to reproduce this using `midflow2.dpf`.  When we change the start time for the first leg, the start time doesn't change, and it doesn't get any new points.

**Comment by helenayele** [comment]
@IanMayo I was trying to change the start time of one of the legs in the property view, but it doesn't change it, https://gyazo.com/87ce253955d8def5ff9ea962a146ed10 , may be I missed something?

**Comment by IanMayo** [comment]
It's ok.  The leg is _Dependent_ on the blue track.  So, we can't extend the leg earlier than we have blue track data for.  So, this is intended behaviour.
