### ISSUE TITLE
M28 - MSI/P2 Release

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3297]
As an **_Analyst , I need different ways of getting Debrief._**
I need to get Debrief using the following scenarios:

### Different Scenarios to get Debrief:

1.  if System Administrators are able to push a piece of software (or a software update) down the network to an analyst PC/laptop.
2.  if an installed copy of Debrief is able to check for updates, and, if any are present, invite the analyst to see what is new, then decide where to let Debrief update itself to the new version.
#### Mechanism 
It can be met by delivering Debrief as a Microsoft MSI file, or the use of a P2 Update Site.  The P2 Update Site is already part of the Debrief build, so it can happen at low cost/risk.  MSI is a file format proprietary to Microsoft, adoption of it represents cost/risk.

### Requirement

1. Ability to easily update Debrief once new software is available
2. Ability to push a Debrief installation to a particular PC, pre-configuring it with how/where to find updates.

**Comment by IanMayo** [comment]
Closing. Created in error.
