### ISSUE TITLE
Unable to edit Polygon

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3304]
For Polygon shapes, users need to be able to add/edit/remove nodes.

In `shapes.rep` there is a Polygon and a Polyline.  In the Outline view, it's possible to expand both shapes to access their nodes.  It's also possible to right-click on one of the shapes, and select `Add node`.

![image](https://user-images.githubusercontent.com/1108513/47065340-8f2d8180-d1da-11e8-8a38-d153448b0cd7.png)

For our new Dynamic Polygons, we don't have the above behaviour.

![image](https://user-images.githubusercontent.com/1108513/47065357-981e5300-d1da-11e8-9351-cd76ade0ed6b.png)

I think the issue is that editable polygons are contained in a `PolygonShapeWrapper` - which provides the additional methods/properties, and the `addOrderedChildren` that lets it expand in the Outline View.  But, our dynamic polygons are contained in a `DynamicShapeWrapper` which extends `ShapeWrapper`.

So, we either need to put our polygons in to a `DynamicPolygonShapeWrapper` - which extends `PolygonShapeWrapper` (while adding any trimmings needed for Dynamic Shapes), or we need to make `DynamicShapeWrapper` more flexible, and return different properties if it's wrapping a polygon.

If we do the former we may need to change the API for the Create Dynamic Shapes code, so the instances return a ShapeWrapper, rather than a PlainShape, I guess.

**Comment by IanMayo** [comment]
@ayeshare - I think you'd be suited to this issue.

**Comment by ayeshare** [comment]
I investigated this a little bit:
_DYNAMIC_POLY: @A "Dynamic A" 951212 052600.000 20 35 0 N 21 02 0 W 20 35 0 N 20 55 0 W 20 42 0 N 20 52 0 W 20 45 0 N 21 00 0 W  dynamic A POLY 17_
adds a dynamic polygon without a drop down tree of nodes under it

_;POLY: @GA30 21.9 0 0 N 21.5 0 0 W 22 0 0 N 21.8 0 0 W 22.1 0 0 N 21.5 0 0 W test\npoly_
adds a polygon with  a dropdown tree of nodes under it.

**Comment by IanMayo** [comment]
Yes, the top one creates a DynamicShapeWrapper, that contains a PolygonShape. The second one creates a PolygonWrapper, that contains a PolygonShape.
