### ISSUE TITLE
Unable to put non-tracks data items and tracks data together on Tote view

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3307]
If I make one of the tracks data as primary and one of the  non-tracks data item as secondary data, the non-tracks data is not shown on tote view. only the track data is displayed.

### Steps to reproduce:
1. Open Sample.dpf
2. Select one of the items from misc layer,(select first line) and make it primary
3. Open Tote view and see that it is displayed 
4. Make one of the tracks primary and make the above selected item Secondary data
See that it is not shown in tote view, Only the tracks data is displayed.

### Expected Result
Both The line and track data should be displayed in tote view.

**Comment by IanMayo** [comment]
This is because the items on the misc layer don't have course/speed/etc.  It is only feasible to show this data for a proper track.

But, we do show range/bearing etc for both.
