### ISSUE TITLE
After Enabling Measure Range bearing, right clicking inside a plot logs SWTException

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3312]
After I enable measure range bearing button, trying to right click inside a plot logs org.eclipse.swt.SWTException: Graphic is disposed , the full stack traces is attached below.
### Steps to reproduce:
1. Open sample.dpf file
2. Select Measure Range bearing button 
3. Right click on one of the tracks line 
4. Then you will get Debrief busy and  this excpetion is logged in eclipse
[SWTException-Unhandled_event_loop_exception.txt](https://github.com/debrief/debrief/files/2492842/SWTException-Unhandled_event_loop_exception.txt)

5 . Select Insert new Sensor Arc ctx menu
6. Finish the wizard using default values.
You will get the sensor arc created. 

### Expected Result:
No error /Exception should be logged and Debrief should be smooth.

**Comment by IanMayo** [comment]
Great, thanks @helenayele 

Would you mind repeating the steps, just to check if it reliably fails this way every time?

**Comment by ayeshare** [comment]
@helenayele @IanMayo cant replicate this

**Comment by helenayele** [comment]
I can't reproduce this issue now, while right clicking inside the plot , debrief is not going to be turned to non-responding state neither , so with some discussion with @IanMayo , closing it.

**Comment by IanMayo** [comment]
Ok, inspecting the error indicates it's related to `GenerateNewInsertSensorArcAction.java`

There was a fix to this class, to avoid an NPE. That may have fixed this issue.
