### ISSUE TITLE
Property editor won't open for Lightweight tracks

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3315]
An analyst has some tracks.

He loads a narrative, that includes some FCSs.   They get imported as lightweight tracks in a dedicated folder.

He can't right-click on the new tracks. Error logs show trouble with showing snail size and shape.

Steps to reproduce:
1. Load `sample.dpf`
2. Load `other_formats\FCS_Narrative.pdf`
3. When the dialog opens, select `Load all data`
4. Expand `Narrative FCSs` layer
5. Select an lightweight track
6. Observe that editors for `Snail Symbol Type` and `Snail symbol size` are not shown.

**Comment by helenayele** [comment]
@IanMayo , would you please specify the location/path of Load FCS_Narrative.dpf file please?

**Comment by IanMayo** [comment]
@helenayele - path corrected

**Comment by helenayele** [comment]
@IanMayo  thanks! Tried to change the Snail Symbol Size and Snail Symbol Type, but I can't see any difference for example if I change the symbol size from medium to huge or from small to huge. The size is always the same like [![Image from Gyazo](https://i.gyazo.com/8b5362e648bb8776d6a152d706937299.png)](https://gyazo.com/8b5362e648bb8776d6a152d706937299) 
And again, I can't see the snail symbol type applied to the lightweight tracks.

**Comment by IanMayo** [comment]
@helenayele - yes, good point.  I'll create an issue for it.
