### ISSUE TITLE
NPE While clicking inside Grid Editor view after plot is closed

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3328]
### Steps to Reproduce

1. Open nosuch.rep file from sr2 folder
2. drag sensor.dsf file
3. Open grid editor view
4. Select 826 positions from nosuch track layer
5. Now Grid Editor View populates track data
6. Close nosuch.rep editor
7. See that the contents in grid editor view are still exist/displayed - 
8. Click inside the Grid editor view - see that NPE error dialog is displayed - https://gyazo.com/d08dc420a70a19339237865cbe5dfced , with the following stack trace 
[NPE_Grid_Editor_view.txt](https://github.com/debrief/debrief/files/2502064/NPE_Grid_Editor_view.txt)

### Expected Result

- While closing the plot, the data inside the grid editor view should be removed - grid view should be empty
- No Exception should be logged while selecting inside this view.

**Comment by ayeshare** [comment]
the data in the grideditor is being retained intentionally even when the input to the grid editor is null.
I see the following comment in the code:
if (input == null)
		{
			// not valid data - set input to null (which clears the UI
			
			// CHANGED:  don't wipe on invalid input. This lets us do Layer Manager edits
			// based on data in the grid editor
			// myUI.inputSeriesChanged(null);
		}
