### ISSUE TITLE
After adding scenario or new leg , 'items' label is missing in outline view

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3336]
### Steps to Reproduce:

1. Open the SATC sub-folder and drag the “L1_OwnshipTrack.rep” file into debrief plot
2. Select Over the Ground (OTG) mode.
3. Drag L1_OwnshipTrack.dsf sensor data to the plot , the Import Sensor Wizard will begin.
4. You can leave this sensor contact name as Plain . Click on Next
5. Choose a color for the sensor data, then click Next
6. Select the value check box so that the sensor data will be visible, then click > Next .
7. In the Rainbow shades dialog, select the check box to shade the sensor cuts.
8. Click on Finish .
9. In the outline view, select the sensor data - Sensor:Plain (11 items)
10. Right-click on it and select SemiAuto TMA > Create new scenario from these bearings .
11.  As soon as the scenario is created, a new name is assigned ,  and it misses **_( 1 items)_**  label , rename it to Single Leg
12. Select Track:Ownship > Sensors (1 items) , and then right-click on Sensor:Plain (11 items) .
13.  From the dropdown menu, select Semi Auto TMA > Add to Single Leg > New Straight Leg for period covered by [sensor cuts] .
14. When the New contribution dialog opens up, name this contribution Leg limits > Click on Ok .
Currently it looks like
SS :  https://gyazo.com/7ac32b9fc92bfb0d504c3e3af41214f6

### Expected Result
In the Outline view, you should see Single Leg (1 item) has changed to Single Leg (2 items) .

**Comment by IanMayo** [comment]
Hmm I do see the `items` text:
![image](https://user-images.githubusercontent.com/1108513/47662261-805bad00-db92-11e8-96ee-411d12e5feb4.png)

@helenayele - can you re-test?

**Comment by helenayele** [comment]
I can still reproduce it - https://gyazo.com/c426a14795009a1a1f7d7422bf9839a7 and
 , I am running from develop branch  - https://gyazo.com/b9c18606fbea474827b744e877377068

**Comment by helenayele** [comment]
I can now see the `items` word , and it look like [![Image from Gyazo](https://i.gyazo.com/42e2ca1e234a3891caef9ae83a62b12f.png)](https://gyazo.com/42e2ca1e234a3891caef9ae83a62b12f)
So closing..
