### ISSUE TITLE
Missing Unit Tests for CoordinateRecorder

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#3339]
I think it’s important that we have scenarios where they start at the same time, primary starts first, secondary starts first, etc.  In that case, it’s probably easier to generate the tracks by hand.
For the test, I think it’s better to do it headless.  So, we put some data into a Layers object.  Then we pass it to `CoordinateRecorder`, then we call `startStepping` once, then `newTime` a few times, then `stopStepping`, then we examine the contents of `_tracks` (or any other relevant data items).

**Comment by IanMayo** [comment]
Yes, @saulhidalgoaular - that's exactly what we should do.

**Comment by helenayele** [comment]
@saulhidalgoaular , would you please put some steps to verify this issue?
