### ISSUE TITLE
NotSerializableException while triggering ctx menus inside a plot

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3344]
Trying to invoke one of the context menus inside a plot will throw NotSerializableException. Full stack trace is attached below.
[Not SerializableException.txt](https://github.com/debrief/debrief/files/2524997/Not.SerializableException.txt)

### Steps 
1. Open sample.dpf
2. Right click on one of the tracks position on the plot
3. Invoke most of the available ctx menus there

See that this exception will be logged in the error log.
### Expected Result
No such exception should be logged.

**Comment by IanMayo** [comment]
@helenayele - could you put some effort into producing a tighter description of what steps are required to reproduce it?

From the listing, it looks like the DynamicShapeCoverage was what triggered it.  Could you focus on that?

You may need to close and re-open the plot to ensure you get a fresh plot each time.

(background, it's _expensive_ for the dev to have to `Invoke most of the available ctx menus there`).

**Comment by helenayele** [comment]
Please find the steps to reproduce the issues from these steps 
Steps :

1. Open sen_tracks_with_narrative.dpf
2. Right click on the Frigate track 

-   copy 0213
-   0213 > color > purple
-   Add new sensor > complete the wizard with default value
-   Insert new sensor arc - complete the wizad with default value
-   Frigate > color > Green
-   Export Shape
-   Generate calculated Course and Speed
-   Add new Sensor   > Finish
-   Copy 0224 

then the exception will be thrown. 

Note: 
I did have the video but I can't attach it due to its volume.

**Comment by helenayele** [comment]
Verified. No exception/issue is seen
