### ISSUE TITLE
Sometimes Image viewer retains the previously opened images

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3356]
Issue Video - https://gyazo.com/575aca8f977b0087c68edbaa26d17ea0

### Steps to Reproduce:
1. Open Image viewer view
2. Drag a folder with timed-images either from sample_data/other_formats folder or file system
3. See that the images are loaded in the view
4. close the image viewer
5. Open Image Viewer view from Window > Show View > Image Viewer 
As can be seen from the video it opened the previous loaded images.

**Comment by IanMayo** [comment]
@helenayele - I'm also unable to replicate this.

**Comment by helenayele** [comment]
@ayeshare @IanMayo  I am still reproducing it - https://gyazo.com/a4693279c2e38ebbbc02377d641cc13a 
May be I want you to try these steps:
1. Open Image viewer
2. Click Open toolbar button on the image viewer and try to load images from your local folders
3. Close image Viewer and open it again.

As can be seen from my video, it caches the one that I loaded from my local machine.

**Comment by IanMayo** [comment]
Hello @helenayele - could you clarify which branch/build you're using?

We've got to reproduce it, before we can resolve it.

@ayeshare - it's interesting that the video starts with the contents of the `Timed Images` folder. But, when it re-opens it's a folder of Helen's lovely family photos.   This folder location must either be a preference, or a memento, or something similar.  If we can't reproduce it, we'll just have to do it via code inspection (sadly).

**Comment by IanMayo** [comment]
Hmm, I had wondered if the issue was because no plot editor is open.  But there is a plot open in the first one.

**Comment by helenayele** [comment]
Tested also by opening plot editors and still the issue persists.

**Comment by ayeshare** [comment]
finally, I managed to reproduce it.  We are purposely remembering the folder that was last opened in the memento object.  After exiting the application and restarting it again, if the imageviewer was open, then it remembers the last open folder and other attributes such as stretch, icon size are also being remembered.

**Comment by IanMayo** [comment]
Great, well done @ayeshare .  So, shall we just persist the attributes _other than_ the last open folder ?

**Comment by helenayele** [comment]
Currently it doesn't remember the last opened folder, but also it doesn't persist the attributes . 
For example , I opened timedImage and make no stretch and choose small icon type as can be seen in the below video - [![Image from Gyazo](https://i.gyazo.com/99dc220fd137fcb227342560348d13c4.gif)](https://gyazo.com/99dc220fd137fcb227342560348d13c4)
And then I closed it , and when I open , I get the default attributes values like , Stretching = true and icon size = Large.
Is this expected?

**Comment by IanMayo** [comment]
Hmm, it would seem better if we remembered the stretch mode and icon size.   Did we used to remember/restore these attributes @helenayele  ?

**Comment by IanMayo** [comment]
Shall we continue to persist them? We're agreed that we shouldn't store the folder path, but it seems right to remember these.

**Comment by helenayele** [comment]
Yes, if that doesn't cost us much. It is just very nice if we keep persist the users' preferences as much as possible. But not sure what @ayeshare  thinks so?

**Comment by ayeshare** [comment]
At present, the states are remembered only after debrief restart. Within the same session the state of the view is not remembered.  I have retained that behaviour.
