### ISSUE TITLE
D28 Import BRT file

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3366]
As an ***analyst*** I wish to ***import BRT data-files*** in order to ***reduce the steps in reconstruction, and potentially overcome a third-party error in generating ambiguous bearings***.

As a by-product of another process, and analyst has a bearing file in BRT format.  If we allow this to be imported, we remove the analysis step of "Convert BRT file to Debrief format".  Sadly, in the current implementation of the third party tool that does this, some of the bearings get messed up.

So, adding this feature will both save time, and result in better quality data.

## Acceptance criteria
1. Drag/drop .BRT file into Debrief, wizard opens.  User answers wizard questions. Check those answers have been used in the import.
2. Drag/drop both Towed Array and Hull-Mounted datasets.  Observe how they're separately handled in Debrief. The Towed Array data should be ambiguous, with an array offset distance. The non towed-array data shouldn't have either.  Learn more about _Ambiguous Bearings_ in the [Debrief Glossary ](https://github.com/debrief/debrief/wiki/glossary)
3. Verify that towed array cuts get converted correctly to ambiguous cuts during the turn
4. Wizard correctly handles single track in plot, multiple tracks with one Blue, multiple tracks with non blue, multiple tracks with more than one blue.

## Data format
This format is CSV of time and relative bearing, like this:
````
1514444259.00000, 113.3
````
The time value is seconds since 1970, and the bearing is degrees.

The time for the value is believed to be 2017/12/12 06:57:39  (excuse typo if that's slightly out).

## Implementation
For Debrief, we need to convert the relative bearing to absolute, using ownship heading.  We also don't know if the data is ambiguous or not.  See discussion on relative bearing here: https://github.com/debrief/debrief/wiki/glossary

So, when the file is dropped into a plot, we do the following:
1. Find the track to add it to:
    * If there is only one track loaded, we use that one
    * if there is more than one track loaded, but there is a single one colored DebriefColors.Blue, we use that one
    * otherwise we popup a dialog of tracks, and ask which one to add it to.
2. Determine what kind of sensor it is:
    * Ask if it's from a TowedArray
    * If it is, then ask for the towed array offset (re-using the previously used value [* see **Note 1**])
3. Choose the color for the data (re-use previous value)
4. Choose the default sensor cut length (re-use previous value)
5. Use the filename as the sensor name
6. Add the sensor cuts to the sensor, using the course at the relevant time to determine actual (and, if necessary, ambiguous) bearing.

**Note 1:** We already have a sensor import wizard. This wizard already remembers values for sensor offset length, and default sensor cut length (range).  We should re-use the values from that wizard as defaults for this wizard.
**Note 2:** it's important that for Towed Array data we walk back down the track for the relevant distance to find Ownship course at that time - in order to calculate the absolute bearings.

## Testing
We need to develop test-files to be used for this.  I've attached some below. If they aren't sufficient then I suggest we reverse-engineer ones from existing Debrief data (both towed array and hull-mounted sonars).   We can open a plot, then measure some bearings at known times, write these to .BRT file, then load them.

The import should be in `org.mwc.debrief.legacy`, and we should use TDD to verify that lines get parsed as expected.

_Hopefully_ we can implement the logic to decide on a subject track using a headless backend, then test the logic in unit tests.  So, we don't just test the import processing - we also test the logic about handling what tracks are present. One way of doing this in a headless fashion is to write the code in `legacy` plugin, but pass it a helper class.  In real Debrief this helper class will make UI calls. In unit testing this helper class will log events, and/or return test data.

We should also certainly have unit tests to verify that we correctly generate absolute bearings from both types of sensor.

## Documentation
We should document our understanding of this format in the Reference Manual

## Test data
Some test data is attached:
[brt_import.zip](https://github.com/debrief/debrief/files/2545122/brt_import.zip)

**Comment by IanMayo** [comment]
@saulhidalgoaular - here's the example I showed you of when we previously created a new file importer type:
https://github.com/debrief/debrief/issues/1021

**Comment by Waynearendse** [comment]
Ian to review code and then demo to Helene

**Comment by IanMayo** [comment]
Fixed in 3393
