### ISSUE TITLE
Bug - All labels showing for dynamic infill

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3370]
When we generate a dynamic infill segment, we copy the formatting from the last position on the previous leg.

But, when we do this, we should not copy the `Label Visible` attribute.  We should not show labels by default for Dynamic Infills.

**Comment by IanMayo** [comment]
Re-open, still not fixed.

**Comment by helenayele** [comment]
[![Image from Gyazo](https://thumb.gyazo.com/thumb/200/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpbWciOiJfYmFjZjc4YjlkYzk2ZjI5NDE5MzZkMmZmYjljOTFiYzQifQ.1oKJsmbqNgcNbjqqfCLdWG9gYxuTDx2BfQFHIuTB3gs-png.jpg)](https://gyazo.com/b7c4d7dc9951a0d4bd59ad71dc6f97ec) - yes not fixed

**Comment by IanMayo** [comment]
Yes, but in your diagram all labels are shown.  This bug relates to this situation.  We have (For example) A label every 10 minutes. When we drag a track at either end of the infill, the points get re-generated. They use the last position on the previous leg as a _template_ to copy.  So, if the last point on the previous leg has a label showing, then all points on the infill have a label showing.  The analysts don't want that. They don't want time labels on the auto-generated infill.

I'll try to work on this today.

**Comment by IanMayo** [comment]
Ok, just investigated.  It looks fixed: https://youtu.be/r6xytgxrcW4

Will have to re-verify it with analyst dataset.
