### ISSUE TITLE
Multiple recording icons are displayed  while recording track positions

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3402]
Issue  - 
https://gyazo.com/64fdf5e69fe835d11ed10654e73dfdd6
https://gyazo.com/c72284f658d811bba098c5a38a367026

I got those duplicate icons that shows recording state while recording.

### Steps to reproduce:
1. Open sample.dpf
2. select record button - then pause recording and cancel exporting
3. repeat step 2
4. Select Record  button.
5. While recording resize - expand the width of the timecontroller by dragging to right. this time you will see multiple recording state's icon

Then you will get those multiple recording states' icon.

Once you see those multiple icons, you can reproduce it always unless you restart debrief.

**Comment by IanMayo** [comment]
Yes, I saw this at a demo last week.  I'd like to skim over it, but it's right that we fix it.

I think that @ayeshare is the natural person to work on it, she's the author of record button code.

**Comment by helenayele** [comment]
Verified
