### ISSUE TITLE
Exported PPT file overlaps the minutes part and reduce its visibility

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3403]
See this exported PPT file 
[DebriefExport-95_12_12_10_46_47.PPTX](https://github.com/debrief/debrief/files/2571352/DebriefExport-95_12_12_10_46_47.PPTX)
Play it and see the minutes parts.

**Comment by helenayele** [comment]
This issue is still reproducible

**Comment by IanMayo** [comment]
Ok, this is a flaw in the master template. The time label should not be transparent - it should have a solid background the same colour as the panel behind it.
