### ISSUE TITLE
M7.1.3 Test quick steps for scientist

### ISSUE THREAD

**Issue by Waynearendse** [debrief/debrief#3419]
Open the module explorer and see the standard scripting modules
Produce a hello world script

Ian has started the script here: https://docs.google.com/document/d/1bWRLxSfBQzJ4EFnuZz4JH1BIr6hjj5eYhlxqRYNngr4/edit#

4 hrs testing

**Comment by IanMayo** [comment]
Ok, document done.

**Comment by IanMayo** [comment]
Oops, closed wrong one.

**Comment by IanMayo** [comment]
Done. Reviewing tutorial will be a future issue.
