### ISSUE TITLE
M7.2.1 Produce shopping list of which objects to share with Scientist

### ISSUE THREAD

**Issue by Waynearendse** [debrief/debrief#3420]
Investigation - 4 hrs
Pulling list of objects (Tree diagram for example google doc) 
DIscussion review with Ian, once Saul has completed the list

Ian to have a discussion with the scientist

In the discussion, we identified that we should also allow:
* **Time Control**. Get time, set time, control VCR controls, change normal/snail mode
* **Track Tote**: set primary, set/add secondary, remove track
* **Projection**:  get viewport, set view, fit to window
* **Object model**:  get current selection, set current selection
* **Clipboard**: copy plot to clipboard as png or wmf. Write text to clipboard

**Comment by IanMayo** [comment]
Done.
