### ISSUE TITLE
M7.2.2 Produce code to expose object models - First Bucket of 8

### ISSUE THREAD

**Issue by Waynearendse** [debrief/debrief#3421]
Call the constructor and Write the Wrappers
Write a unit test for each wrapper
30 mins per object - check no exceptions is thrown. Testing diff parameters
Add the line for code completion to the wrappers 
For one Buckets of 8 = 4hours

**To include investigating why new object didn't appear in Outline View**

Code review 1 hour

**Comment by saulhidalgoaular** [comment]
Methods ready for testing

Shapes:
- createEllipse
- createFurthestOnCircleShape
- createPolygon
- createRangeRingShape
- createRectangleShape
- createWheelShape

Core
- createFont

Narratives
- createNarrative

**Comment by helenayele** [comment]
@saulhidalgoaular  , to create createFurthestOnCircleShape , we need to expose WorldSpeed, and I can't see it in the module explorer.
