### ISSUE TITLE
M7.2.2. Produce code to expose object models - Third Bucket of 8

### ISSUE THREAD

**Issue by Waynearendse** [debrief/debrief#3425]
Call the constructor and write the wrappers
Write a unit test for each wrapper
30 mins per object- check no exceptions is thrown. Testing diff parameters
Add the line for code completion to the wrappers
Second bucket of 8 = 4 hours
Code Review 1 hour

**Comment by saulhidalgoaular** [comment]
* Tote
 - getPrimaryTrack()
 - getSecondaryTracks()
 - setPrimaryTrack()
 - setSecondary()
 - addSecondary()

* Core:
 - createDuration()
 - getTimeManager()
 - getTimeControlPreferences()

**Comment by helenayele** [comment]
@saulhidalgoaular can't find getTimeManager() and 
getTimeControlPreferences()  in the core module

**Comment by IanMayo** [comment]
Done.
