### ISSUE TITLE
Sometimes Invalid final field MWC.GUI.JFreeChart.ColouredDataItem._myColor error dialog is shown after creating xy plot

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3434]
### Steps to reproduce:
1. Open sample.dpf  file
2. Open time controller view and select DTG format as ddHHmm
3. Select the period 120800 to  ​121100 
4. In outline view, select both COLLINGWOOD and NELSON tracks using ctrl+click
5. Right click > select XY plot
6. View time variable plot ​dialog will open; select Range ​from the available
attributes
7. Click on OK ​and select COLLINGWOOD track as the primary plot
8. Click inside the plot area, in the existing views , and wait for some time
the time is too random the dialog can be seen in some seconds range like 10-20 sec  or in some minutes ranges from 4- 7 minutes.

this time you might get this error dialog - [![Image from Gyazo](https://i.gyazo.com/36070f68a9851e91157eb10f92b65d6c.png)](https://gyazo.com/36070f68a9851e91157eb10f92b65d6c)

[Invalid final field MWC.GUI.JFreeChart.ColouredDataItem._myColor.txt](https://github.com/debrief/debrief/files/2581226/Invalid.final.field.MWC.GUI.JFreeChart.ColouredDataItem._myColor.txt)

**Comment by helenayele** [comment]
The same exception with the same error dialog is shown while triggering View Sensor range plot action.
#### Steps:
Open sen_tracks.rep file 
Drag sen_ssk_sensor.dsf to the plot
Open Track:New_SSK layer from outline view and ctrl + click  on Sensor:New_SSK_BB(15 cuts) and Track:New_SSK 
 Right click > View Sensor range plot (one sensor vs one track)
Then the above dialog will popup and if not seen immediately Just wait 4-5 minutes.

**Comment by saulhidalgoaular** [comment]
Hello @helenayele 
I am closing this ticket then. It was fixed in.
https://github.com/debrief/debrief/pull/4862

**Comment by helenayele** [comment]
The error and exception are no more reproducible- Verfiied
