### ISSUE TITLE
Duplicate messages on Sensor import wizard

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3449]
We have got duplicate messages on the same page of Sensor import wizard - [![Image from Gyazo](https://thumb.gyazo.com/thumb/200/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpbWciOiJfNGIwOGUyYWVjNjY0Zjk0ZWZjMGJlMWE4MGQzMmU4MTcifQ.S4grwtJIkRrShzcsVq-W_7BZFnj11PrBTxB4ckKxHC0-png.jpg)](https://gyazo.com/f46350186e43c8793bd9baa73e5368cb)
as can be seen " you can prevent this wizard from opening using
the Debrief preference titled:
'Show the wizard when importing sensor data from REP'" is written two times.

**Comment by IanMayo** [comment]
Fixed, by removing first instance of message.

**Comment by helenayele** [comment]
Verified
