### ISSUE TITLE
Use better word in Frequency section of the Import Sensor wizard 

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3450]
Wizard Screenshot:
[![Image from Gyazo](https://thumb.gyazo.com/thumb/200/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpbWciOiJfYjNkMDUyMjMxMjMzY2U3ZmRlYzBjODNiNjU0NTgzZjUifQ.ozQGVR2IGxN024OhNPe18pSvA7H-GWAOiRs_6mKmdwQ-png.jpg)](https://gyazo.com/29062b2ac06787319f3700540552810c)

The label 'Name' doesn't give sense when its value is number i,e in this case 220.00 , it is better if we use Value as a label rather than Name here.

**Comment by IanMayo** [comment]
Fixed, by providing `Base freq` field title.

**Comment by helenayele** [comment]
Verified
