### ISSUE TITLE
Auto-select one of the existing tracks in Tracks combo - Import BRT Sensor Data Wizard

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3455]
Screenshot:

[![Image from Gyazo](https://thumb.gyazo.com/thumb/200/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpbWciOiJfOGZmODIwMWZmNjIxMTliOTM3N2U3OTQ1Nzg5NzljYTYifQ.fXEi-CItv5rbfCJ1nAGe6AIhoZHHlvbsP_-SWCfKjGU-png.jpg)](https://gyazo.com/ae7dfd6f2bdf3ff0dcd445a994856996)

As can be seen from the above image, it seems empty especially for first time user. It would be more easily to use if we have selected one of the available track options.

**Comment by IanMayo** [comment]
Ok, by default we now select the first item in the combo.

@helenayele -  the logic around whether the _Select Track_ step is added to the wizard has changed - so extra testing of this is justified.

**Comment by helenayele** [comment]
Verified
