### ISSUE TITLE
Sensor offset and Array-offset value set in the  import BRT Sensor Data  wizard are not identical

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3456]
### Steps to Reproduce:
1. open All Tracks Use Current Heading.rep from the sample test file 
2. Drag to it HULL_ZERO.brt file - and make sure that you set the array-offset value =  -41
[![Image from Gyazo](https://thumb.gyazo.com/thumb/200/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpbWciOiJfNDllNWQzM2VlNTRhNmI5ZmM3YWUyYmY5NzNiZTVhNDkifQ.S_ukkGosHVvPzensqgZOYpFlxWo0mXv6cdINNo4J_80-png.jpg)](https://gyazo.com/dbe23c0fd9c53ef79dcaeb23300123db)
3. make the sensor visible and complete the wizard.
4. Select this sensor in outline view and see its sensor-offset value in properties view -  see that it is totally different from what is set in the wizard.
[![Image from Gyazo](https://thumb.gyazo.com/thumb/200/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpbWciOiJfNmE4NmVkODI4NzYyZTA5MTFlYWViNzkyMTM1ZmQyNGYifQ.nDCbHQLB3Izpy4OfJU4b7yrdHA4jqpHd4eakYih1GIE-png.jpg)](https://gyazo.com/9b5192045dfc3e344d835af65613a6ea)

**Comment by IanMayo** [comment]
Hey, well spotted @helenayele - this is a really good one.

**Comment by IanMayo** [comment]
Aah, got it @helenayele 

You're looking at different units.  In the wizard for the screenshot you've selected 41 kyds (kilo yards, thousands of yards).

In the second screenshot you're showing the value in metres.

So, if in the wizard you select 41 `m` (metres), then the value will correctly be displayed when the data is loaded.

I think this issue can be closed.

**Comment by helenayele** [comment]
yes, correct and verified
