### ISSUE TITLE
Unable to edit Start/Finish DTG of Imported BRT File in properties view

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3457]
Trying to edit Start/Finish DTG of the imported BRT file logs "We don't support setting hte coverage value".
But it doesn't return anything for the user, or it doesn't accept any of the user inputs for this specific property. 

This behavior is not user friendly for a user who plays in Debrief. So if we don't support editing this property , make this property un-editable or show proper message for the user.

**Comment by IanMayo** [comment]
@helenayele - I'm producing an update that makes it a read-only property, so the user doesn't think they're making an edit.
