### ISSUE TITLE
M1.6.2.0.1 Dev adding the the map component +libraries plus showing the libraries

### ISSUE THREAD

**Issue by Waynearendse** [debrief/debrief#3478]
Adding the map component +libraries plus showing the libraries

Dev adding the libraries called geotools 30 mins

Add Geotools map component 1 hour includes review

Load coastline data-file (for acceptance) - Look for file with Geot format 
2 hrs
Shapefile

Acceptance: pan/zoom around data

**Comment by IanMayo** [comment]
@unnivm  & @ayeshare - I'm not sure, but the existing merge PR may have resolved this too:
https://github.com/debrief/debrief/pull/3519
