### ISSUE TITLE
M1.6.2.0.2 Testing load map in Debrief lite

### ISSUE THREAD

**Issue by Waynearendse** [debrief/debrief#3479]
Testing 40 minutes with discussion

@helenayele should be able to do some testing here.

When you start the app, it may ask you to load a data-file.  There's one in the repo at: `org.mwc.cmap.NaturalEarth\data\ne_110m_admin_0_countries_89S\ne_110m_admin_0_countries_89S.shp`

**Comment by helenayele** [comment]
Testing comments for this issue are found at https://github.com/debrief/debrief/issues/3535#issuecomment-444905311 , and please see the error log there.

**Comment by IanMayo** [comment]
Done.

**Comment by helenayele** [comment]
Verified
