### ISSUE TITLE
M1.6.2.3.1 Add range/bearing toolbar button

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3483]
Add UI to display range/bearing

Acceptance: able to switch to mode, measure width of boat1.rep - width matches that from full Debrief. Bearing shown as 090 degrees (ish).

(search for existing implementation)

**Ian to handle UX with Swathy**

4hrs to 6 hrs maximum

**Comment by IanMayo** [comment]
@unnivm - I'd like you to add this to your to-do list, please.   It will involve adding a new mouse mode button to the `View` ribbon toolbar.

**Comment by IanMayo** [comment]
@saulhidalgoaular - I'd like you to work on this, please.

The button will be a new "mouse mode" button, that will sit next to "Pan" and "Zoom":
![image](https://user-images.githubusercontent.com/1108513/54281183-1405a700-4591-11e9-96d9-e6303360dd42.png)

The implementation of the `Zoom` button already draws a red rectangle on the screen.

I suggest you replicate some of the implementation.  You'll need to obtain/download some GeoTools sources in order to do that.

But, instead of drawing a rectangle with TL/BR as drag-start and drag-end, you just draw a straight line.  The line should have range and bearing in text written along it.  When the line is being moved, that text will also be shown in the (currently unused) status bar:
![image](https://user-images.githubusercontent.com/1108513/54281174-0ea85c80-4591-11e9-9b4c-2f4a4c20ebcc.png)

**Comment by saulhidalgoaular** [comment]
Ok. Working on it!!
