### ISSUE TITLE
Helping Team West with Maven project plugin issue

### ISSUE THREAD

**Issue by Waynearendse** [debrief/debrief#3498]
Product Owner requested that Unni help team west with a Maven plugin issue, that was done yesterday, Unni is back onto Team east tasks today 

@unnivm I just put this at around 2 hours of work you did yesterday, i don't know how long you spent on it?

**Comment by unnivm** [comment]
@Waynearendse, yes that is correct. I spent 2 hours of research on this item and recommended a probable solution for this. And based on Product Owner instruction, I have concluded this research now.
