### ISSUE TITLE
M28.4 Test MSI Release

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3500]
Once we have an MSI release, we'll need to test it.

I guess the testing will include the following:
* [ ] Installer runs on an MS Windows PC
* [ ] Program & tutorials present in Start Menu
* [ ] Program starts correctly
* [ ] Tutorials open correctly
* [ ] Uninstaller works, removes Program & Tutorials

Note: we will need to check how the update process works.  So, Ian will have to artificially produce one or more new releases.

**Comment by helenayele** [comment]
### Current functionality (Good side) :
It is installed and it looks like this in start menu -
 [![Image from Gyazo](https://i.gyazo.com/9aac598b7173ab0631669d476ee30b21.png)](https://gyazo.com/9aac598b7173ab0631669d476ee30b21)

1. Debrief program starts correctly
2. Debrief functions well
3. Both Tutorials and user guide are opened without any issues
4. I can uninstall it from control panel - window program successfully.

### Needs to be improved

1. When starting for the first time I get the following errors logged 
  [![Image from Gyazo](https://i.gyazo.com/e46befc84251f5a380523431cfedae3e.png)](https://gyazo.com/e46befc84251f5a380523431cfedae3e)
 But after cleaning the log and starting debrief, no such error are seen
2. Debrief doesn't give any menu to uninstall it - used OS level menus to uninstall it , when it is uninstalled,  it shows this dialog - 
[![Image from Gyazo](https://i.gyazo.com/e9f40856d02307e3c41122076b9148f3.png)](https://gyazo.com/e9f40856d02307e3c41122076b9148f3)
Finally this dialog will be removed when it finishes uninstalling - it doesn't tell the user, it just finished uninstalling
3. This is also the same when it finishes installing. It doesn't inform its users whether the installation is done successfully or not.

**Comment by IanMayo** [comment]
> Finally this dialog will be removed when it finishes uninstalling - it doesn't tell the user, it just finished uninstalling.

Ok @helenayele, so you think it should show a **Successfully uninstalled** confirmation, right?

**Comment by helenayele** [comment]
Yes please!
We shall  show this confirmation both when it completes installing and uninstalling debrief.
