### ISSUE TITLE
M1.6.4.2 Property Editor Dialog

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3511]
Introduce ability to edit object properties.  Double-clicking on an item in the Outline View (or the plot) should open a modal property editing window that self-populates from the PropertyDescriptor elements of the subject shape.

Test: verify that a range of different object types can be edited (esp. Lightweight track), and that a range of property types are supported

**Comment by IanMayo** [comment]
This work is partially completed in #3572

**Comment by IanMayo** [comment]
Working: 
![image](https://user-images.githubusercontent.com/1108513/51533342-6f8da100-1e3a-11e9-88ed-a7c86641c65b.png)
