### ISSUE TITLE
M1.6.1.0.3 Test Created Java application

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3535]
Test create java application and make sure that 
 The application name is Debrief-Lite 
 Check created layout
 Resize panes
check dynamic behaviours
menus and toolbar

Acceptance: open application, inspect controls

**Comment by helenayele** [comment]
While running Debrief-lite and playing with it, it throws this exception silently - 
[Debrief_lite_error_log.txt](https://github.com/debrief/debrief/files/2653577/Debrief_lite_error_log.txt)
The application looks like this when it first runs -
 [![Image from Gyazo](https://i.gyazo.com/430c02fbced4fd53b01681996ccdca9c.png)](https://gyazo.com/430c02fbced4fd53b01681996ccdca9c)

And after selecting map (.shp) file  from  `org.mwc.cmap.NaturalEarth` folder  it looks like :
 [![Image from Gyazo](https://i.gyazo.com/61c9ce6d4373f0fed0f1251b6dcf5e76.png)](https://gyazo.com/61c9ce6d4373f0fed0f1251b6dcf5e76)

So currently 

1.  zoom-in/zoom-out , Click and drag to pan and display full extent of..buttons works well.
2.  the sub-menus inside File menu are not functional as well
3. @IanMayo  suggested to remove Click to Identify button by saying:  "We should probably remove `Click to identify`"
4. But there is a gray a gray area between the graph view and the map plot , @IanMayo  just accepted it for now.

**Comment by unnivm** [comment]
Please find the status of this item in '**develop**' branch

The application name is Debrief-Lite  - The application name is **Debrief Lite (1.1)**

Check created layout - Yes layout has been created with the panes (TimeController, outline, map and graph)

Resize panes - Panes are re-sizable 

check dynamic behaviours = The dynamic behavior is it can load different  map files at the time of loading the application and display map content.

menus and toolbar - One menu called 'File' and there are 6 controls related to map. These controls are working as expected.

**Comment by helenayele** [comment]
My other comment is on the file chooser dialog box, it was nice if we can paste paths to it, instead of moving to each file path manually.

**Comment by helenayele** [comment]
The above issues are all related to the map loading and this is handled in separate issue at https://github.com/debrief/debrief/issues/3479 so closing this issue
