### ISSUE TITLE
Produce viewer for bulk sensor/track data

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#357]
*[Migrated from Assembla ticket [357](https://www.assembla.com/spaces/Debrief/tickets/357) - reported by @IanMayo on 2011-03-29 14:56:46]*

Based on a narrative-related conversation with Paul O it appears there's merit in a sensor/solution viewer control.

Bearing and solution data is only really presented in the form of bearing fans/ellipses.  This leaves DaveW measuring sensor bearings by hand to see if it matches something in the narrative - it isn't possible to read-out the bearing.   (well, it is using the grid editor - but that's for editing).

So we came up with a view like this:
![tacticaldataviewer](https://cloud.githubusercontent.com/assets/1108513/8202380/42af848a-14d1-11e5-9bf5-17b43b9f995d.png)

I guess there are two modes of data to view:
* track positions (for which each track only has one)
* sensor data (for which a track may have several).

So, if the user selects a track, or a track's **positions** element, then we'll show the position related data (course, speed, depth).

Or, if the user selects one SensorWrapper then we'll show time plus bearing, ambig bearing, and freq for that sensor.  Or, if multiple blocks sensors are selected the top element will just show the available parameters, and selecting one puts that attribute for all sensors into the XY plot view.

GriddedDataProvider will give a list of editable properties for the selected object(s).

I imagine that it's possible to zoom in/out of the time graph using +/- buttons, or ctrl-wheel.  The left/right keys and the normal wheel operation would pan through time.

We'll need to understand how to assign data to the monitor. It could have a "selection following" ability, but this could get really annoying.  So, an alternate method would be for the user to drag/drop a block of items onto the view.

**Comment by IanMayo** [comment]
Superceded by the Tactical Overview, based on Limpet functionality.
