### ISSUE TITLE
Script changes - Fixes of the reviews mentioned in the script demo document and new methods

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#3573]
* createColor name conflict with /System/UI/
* createDateFromString method to make a HIReDate from a String.
* Nodes for polygon are not needed in the creator.

// More details are explained in this document.
https://docs.google.com/document/d/1nDHFUw4Pywll5dD3kMIjYaq9s9SngGNvamLK6DHcRBg/edit

**Comment by IanMayo** [comment]
@saulhidalgoaular - another request, please.

![image](https://user-images.githubusercontent.com/1108513/50342312-6c8d5100-051a-11e9-8848-d2e740e5f28f.png)

I'd like us to do some more processing of the object, please.  `Editable` is the parent type for all things that can be selected in the Outline View.

So, could you have a look at the returned object.  If it's a StructuredSelection item, then please create an array of the same size, and process the contents of the selection to retrieve the Editable items?  (_I think_ the selection will be an array of EditableWrapper items, so you retrieve the Editable from each one).

**Comment by IanMayo** [comment]
Done.

**Comment by helenayele** [comment]
Verified
