### ISSUE TITLE
M1.6.4.4 Implement new ribbon bar

### ISSUE THREAD

**Issue by ayeshare** [debrief/debrief#3585]
The first step will be to integrate the libs, and to put the ribbon bar at the top.  Then the map controls can be put into a View tab.

I'd like you flesh out the ribbon a bit more, please.  We don't need to implement the backend for the buttons, but if you add them, we can start to learn lessons about laying them out.

Note: I've used the ribbon terms introduced in this document: https://blog.frankel.ch/flamingo-tutorial/

* [ ] Debrief control menu button (see image below).  Under this will be Help and About
* [ ] File task . (open, close, etc)
* [ ] View task, to include map controls, repaint, etc.
* [ ] Chart Features 'task' . (items from Debrief's `Chart Features` menu)
* [ ] Drawing menu 'task' (items from Debrief's `Drawing` menu)
* [ ] Time 'task' (to include some controls that simulate Time Controller)
* [ ] Introduce **Substance** skinning, with **Cerulean** theme

Control menu:
![image](https://user-images.githubusercontent.com/1108513/50343340-6a2cf600-051e-11e9-96f5-e7e7c07ee34d.png)

## Update Jan 2019
@ayeshare has included the relevant libs in the build, and has implemented an initial ribbon bar.

We now need to move on, to integrate the full initial set of capabilities, and to organise the contents of the ribbon bar.  Organising the ribbon bar contents has moved to #3594 .  But, there is still value in connecting up the functionality to the buttons.

**Comment by helenayele** [comment]
The buttons are put in place but their implementation remains

**Comment by IanMayo** [comment]
Issue complete.

**Comment by helenayele** [comment]
Verified
