### ISSUE TITLE
Add theming to Debrief Lite

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3587]
* [x]  Introduce Substance skinning, with Cerulean theme

**Comment by ayeshare** [comment]
This was implemented as part of #3585

**Comment by IanMayo** [comment]
Done.

**Comment by helenayele** [comment]
@ayeshare  This is added on Lite tab only right?

**Comment by IanMayo** [comment]
It's the ribbon bar the the top of Debrief-Lite
