### ISSUE TITLE
M7.6 Investigate importing another file into JS script

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3588]
We wish users to be able to build up some utility scripts, and then call them from other script files.

We need to find out how to do this in Eclipse EASE

_Maybe_ @saulhidalgoaular should join the Eclipse EASE mailing list , then introduce himself on it, and ask the question.

**Comment by IanMayo** [comment]
Done: https://docs.google.com/document/d/1S86Hjsb3ub4JZcTuQE6hYFcuLpohbwBt8sMwsi0PwD0/edit?ts=5c2f393f#heading=h.sazug1atjru

**Comment by helenayele** [comment]
Verified
