### ISSUE TITLE
M1.3.2 UX for Ribbon Bar

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3594]
We have a working ribbon bar in place, we need to consider the logical organisation of the controls within it.

Most of the "insert" controls from full Debrief will be there, plus traditional file management stuff.

We hope to _minimise_ the use of right-click menu for operating on things in the Outline View - since they're effectively hidden for new users.  So, we _may_ wish to have a ribbon-bar of operations - such as "Resample data at..".  If the user clicks on it, but a track isn't selected in the Outline, then a dialog will inform the user what is needed for the button to work.   Well _that's an idea for it, anyway_.

**Comment by IanMayo** [comment]
@ayeshare  - I've reduced the number of elements in the `Insert` part of the ribbon bar:
https://docs.google.com/drawings/d/1MhpvO0lKLRffro40xJOdbOUahFrt74b53pAWap6DqJc/edit

**Comment by helenayele** [comment]
Per drawing doc,  'Toggle for select target layer' shape is not included. And when comparing with full debrief the following shapes are still missing 

1. Wheel
2. Furthest on circle
3. Range Ring
4. Track Segment and 
5. Vector

**Comment by IanMayo** [comment]
Current implementation satisfactory.
