### ISSUE TITLE
Merge of Debrief Ease.

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#3596]
**Requirements**

Branching off the current ease_develop.  The new branch will be *ease_develop_merge*.   It contains scripting plugin from a few weeks ago.  Into your new branch, you’ll add the up-to-date scripting:
• plugin extension
• modules
• demo scripts
• new build instructions (including javadoc)
• changes outside scripting plugin that are needed for scripting (prob in _legacy_ sources)

We’ll need to do some testing in that branch, to check we’ve caught everything.  Then we’ll merge it back into ease_develop.   *Until* all users have moved to J8, we’ll have to keep that ease_develop branch, and not merge it into develop.   But each time we want to do a release with scripting, we’ll have to merge _master_ into that _ease_develop_ and do a Scripting release off that branch.

**Comment by IanMayo** [comment]
Fixed in #3598
