### ISSUE TITLE
Put ellipses into a layer (shapes.rep example)

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#3605]
Put ellipses into a layer (shapes.rep example)
Recovering this commit from the wrong branch.
https://github.com/debrief/debrief/commit/25e9f855b6f9d6648f4f8cd41cd3646a28b653ac

**Comment by helenayele** [comment]
Verified.
Yes, I can find around 7 ellipses under TUAs layer in shapes.rep file.
