### ISSUE TITLE
Tidying map control

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3632]
* When the central mapping panel resizes, the displayed map should resize to use all the space
* the application should start with the map in "zoom in" mode
* correctly handle map pane resizing (should zoom to in/out as necessary to ensure viewport remains steady - see below)

I'm assigning this to @unnivm , but don't believe he will step on @ayeshare 's toes since the work should mostly just be in the map rendering component.

## Viewport resizing
The user is able to adjust the size of the map control by either changing the size of the application, or reducing the space taken up by the supporting views (outline, graph, notes).

When this happens, the map should adjust the zoom level so that the previously viewed data remains visible.  So, when the app is made larger the chart zooms in accordingly.

Here's an example of what happens when QGis resizes:
https://youtu.be/j6laMfKoTtI

And here is an example of how D-Lite current resizes: 
https://youtu.be/HxyuxGEoZWw

**Comment by unnivm** [comment]
@IanMayo .

I will work on these issues after taking latest from Ayeska's 3585_1_implement_actions branch
