### ISSUE TITLE
Robustly handle mis-formatted position comment separator

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3645]
We allow an optional comment marker at the end of position fixes, following a `//` separator marker:
````
951212 050300.000 NONSUCH @A@00 22 12 10.51 N 21 32 27.27 W 268.7 2.0 0 Standard label // Custom comment
````

An analyst has appended the separator marker to all positions, even when there isn't a comment or label.  
````
951212 050300.000 NONSUCH @A@00 22 12 10.51 N 21 32 27.27 W 268.7 2.0 0  //
````
This has caused an ArrayIndexOutOfBoundsException at ImportReplay.java#1330

We should robustly handle this occurrence.

**Comment by saulhidalgoaular** [comment]
I think we could close this one. It was merged

**Comment by helenayele** [comment]
@IanMayo / @saulhidalgoaular  , would you put some steps to test this please? 

I just tried to copy some of the lines from boat1.rep file and create new rep file and add //  with some text and without adding comment . After that not sure what to do, to test this issue.
