### ISSUE TITLE
D-Lite ribbon: implement Toggle for select target layer

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3663]
In the **Insert** ribbon tab we have the toggle button for whether the user should be invited to choose the target layer.

For this we need a Swing popup dialog that duplicates the logic in `getLayerName()` in `CoreInsertShape`.

It would be logical to include this code in the `CreateShape` class.

The `trimmedLayers` part of `CoreInsertShape` will be necessary.   Let's not duplicate the code.  Let's move it into the `Layers` class, then we can call it from D-Lite and Full-Debrief

**Comment by IanMayo** [comment]
@ayeshare - I think I remember you're still working on this issue - hopefully you'll be ok on it for the next couple of days.

**Comment by helenayele** [comment]
Verified
