### ISSUE TITLE
Remove borders from shape buttons

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3664]
In the `Insert` ribbon bar, the shape buttons have borders, but the reference data buttons don't:
![image](https://user-images.githubusercontent.com/1108513/51738813-f2576b80-2087-11e9-895f-3450ce6a4006.png)

The UI would look neater if they didn't have that border.  I had a quick look at the code, but couldn't see a setting to handle this.

I _think_ the difference is that one is a command, and one is a command button.

**Comment by ayeshare** [comment]
This will be done as part of #3668

**Comment by IanMayo** [comment]
Fixed, in #3693
