### ISSUE TITLE
D-Lite tie in Time Controller

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3681]
We've got our Time Controller UI, we now need to tie the controls into the Debrief plot.

This is the first challenge.  The next challenge is to tie the Normal/Snail painters into the plot, too - #3682

**Comment by IanMayo** [comment]
Still have to do:
* [ ] update time filter UI to match data
* [ ] implement filter to time
* [ ] correctly display the time label (Green on black)

**Comment by IanMayo** [comment]
@saulhidalgoaular - I'm assigning this to you, it contains some small cosmetic changes to finish of the Time Ribbon.

**Comment by saulhidalgoaular** [comment]
Ok. Ok. Working on it.

**Comment by helenayele** [comment]
And also Clicking on properties button should open the property view

**Comment by saulhidalgoaular** [comment]
I think we can close this issue. Branch with the features has been merged to Snail Painter. Final fix has been merged to Develop and verified by Ian.

**Comment by helenayele** [comment]
Verified
