### ISSUE TITLE
Dynamic Shape Handler needs to move plugin

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3683]
`DynamicShapeLayerHandler` and `DynamicShapeHandler` are currently in org.mwc.debrief.core

That means they can't be referred to from `Lite`.

More them to Debrief.legacy.

In full Debrief they're loaded by extension in the `plugin.xml` - we should explicitly register them in `DebriefLiteApp`

**Comment by helenayele** [comment]
Currently we drag and drop only rep files, and, there are a couple of data types that don't currently load in d-lite.  They will cause the .dpf import to fail.

**Comment by IanMayo** [comment]
Ooh, this is quite complex, since it also means introducing new layers.  Defer.

**Comment by helenayele** [comment]
1. Able to load boat1t.dpf - layers are loaded in outline , but not rendered on the map
2. While loading boat_1_2_arcs.rep , no exception is thrown, even if nothing is loaded both in the outline and map
3. Able to load all the problematic dpf files like MDA_Test.dpf , old_turn_example.dpf, thirty_min_earlier_first_turn.dpf, thirty_min_extra_leg.dpf etc. without any issues.
Hence verified
