### ISSUE TITLE
[Debief-Lite] Clicking inside Chart feature layer throw NPE

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3688]
After launching Debrief-lite, trying to select the Chart feature layer inside the outline view logs this NPE.
[NPE.txt](https://github.com/debrief/debrief/files/2827154/NPE.txt)

### Steps to reproduce
1. Launch Debrief-Lite
2. On outline view, click on chart feature layer

**Comment by IanMayo** [comment]
You do mean right-click edit, right @helenayele ?

**Comment by helenayele** [comment]
Verified - not reproducible now
