### ISSUE TITLE
Improve naming of Property Methods

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3705]
For property editing, lots of our Debrief data objects have a set of properties defined. These properties allow the property editor to auto-config to display the relevant list of editable properties.

Debrief data objects can also define methods that may be called.  These methods are exposed using the name of the Java function:
![image](https://user-images.githubusercontent.com/1108513/52346367-5a5a6a00-2a17-11e9-9ac8-83142371dabf.png)

We should refine this processing, so that we provide (and display) a human-readable button label, while still relying on the Java method name internally.

I suggest we modify `SwingPropertyEditor2.showMethods()`  to use `getDisplayName()` instead of `getName` as the button label.

Eclipse search shows 35 instances of object methods being declared:
![image](https://user-images.githubusercontent.com/1108513/52347209-4d3e7a80-2a19-11e9-9147-da6ed64ccff7.png)

We should go through them, and ensure the display label is short & concise enough to be used as the button label.  The property is currently used as a tooltip, so it's quite verbose.

Note: when the display name is used instead of the name in the Track object, we do get nice readable buttons (below).  But, since the buttons have got wider, we've lost one of the buttons.  We need to modify the container to resize to fit - let's solve that in a separate issue.

![image](https://user-images.githubusercontent.com/1108513/52347307-837bfa00-2a19-11e9-9b62-950e6ad68a2d.png)

**Comment by IanMayo** [comment]
@helenayele - how about taking on this software issue?

You are welcome to ask for support/guidance from me, @saulhidalgoaular , @ayeshare if you need it :-)

**Comment by helenayele** [comment]
sure Ian

**Comment by helenayele** [comment]
@IanMayo  done, please commit.

**Comment by IanMayo** [comment]
@helenayele - you need to go to the "Branches" page, then create a New Pull Request for your branch:

![image](https://user-images.githubusercontent.com/1108513/52424254-834f2d80-2af1-11e9-86fa-7ec5c1e937b6.png)

Or, when you go to the Debrief Repo on GitHub, _maybe_ you'll get a yellow banner inviting you to create a PR for your recently changed branch.

**Comment by helenayele** [comment]
done!

**Comment by helenayele** [comment]
Verified. Buttons labels are improved.
