### ISSUE TITLE
Thread blocking on file load

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3718]
I thought I had an intermittent problem, then I dismissed it as OSX only.

But now it's happening for a MS Windows user.

When they drag in `sen_tracks.rep`, the import freezes at 50%.  That data-file contains positions for one track, then another track.  They are the same length. So, it's at the 50% mark when the second track starts.

I suspect Debrief is trying to display the `Select track mode` dialog for the second track, while the dialog is still shown for the first one.

![image](https://user-images.githubusercontent.com/1108513/52416896-91498200-2ae2-11e9-8922-dc90087efc5e.png)

I think this started appearing after the Import Rep processing was rationalised, to reduce the use of . threads starting other child threads.

**Comment by IanMayo** [comment]
@helenayele - could you check if this is fixed in `master` please?

**Comment by IanMayo** [comment]
Fixed in #3770

**Comment by helenayele** [comment]
I see some screen blinking when I try to laod split_sen_tracks.rep file 
[![Image from Gyazo](https://i.gyazo.com/bfcd07c9e2305a72b9150311545e89ea.gif)](https://gyazo.com/bfcd07c9e2305a72b9150311545e89ea) 

other than this no issue is seen
