### ISSUE TITLE
Fit to Window action should be corrected in empty plot

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3720]
See the the below video to see the issue: 

[![Image from Gyazo](https://i.gyazo.com/8c24e3d6622374ada6bb70fb65f32582.gif)](https://gyazo.com/8c24e3d6622374ada6bb70fb65f32582)

In empty plot, When we click on Fit to Window , it shouldn't change the display. No reason to change the display!
### Steps to reproduce the video:
1. Launch D-lite
2. Click View > Fit to Window , see that the display is changed

**Comment by IanMayo** [comment]
Yes - doing nothing when no data present would be better.
