### ISSUE TITLE
Add Mouse drag event for zoom-out functionality

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3724]
D-Lite almost behaves the same regarding those zoomin/out buttons but there is small difference, in full debrief we can zoomin/zoomout using mouse by dragging from top-left to bottom right and from bottom-right to top-left to get zoomIn and zoom-out functionalities respectively. 
But in D-lite we only get ZoomIn functionality with mouse drag , but we don't have any option to zoom-out with Mouse drag.
So can we include zoomOut functionality with mouse drag just like Full debrief?

**Comment by IanMayo** [comment]
Defer for future release.

We'll have to change the behaviour of the GeoTools mouse-drag code.

Actually, it would be good to contribute the fix back to the GeoTools project.

**Comment by IanMayo** [comment]
Close. Duplicated of #3948
