### ISSUE TITLE
NullPointerException while selecting "Select Point" action  of  Some shapes' Center property

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3728]
After I insert Arc Shape on Shapes.rep file,when I try to edit Center property, it logs NPE.
[NPE_Proprty_Arc.txt](https://github.com/debrief/debrief/files/2844189/NPE_Proprty_Arc.txt)

### Steps to Reproduce:
1. Drag shape.rep file to D-Lite map
2. Select Insert > Arc
3. Double click Arc from outline > Misc layer and modify its properties - [![Image from Gyazo](https://i.gyazo.com/c8a151cbf2e4406e739d7b7c5422bf2f.png)](https://gyazo.com/c8a151cbf2e4406e739d7b7c5422bf2f)

4. Go to  Center property and Select  Select Point button next to "Edit" button.

**Comment by helenayele** [comment]
The same exception is thrown while we select "Select point" button next to edit button of the Center property of the below shapes:

1. Label
2. Ellipse
3. Circle
4. Line

**Comment by helenayele** [comment]
still reproducible

**Comment by IanMayo** [comment]
This isn't just a code fix. We need a strategy for editing locations. I'll talk to Celine about it.

**Comment by IanMayo** [comment]
@ayeshare - @saulhidalgoaular is working on the ability to drag shapes, just like full Debrief.  So,  please remove the "Select Point" button for D-Lite.

Note, we'll still need it for Debrief-Legacy, since it doesn't have modal Properties Window.

**Comment by helenayele** [comment]
SelectPoint button now removed from shapes' property
