### ISSUE TITLE
Non-Working Toolbar items in D-Lite

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3730]
The following toolbar buttons/actions are not implemented
A.  In File Menu

1. New
2. New(Default)
3. Open Plot
4. Import Replay

B . Lite
 Help > Help Content

C, Time

1.   Normal
2.   Snail
3.   Record to PPT
4.   Edit Time-Step Property
5.   Format Time Control
6.   Filter to Time functionality

**Comment by IanMayo** [comment]
@helenayele - please update this list of non-working features.

**Comment by helenayele** [comment]
A.  File menu:

- All toolbar actions are implmented but the "Copy plot to png" action doesn't work copy the plot  and handled at #2996

B . Lite

- Help > Help Conten

C. Insert

- Grid - handled at #3733
- CoastLine - trying to insert this logs "Can't find icon:icons/16/coast.png" on the console but the empty cost plotter is shown on outline view
- NaturalEarth 
- Polygon - throws NPE - handled at #3725

D. Time

- Record to PPT

**Comment by helenayele** [comment]
- Copy to png is implemented
- Polygon is created successfully.

Remaining:
1. Lite > Help > Help Content
2. Inserting Coastline and NaturalEarth - logs this in the console:
INFO:  Coastline file not found,trying to load from classloader
ERROR:  Coastline file could not be loaded from class loader
ERROR:  File not available. Coastline not loaded.

3. Record to PPT - also not implemented.

**Comment by helenayele** [comment]
Still the same

**Comment by helenayele** [comment]
Currently the remaining items is
1. Lite > Help > Help Content
2. Record to PPT is remaining but hidden for users

**Comment by helenayele** [comment]
Currently Lite > Help is opening a readme.pdf file about D-Lite. So nothing left  Verifying...
