### ISSUE TITLE
Selecting ShowAutoCalc property of Line shape logs NPE

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3731]
After inserting Line on a plot , trying to select  ShowAutoCalc property of Line shape
[![Image from Gyazo](https://i.gyazo.com/be2e7c95c0b1843442a4c20a7e21a61f.png)](https://gyazo.com/be2e7c95c0b1843442a4c20a7e21a61f)
logs this:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at MWC.GUI.Shapes.LineShape.paint(LineShape.java:265)
	at Debrief.Wrappers.ShapeWrapper.paint(ShapeWrapper.java:1011)
	.... Full stack trace is this
[AWT-EventQueue-0- java.lang.NullPointerException_ShowAutoCalc.txt](https://github.com/debrief/debrief/files/2845575/AWT-EventQueue-0-.java.lang.NullPointerException_ShowAutoCalc.txt)

But after selecting this property it remained selected.

### Expected Result:
It should show Calculated value and no such exception should be logged.

**Comment by IanMayo** [comment]
Ok, but defer it, it's quite niche.

**Comment by helenayele** [comment]
@IanMayo we shall better disable this functionality , our users don't deserve to see this exception please.

**Comment by helenayele** [comment]
NO NPE is shown , hence verified. But the auto-calculated values are not somewhat readable and will be filed in separate file.
