### ISSUE TITLE
Show user friendly message when things go wrong

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3732]
For example if a user adds a plot on D-Lite map and adds scale on it and zoomed-out many times, D-Lite shows an error dialog that is not user friendly at all -
[![Image from Gyazo](https://i.gyazo.com/4d37bb2c692426083bd898c1133180db.png)](https://gyazo.com/4d37bb2c692426083bd898c1133180db)
 And logs this to the console 
2019-02-08T18:23:21.339+0300  WARNING  Possible use of "Mercator_1SP (Inverse transform)" projection outside its valid area.
Longitude 195°42.3'W is out of range (±180°).
Trace output to file:C:\Users\helena\DebriefProject\debrief\org.mwc.debrief.lite\trace.txt
Zoomed out too far!
Trace output to file:C:\Users\helena\DebriefProject\debrief\org.mwc.debrief.lite\trace.txt
Zoomed out too far!
Zoomed out too far!
Zoomed out too far!
Zoomed out too far!
Zoomed out too far!
Zoomed out too far!
Zoomed out too far!

**Comment by IanMayo** [comment]
Sure. We should invite @Celine to come up with UX strategy for this, eventually.

**Comment by helenayele** [comment]
Not reproducible in the current build - it just stops zooming after sometime.  hence closing.
