### ISSUE TITLE
Grid doesn't have proportional size when added on the map/plot

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3733]
When I try to add Grid to the plot ,I can see from outline view that it is added, but in the plot ,I can't see it added, unless I minimized the map area many times. It seems grid is not added, but in reality it is added.

Steps:
1. Drag Shapes.rep to the map area
2. Insert Grid  - in default mode , it looks like - [![Image from Gyazo](https://i.gyazo.com/81ee5796f7494f2d8bd5ac765251c579.png)](https://gyazo.com/81ee5796f7494f2d8bd5ac765251c579)

3. Zoom-out many times if you can see the whole grid , but me, I tried to zoom-out many times(more than 20 times), but can't see it  - [![Image from Gyazo](https://i.gyazo.com/6a669e90ed21996f5c9c4748cec7d79b.png)](https://gyazo.com/6a669e90ed21996f5c9c4748cec7d79b)
finally I get blank area 
[![Image from Gyazo](https://i.gyazo.com/c4fbb0bbbb3187ace782fd8b3769dcd2.png)](https://gyazo.com/c4fbb0bbbb3187ace782fd8b3769dcd2)
And finally logs 

org.geotools.referencing.operation.projection.ProjectionException: Latitude 90°00.0'N is too close to a pole.
	at org.geotools.referencing.operation.projection.Mercator.transformNormalized(Mercator.java:146)
	at org.geotools.referencing.operation.projection.MapProjection.transform(MapProjection.java:897)
	at org.geotools.referencing.operation.projection.MapProjection.transform(MapProjection.java:938)
	at org.geotools.referencing.operation.transform.AbstractMathTransform.transform(AbstractMathTransform.java:237) ....

### Expected Result:
When user inserts Grid , show immediately like Debrief full v. do. If not possible try to show the grid with at least  2-3 s zoom-out clicks.

**Comment by IanMayo** [comment]
Rendering a grid does appear broken - to be fixed.

**Comment by helenayele** [comment]
Sure, I can see it now after Zooming-Out -
 [![Image from Gyazo](https://i.gyazo.com/af4372ba2f8fce3ee87cdfcc4ef00418.png)](https://gyazo.com/af4372ba2f8fce3ee87cdfcc4ef00418)
