### ISSUE TITLE
StartDTG and EndDTG property values are not validated during entry

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3734]
For example I just entered those invalid values for those 2 properties and select Apply
[![Image from Gyazo](https://i.gyazo.com/a41449b93a5ff64c947737bd14b0f921.png)](https://gyazo.com/a41449b93a5ff64c947737bd14b0f921)
D-Lite doesn't complain. And when I close this property dialog and opened it , it doesn't retain those values, since they are invalid. But if I insert valid input, it will retain those values.

**Comment by IanMayo** [comment]
Ok, I don't think this works in Full Debrief either. Defer, for now.

**Comment by helenayele** [comment]
We now have date validation and if user enters invalid date ,it will complain like :
[![Image from Gyazo](https://i.gyazo.com/bddb7604192c11c3f7596e180d66a815.png)](https://gyazo.com/bddb7604192c11c3f7596e180d66a815)
[![Image from Gyazo](https://i.gyazo.com/5123b3f97b104c2a4973e1a5e0fabb9f.png)](https://gyazo.com/5123b3f97b104c2a4973e1a5e0fabb9f)
Even it validate whether start date is before end date or not
[![Image from Gyazo](https://i.gyazo.com/8052a16d6c1dca405c26646442117257.png)](https://gyazo.com/8052a16d6c1dca405c26646442117257)

So Closing this issue.
