### ISSUE TITLE
While inserting Ellipse only its label is drawn on the plot

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3735]
Screenshot of the issue:
[![Image from Gyazo](https://i.gyazo.com/bf0039546e188a4fefc38956eaf0c96f.png)](https://gyazo.com/bf0039546e188a4fefc38956eaf0c96f)

### Expected Result

Draw  and show Ellipse on the map.

**Comment by IanMayo** [comment]
Ok, I've just fixed this. The original code had an ellipse with zero height and width.

**Comment by helenayele** [comment]
@IanMayo  is the fix merged in develop or in other branch? I am not getting the fix.
[![Image from Gyazo](https://i.gyazo.com/ac93cc4e7d4a9cdf95673d6ecde5369d.png)](https://gyazo.com/ac93cc4e7d4a9cdf95673d6ecde5369d)

**Comment by IanMayo** [comment]
The fix is present in the branch for this PR:
https://github.com/debrief/debrief/pull/3828
