### ISSUE TITLE
Label is inserted in Misc layer by default irrespective to "Select target layer" state

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3739]
### Steps to reproduce:

1. Create 3 new layers after opening boat1.rep to D-Lite
2. Select Insert Menu > Enable"Select target layer" button
3. Select Label button, see that it is inserted in misc layer automatically
4. Select other shapes like circle, arc ,etc
5. See that "Adding a new drawing feature" dialog is shown to select the layers manually.
Note:
Full Debrief shows this "Adding a new drawing feature" dialog" while adding Label object if this "Select target layer" button gets enabled.

Video that shows the issue:
[![Image from Gyazo](https://i.gyazo.com/fcc4fe6370be6ed2322bf9ae09cc2462.gif)](https://gyazo.com/fcc4fe6370be6ed2322bf9ae09cc2462)

### Expected Result
When adding shapes, if  "Select target layer" button gets enabled, always display "Adding a new drawing feature" dialog to choose layers from.

**Comment by ayeshare** [comment]
In full debrief the label doesnt get added to a layer.  Does it have to be done that way?

**Comment by helenayele** [comment]
In full debrief Label gets added in to select layer if Manually Select Layer button gets enabled.
[![Image from Gyazo](https://i.gyazo.com/5dee65fac55676b4063e1e3522ac8e61.gif)](https://gyazo.com/5dee65fac55676b4063e1e3522ac8e61)

**Comment by IanMayo** [comment]
@helenayele - could you check this please?

**Comment by helenayele** [comment]
Working as expected. Now if "Manually Select Layer" button gets enabled, when I try to insert label it will ask which layer I want to insert it. So Verified.
