### ISSUE TITLE
Don't allow a user to create a layer with blank name

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3740]
Currently a user can create a layer without providing a name.
It looks like this:
[![Image from Gyazo](https://i.gyazo.com/f56e5377a2f78471fa9badd776581817.png)](https://gyazo.com/f56e5377a2f78471fa9badd776581817)
Even if it has no any effect on the application, creating a layer without a name has no any value for the user.
So prohibit creating a layer without a name.

Note:
In full Debrief, user can't create a layer without a name .

**Comment by IanMayo** [comment]
I know we can't modify the input dialog to force it to contain something, but we could popup an error if the dialog closes with an empty layer name.

The dialog will say:
`A layer can only be created if a name is provided. The shape has not been created".

**Comment by helenayele** [comment]
In this build , when I try to insert a shape by creating new layer with empty space, the shape is not created - it behaves like debrief. 
But When I try to create a new layer by clicking add layer button in outline view, it is created and also no dialog is shown that says 'A layer can only be created if a name is provided. The shape has not been created'

Video:
[![Image from Gyazo](https://i.gyazo.com/cd00cc7d7e145db15c40fffeff8f73b0.gif)](https://gyazo.com/cd00cc7d7e145db15c40fffeff8f73b0)

**Comment by IanMayo** [comment]
Ok, @ayeshare - I guess you have a bit more to do here.  We shouldn't create layer if a name isn't provided.  In fact, we should popup a warning dialog explaining that.

**Comment by helenayele** [comment]
Some Issues:
1. The dialog is shown even if user cancels layer creation action
  Steps:

-  select Add Layer action from outline view
-  When Add Layer dialog is shown ,select Cancel button 
- [![Image from Gyazo](https://i.gyazo.com/77bdf417891918e3793892b60c0dd8d0.gif)](https://gyazo.com/77bdf417891918e3793892b60c0dd8d0)

2. And if user wants to insert shapes and selects any shape like circle or line without enabling 'Select Target Layer' button, this dialog is shown.  
 [![Image from Gyazo](https://i.gyazo.com/b14482d52e1ddb1373bc3c69610be69e.gif)](https://gyazo.com/b14482d52e1ddb1373bc3c69610be69e)

3.  The Warning icon and the text inside this dialog are not aligned.

Due to 1 and 2 , re-opening..

**Comment by helenayele** [comment]
From the above comment, only the first issue is not fixed. Issue 3 is tracked in different issue.

**Comment by IanMayo** [comment]
Now fixed.

**Comment by helenayele** [comment]
Currently 
When I create a layer from outline view with empty name, the layer is just created and seen in the outline view. [![Image from Gyazo](https://i.gyazo.com/adeac5dd0d35308ceeb8c5d1b6a21701.gif)](https://gyazo.com/adeac5dd0d35308ceeb8c5d1b6a21701)

**Comment by ayeshare** [comment]
I remember fixing this yesterday. the fix will be available when 3780 is merged

**Comment by helenayele** [comment]
All the above issues are fixed and working as expected.
