### ISSUE TITLE
D-Lite ensure newly added item is visible & selected

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3750]
When we add something from the `Insert` tab, its parent layer should be open, and it should be selected.

**Comment by helenayele** [comment]
When we insert shapes from Insert menu, we can get the items being expanded and selected but for label , When we insert it, the layer is expanded but the inserted label is not selected. See this:

[![Image from Gyazo](https://i.gyazo.com/205c3e7ff18db8ce20bc2550aba637cf.gif)](https://gyazo.com/205c3e7ff18db8ce20bc2550aba637cf)

**Comment by ayeshare** [comment]
Well spotted @helenayele , Fixed it now.

**Comment by helenayele** [comment]
Thanks, Verified.
