### ISSUE TITLE
Better to support click + enter to open property dialog

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3766]
Users currently edit items by double-clicking on them in the outline view:
![image](https://user-images.githubusercontent.com/1108513/56270089-3db07180-60ed-11e9-98db-b9e482768242.png)

Currently to open property window, we use double click. But mostly double click is replaced by left-click and pressing Enter key. 

### Expected Result
To open Property window support click + enter keys  in addition to double-clicking.

Note: @ayeshare indicated that it's easier to support `alt-enter`.

**Comment by IanMayo** [comment]
@helenayele - I'm going to get some direction from UX on this.

**Comment by ayeshare** [comment]
I have supported Ctrl+Enter for edit.  Others are standard keys Ctrl+C for copy, ctrl+V for paste, ctrl+X for cut. Del key for delete.  I am not sure whether these work on macos.  This needs to be tested on mac.

**Comment by helenayele** [comment]
I have tested all those shortcuts on window OS. But as Ayesha suggested we need to test on mac. @IanMayo  can you check those shortcuts works well please?
Ctrl + C
Ctrl + X
Ctrl + V
and Del key to delete and 
Ctrl + Enter to open property window.

**Comment by IanMayo** [comment]
Yes.  Well, it's <cmd> on the MacOS, not <ctrl> - but that's the correct (expected) behaviour.

**Comment by helenayele** [comment]
Okay thanks - Verified
