### ISSUE TITLE
Remove Layer collapse and cursor jump after modification

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3767]
After modifying some properties of a layer the cursor jumps on the next layer in outline view. For example if I have been modifying the first label properties and when I close the property window, 
[![Image from Gyazo](https://i.gyazo.com/a6042d26c58e6915e18f02d3b85b63e8.png)](https://gyazo.com/a6042d26c58e6915e18f02d3b85b63e8)

the cursor jumps on the next layer (Buoys(3 items)) .

[![Image from Gyazo](https://i.gyazo.com/206319657ae735f8f0c16c900343e5d7.png)](https://gyazo.com/206319657ae735f8f0c16c900343e5d7)
 This really confuses user.

The other issue is , after modification the layers gets collapsed  and I think this is known issue but didn't get filed.
Video:
[![Image from Gyazo](https://i.gyazo.com/84efb94d1d0e60181f10efd4ad9fec81.gif)](https://gyazo.com/84efb94d1d0e60181f10efd4ad9fec81)

**Comment by ayeshare** [comment]
the fix for #3750, might even fix this. please check again after merging #3750

**Comment by helenayele** [comment]
Yes Fixed!
