### ISSUE TITLE
D-Lite time filter should use date format from drop-down

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3772]
Next to the "current time" box we have a drop-down of time formats.

The selected time format should also be used for the min/max labels in the time filter.

**Comment by saulhidalgoaular** [comment]
Solved in the following commint: https://github.com/debrief/debrief/pull/3727/commits/4026bd02344b5edcd0bf92b731040f886aae84b5
Branch `3681_time_controller_improvement `

**Comment by helenayele** [comment]
Verified

**Comment by saulhidalgoaular** [comment]
I think we can close it. Fix has been merged to develop and it was verified by Helen.

**Comment by helenayele** [comment]
Verified in develop branch as well
