### ISSUE TITLE
Debrief-Lite cosmetic issues

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3785]
We have the following cosmetic issues in D-Lite

1. Put  the icon and the text next to it on the same line - [![Image from Gyazo](https://i.gyazo.com/d5b59b7e18da7e34c410f5e399130915.png)](https://gyazo.com/d5b59b7e18da7e34c410f5e399130915)

2. Issue at https://github.com/debrief/debrief/issues/3738#issuecomment-462783546

**Comment by IanMayo** [comment]
Slipping to milestone 3

**Comment by ayeshare** [comment]
This is a very minor ui issue. I am using a standard joptionpane dialog to show the error message.  If this needs to be changed, i need to customize it.  @IanMayo please take a call on whether it is worth it.

**Comment by IanMayo** [comment]
Good question @ayeshare.

No - let's not risk fragility from developing our own custom dialogs. 

Let's leave it as-is.
