### ISSUE TITLE
Allow bow null in range rings

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#381]
*[Migrated from Assembla ticket [381](https://www.assembla.com/spaces/Debrief/tickets/381) - reported by @IanMayo on 2011-07-25 08:35:20]*

There are instances where a user may wish to show a bow null in addition to a stern null.

This would be implemented by providing a Start Angle parameter - and letting the arcs start at that angle.

We'd add a new property, handle store/retrieve, plus change the plotting to start at the right angle.

**Comment by IanMayo** [comment]
New sensor arcs features meet this requirement.
