### ISSUE TITLE
Provide better options to save with other name or to replace the opened plot while resetting

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3810]
If user selects New action after opening a plot, D-Lite asks to save the plot or not. If user selects save , the plot is saved automatically by its given name. It doesn't provide an opttion to the user to save the file with different name. And also if there were a plot with the same , it will replace it without asking the user as well.

### Steps to reproduce:
1. Open boat1.rep file and save it as boat1.dpf
2. Select New Action
3. Again open boat1.rep file 
4. Select New Action - this time it brings the save option dialog, select Save button to save the plot
[![Image from Gyazo](https://i.gyazo.com/f2c79740d23a5969240e1cd981f4cfae.png)](https://gyazo.com/f2c79740d23a5969240e1cd981f4cfae)
5. See that it automatically save the file as "boat1.dpf" 
Internally it replaces it but it didn't tell the user.

**Comment by helenayele** [comment]
Verified. Should be verified once again when #3789 is fixed.

**Comment by IanMayo** [comment]
Re-opening, mistakenly closed with merge of related PR.

**Comment by IanMayo** [comment]
@helenayele - I think this has gone away now.

**Comment by helenayele** [comment]
Yes, it has gone away. closing..
