### ISSUE TITLE
Some of the functionalities in the Step Control properties window are not working

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3811]
Some of the step control's properties like
[![Image from Gyazo](https://i.gyazo.com/027e0edb9f697e20b33caf3176a80948.png)](https://gyazo.com/027e0edb9f697e20b33caf3176a80948)

1. Edit Highlighter - throws InvocationTargetException
2. Edit DisplayMode - throws InvocationTargetException
3.  DateFormat - no exception is thrown
4. . Font Size - throws InvocationTargetException
5. Highligther - Throws InvocationTargetException
Full stacktrace
[java.lang.reflect.InvocationTargetException.txt](https://github.com/debrief/debrief/files/2926187/java.lang.reflect.InvocationTargetException.txt)

**Comment by IanMayo** [comment]
@saulhidalgoaular - once you've finished your current work, could you take this on, please?

I guess that for the `edit` buttons, we'll need to popup another Properties Window.

**Comment by helenayele** [comment]
Verified.
