### ISSUE TITLE
For some rep files Time control is not activated

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3815]
For Rep files like shape.rep, Time Control is not active and looks like this 
[![Image from Gyazo](https://i.gyazo.com/8a691adc19a0381b6c0d35ade2a1ef7c.png)](https://gyazo.com/8a691adc19a0381b6c0d35ade2a1ef7c)

But in full debrief, Time control is playing well for the same file.

**Comment by saulhidalgoaular** [comment]
Fixed in the commit https://github.com/debrief/debrief/pull/3727/commits/50c2538397601c579683c3a297080cab2cb6f7fa
Branch `3681_time_controller_improvement `

**Comment by helenayele** [comment]
Verified, able to get time control enabled for the above Rep file and tried to open some Rep files from sample_data sub_folders as well.

**Comment by saulhidalgoaular** [comment]
I think we can close this issue. Fix has been merged to Develop and verified by Helen.

**Comment by helenayele** [comment]
Verified
