### ISSUE TITLE
implement new design for layers popup dialog

### ISSUE THREAD

**Issue by ayeshare** [debrief/debrief#3820]
https://xd.adobe.com/view/b84612dd-e964-4322-699d-90574b10b452-ce77/screen/9e7e3619-b626-4a9b-a0aa-13956e655dbb/Add-shapes-layer-selector

The link above has the UX design for this requirement.
Select Layer drop down should list the existing layers. Two special options should be available viz, Active Layer and New Layer.
Selecting Active Layer should use the layer that is selected in the outline view
New layer should allow a new layer to be created.

When user clicks on the drop down, the select layer drop down should be populated.

**Comment by IanMayo** [comment]
No, that wasn't the plan.  We're not associating it with the selected layer in the Outline View.

This menu will contain a list of the current layers that can accept shapes (everything except TrackWrapper and Narratives layer types).

When the user clicks on the drop-down, D-Lite will scan through the Layers, then populate the drop-down.

There will also be an entry titled "User-selected layer".  If this entry is selected, we will popup the layer selector dialog each time a new shape is added.

But, if one of the existing layers is selected, we'll always create new shapes in that layer.

**Comment by helenayele** [comment]
Verified
