### ISSUE TITLE
No dirty marker is seen after opening a file in D-Lite

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3825]
After we open a rep/dpf file in D-Lite, the dirty marker is not seen. it is seen if we add a shape. But if we try to close this file by selecting either **New** or **Open Plot** action, it  asks the user to save it or not.
 
[![Image from Gyazo](https://i.gyazo.com/7cf6a27254a2711dfaa42b328dc9d1ca.gif)](https://gyazo.com/7cf6a27254a2711dfaa42b328dc9d1ca)

But in full Debrief , as soon as we open the file the dirty marker is shown.

**Comment by helenayele** [comment]
Currently when I open rep files in D-Lite , I see the dirty marker, but I am not still getting it when I open dpf files by dragging.

**Comment by IanMayo** [comment]
Ok. I don't think this is an issue.  In full Debrief, it will assign auto-assign primary and secondary (if poss) when a .rep file is dragged in.   But, we don't have primary/secondary in D-Lite.

**Comment by helenayele** [comment]
Accepted
