### ISSUE TITLE
Outline View selection controls

### ISSUE THREAD

**Issue by ayeshare** [debrief/debrief#3830]
UX Design for the outline view 
https://xd.adobe.com/view/b84612dd-e964-4322-699d-90574b10b452-ce77/screen/0fb0e1f7-1ae8-4b2b-b6e2-03c11e8f75af/Debrief-lite-Outline-elements-controls-multiple-it

When user selects one or more items in the ui display the controls edit,copy,paste and delete icons.
Paste will be enabled only if copy has copied an item to the clipboard.

**Comment by IanMayo** [comment]
Good.  But, there's a minor complication.

We can't offer 'Paste' in all cicumstances.  We can't paste fixes into a plain layer, and we can't paste shapes into a track.  We could keep the button disabled when this happens, or we could allow it to happen and then pop up a warning dialog after the paste.  

It's a minor time-waste to allow the paste when we could have prevented it, but popping up the dialog allows us to explain to the user what the probelm was.

I'll ask for ux device on that part - but I don't want it to hold you up.

**Comment by clenoble** [comment]
It's better to prevent the user to try to do something that's not possible, than to let him to do it and get an error message. 
I would disable the icon when the paste location is not appropriate. 
On hover over the disabled icon, I would add an instruction message: "Select [appropriate pasting location]". Ideally, the exact type of location is specified in the hover message based on which object has been copied.

**Comment by IanMayo** [comment]
Perfect, thanks @clenoble .

**Comment by helenayele** [comment]
Verified
