### ISSUE TITLE
Put pan/zoom/rng-brg into Radio Buttons

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3838]
We show the modal mouse buttons in a group of 3 in the Ribbon View toolbar.

But, they should be displayed as radio buttons, with only one of them activated.

**Comment by IanMayo** [comment]
Done.

**Comment by helenayele** [comment]
Verified.
The three mouse mode sections , Pan, Zoom-In and Rng/Brg are in radio buttons
