### ISSUE TITLE
Time player is enabled after resetting

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3845]
### Steps to Reproduce:

1. load boat1.rep
2. See the time menus - they are enabled and ready to play
3.  Select New Action from  File menu - Don't save it
4. Now the map has no any track and empty 
5. Select Time menu and see that all the time player menus are enabled and click Play
it is playing
[![Image from Gyazo](https://i.gyazo.com/a951b1e36a909c9875399b72eaa91681.gif)](https://gyazo.com/a951b1e36a909c9875399b72eaa91681)

**Comment by IanMayo** [comment]
Ok, we need to disable the time controller in the `resetPlot()` processing.

I'll do this.

**Comment by helenayele** [comment]
Verified
