### ISSUE TITLE
Add New Dialog issue after resetting

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3847]
There is a case where D-Lite not allow users to exit unless they created new layer after they initiated it.

Steps to reproduce:

1. Open boat1.rep 
2. Select New > don't save
3. Select Insert Menu > On the layer combo, Select [Add New Layer] option
4.  Select one of the shapes , say Arc 
5. When New Layer dialog  gets displayed , click cancel , then a dialog is shown that tells , the user the shape is not created unless new layer is added
6. Invoke it again , When the dialog is shown, try to Cancel 
7. Don't insert any value to it and Click Okay, 

This time , it will not be closed unless you insert a layer name.

Video:

[Add_dialog_issue.zip](https://github.com/debrief/debrief/files/2969949/Add_dialog_issue.zip)

**Comment by IanMayo** [comment]
Well found @helenayele - that's a tricky one.

**Comment by ayeshare** [comment]
This one's already fixed and I can see the fix in develop

**Comment by helenayele** [comment]
Yes,not reproducible . Hence closing..
