### ISSUE TITLE
Time player need to show "Play" button when it reaches end of time

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3849]
Currently when the the time player reaches end of time, it doesn't show the Play icon, but in full debrief it shows the play Icon.

[![Image from Gyazo](https://i.gyazo.com/1742dabecd0217305be578235db67868.png)](https://gyazo.com/1742dabecd0217305be578235db67868)

See that it reaches its end time, but yet shows  the button with "Start Playing" tool-tip

**Comment by IanMayo** [comment]
@saulhidalgoaular is the expert on the time controller, so I think this is one for him.

**Comment by helenayele** [comment]
Verified
