### ISSUE TITLE
Time player - shows no marker at the end of shorter track

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#3852]
Mentioned by @helenayele in slack.

**Comment by saulhidalgoaular** [comment]
> Shorter boat keeps dancing while playing with longer track

**Comment by saulhidalgoaular** [comment]
Yes. 
[boats.zip](https://github.com/debrief/debrief/files/2970552/boats.zip)
[d-lite_tracks_time_player.zip](https://github.com/debrief/debrief/files/2970553/d-lite_tracks_time_player.zip)

**Comment by helenayele** [comment]
Sure
[boat2_short.zip](https://github.com/debrief/debrief/files/2970809/boat2_short.zip)

**Comment by helenayele** [comment]
Verified - as per the comment on #3861.
Currently it looks like this when two tracks plays - 
[![Image from Gyazo](https://i.gyazo.com/6adff4c5ab11c804b0e1ed583e3b9d3b.gif)](https://gyazo.com/6adff4c5ab11c804b0e1ed583e3b9d3b)
