### ISSUE TITLE
M1.6.4.10 Support for Undo in D-Lite

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3865]
We need to introduce support for Undo in Debrief-Lite
----
#### Update 
Ayesha & I just chatted.
1. ensure undo/redo works for:
    a. insert decorations (scale/grid)
    b. insert shapes & reference data
    c. pan/zoom/zoom-out/fit-to-window
    d. property editing
    e. support for cut/paste/delete/add-layer in Outline View
2. add UI elements for undo/redo
3. connect UI to UndoBuffer

The logical sequence for these is to break them down into these PRs:
a.  2, 3, 1a . **Done**
b. 1b . **Done**
c. 1c . _defer until after GeoTools upgrade_
d. 1d . **Done**
e. 1e

The split is so we can review/discuss a working implementation before going on to support the other actions.  The other steps are broken down into separate PRs, since they represent quite different implementations of Undo.

----

It will need a place on the toolbar (or _maybe_ in the application-level drop-down, shown as an _Orb_ in the flamingo tutorial).

We will also need a command history class, into which changes are stored, so we can move backwards & forwards through undo/redo.

We will then have to wrap a number of UI changes in to `Action` objects, that have execute, undo, redo, etc.

Hey, here's an article from TWENTY ONE YEARS AGO on implementing a Swing undo history:
https://www.javaworld.com/article/2076698/add-an-undo-redo-function-to-your-java-apps-with-swing.html

And here's a slightly more modern one:
https://www.forward.com.au/javaProgramming/javaGuiTips/undoRedo.html

**Comment by IanMayo** [comment]
@ayeshare - I'm assigning this meaty one to you.

We've got an `UndoBuffer` object in D-Lite.  I'd like you to work through the ribbons, integrating the undo functionality.  It's probably worth starting with `Insert` and `View` menus.  Hopefully you can copy the functionality from either Debrief Classic or Full Debrief.  You will also have to add `undo` and `redo` buttons to the title bar of the app.

Happy to support you as required.

**Comment by helenayele** [comment]
Functional tests:
1. After user adds a layer , s/he can undo the action so the new layer should be removed
2. After a user deletes a layer. s/he can undo the action so the removed layer should be re-appear
3. After a user removes a layer or shape in a layer, or position from track layer, redo can make the object to appear in the previous location. The same for adding action.
4. If user tries to cut /copy and paste an object, and wants to redo - the pasted object should be removed from current position and be available  in original location.

**Comment by IanMayo** [comment]
re-open, not all items are complete.

**Comment by helenayele** [comment]
Currently 
1.  Able to undo and redo shape/decoration/reference data insertions from insert tab - but when I insert shape in new layer - and click undo - the inserted shape will be removed, but the added layer is NOT removed.

2. I am able to undo and redo properties edited from Property dialog. But for example if I change the visibility from outline panel, undo and redo doesn't work.


3.  1.e remaining

**Comment by IanMayo** [comment]
Thanks Helen,
1. I'm ok with the layer not being removed
2. Yes, we should capture hide/reveal from the Outline Panel
3. Yes, 1.e. is remaining.

**Comment by ayeshare** [comment]
I have fixed removing the layer when undone

**Comment by helenayele** [comment]
only 1c remaining and will file in separate issue. so closing
