### ISSUE TITLE
Default layer only inserts one shape

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3866]
When user doesn't select the layer from layers drop-down and insert shape, only the first shape is inserted in Misc layer. Then after that the misc layer is not selected in the drop-down and also the selected shapes are not going to be added in Misc layer. 
See this video:
[![Image from Gyazo](https://i.gyazo.com/0bdb90dae15eab54d841f725a84a8990.gif)](https://gyazo.com/0bdb90dae15eab54d841f725a84a8990)

**Comment by IanMayo** [comment]
Ok, this looks like it had the wrong behaviour.

In the video, `Select layer` is selected. In this mode, the user should be invited to choose a target layer each time.

**Comment by IanMayo** [comment]
@helenayele - I've been working in this area in my PR for #3873 

It's probably work you rechecking this, in that branch `3873_duplicate_add_layer`

**Comment by helenayele** [comment]
Yes, I checked in 3873_duplicate_add_layer , I don't see now "Select layer" in the layers combo-box at all. I see 'User Selected Layer' is selected by default when D-launches. So the issue is no more reproducible.

**Comment by IanMayo** [comment]
Close. Sorted.
