### ISSUE TITLE
Updated File/Application menu

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3870]
We have an updated UX for the `Application Menu` in D-Lite:
https://xd.adobe.com/view/b84612dd-e964-4322-699d-90574b10b452-ce77/

See also the re-organisation of the `File` tab on Page 2 of the UX design.

Hopefully the icon for the application menu will be a nice big Debrief icon.

**Comment by helenayele** [comment]
Verified , but according to the prototype, we need 2 small changes :
1. Open should be in import section

2.  Close button's icon should be changed
