### ISSUE TITLE
NPE logged while saving map without a track

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3874]
After inserting shapes to D-Lite without opening track, when I try to save the map, it throws NPE with attached stack-trace
[NPE_while_saving_map.txt](https://github.com/debrief/debrief/files/2982960/NPE_while_saving_map.txt)

### Steps:

1. Launch D-Lite
2.Insert Line, lable and circle shapes
3. Select New > then Save
.

**Comment by IanMayo** [comment]
Close. Duplicate of #3857

**Comment by helenayele** [comment]
Yes, no more reproducible after fixing #3857
