### ISSUE TITLE
Layers combo should refresh its size immedietly

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3886]
After resetting, layers combo does left extra spaces. It should refresh its size as soon as it gets reset.

### Steps
1. Load Shapes.rep
2. Open Layers combo from insert menu and see its size
3. On File menu , select New > Don't save it
4. Now select Insert menu and open layers combo - it has some extra spaces left seen.
[![Image from Gyazo](https://i.gyazo.com/9009fff083b5527ad5425c06e6e65a49.png)](https://gyazo.com/9009fff083b5527ad5425c06e6e65a49)
5 . Click inside the combo again and see that now it gets refreshed and no more extra spaces.
Video
[space_in_layers_combo.zip](https://github.com/debrief/debrief/files/2991147/space_in_layers_combo.zip)

**Comment by IanMayo** [comment]
Hello @theanuradha - you haven't had much to do with Debrief-Lite.  But, I'd like your support in tidying up some UI issues, please.

For this one, you'll branch off `develop`. 

Hmm, I think there's at least one other issue associated with this drop-down.  I'll try to assign them to you, too.

**Comment by IanMayo** [comment]
@helenayele - this should be fixed now.

**Comment by helenayele** [comment]
yes, now it is resized according to the size of the layers. Verified.
