### ISSUE TITLE
Play button keeps the old selection mode after reaching the end of a track in Full-Debrief

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#3887]
When we play until the end of the track, button looks like it stopped normally. However, if we go back in time using the slider and we press play again, I see that it doesn't play. 

Steps to reproduce:
1. Open a rep file.
2. Press play until the end (leaving it to stop by itself)
3. Go back in time using the slider.
4. Press play again (It doesn't start).

**Comment by helenayele** [comment]
Verified
