### ISSUE TITLE
Number format exception is logged when loading dpf file with sensor data

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3892]
### Steps to reproduce:

1. Open sample_lots_of_sensors.dpf 
2. See that lots of java.lang.NumberFormatException are logged. See this stack trace:
[NumberFormatException_while_loading_sample_lots_of_sensors.dpf.txt](https://github.com/debrief/debrief/files/2996591/NumberFormatException_while_loading_sample_lots_of_sensors.dpf.txt)

**Comment by helenayele** [comment]
Verified

**Comment by helenayele** [comment]
But @IanMayo  the exception mentioned at #3893 #pullrequestreview-217817375
still reproducible

**Comment by IanMayo** [comment]
Closing this, captured issue in #3902
