### ISSUE TITLE
D-Lite is too slow while managing sensor data

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3896]
D-Lite pause for some seconds while D-Lite loads a single sensor cut properties window.
It also takes so much seconds while expanding sensor items. 

### Steps
1. Launch D-Lite
2. Open sample_lots_of_sensors.dpf
3. try to expand the sensors layer it see the items inside it
4. Try to double click to open the properties window of the sensors.

See that D-Lite does take some minutes to respond to user input.
[D-Lite_is_slow_sensor_Data.zip](https://github.com/debrief/debrief/files/2997176/D-Lite_is_slow_sensor_Data.zip)

**Comment by IanMayo** [comment]
I'm removing this from milestone 3.  We aren't expecting D-Lite users to work with high volumes of sensor data.

It's still worth resolving in D-Lite, but no urgently.

**Comment by IanMayo** [comment]
This may be related to the performance issue in #4480

**Comment by helenayele** [comment]
I can open the property files of large sensor cuts within seconds. the speed is really improved
https://screencast-o-matic.com/watch/cYnrIRwmV1

[![Image from Gyazo](https://i.gyazo.com/d46f3f38b47596908feabfc1a049e533.gif)](https://gyazo.com/d46f3f38b47596908feabfc1a049e533)

**Comment by helenayele** [comment]
Yes , I see very little sluggishness  while making the visibility of 484 sensor cuts on and off. And it seems acceptable.
[![Image from Gyazo](https://i.gyazo.com/3ac45eab587ae2a7af2571120547d38e.gif)](https://gyazo.com/3ac45eab587ae2a7af2571120547d38e)

And while it opens the property of sensor cuts, I don't see slowness  :
[![Image from Gyazo](https://i.gyazo.com/749195f007d9f2e13442f9a64b326749.gif)](https://gyazo.com/749195f007d9f2e13442f9a64b326749)
So closing this issuee.
