### ISSUE TITLE
D-Lite snail mode plotted as dashed lines

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3912]
Here are the symbol painters, when running in normal painting mode:
![image](https://user-images.githubusercontent.com/1108513/54984405-b61c8a80-4fa6-11e9-9807-6347052a1a5f.png)

(Switch to symbol highlighter by opening `Time Properties`, then changing the `Highlighter` to `Symbol Highlight`).

Note how pixelated the two symbols are.  Note that the red track was changed to a submarine shape by opening the track properties and changing the `Symbol Type`.

Here is the equivalent in Snail Mode:
![image](https://user-images.githubusercontent.com/1108513/54984506-e3693880-4fa6-11e9-8fc9-2b7a1f2f545c.png)

Two issues:
* there is a gap between the last plotted point and the symbol (that's probably logic related, rather than XOR)
* there are gaps along the track history.  Could this be because the when the drawn line overlaps a previous line, it removes it (via XOR-ing).

**Comment by IanMayo** [comment]
Steps to reproduce:
1. Open DebriefLiteApp
2. Drag in `shapes.rep` from `sample_data`
3. Switch between `Normal` and `Snail` mode via the `Time` toolbar

**Comment by helenayele** [comment]
I got this while playing in snail mode after changing both the highlighter and symbol type - 
[![Image from Gyazo](https://i.gyazo.com/f7194cc4822ba26fb244a6f0e0404bb7.gif)](https://gyazo.com/f7194cc4822ba26fb244a6f0e0404bb7)

**Comment by helenayele** [comment]
Using symbol highlighter and using default values, I don't see any gaps between the symbol and rest of the positions :
 [![Image from Gyazo](https://i.gyazo.com/71e31777709cb440d5f3d557a7b88756.gif)](https://gyazo.com/71e31777709cb440d5f3d557a7b88756)

And with symbol highlighter , and using trail length = 2 hours and vector stretch = 50 , it looks like
[![Image from Gyazo](https://i.gyazo.com/bdd6b5a2fca88322239a86ca4894ba7d.gif)](https://gyazo.com/bdd6b5a2fca88322239a86ca4894ba7d)
(sample.dpf)

So should be verified
