### ISSUE TITLE
D-Lite Properties Window tidying

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3913]
We still use the method name for the name in the popup Properties Window.
![image](https://user-images.githubusercontent.com/1108513/54984693-51adfb00-4fa7-11e9-9bfc-c5146e9b1824.png)

We moved away from this in Full Debrief.

Modify this panel to use the pretty-printed label value, like we do in full Debrief:
![image](https://user-images.githubusercontent.com/1108513/54984736-6db19c80-4fa7-11e9-9e06-3ede62379dc1.png)

It does look like it's the `displayName` that we should be using for the properties:
![image](https://user-images.githubusercontent.com/1108513/54984955-d862d800-4fa7-11e9-812e-15481a383f2c.png)

**Comment by helenayele** [comment]
Verified
