### ISSUE TITLE
M1.6.2.9.1 UI for Time graphs

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3922]
New UI elements:

* NOT! (Graphs will be created using the toolbar in the Graph pane) Introduce `Commands` ribbon bar. It's first control will be View XY Graph - active when one or more tracks are selected.

* Introduce `Graph` resizable panel, beneath the map control. It will probably also need a toolbar that contains some elements from full-Debrief XY Plot.

Once these elements are in place, we're ready to start plotting graphs.

**Comment by saulhidalgoaular** [comment]
I have added the resizable panel. I _think_ the toolbar can be implemented in the issue https://github.com/debrief/debrief/issues/3924

**Comment by helenayele** [comment]
Verified
