### ISSUE TITLE
M1.6.2.9.3 Implement graph toolbar 

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3924]
Full Debrief has quite a complex graph toolbar (and drop-down):
![image](https://user-images.githubusercontent.com/1108513/55072563-5fd14980-5083-11e9-83a8-bc85b129e10d.png)

Consider which features we want in D-Lite, and create a UI toolbar in the new panel, to implement them.

The code for the features is probably mostly in `XYPlotView`.

**Comment by helenayele** [comment]
Verified
