### ISSUE TITLE
Can't import multiple files into D-Lite

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3926]
I want to open two `.rep` files in Debrief-Lite.

I use `Import Rep` to load the first.  When I click on it again, to load the second, it invites me to save my changes before the plot is closed.

I don't think import (or open) should do a plot reset.  Users should use `File > New` to do that.

**Comment by helenayele** [comment]
Verified

**Comment by helenayele** [comment]
Re-Opened, Regression.
Now I can't open multuple files at the same time.

[![Image from Gyazo](https://i.gyazo.com/fd5fd9087128f5b7555fce582f0b8673.gif)](https://gyazo.com/fd5fd9087128f5b7555fce582f0b8673)

**Comment by IanMayo** [comment]
Oh dear, I hope this wasn't me.

**Comment by saulhidalgoaular** [comment]
> Re-Opened, Regression.
> Now I can't open multiple files at the same time.
> 
> [![Image from Gyazo](https://camo.githubusercontent.com/b6580b979c7bccbbf086bed895a0ae2785f4e523/68747470733a2f2f692e6779617a6f2e636f6d2f66643566643930383731323866356237353535666365353832663062383637332e676966)](https://gyazo.com/fd5fd9087128f5b7555fce582f0b8673)

Fixed here
https://github.com/debrief/debrief/tree/3926_fix_merge_issue

**Comment by helenayele** [comment]
Now able to import multiples rep files  ,hence verifying...
