### ISSUE TITLE
M1.6.2.9.5 Implement XY Graph properties

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3928]
The XY Plot has a number of properties. 

Introduce support for showing these in the popup property window.

**Comment by saulhidalgoaular** [comment]
Feature covered in this Pull Request. https://github.com/debrief/debrief/pull/4012

**Comment by saulhidalgoaular** [comment]
Merged in this PR https://github.com/debrief/debrief/pull/4012

**Comment by helenayele** [comment]
Verified
