### ISSUE TITLE
M1.6.3.5 Export graphs

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3929]
As an **analyst** I wish to **export calculated data** in order to **include the information in a report or presentation**.

We have 3 modes of exporting data from an XY Plot
* Export as bitmap on clipboard
* Export as WMF on clipboard
* Export as textual (CSV) data of measurements/calculations

All of the above are present in the Full-Debrief version of XY Plot. So, it should be relatively easy to include them in Debrief-Lite.

**Comment by saulhidalgoaular** [comment]
I _think_ it was covered in https://github.com/debrief/debrief/pull/4012

**Comment by helenayele** [comment]
They are included and working fine - so closing...
