### ISSUE TITLE
Introduce "Close" button, and "Closed" state

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3939]
We wish to allow a user to Close the current document.

The handler for this should invite the user to save the plot (if necessary).  

Then the map pane will be hidden, the Outline will be emptied, and the Graph cleared.  All plot-related controls should be disabled.

Clicking on Open, New or Import should re-enable plot-related controls.

**Comment by helenayele** [comment]
@IanMayo  can't see the close button merged in develop branch. 
After I launch D-Lite and open Rep file, I can't get the Close button - [![Image from Gyazo](https://i.gyazo.com/9e17ce2e98c95f57b80d26abd6afd34f.png)](https://gyazo.com/9e17ce2e98c95f57b80d26abd6afd34f)

**Comment by IanMayo** [comment]
Isn't it now under the `Lite` menu tab?

**Comment by helenayele** [comment]
no it is not - [![Image from Gyazo](https://i.gyazo.com/63fad95ea8e8c971977a19c606fc8f40.png)](https://gyazo.com/63fad95ea8e8c971977a19c606fc8f40)

**Comment by IanMayo** [comment]
Oops, yes - that's exit, not close.

In that case, I'm sorry @helenayele  & @saulhidalgoaular - I expect I deleted the code for the button while I was fixing one of several merge conflicts yesterday :-(

**Comment by helenayele** [comment]
hmm, so would it be fixed soon? it is a blocker issue by the way. I can't verify the other closed issues since  I can't open files properly.

**Comment by helenayele** [comment]
Verified
