### ISSUE TITLE
Can't import multiple dpf files in D-Lite

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3946]
The issue is the same as #3926 . But this time using "Open Plot" action.
 when I try to open multiple dpf files using open plot action, it asks me to save the opened plot first. But in full debrief , user can open multiple dpf files.

**Comment by IanMayo** [comment]
@helenayele - I'm discussing the role/meaning of the Open button with Celine in the comments for this design file:
https://xd.adobe.com/view/b84612dd-e964-4322-699d-90574b10b452-ce77/screen/9b43574e-9097-4a65-a9ab-cd0cd3496de9/File/

**Comment by ayeshare** [comment]
@IanMayo do we have a design solution for this?

**Comment by IanMayo** [comment]
Hello @ayeshare - yes, the agreed behaviour is to have "Open Plot" (which replaces the current one) and "Debrief Plot" in the "Import" section - which adds the data to the current plot.

**Comment by helenayele** [comment]
Able to import multiple dpf files by using **Plot** action
