### ISSUE TITLE
Reverse drag to zoom out

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3948]
When in Zoom mode in full Debrief, the user can drag from bottom-right to top-left to perform a zoom out operation.

This reduced the amount of switching between mouse modes.

See if the GeoTools zoom tool could be extended to optionally include this mode.

The zoom out operation is interpreted as:
> the user is selecting the region he wants the current perspective plotted into

So, if the user draws br-tl rectangle at the top-right of the current plot, the current viewport will shrink to occupy that rectangle, and a large new area of coverage to the South-West is now displayed.

** Note **

In #4263 Ian has provided a partial implementation of this feature.  It zooms out proportionally to the selected area, but it has one flaw.  In full Debrief the old viewport centre is moved to the centre of the selected area.  In this Debrief-Lite implementation the new zoomed out area is centred on the centre of the selected area.

**Comment by ayeshare** [comment]
@IanMayo I spent some time trying to fix this with different combinations, but I see your fix to be the best possible thing I could think of.  Even the standard zoomout tool in geotools api didnt make it any better.

**Comment by IanMayo** [comment]
Sure, ok @ayeshare. Closing.

**Comment by helenayele** [comment]
In full debrief it looks like this :
[![Image from Gyazo](https://i.gyazo.com/397a5f395e8ccae06ced6166ac061ad5.gif)](https://gyazo.com/397a5f395e8ccae06ced6166ac061ad5)

In D-Lite it looks like 
[![Image from Gyazo](https://i.gyazo.com/b5b988083d6ebe021777d76b2b0b632c.gif)](https://gyazo.com/b5b988083d6ebe021777d76b2b0b632c)

Verified.

**Comment by IanMayo** [comment]
@helenayele  - the behaviour still isn't quite the same.  I've captured the issue here:
https://github.com/debrief/debrief/issues/4888

But, now that we have reverse-drag working, it's a relatively low priority.

**Comment by helenayele** [comment]
Yes , I know the behavior is different on the 2 products that is why I tried to show it in video recordings. But I thought you said let's keep it as it is..
