### ISSUE TITLE
Properties editor not opening for Tracks

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3960]
Ooh, this is a scary one.

I open Debrief. I drag in `boat1.rep` and `boat2.rep`.  

If I double-click on one of the tracks `Track:NELSON`, the property editor only shows with one item:
![image](https://user-images.githubusercontent.com/1108513/55541320-b14d8a00-56bc-11e9-8e68-1f14765db896.png)

I suspect we either have to step through the `getInfo()` method in TrackWrapper, or use `git bisect` (hopefully from a graphical git client) to find where the problem was introduced.

**Comment by helenayele** [comment]
Able to see all the properties of the track after importing 2 tracks
[![Image from Gyazo](https://i.gyazo.com/bd51515589055518516e6ab3b49bd675.png)](https://gyazo.com/bd51515589055518516e6ab3b49bd675)
Verified.
