### ISSUE TITLE
Exit button's icon has thicker border than the help button 

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3965]
[![Image from Gyazo](https://i.gyazo.com/5f7f0c18159cb2f9fcf3664a9e15a21f.png)](https://gyazo.com/5f7f0c18159cb2f9fcf3664a9e15a21f)

Can we make the border of the Exit button's thickness like the help button, to have uniform looking?

**Comment by IanMayo** [comment]
I've already created an issue in the `debrief-icons` repo.

**Comment by helenayele** [comment]
This is issue is fixed in the current build of D-Lite and looks like :
[![Image from Gyazo](https://i.gyazo.com/e6d0a2bd94a43a68825e446d5e72117a.png)](https://gyazo.com/e6d0a2bd94a43a68825e446d5e72117a)
