### ISSUE TITLE
Cut action doesn't remove an item after pasting 

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4014]
Currently after I cut a shape from one layer and paste it into another layer, the shaped doesn't get removed from the original layer.
[![Image from Gyazo](https://i.gyazo.com/42530fabb654859dd0c63c545df022e5.gif)](https://gyazo.com/42530fabb654859dd0c63c545df022e5)

This happens for both shapes and positions.

**Comment by ayeshare** [comment]
Opening compositeTrack.dpf, copying a position and pasting back fails with an error.  The exception is being caught and posted back to the user in a popup dialog.
A better solution as proposed by @IanMayo :I _think_ we need some kind of intelligent logic to encode what is allowed to be added to what.    _Maybe_ a `canAccept(Object val)` for all `Plottables` items.

**Comment by helenayele** [comment]
hmm @ayeshare , what about when cut action doesn't succeeded? for example from compositeTrack.dpf file, I tried to cut a position and paste, I get invalid error in pasting dialog but the cut position doesn't get replaced in to its original position after I cut it - but the same happens in full debrief.
 But in other example if I have  a shape  say A  in layer 1 , and if I try to cut it and paste it into Layer 2 - Layer 2 has also the same shape A , currently Shape A is removed from layer 1 - is this expected?
