### ISSUE TITLE
Sensors' Property window show some unexpected labels

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4049]
See the issue at https://github.com/debrief/debrief/pull/4031/files#pullrequestreview-227133904

**Comment by IanMayo** [comment]
@helenayele - you commented on the label here:
https://github.com/debrief/debrief/pull/4031#pullrequestreview-227133904

Could you tell us which label looks unexpected?

**Comment by helenayele** [comment]
this one
[![Image from Gyazo](https://i.gyazo.com/c59820d21062c9419204fe61d6722ead.png)](https://gyazo.com/c59820d21062c9419204fe61d6722ead)
is this label correct?

**Comment by IanMayo** [comment]
Aah, @helenayele - you mean the formatting of the text in the text box, right?

**Comment by helenayele** [comment]
Right, the formatting should be improved as well the text doesn't seem the correct label name.
It will repeat itself if you expand it.

**Comment by saulhidalgoaular** [comment]
Good afternoon.

I have loaded this file, and that text in labels is correct. It can be seen inside the sensor file and also in FullDebrief.

![image](https://user-images.githubusercontent.com/11049943/56768286-7ca18f80-679d-11e9-9b50-163d2797ec5f.png)

![image](https://user-images.githubusercontent.com/11049943/56768390-c12d2b00-679d-11e9-9968-72f0fe3f35f6.png)

Do you have details of how you want the new formatting? I could do autowrapping, bigger font, subwindows, etc.

**Comment by helenayele** [comment]
@IanMayo should have the idea how to format the label.

**Comment by IanMayo** [comment]
Aah, well spotted @saulhidalgoaular  - the original content includes tabs, so that's how they're presented in Debrief.  This is expected behaviour.

**Comment by helenayele** [comment]
Okay Ian accepted
