### ISSUE TITLE
Unable to resize the width of D-Lite after graph is plotted

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4051]
### Steps to reproduce the issue

1. load sample.pdf
2. On the graph pane, try to select the range graph.
3. After the graph is drawn , try to maximize D-Lite using Maximize button, then restore the size
4. Then try to decrease the width of D-Lite, by dragging to left.
See that it is not re-sizable at all.
[![Image from Gyazo](https://i.gyazo.com/4bff9338229656d23b22d11473020fc3.gif)](https://gyazo.com/4bff9338229656d23b22d11473020fc3)

**Comment by IanMayo** [comment]
I'm pretty sure this is related to the map, rather than the graph.

Investigate it once we've updated to new GeoTools.

**Comment by helenayele** [comment]
Okay I will test it

**Comment by IanMayo** [comment]
Ok. We can resize the map before we create a graph, even with the graph panel open.  But, as soon as we use the drop-downs to create a graph, we can no longer resize the map.

**Comment by ayeshare** [comment]
@IanMayo @helenayele I could replicate this consistently, but now, I just cant replicate. I tried launching it in command line and still I cant.  I was playing with it to see exactly what was going on and now it cant be replicated.

**Comment by helenayele** [comment]
okay let me try it

**Comment by helenayele** [comment]
Not possible to resize the map following these steps:
Step 1
1. Launch D-Lite
2. Expand the graph pane
3. Try to resize now - not possible to resize it
[![Image from Gyazo](https://i.gyazo.com/9aa73641b9234ded4e4d62a0af418203.gif)](https://gyazo.com/9aa73641b9234ded4e4d62a0af418203)

Step 2 
 1. Launch D-Lite
2. Expand the graph pane
3. Select both drop-downs 
4. Now try to resize - Not possible again
[![Image from Gyazo](https://i.gyazo.com/e1161260dfe5804bf37312d1cb0743ab.gif)](https://gyazo.com/e1161260dfe5804bf37312d1cb0743ab)

And also not able to resize the map to left after I load sample.dpf file and select my graphs 
1. Launch D-Lite
2. Open sample.dpf
3. Select graph and track
4. Resize it -  Not able to resize to left , but I can resize to right
[![Image from Gyazo](https://i.gyazo.com/00c4ab628a9a1a37f5ecf808934521cc.gif)](https://gyazo.com/00c4ab628a9a1a37f5ecf808934521cc)

**Comment by IanMayo** [comment]
I _may_ have found something related to this.  It looks like the narrative panel sits alongside the map. But, the graph panel seems to sit on top of it.

I can load some data `boat1.rep`.  Then fit to window - and it will all be visible.  If I make the graph panel really tall, the viewport doesn't zoom out to ensure we're still showing the whole track. If I then fit to window, it doesn't zoom out. If I shrink the graph panel, I see the track was beneath it all the time.

But, when I grow the narrative panel - the view on the tracks zoom out.  When I shrink the narrative panel, an empty box is shown in the uncovered space. This is only filled in when I finish the drag operation.

**Comment by helenayele** [comment]
Able to resize D-Lite but Getting a bunch of error while resizing the panels - [![Image from Gyazo](https://i.gyazo.com/c046da3c3775bac178d30ce7f19dddb9.png)](https://gyazo.com/c046da3c3775bac178d30ce7f19dddb9) , is filed as separate issue on #4576
