### ISSUE TITLE
XY Plot needs to update on new tracks

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4055]
The XYPlot menus don't update when we reset and load a new set of tracks.

_Maybe_ the XY Plot should register as a listener for for `_layers.dataExtended()`

When the data has changed, XY Plot would pull together list of tracks.  If it's different to what's in in the menu, the menu would update (keeping the current selection, if possible).

**Comment by saulhidalgoaular** [comment]
H @IanMayo , Do you have a way of checking if two TrackWrapper are equals? It will be needed to compare all the properties to see if there has been any change. It will also help to keep the current selection of tracks, Now I am always rerendering it all after any change.

**Comment by saulhidalgoaular** [comment]
Fixed and merged in https://github.com/debrief/debrief/pull/4096

**Comment by helenayele** [comment]
Currently when we select 
NEW
Open
Close , the XY graph will be reset. When we load new dpf file using open action, the xy graph will close the existing file's graph and removes all tracks from the select track combo.
But if user uses 'Replay' action , it doesn't remove the tracks from the select tracks combo but the graph will be reset.

**Comment by helenayele** [comment]
Verified
