### ISSUE TITLE
Implementing Time Filtering for XY Plot

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#4062]
Debrief Lite need to have Time Filtering for XY Plot using the Time Controller tab in the Ribbon.

**Comment by helenayele** [comment]
Currently the xy graph doesn't refresh itself after user filters the start and end time. But full debrief does refresh its graph as soon as a user  modifies the start and end date.
[![Image from Gyazo](https://i.gyazo.com/d45136b9eb80c052ade9d469f8e8e68c.gif)](https://gyazo.com/d45136b9eb80c052ade9d469f8e8e68c)
So Re-opening...

**Comment by helenayele** [comment]
Now the graph refreshes whenever there is a change in time filter. So verified.
