### ISSUE TITLE
XY plots are not drawn for some dpf file in D-Lite

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4067]
I tried to load sen_tracks_with_narrative.dpf on D-Lite but graph pane is still blank. 
But in full debrief the xy plot is drawn successfully.

[![Image from Gyazo](https://i.gyazo.com/1e39d721a743eb07e23f750231aeef62.png)](https://gyazo.com/1e39d721a743eb07e23f750231aeef62)

**Comment by IanMayo** [comment]
@helenayele - Saul's PR containing the graph plotting isn't in `develop` yet, so you won't see any graphs.
But, I do hope we can merge it soon.

**Comment by helenayele** [comment]
oh my goodness, @IanMayo , but how do you know that I checked it in develop branch? yes sure , I did check it even in the other branch. Sorry

**Comment by saulhidalgoaular** [comment]
Good afternoon.

Graph Plotting has been already merged into `develop`.

**Comment by helenayele** [comment]
Yes. able to see now the graph on develop branch- Verified
