### ISSUE TITLE
RuntimeException while pasting leg positions 

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4072]
When I try to copy and paste leg positions from CompositeTrack.dpf file, I get runtime exception with the following stack trace. 
If we don't support this features we should disable the paste action.
[java.lang.RuntimeException_can't add this type to a composite track wrapper.txt](https://github.com/debrief/debrief/files/3111066/java.lang.RuntimeException_can.t.add.this.type.to.a.composite.track.wrapper.txt)

Video:
[![Image from Gyazo](https://i.gyazo.com/fed93551475775d4335c9d5246cea490.gif)](https://gyazo.com/fed93551475775d4335c9d5246cea490)

**Comment by ayeshare** [comment]
![image](https://user-images.githubusercontent.com/38917949/57058648-a80d0880-6cce-11e9-8bc9-b268663cec4d.png)

Fixed this by showing the error back to the user in a popup.  I see the fix already in develop.

**Comment by helenayele** [comment]
Yes now able to see proper dialog :
[![Image from Gyazo](https://i.gyazo.com/5865a8486226694ca9adaa7754dacee5.png)](https://gyazo.com/5865a8486226694ca9adaa7754dacee5)
and also the exception is not thrown. 
Hence closing..
