### ISSUE TITLE
Rename tracks when duplicate tracks found in XY Plot

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4074]
Currently when we load a single dpf file 2 or 3 times , the Select combo in the xy plot doesn't rename them and it looks like :
[![Image from Gyazo](https://i.gyazo.com/d347be2a7a970ecc554162aa21b4d010.png)](https://gyazo.com/d347be2a7a970ecc554162aa21b4d010)
And
 When I select one of them it will select the other like this:
[![Image from Gyazo](https://i.gyazo.com/0419f92d1a7b185b8138852817ebea95.gif)](https://gyazo.com/0419f92d1a7b185b8138852817ebea95)

### Expected Result:
Rename the tracks like the outline pane does

**Comment by saulhidalgoaular** [comment]
This was fixed in https://github.com/debrief/debrief/pull/4087 , and it is already in `develop`.

**Comment by helenayele** [comment]
Verified - now it renames the tracks like
 [![Image from Gyazo](https://i.gyazo.com/bb22c855a1174138cec7f5c23a2415ae.png)](https://gyazo.com/bb22c855a1174138cec7f5c23a2415ae)
