### ISSUE TITLE
Right-click menu failing for AIS import

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4076]
An analyst is importing AIS tracks.  A sample of this data is in `other_formats` \ `150304_0914.txt`

Debrief _mistakenly_ stores them as lightweight tracks in a `WECDIS Tracks` folder.  It _Should_ put them into an `AIS Tracks` folder.

When the analyst tries to delete the tracks, a NPE is thrown, at line `516` of `FixWrapper.java`

Try to reproduce, then fix.

Note: it appears to be because fixes don't have their parent track assigned.  The issue couldn't be reproduced at the analyst PC, so we have a challenge in proving a fix.

**Comment by helenayele** [comment]
No exception is thrown while deleting , cutting/copying an item from AIS layer are  also successful - Verified.
