### ISSUE TITLE
Editing Time properties duplicates tracks in select tracks combo of XY Graph

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4081]
While playing the time from time controller, when I try to edit the small steps property from time controller, the tracks name is duplicated 3 times in the xy graph.
See this video:
[Editing_time_duplicate_tracks.zip](https://github.com/debrief/debrief/files/3115988/Editing_time_duplicate_tracks.zip)

### Steps to reproduce:
1. Load sample.dpf
2. Select Range or Bearing graph and select Nelson in display and the other track in relation to
3. Go to Time menu and start playing
4. See the vertical bar moving  - good and see also the Select tracks combo - only 2 tracks shown - good
5.  Now go to Edit time properties  and change the small scale to 30 or 10 minutes and Apply
and close the window - as can be seen , I have issue in closing this window - there is late response in closing it (already reported)
6. Open Select tracks combo now - see that the tracks are duplicated.

**Comment by helenayele** [comment]
Following the above steps , after I edit time properties window and apply and close ,the graph just disappears and looks like this - [![Image from Gyazo](https://i.gyazo.com/c1516a66f2321a4d4bdd43d2bcff0e75.png)](https://gyazo.com/c1516a66f2321a4d4bdd43d2bcff0e75) 

I didn't like this approach, full debrief just refreshes its graph after a change and it is good if D-Lite behaves the same.

**Comment by saulhidalgoaular** [comment]
Good morning @helenayele . Yes. You are right. Honestly, I didn't like this approach too much either. I have implemented a different one in branch `4062_time_filtering_for_xy_graph`. I have pushed it there, because it was needed for the Filtering fix. Please, check it.

**Comment by IanMayo** [comment]
Waiting for test from @helenayele

**Comment by helenayele** [comment]
Sure - 
Tracks are not duplicated
Graph just refreshes itself like full Debrief 
So verifying... and closing..
