### ISSUE TITLE
Provide tooltips for undo/redo buttons

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4093]
D-Lite now has undo/redo buttons.

It may help the analyst if they knew what operation they were about to undo/redo.

We can retrieve the name of the next operation on the undo/redo buffer.  We should be able to dynamically set the tooltip on the buttons.

Well, we could either manually change the tooltips each time the UndoBuffer is modified.  Or, we could _somehow_ provide an accessor that provides the relevant text each time the tooltip is about to appear.

Flamingo appears to have gone through a major change for it's 2.0 release.  We should probably defer this change until after then.

The radiance upgrade is covered in #4094

**Comment by ayeshare** [comment]
Agreed that there is no support for dynamic tooltips now.

**Comment by helenayele** [comment]
We have got tool-tips for undo and redo actions while
- adding/removing shapes
- deleting layers
- cut/past actions
- modifying properties
[![Image from Gyazo](https://i.gyazo.com/f1326d804e750edb70cb595de2e957db.png)](https://gyazo.com/f1326d804e750edb70cb595de2e957db)

But when we make a layer invisible by selecting the layer with the eye icon, the tool-tip is unreadable and needs to be changed.
[![Image from Gyazo](https://i.gyazo.com/e69c44035408bf805191f4648148db72.png)](https://gyazo.com/e69c44035408bf805191f4648148db72)

**Comment by helenayele** [comment]
[![Image from Gyazo](https://i.gyazo.com/87030c14d7023c49cf6fb44fc45e3bf3.gif)](https://gyazo.com/87030c14d7023c49cf6fb44fc45e3bf3)
 When I hide positions, and see the undo/redo tool-tips, I don't get any word after the word "hide" , it didn't include the positions label on the tool-tip
