### ISSUE TITLE
Technology upgrade - Java / Eclipse / Others

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4094]
This issue covers the steps to upgrade the technology we're sitting on.

One customer base was reliant on Java7.  But, now that they're happy to take an embedded JRE we can upgrade.

Alongside this, we will also upgrade some library dependencies.

Ian _believes_ this is the sequence:
* [x] update build to Java 8
* [x] update Eclipse to 2019-03
* [ ] update build to Java 11 (not Java 9, since it's already past end-of-life)
* [ ] update GeoTools to newest stable release
* [ ] update Radiance/Flamingo to newest stable release (#4562 )

Note: there some GeoTools build tips here:
https://docs.geotools.org/latest/userguide/build/install/jdk.html#building-geotools-with-java-11

Here is the upgrade path, through a series of GeoTools versions. Significantly, it includes how to handle Units of Measurement issues:
https://docs.geotools.org/latest/userguide/welcome/upgrade.html

**Comment by helenayele** [comment]
Good evening @IanMayo , would you please put steps to verify this issue?

**Comment by IanMayo** [comment]
@theanuradha - I've come back to this issue. We haven't upgraded the build to Java 11 yet, have we?

Would you mind taking that on next?
