### ISSUE TITLE
Fix RCPTT test-suite

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4115]
As part of merging EASE back into trunk, Ian had to disable the RCPTT tests.

The RCPTT tests need fixing, as long as it's not too much effort.

If it's more than a couple of days of effort, then we should probably defer it, until after @theanuradha has completed the Jubula/SWTBot/RCPTT comparison: #4083

**Comment by IanMayo** [comment]
@theanuradha = this is probably the next most important issue to resolve, please.

**Comment by theanuradha** [comment]
@IanMayo im on it

**Comment by theanuradha** [comment]
@IanMayo this is done right ?

**Comment by IanMayo** [comment]
Yes, done.
