### ISSUE TITLE
Newly added layer from outline view should be auto-selected in Select Layer combo

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4116]
Currently newly added layer is selected in outline view, but it is not selected in Select Layer combo and after user created this layer in outline view , when s/he tries to insert a shape, the inserted shape will not be created in the new layer.

### Steps:

1.  Open Insert ribbon
2.  Select any existing layer from Select layer combo
3. Create layer using Add Layer button in outline view
4. See that after creation of this new layer, it is not selected in select layer combo
5. Insert a shape , see that the shape is inserted in layer selected at step 2 not on newly created layer at step 3.

**Comment by ayeshare** [comment]
@IanMayo @helenayele This is not expected behaviour. Only if the layer is selected in the select layer combo, shapes should get inserted into that layer.

**Comment by helenayele** [comment]
Closing - invalid bug
