### ISSUE TITLE
 After redo, the text for the layers disappears

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4128]
this is mentioned at comment https://github.com/debrief/debrief/pull/4102#issuecomment-488648878

**Comment by ayeshare** [comment]
@IanMayo I tried the following to reproduce this bug:

1. Loaded sample.dpf
2. Deleted a label from misc layer
3. Undo
4. Redo
Everything worked fine.

Do you remember what you did before you saw this bug?

**Comment by helenayele** [comment]
@ayeshare  you just need to change the visibility from the outline view then undo it

**Comment by helenayele** [comment]
This is reproducible following these steps 
1. Load sample.dpf
2. From the Misk Layer, select the first shape and make it invisible by selecting on the eye icon.
3. Select undo, this time you can see that the Misk layer label gets hidden.
[![Image from Gyazo](https://i.gyazo.com/1ac7e68f7605181ecab56cb1a2f99798.gif)](https://gyazo.com/1ac7e68f7605181ecab56cb1a2f99798)

**Comment by helenayele** [comment]
This issue is no more reproducible and have been fixed in other PR.
[![Image from Gyazo](https://i.gyazo.com/69dc571d2ddc400f14c0909c3c6635b2.gif)](https://gyazo.com/69dc571d2ddc400f14c0909c3c6635b2)

So verifying...
