### ISSUE TITLE
Some console messages after undo/redo actions

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4129]
The issue is mentioned at https://github.com/debrief/debrief/pull/4102#issuecomment-488693308
### Steps to reproduce

1. Launch D-Lite
2. Delete Chart Features layer
3. Add 2 shapes in different layers
4. Add 2 circles in one of the layer
5. Click undo so many times that no items are found in the map except chart features layer
6. Click again redo till all items are shown again
7. Insert 2 grid and 2 scale , but only 1 scale is created in Chart features layer
8. Click undo till all items are hidden
9. Click redo till all items are shown again - But see that grid is not shown
10 . Add Grid again
11. Click Undo
12. Click redo 
13. Repeat undo and redo , you will get atleast this message 
Failed trying to remove Grid from Chart Features (1 items)
or at most the explained console messages on the comment.

### Video that shows the issue:
[console_message_video.zip](https://github.com/debrief/debrief/files/3153100/console_message_video.zip)

**Comment by ayeshare** [comment]
@IanMayo is the fix for this, check to see if scale is already present, then the createscale action should not execute?

**Comment by IanMayo** [comment]
Hmm, @ayeshare - I'd like us to find out why we can't add a second scale, please.  It may be a symptom of a greater problem.

**Comment by ayeshare** [comment]
> Hmm, @ayeshare - I'd like us to find out why we can't add a second scale, please. It may be a symptom of a greater problem.

We cant add another scale because we are using concurrentskiplistset to add the ScalePainter object.  The scalePainter object implements comparator and a compareTo method is implemented.  The compareTo method checks for the name of the object, every new scalepainter object has the same name.  So the two objects are same and so it never gets added to the list.  How should we fix this? Should we prevent adding a duplicate scale object?

**Comment by IanMayo** [comment]
Good research @ayeshare 

I guess we just have to provide a compareTo in scalePainter.  This would get the hashcode for each one, and return the results of `integer.compareTo(other)`.  Get the hashcode using this https://stackoverflow.com/a/909861/92441

**Comment by helenayele** [comment]
No error or console messages are shown while following the above steps.
Verified
