### ISSUE TITLE
No Undo action present for layer created from Select Layer combo

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4130]
We don't have undo action for layer created from Add Layer command found in Select layer combo.

Steps:
1. Launch D-Lite
2. Go to Insert > From Add layers combo select 'Add New Layer' option to create a layer.
3. See that undo action is yet disabled and unable to undo creating new layer.

**Comment by IanMayo** [comment]
@helenayele - I'm demoting this: it's something missing, rather than something that is broken.

**Comment by helenayele** [comment]
Able to undo and redo created layer with add new layer action from the combo. But I am unable to redo a shape created in this layer. 
### Steps:
1. Create new layer from add new layer action in the combo
2. Insert a shape i.e add label
3. select undo 2 times
4. Select Redo 2 times
5. See that the shape/label is not retrieved

**Comment by helenayele** [comment]
Verified
