### ISSUE TITLE
Default Folder for WMF in Full Debrief

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#4140]
When I run the WMF export in the XY Graph section for Full Debrief, It shows the following error.

![image](https://user-images.githubusercontent.com/11049943/57404885-15c3a380-71ab-11e9-8d90-247e87a69ee8.png)

It suggests to check out the properties section, but there is no option about WMF Directory.

**Comment by helenayele** [comment]
Verified - no such dialog is now seen
