### ISSUE TITLE
After resetting or closing files track names still reside in the XY graph's combo

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4149]
After a user resets using NEW action or Closes a file, even if the graph resets/closes, still the tracks name are retained in the Select Tracks combo.
[![Image from Gyazo](https://i.gyazo.com/f123a3967dedf4b180664bab82fa416f.gif)](https://gyazo.com/f123a3967dedf4b180664bab82fa416f)

**Comment by saulhidalgoaular** [comment]
Good morning. This issue has been solved in this branch `4143_disable_inappropiated_xy_graph`.

**Comment by helenayele** [comment]
It throws NPE while closing tracks 
[NPE_while_deleting_track_from_outline.txt](https://github.com/debrief/debrief/files/3178740/NPE_while_deleting_track_from_outline.txt)

### Steps to reproduce:
1. Open boat1.rep
2. Open boat2.rep
3. Close , and don't save
4. See that it throws the above exception but select track combo is empty

**Comment by helenayele** [comment]
Issue no more reproducible hence verified.
