### ISSUE TITLE
Specifying location in Debrief-Lite

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4153]
Debrief-Lite deliberately has fewer controls than full Debrief.

But, we're missing a piece of functionality - changing the location for an item, such as the corner of a rectangle, or the location of a label:
![image](https://user-images.githubusercontent.com/1108513/57516781-4b809d80-730d-11e9-87a4-ba88b2f59b38.png)

In full Debrief we support this through several mechanisms:
1. drag feature mouse mode:  when in this mode, the cursor goes green when over something draggable, and it moves when dragged
2. copy location: the user can right-click on the plot, select "Copy cursor location", then "Paste location" over a location attribute in the property window
3. property editor: the user can expand the location in the property editor to reveal the individuals fields for the location (lat degs, mins, secs, etc).  This is the way exact locations get entered - for example if they've come from an email

In D-Lite, we don't have the drag mouse-mode (1).   Since our property editor is modal, the user can't then right-click on the map to copy a location (2).  Debrief-Lite does have a popup property editor:
![image](https://user-images.githubusercontent.com/1108513/57516539-d4e3a000-730c-11e9-9d76-533dbd14f727.png)

(it's old & clunky, but it works)

So, we're still missing the ability to set a location to be some point on the map (as with 1. and 2.).

**Comment by IanMayo** [comment]
We've heard back from Celine, she favours the mouse modes like we have in full Debrief.

I believe we'll need two modes:
- drag whole feature
- drag element

The first will result in the whole shape being dragged. The latter will drag a corner/end.

The logic can be copied from full Debrief.

**Comment by IanMayo** [comment]
We've heard back from Celine, she favours the mouse modes like we have in full Debrief.

I believe we'll need two modes:
- drag whole feature
- drag element

The first will result in the whole shape being dragged. The latter will drag a corner/end.

The logic can be copied from full Debrief.

**Comment by helenayele** [comment]
Just like full debrief, we need to support undo/redo actions for Drag whole feature and Drag Element functionalities.

**Comment by helenayele** [comment]
The last comment is tracked as separate issue at #4233  
Drag whole feature and Drag Element work as expected now - Verified
