### ISSUE TITLE
MSI generated by Travis is not running on Windows

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#4160]
Here are the steps/hints I have reached for this issue:
* When I run the build msi in my computer (using Arch Linux), it works perfectly on Windows.
* When I install the msi generated by travis with `wine` for linux, it works perfectly.
* Travi's msi fails on Windows.
* I have opened the msi with `msiless` it looks good.

Travis has been configured to use Ubuntu trusty. Somehow Debrief doesn' t compile on travis with Ubuntu Xenial.

Last working msi was generated by travis at 2019/03/19.

**Comment by IanMayo** [comment]
Dropping this. We're just going to run build on MS Windows.
