### ISSUE TITLE
Some difference in XY Graphs between full debrief and D-Lite

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4167]
Using the same files, when I try to generate xy graph in full debrief and D-Lite, I see some differences. For example the below graph is Bearing graph on sen_tracks.rep file.
[![Image from Gyazo](https://i.gyazo.com/8525b16f02d66fc34805580c285b17e6.png)](https://gyazo.com/8525b16f02d66fc34805580c285b17e6)

On the left is on full debrief and on the right is on D-Lite.

**Comment by IanMayo** [comment]
This could be tricky. I'm happy to take it, I produced the "special handling" years ago.

**Comment by IanMayo** [comment]
Actually, I think @saulhidalgoaular  the wizard may be able to handle it.  The full Debrief algorithm will include a step that inserts two fake points, to make it look like the line passes through 360 degs, then zero degrees.  

The code is here in `debrief.legacy` - so I'm surprised it isn't being used for both applications:
![image](https://user-images.githubusercontent.com/1108513/62685349-6a4d0980-b9ba-11e9-8150-724d9af00fb6.png)

**Comment by helenayele** [comment]
Verified : 
[![Image from Gyazo](https://i.gyazo.com/bb8d369b4718bc6363fadc7bcc4fbab3.png)](https://gyazo.com/bb8d369b4718bc6363fadc7bcc4fbab3)
