### ISSUE TITLE
Tote Information is outdated when tracks are deleted

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#4181]
Steps to reproduce are here:
https://github.com/debrief/debrief/pull/4154#pullrequestreview-236502867

After deleting a track from the Outline view, the Normal Highlighter continues to render it.

~~Plot highlighters are still getting rendered, and also primary/secondary tracks are getting outdated after deletion.~~
Also please handle https://github.com/debrief/debrief/pull/4154#issuecomment-493903284 on this PR.

**Comment by helenayele** [comment]
No marker/highlighter remains on the plot - [![Image from Gyazo](https://i.gyazo.com/9b2e08c4ff8fae6c97ed7aa5a18c6d01.gif)](https://gyazo.com/9b2e08c4ff8fae6c97ed7aa5a18c6d01)

Hence verified
