### ISSUE TITLE
New shapes not shown when inserted

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4191]
If we insert a new shape (such as a rectangle) it only gets shown on the plot if we have pre-selected the target layer.

Steps to reproduce:
* open boat1.rep
* switch to _insert_ tab
* click on rectangle
* select target layer (`Chart Features`)
* observe that rectangle not shown

But, if we select `Chart Feature` from the target layer drop-down it does appear.

**Comment by helenayele** [comment]
Verified - even if slow on sample.dpf file
