### ISSUE TITLE
P2 update doesn't update Version details

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4195]
I've downloaded and opened 3.0.476

I've then added the P2_repository for 3.0.478 as an update site.
* download `P2_Repository.zip`
* open 3.0.476, from `Help` menu, select `Install new software`
* add `P2_Repository.zip` as `Local` site.  Give site a name ("Local P2")
* click on ok
* it will offer 478 as an update
* follow wizard steps, let it restart

I ran `Check for updates`, it found the new version, and updated.  But, it still shows 476 as version:
![image](https://user-images.githubusercontent.com/1108513/58176478-4242e980-7c9a-11e9-900d-0033e31e8cfd.png)

Here is the installation details:
![image](https://user-images.githubusercontent.com/1108513/58176500-51c23280-7c9a-11e9-84ea-808952c0ba1d.png)

Once expanded, it shows the valid (updated) version numbers for the Debrief components:
![image](https://user-images.githubusercontent.com/1108513/58176523-60104e80-7c9a-11e9-85b8-9b627202c659.png)

**Comment by ayeshare** [comment]
Following the steps as above and upgrading from 3.0.479 to 3.0.480, everything looked fine. I couldnt test the upgrade from 3.0.476 to 3.0.478 as there was no p2_repository under releases for 3.0.478

**Comment by IanMayo** [comment]
These updates are now working fine.

**Comment by IanMayo** [comment]
No, these updates aren't working fine :-(

When we do a P2 update, the Help/About still contains the version details from the first version that was run.

The installation details pages indicate the app is actually running newer versions, but the startup splash and Help/About are wrong.

**Comment by IanMayo** [comment]
Sorted. If there wasn't an update to `debrief.core`, then that plugin wasn't getting incremented. We need to force that plugin to increment for the new version to be published.
