### ISSUE TITLE
Able to play a track after deletion

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4199]
After I delete a track from outline , the track just continues to play.
[![Image from Gyazo](https://i.gyazo.com/6bfe251275e507726c3bdb88dfda6dc1.gif)](https://gyazo.com/6bfe251275e507726c3bdb88dfda6dc1)

### Steps:
1. Launch D-Lite
2. Open boat1.rep
3. Go to Time menu and start playing the track.
4. In the outline pane, try to delete the Nelson Layer
5. See that the track just continues to play - see the highlighter and the timer 
### Expected Result
Everything in the Time menu including the time controller should reset .

**Comment by IanMayo** [comment]
Yes, the Time Controller should be a layers listener, and should pause/refresh on data being extended/modified/reformatted.

**Comment by helenayele** [comment]
The above issue is no more reproducible hence Closing..
