### ISSUE TITLE
Remove Insert Polygon Shape from D-Lite

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4201]
In full Debrief polygons rely on right-click editing to add points.

But, we don't have right-click in D-Lite.  For now, we should remove `Polygon` from the `Insert` tab.

It's ok to just comment out the lines, ready for if/when we re-instate them, with suitable UI features to maintain the polygon.

**Comment by helenayele** [comment]
Polygon shape is removed now - Verified
