### ISSUE TITLE
Can't click on sensor cuts

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4208]
We can now click on TMA fixes, but we can't click on sensor cuts

**Comment by helenayele** [comment]
Thanks, yes works fine like this:
[![Image from Gyazo](https://i.gyazo.com/656ae14ab3aa3c5a62581a0b072bd6c1.gif)](https://gyazo.com/656ae14ab3aa3c5a62581a0b072bd6c1)
Verified.
