### ISSUE TITLE
D-Lite fails silently to import sensor data on wrong track

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4209]
When user tries to import sensor data on wrong track , D-Lite reports that the import was successful by showing this dialog.
[![Image from Gyazo](https://i.gyazo.com/8d76315875d00be8deb2269203edafbd.png)](https://gyazo.com/8d76315875d00be8deb2269203edafbd)

 But if user tries to load wrong sensor data for the track, D-Lite doesn't import the sensor data, instead it logs this on the console:

"Error:Not storing sensor, track not found" 
But Full debrief does report that the sensor data doesn't get the correct track by showing "Sensor Track not found dialog" :
[![Image from Gyazo](https://i.gyazo.com/9c0282ee0b9b7656ce45a42704a320b6.png)](https://gyazo.com/9c0282ee0b9b7656ce45a42704a320b6).
Even if Full debrief reports this, if I click okay button of this dialog by selecting one of the track, the sensor data is imported like this 
[![Image from Gyazo](https://i.gyazo.com/7e4a4813144d6091151f00e5bf2e03b9.png)](https://gyazo.com/7e4a4813144d6091151f00e5bf2e03b9)
I don't think Full debrief should load this sensor data in invalid track name, and I think this should be improved in full debrief also.
### Steps to reproduce:
1. Launch D-Lite
2. Open samplescale.dpf
3. Drag sen_frig_sensor dsf

**Comment by IanMayo** [comment]
Ok.  We're accepting that D-Lite won't have all the capabilities of full Debrief.

So, when the parent track isn't found, let's popup the warning in a dialog, rather than leaving it on the console. The warning should say "Couldn't find Track titled:zzzz" <- insert sensor data track name here.

**Comment by helenayele** [comment]
Verified
