### ISSUE TITLE
Obtain finer resolution depth data

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#425]
*[Migrated from Assembla ticket [427](https://www.assembla.com/spaces/Debrief/tickets/427) - reported by @IanMayo on 2011-11-25 13:39:30]*

Stuart L saw a diagram that had higher resolution shaded bathy. 

He was envious.  If viewed in Debrief the background would have shown flat bottom.  In truth it wasn't flat, and there were significant features there.

Investigate if/how I can provide higher resolution bathy data.

**Comment by IanMayo** [comment]
Fixed, with introduction of Natural Earth data
