### ISSUE TITLE
Status bar should show current mouse position

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4256]
When we're in range/bearing mouse mode, the status bar shows the current measured range and bearing.

But, when we're in any other mouse mode, the status bar should show the current location (lat/long). The text should be displayed using the `BriefFormatLocation` class.

It should be possible to copy some of the implementation from the Range/Bearing class.

Hopefully some fancy architectural strategy can be used to share the functionality across the assorted mouse modes.

**Comment by helenayele** [comment]
It shows the lat/long attributes even if we are in Rng/Brg mode when mouse is released. Is this expected behavior? 
[![Image from Gyazo](https://i.gyazo.com/dcfcc583b05f8e101e8b5174b9c65fb8.gif)](https://gyazo.com/dcfcc583b05f8e101e8b5174b9c65fb8)
