### ISSUE TITLE
D-Lite build should use valid version number

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4258]
The D-Lite build should take its version number from the `MANIFEST.MF`.  But, currently it's using a hard-coded value.

The build users a hard-coded filename when it deletes existing versions. I guess we'll have to use a wildcard instead.

**Comment by IanMayo** [comment]
@helenayele - I'm pretty sure we've done this.  The Splash screen now shows the valid build date.

**Comment by helenayele** [comment]
Yes . sure  - verified
