### ISSUE TITLE
Need to allow NMEA import in D-Lite

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4271]
While discussing the July release with the scientists, it became clear that it would be valuable if sea-riders could drag/drop NMEA data files into Debrief-Lite.

There's a sample file in `sample_data \ other_formats \ NMEA_trial.log`

In addition to drag/drop onto an existing plot, we should add it to the `Import` types.

The legacy class to perform this import is in `Debrief.ReaderWriter.NMEA.ImportNMEA`

**Comment by ayeshare** [comment]
As of now, this is implemented without the dialog that prompts for frequency in Full Debrief.  The frequencies are hardcoded to 1min

**Comment by helenayele** [comment]
Verified.
