### ISSUE TITLE
Time going backwards when the small step is set to one hour

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4319]
Issue :
https://gyazo.com/9f126c71ecb3d22a839179fcf2e29fb6

When the small step value is set to 1 hour , the time player goes backwards.

Steps:
1. Launch D-Lite
2. Open boat1.rep
3. Go to time menu and select Edit properties window and set small scale value to 1 hour
4. Select play 

See it may not play when the slider is at the start position, move the time slider to the middle and select play
See that it plays backward.

**Comment by IanMayo** [comment]
Fixed in #4320

**Comment by helenayele** [comment]
Verified
