### ISSUE TITLE
Close button is still disabled after opening Narratives.rep file

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4336]
Close button is not enabled after narrative files are opened in D-Lite. 
See the screenshot:
[![Image from Gyazo](https://i.gyazo.com/14feed679dff6ee7cfb1b85ee00fcd69.png)](https://gyazo.com/14feed679dff6ee7cfb1b85ee00fcd69)

### Step:
Open narrative.rep or any narrative files from sample_data project on D-Lite

**Comment by helenayele** [comment]
When we edit some property of a narrative entry and Apply, the close button gets disabled.

[![Image from Gyazo](https://i.gyazo.com/6497159758918c1f9bc98f5a1cf3bfdd.gif)](https://gyazo.com/6497159758918c1f9bc98f5a1cf3bfdd)

**Comment by helenayele** [comment]
Again the above issue is reproducible - after editing narratives property and pressing apply, close button is disabled - hence re-opening

**Comment by ayeshare** [comment]
I tried this and cant replicate it on develop

**Comment by helenayele** [comment]
Not reproducible with RC 6 here as well. So closing..
