### ISSUE TITLE
Narratives are not loaded if we have narratives layer in outline panel

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4337]
After launching D-Lite , I try to create new layer with "Narratives" name. After that I try to  load narrative.rep file but narratives are not loaded on Narrative panel.
[![Image from Gyazo](https://i.gyazo.com/3f413ade3c835e6105f91578fe10ce5c.png)](https://gyazo.com/3f413ade3c835e6105f91578fe10ce5c)

**Comment by IanMayo** [comment]
@helenayele - could you give a little more detailed steps to reproduce?

**Comment by saulhidalgoaular** [comment]
oh, I was able to reproduce it. I am working on it.

**Comment by helenayele** [comment]
Sure :
1. Launch D-Lite
2. Create a new layer with "narratives" or "Narratives" name
3. Open narratives.rep file
See that narratives pane doesn't load the narrative entries

**Comment by saulhidalgoaular** [comment]
I am including now the solution for Full-Debrief

**Comment by helenayele** [comment]
Narratives are not loaded in Narrative Panel after creating Narratives layer and loading narrative.rep
[![Image from Gyazo](https://i.gyazo.com/ab06a550b1e6b119424de5648b9fc213.jpg)](https://gyazo.com/ab06a550b1e6b119424de5648b9fc213)

**Comment by helenayele** [comment]
Tested with RC5
Unable to create with 'Narratives' layer - it says reserved word - [![Image from Gyazo](https://i.gyazo.com/58e099a169a836bf43cd22b5e73e5bdf.png)](https://gyazo.com/58e099a169a836bf43cd22b5e73e5bdf)

But able to create with 'narratives' name - so please avoid also 'narratives' name

**Comment by IanMayo** [comment]
This was my fault. I knew it should have been a case insensitive comparison.

**Comment by helenayele** [comment]
Verified
