### ISSUE TITLE
When Wrap word is disabled narratives entries are not fully shown

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4339]
When we disable the wrap word button, the narrative entries are partially shown.

See the below video to see the issue:
[![Image from Gyazo](https://i.gyazo.com/fb95f8dd60de61a525aaf69dcfcf623c.gif)](https://gyazo.com/fb95f8dd60de61a525aaf69dcfcf623c)

**Comment by IanMayo** [comment]
Yes, I just saw this, too.

**Comment by IanMayo** [comment]
Fixed in #4408
