### ISSUE TITLE
Failure in projection transform error while inserting shapes

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4340]
When I insert shapes like label,etc, I get the following exception being thrown  and the shape is also not shown on the map but it is listed in outline view. 
[![Image from Gyazo](https://i.gyazo.com/062130c064ac8b93f406eadb5a1fffc0.png)](https://gyazo.com/062130c064ac8b93f406eadb5a1fffc0)

[Failure in projection transform.txt](https://github.com/debrief/debrief/files/3373526/Failure.in.projection.transform.txt)

**Comment by IanMayo** [comment]
Yes, Helen.

Plus, if you open the shape in the properties editor you can see the coordinates are way off.

I'll take this, to start wtih.

**Comment by helenayele** [comment]
Yes, it looks like this :
[![Image from Gyazo](https://i.gyazo.com/9bfa56d3983ff8313762e1e3d2b95bbf.png)](https://gyazo.com/9bfa56d3983ff8313762e1e3d2b95bbf)

**Comment by helenayele** [comment]
Verified - able to insert shapes without any issues now
