### ISSUE TITLE
Export to clipboard

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4343]
Can we provide export to clipboard for D-Lite?

Can we re-use the implementation from full Debrief?

Aah, maybe simpler functionality - just putting a still image (png) of the current plot.

I'm pretty sure there's quite a lot of demo sources to do this.

**Comment by IanMayo** [comment]
This _may_ be a way of doing it:
https://stackoverflow.com/a/10796047

Here's an article that covers a range of ways of capturing, including a panel within the app (such as our map pane).

A separate challenge is to put the PNG onto the clipboard.

**Comment by IanMayo** [comment]
Duh, this works.  We just need a confirmation dialog to indicate the image is on the clipboard.

**Comment by IanMayo** [comment]
Don't worry about confirmation. The button is now labelled as `Clipboard`.

**Comment by ayeshare** [comment]
This feature is already implemented
