### ISSUE TITLE
Only expand D-Lite panels that have content

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4349]
We have our collapse/expand button.

But, it shows the the graph and narrative panels, even if they don't have any content.

On an 'expand' operation, the button should check if the panel has content (a graph, or narratives) - and only expand panels that have something showing.

Aah, or, it should only expand panels that were previously open.

**Comment by helenayele** [comment]
Yes better to remember previously opened panels

**Comment by IanMayo** [comment]
This is fixed.

**Comment by helenayele** [comment]
Verified in RC 6 
Now :
it remembers closed state
If panel was expanded in collapsed state, clicking the collapse/expand button will expand all the panels if they were expanded.
