### ISSUE TITLE
Plot doesn't refresh immediately after zoom-in/zoom-out

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4350]
After opening a plot , I try to zoom-in/out but the plot takes more than a minute  to apply the operation.

### Steps to reproduce:
1. Launch D-Lite
2. Open sample_lots_of_sensors.dpf file
3. Select zoom-in button on the view menu
4. See that it takes more than one minute to zoom-in

**Comment by IanMayo** [comment]
With the sensor data visible, I would expect a delay. 

But, without sensor data visible, zoom/pan are instantaneous for me.

Could you re-test?

**Comment by helenayele** [comment]
It takes around 43 seconds to do zoom-in operation on sample.dpf file here.
[zoom-in_on_sample_file.zip](https://github.com/debrief/debrief/files/3377463/zoom-in_on_sample_file.zip)

**Comment by IanMayo** [comment]
Helen - is that with your _new_ laptop?

Are any errors being logged?

**Comment by helenayele** [comment]
Sure..yes it is with the fastest and latest laptop
[sample.zip](https://github.com/debrief/debrief/files/3377495/sample.zip)
. 
No errors are logged on the console.

**Comment by IanMayo** [comment]
Aaah, it's that Chart Lib layer.  If you switch that off, it's instantaneous.
![image](https://user-images.githubusercontent.com/1108513/60971113-5b235f00-a31b-11e9-9114-7f7beb096d0e.png)

I can only imagine each feature in it is triggering a redraw.

**Comment by helenayele** [comment]
By the way the issue is on/off . First I tried with boat1.rep file both zooming-out and fit-to-window works perfect, then I opened sample.dpf file and when I try to zooming-out, it takes too much time to effect the zooming. Then When I try with boat1.rep again, it becomes again slow.

**Comment by IanMayo** [comment]
Ok. I think I've got it.  

After doing `Close` on a plot, then opening a new file, the plot no longer updates properly.  You have to trigger an update by resizing the panel, or something like that.

**Comment by helenayele** [comment]
The issue is still reproducible
Steps:
1. Open boat1.rep
2. Close using close button
3. Open boat2.rep file
4. Select Zoom-out
See that it doesn't respond quickly - it takes some time

**Comment by helenayele** [comment]
Sometimes, zooming-out doesn't work for this file 
[boat1.zip](https://github.com/debrief/debrief/files/3386111/boat1.zip)
and logs this
2019-07-12T13:33:43.639-0700  SEVERE  null
java.lang.NullPointerException
	at org.geotools.renderer.lite.StreamingRenderer.queryLayer(StreamingRenderer.java:925)
	at org.geotools.renderer.lite.StreamingRenderer.processStylers(StreamingRenderer.java:2069)
	at org.geotools.renderer.lite.StreamingRenderer.paint(StreamingRenderer.java:820)
	at org.geotools.swing.RenderingTask.call(RenderingTask.java:106)
	at org.geotools.swing.RenderingTask.call(RenderingTask.java:41)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Or there is so much delay in zooming-out this file

**Comment by IanMayo** [comment]
Ok @helenayele  - thanks for catching this one - it would really have bitten us.

We load a default set of background data in D-Lite. When you saved `boat1.dpf`, it saved that background data. When we reload it, the background data is already there, and it confuses the map renderer.

**Comment by IanMayo** [comment]
Fixed in #4402

**Comment by helenayele** [comment]
Verified - when I zoom-out - I see something like this:
[![Image from Gyazo](https://i.gyazo.com/9a032be3557fc0460a05cbcca8a73fa9.gif)](https://gyazo.com/9a032be3557fc0460a05cbcca8a73fa9)
