### ISSUE TITLE
Disable Delete action for 'Background coastline' default layer

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4352]
Currently when a user selects 'Background coastline' Layer, Delete button is kept enabled and when user selects it, the layer doesn't get removed instead .
'Error:We need to keep one backround layer, to enable correct projection' is logged on the console.
Instead of allowing the user to select delete button, it is better to disable  this  button when the user selects this default layer.

**Comment by IanMayo** [comment]
It's not that simple. If the user drags in a GeoTiff, we can then delete the background layer. It's just that we need one background layer.

**Comment by IanMayo** [comment]
Closing this.  While not perfect, the current implementation seems the most robust.

**Comment by helenayele** [comment]
Okay
