### ISSUE TITLE
D-Lite doesn't show filtered end time when it finishes playing

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4357]
When we filter time and set our end date to some value say y , and if the track has an end date say Z, D-Lite stop playing when it reaches y but it shows Z.  

[![Image from Gyazo](https://i.gyazo.com/ce8c386348de0a43e706b36017b46efe.gif)](https://gyazo.com/ce8c386348de0a43e706b36017b46efe)
### Steps to reproduce:
1. Open boat1.rep file
2. Open Time menu and set start time = 0620 and end time = 1003
3. Start playing and see that when it reaches to 1003 , it ends playing but it shows 1141

**Comment by IanMayo** [comment]
Ok.  The timer allows itself to carry on to the end time of the data. I don't think it knows about the filter period.

I'm going to remove this from this milestone - since introducing a fix may introduce another problem.

**Comment by helenayele** [comment]
Verified
