### ISSUE TITLE
D-Lite track font & style

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4360]
> When editing track properties font and line style don't seem to have an effect

**Comment by helenayele** [comment]
Track font has an effect
 [![Image from Gyazo](https://i.gyazo.com/5023761936285d393ba996165e98dbb9.gif)](https://gyazo.com/5023761936285d393ba996165e98dbb9)
And also  Symbol Color has no effect 
 [![Image from Gyazo](https://i.gyazo.com/0eb12706a7099f1704ea71f24f6e99e0.png)](https://gyazo.com/0eb12706a7099f1704ea71f24f6e99e0)

**Comment by IanMayo** [comment]
Can't reproduce. Closing.

**Comment by helenayele** [comment]
@IanMayo , I am still reproducing the track line style and symbol color properties.
[![Image from Gyazo](https://i.gyazo.com/bc13acfdcf90560b401c19e0cb5dd378.gif)](https://gyazo.com/bc13acfdcf90560b401c19e0cb5dd378)

**Comment by helenayele** [comment]
Symbol Color is only applied when we select symbol highlighter. But we need to fix the line style property of a track if possible.

**Comment by helenayele** [comment]
Line Style - is applied correctly - Verified.
