### ISSUE TITLE
D-Lite property editors locked

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4368]
We use a number of popup property editors.

But, it's not possible to change the value of any of them.

Here's the `Track font` property editor for a track:
![image](https://user-images.githubusercontent.com/1108513/61003506-03f1ae80-a35c-11e9-8f24-cca4ace8588c.png)

The font size drop-down is selected. But, I can't change any values on it.

**Comment by IanMayo** [comment]
@helenayele - would you see if you can reproduce this on MS Windows, please?

**Comment by helenayele** [comment]
Sure. In windows , I can change the font color without any issues -
 [![Image from Gyazo](https://i.gyazo.com/d725fb32481554c7d41a71b9c08cbea1.gif)](https://gyazo.com/d725fb32481554c7d41a71b9c08cbea1)

**Comment by IanMayo** [comment]
@helenayele  - phew :-)

**Comment by IanMayo** [comment]
Yes, works on MS Windows

**Comment by helenayele** [comment]
Verified
