### ISSUE TITLE
Link to D-Lite Help Guidance

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4370]
D-Lite is going to be delivered with help guidance.

The master copy of the help guidance will be in a PPT presentation. But, to give the most versatility, it will probably be provided as a PDF document.

In D-Lite we should include a button/control to access the help guidance.

**Comment by IanMayo** [comment]
I've implemented the first step(s) for this. We just have to provide the PDF, and update the URL.

**Comment by helenayele** [comment]
@IanMayo  When I select the help menu from D-Lite , I see a popup dialog , [![Image from Gyazo](https://i.gyazo.com/3cbd6c52ea12536d264a7c63c942571e.gif)](https://gyazo.com/3cbd6c52ea12536d264a7c63c942571e) , But it doesn't tell any specific location where a user can get this pdf file.

**Comment by helenayele** [comment]
Okay now When I click the Help button, I get the readme.pdf file opened in browser. So I think the only thing remaining is the PPT file.

**Comment by IanMayo** [comment]
Sorted. We don't provide the PPT, just the PDF version of it.

**Comment by helenayele** [comment]
Okay Verified then.
