### ISSUE TITLE
Validate Tif file before importing

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4375]
When D-Lite imports Tif file, it only see whether the file has tif file extension. But as we know, we can have pictures/images with Tif file extension. So if user provides an image with tif file extension, D-Lite will try to import the file but fails to do in the middle and throws the below exception.

Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: Trying to get a reader from an unknown format.
	at org.geotools.coverage.grid.io.UnknownFormat.getReader(UnknownFormat.java:83)
	at org.mwc.cmap.geotools.gt2plot.WorldImageLayer.loadLayer(WorldImageLayer.java:226) 
[UnsupportedOperationException_Tif_picture.txt](https://github.com/debrief/debrief/files/3381900/UnsupportedOperationException_Tif_picture.txt)

So it would be cool if we have a validation mechanism before try to import invalid files

**Comment by IanMayo** [comment]
We can only tell if we can import it by processing the file.  We won't be able to process all the files shown in the files directory.

Nice idea @helenayele - but it's not for us.

**Comment by helenayele** [comment]
Okay accepted!
