### ISSUE TITLE
Error is logged after zooming-out a tif file at certain level

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4376]
After zooming-out a tif file 6 or 7 times,"Possible use of "Mercator_1SP (Inverse transform)" projection outside its valid area"   is logged on the console.
https://screencast-o-matic.com/watch/cqiXlAOoNw

After this error, Fit-to-Window or Zoom-in operations are not working.

**Comment by IanMayo** [comment]
Aah yes. Will try to prevent excessive zoom out.

**Comment by helenayele** [comment]
Can you also prevent the zooming-out action by dragging the mouse ?

**Comment by IanMayo** [comment]
ooh, well spotted :-)

**Comment by helenayele** [comment]
Verified - Excessive zooming is prevented successfully. But I have a fear if it is applied on all other file types (dpf, rep)?
