### ISSUE TITLE
Unable to import Tif files by dragging

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4378]
Trying to open Tif files by dragging raises java.lang.RuntimeException: "metadata" handler not found.' and also an error dialog is shown.
But the same file is opened without any issue by using the TIF import action.
See this video: 
https://screencast-o-matic.com/watch/cqiXlMOo8E

**Comment by IanMayo** [comment]
@helenayele  - I can't reproduce this at the moment, would you mind re-testing it?

**Comment by helenayele** [comment]
I am still reproduce it - [![Image from Gyazo](https://i.gyazo.com/7b9afd8f7d4893efcb0a6cac4a5a2e31.gif)](https://gyazo.com/7b9afd8f7d4893efcb0a6cac4a5a2e31)

**Comment by IanMayo** [comment]
Can you reproduce it in RC5?

**Comment by helenayele** [comment]
Yes , reproducible in RC5 - https://screencast-o-matic.com/watch/cqioeDOYFs

**Comment by IanMayo** [comment]
Hmm, @ayeshare - this looks like Debrief is trying to parse an XML file, even though @helenayele is dragging in a TIFF.  The message she sees comes from `MWC.Utilities.ReaderWriter.XML.MWCXMLReader`

I don't get the error - something strange is happening.  Would you mind checking if you have the problem, and learning more about it, please?

**Comment by ayeshare** [comment]
@IanMayo am looking into it

**Comment by ayeshare** [comment]
@IanMayo Ahh!! I remember this, It happened to me, I was dragging the file with .tif.xml extension instead of .tif, on windows, by default, extensions dont get displayed.  So BRITISH_ISLES.tif shows up as BRITISH_ISLES and BRITISH_ISLES.tif.xml shows up as BRITISH_ISLES.tif. @helenayele please verify this is not the case

**Comment by helenayele** [comment]
Yes , @ayeshare  , it looks like this on my windows platform : 
[![Image from Gyazo](https://i.gyazo.com/c10d8c2f2bdf1ab34e03799e9a2f89a7.png)](https://gyazo.com/c10d8c2f2bdf1ab34e03799e9a2f89a7)

Yes , I was trying to drag the last file (BRITISH_ISLES.tif ) .

And When I try to drag "2_BRITISH_ISLES" file without extension, I am able to load the file without any issues.

**Comment by IanMayo** [comment]
Aah, well remembered @ayeshare - thanks for helping out :-)
