### ISSUE TITLE
D-Lite shows invalid content while launching

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4392]
When launching D-Lite , it shows the following invalid content before showing the map.
https://screencast-o-matic.com/watch/cqilicOb2O

**Comment by helenayele** [comment]
I am still getting this content while launching and it stays there for some time.

**Comment by IanMayo** [comment]
@helenayele - could you double-check you're on a new version?

I'm using two different Windows laptops, and I don't get it on either.

**Comment by helenayele** [comment]
Verified - not repreducible
