### ISSUE TITLE
Time controller menus should be disabled when narrative file is loaded

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4393]
Currently when we load narrative.rep / narrative.dpf files , time controller button are enabled. 
And Time controller buttons will be disabled when we edit time properties and Apply our change.
See this video:
[![Image from Gyazo](https://i.gyazo.com/466dd5be8935d8731b756f1cd7814462.gif)](https://gyazo.com/466dd5be8935d8731b756f1cd7814462)

Note:
_This issue only occurs on current version of develop branch_

**Comment by IanMayo** [comment]
Yes, this would make sense. But, I'm nervous of introducing a problem with the fix. So, I'm going to remove it from this milestone.

**Comment by helenayele** [comment]
Time controllers are disabled when no track data is available in map panel.  so closing...
