### ISSUE TITLE
Trail Length editing problem

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4395]
When I enter a value on trail length, it will be changed after I changed the unit measure of the time.
See this video:
[![Image from Gyazo](https://i.gyazo.com/d5b227be9106a8f1af3f3ad76d78d6f7.gif)](https://gyazo.com/d5b227be9106a8f1af3f3ad76d78d6f7)

I entered 34 but when I change the unit of measure to minutes , it changed the value to 2040.

**Comment by IanMayo** [comment]
This is ok Helen, it's intended behaviour.  2040 is 34 hours expressed in minutes.
