### ISSUE TITLE
Switch D-Lite tools to correct mode on load DPF

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4397]
DPF files store the snail display mode.

But, when we load them into D-Lite the toolbar doesn't update, so it may mistakenly show the wrong mode.

Update the ribbon toolbar to match the loaded data.

**Comment by IanMayo** [comment]
Can't find programmatic way to set toggle button in ribbon bar. Question posted here: 
https://stackoverflow.com/questions/57018228/flamingo-ribbon-bar-programatically-set-toggle-button

The alternative is to set the stepping mode to the current state of the toolbar.

**Comment by IanMayo** [comment]
We now have a solution to this:
https://stackoverflow.com/a/57261740/92441

We _may_ have to store the `Command`, in order to set the toggle state.

**Comment by saulhidalgoaular** [comment]
Good afternoon @IanMayo .
To use the method described, we need to update at least to Flamingo 2.0.

https://github.com/kirill-grouchnikov/radiance/blob/v2.0.0/flamingo/src/main/java/org/pushingpixels/flamingo/api/common/model/Command.java#L244

Command class is not available in Flaming 1.0.2 . Shall we update?

**Comment by IanMayo** [comment]
Aah, yes, @saulhidalgoaular - that does ring a bell

Yes, it would be great to move to Flamingo 2.0.  I think we _did_ have a Java version problem, but we shouldn't now that we've updated.

I suggest we move to Flamingo 2.0 in a separate branch to this fix, to keep it a tidy task.  Note: if we update the libs/jars, we may have to update the Ant build to reflect it.  Is that right, @ayeshare ?

**Comment by ayeshare** [comment]
yes, we need to update

**Comment by IanMayo** [comment]
Ok. Flamingo update covered in this ticket:
https://github.com/debrief/debrief/issues/4094
