### ISSUE TITLE
Vector Stretch value is not retained 

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4427]
While editing the properties of vector stretch value in 'Edit Display mode' Properties window, the value is not retained , and also not applied to the track.

### Steps to reproduce

1. Launch D-Lite
2. Open boat1.rep file
3. Open Time menu
4. Select Edit Time properties button to edit time properties
5. Select Display mode as Snail and apply
6. Select Edit Display Mode button
7. Now 'Snail Painter; Property window will popup
8. Now edit Vector Stretch property  and note that its default value is 1 
9.  Set a value of 50
9. Select Apply and Close both property windows
10. See that it tries to apply on the track but immediately comes back to its original position 
11. If you open and see the vector Stretch property, it will not retain the given value at step 9 

https://screencast-o-matic.com/watch/cqiTjYOaXL

**Comment by IanMayo** [comment]
@saul, could you have a look at this? I'd like to do a release tonight  (in about 10 hours time :-) )

**Comment by helenayele** [comment]
Verified. With Vector stretch of 50 it looks like :
[![Image from Gyazo](https://i.gyazo.com/88acd88f9c163d95c46c9835540bff3d.gif)](https://gyazo.com/88acd88f9c163d95c46c9835540bff3d)
