### ISSUE TITLE
Circles rendered as polygons

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4434]
Circle Shapes are being plotted with too few coordinates:
![image](https://user-images.githubusercontent.com/1108513/62532817-2f719700-b83d-11e9-9fda-31ea36891952.png)

An optimisation that was introduced as part of the performance review in early July was mistakenly left in the production code.

A final constant indicates how many elements there should be:
````
	/**
	 * the number of segments to use to plot this shape (when applicable)
	 */
	public static final int NUM_SEGMENTS = 40;

````

**Comment by helenayele** [comment]
Verified - both imported circles or newly added circles are drawn as circle.
