### ISSUE TITLE
NullPointerException after adding and removing tracks.

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#4443]
Debrief Lite sometimes crashes when you add and remove tracks. It is very hard to reproduce it.

It is related with the TrackWrapper Segments (_theSegments variable). It says it has elements and then it says it doesn't have.
Lines of Interest:
TrackWrapper.java@2276  <--- Here is says it is not empty.
TrackWrapper.java@2693  <--- Here it is empty.

This bug should also be in Full Debrief.

Steps to reproduce:
1. Add/Remove tracks.

**Comment by IanMayo** [comment]
Hey, @saulhidalgoaular  - well spotted, thanks :-)

**Comment by IanMayo** [comment]
@helenayele - could you investigate, and see if you can find a reproducible way of triggering the bug?

**Comment by helenayele** [comment]
[NPE while addingremoving track.txt](https://github.com/debrief/debrief/files/3486192/NPE.while.addingremoving.track.txt)
Got this exception while following these steps :
1. Open BULK_BLUE_TRACKS.rep 
2 . Select course graph and select all tracks 
3. On outline view, delete all the 3 tracks 
4.  Drag again Bulk_Blue_tracks.rep file

**Comment by saulhidalgoaular** [comment]
I have tried the 3 ways to reproduce it you mention, but somehow it is not reproducible. I will continue trying.

**Comment by helenayele** [comment]
Verified
