### ISSUE TITLE
NPE While re-adding a track to the plot

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4445]
After I remove the track trying to load on D-Lite cause NPE to be logged in addition it shown an error dialog that says the file is invalid.
[![Image from Gyazo](https://i.gyazo.com/f1ad2f0e2f46f8fa8bf2dc520377757e.png)](https://gyazo.com/f1ad2f0e2f46f8fa8bf2dc520377757e)
[NPE while addingremoving track.txt](https://github.com/debrief/debrief/files/3486285/NPE.while.addingremoving.track.txt)

### Steps to reproduce:

1. Launch D-Lite
2. Load boat1.rep file by dragging from file system
3. Select Course graph 
4. Delete the Nelson track from outline
5. Try to drag it again
6. See that it shows the above Error dialog with NPE being logged.
Note :
If you don't select the graph type , no issue will be observed.
Not happening in full debrief also

**Comment by saulhidalgoaular** [comment]
Repeated at #4443

**Comment by saulhidalgoaular** [comment]
Fixed at https://github.com/debrief/debrief/pull/4468

**Comment by helenayele** [comment]
Getting this console messages :
`Error:Insufficient points found in secondary track.
Please check coverage of time controller bars`
While adding and removing a single track -
Steps 
1.Launch D-Lite
2. Load boat2.rep file
3. Select course graph 
4. Delete the track from outline view
5. Load it again by dragging
This time the above message is logged on console.
https://screencast-o-matic.com/watch/cqjrjRtQMm

**Comment by saulhidalgoaular** [comment]
I think that is ok. It is re-rendering the Graph while file is getting loaded (and track is still empty), but then it is properly rendered after it is loaded.

**Comment by helenayele** [comment]
Okay, from the console log, it says that  `...secondary track`  but I only load a single track. Why it says secondary track?
