### ISSUE TITLE
D-Lite  doesn't respect filter end time 

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4464]
If we set end time in the Filter to time control for a track and starts playing, the player doesn't stop when it reaches its configured end time instead it stops when it reaches the tracks end time.

### Steps to reproduce:

1. Load boat1.rep
2. Set the time format to HHmm format
3. Set start time : 0701 and End time  : 0801
4. Start playing
5. See that it doesn't stop playing at 0801 instead it stop playing when it reaches at 1141
Note :
This is regression.
https://screencast-o-matic.com/watch/cqjoIBtnc1

**Comment by saulhidalgoaular** [comment]
Repeated at #4357

**Comment by helenayele** [comment]
Verified
