### ISSUE TITLE
Performance problem with layer of missing charts

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4480]
Debrief-Lite is very slow in adding new items when there is a large (180 items) layer of missing charts.

https://screencast-o-matic.com/watch/cqjt2MtqjC

With these charts deleted, the performance is almost instantaneous.

We should investigate what is causing the performance problem, in case it has other knock-on problem in the future.  We can investigate it using `YourKit Java Profiler`.  I can provide details of our Open Source license.

The problem can be reproduced from the `samplescale.dpf` data-file.

**Comment by helenayele** [comment]
I don't see now any performance issue while adding new shapes on sample_scale file.
