### ISSUE TITLE
Reduce instances of Geo Transform in D-Lite

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4485]
We declare the projection transform in both LiteMapPane and in GeoToolMapProjection

We should just use the one in GeoToolMapProjection - and pass it into LiteMapPane.

But, it _looks_ like the reverse transform is declared in LiteMapPane:

LiteMapPane:
````
      theTransform = CRS.findMathTransform(worldCoords, worldDegs);
````

GeoToolMapProjection:
````
      data_transform_val = CRS.findMathTransform(worldDegs, worldCoords);
````

We should certainly switch to just using the latter one.  But, along the way we should verify if/where we're reversing the transform used in the first - to check we're not doing the wrong transform.

**Comment by helenayele** [comment]
@IanMayo  , would you please put some details how to test this issue ?

**Comment by IanMayo** [comment]
@helenayele - sorry for the delay.

The change is under the covers.  But, the area it will most likely break is in converting from screen coordinates (pixels) to data coordinates (degrees) and back.  So, double-clicking on an item should make the properties window for the correct item show.

Or, if the coordinates for a shape are in the centre of another shape (such as a rectangle) then the new shape should be plotted at the centre.

The lat/long indicator status panel should shows the correct latitude and longitude, so as the mouse goes over a marker, the lat/long should match the known origin of that marker.

**Comment by helenayele** [comment]
Verified - Shapes show correct coordinates(lat/lon)
