### ISSUE TITLE
Possible overflow in Time representation of Debrief Lite

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#4487]
After loading tracks in very different time range, time slider doesn't behave properly. Time goes forward and backward.

Steps to reproduce:
1. Load BULK_RED_TRACKS.rep
2. Load boat2.rep
3. Slide the Time bar.

**Comment by IanMayo** [comment]
@saulhidalgoaular - just to be sure we understand the issue (and in case it returns), would you mind either adding a stack trace, or describing in what way the time bar is failing?

**Comment by saulhidalgoaular** [comment]
Yes. Bar goes back to 0 (at the beginning), because time calculation go to negative values due the overflow. It only happens when time range is too big.

![baroverflow](https://user-images.githubusercontent.com/11049943/64069258-3aee8d00-cc46-11e9-8cdf-c7d855ae6dd2.gif)

**Comment by saulhidalgoaular** [comment]
I added a dependency to #4474 , because you can reproduce it only after fixing it.

**Comment by helenayele** [comment]
Able to slide to right or left and also the tracks plays well. - Verified
