### ISSUE TITLE
Trouble with named layers & Sensor Arcs

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4495]
I am having a play with layers within the rep file but cannot seem to get SENSORARC lines to play nicely. I don’t get any errors but they don’t appear, whereas they do if I do not specify any layers.
 
This content below shows the track but not the arcs but if I remove the [LAYER=1] everything works as expected. Actually when you have the layer none of the extended symbology data fields work either.
 
Is this expected behaviour? For info:
 
Version: 3.0.444
Build id: 20180809
Build date: 2018-08-09
```` 
951212 050000.000 "NEL STYLE"   @C[LAYER=1]      22 12 10.63 N 21 31 52.37 W 269.7   2.0      0
951212 050100.000 "NEL STYLE"   @D[LAYER=1]      22 12 10.58 N 21 32  2.98 W 269.7   2.0      0 Override label 1
951212 050200.000 "NEL STYLE"   @A@00[LAYER=1]   22 12 10.51 N 21 32 14.81 W 269.9   2.0      0 Override label 2 //
951212 050300.000 "NEL STYLE"   @A@00[LAYER=1]   22 12 10.51 N 21 32 27.27 W 268.7   2.0      0 Override label 3 // comment 3
951212 050400.000 "NEL STYLE"   @BA10[LAYER=1]   22 12 10.28 N 21 32 40.33 W 270.6   2.0      0 // comment 4
951212 050500.000 "NEL STYLE"   @BA10[LAYER=1]   22 12 10.39 N 21 32 53.47 W 269.4   2.0      0
951212 050600.000 "NEL STYLE"   @CB20[LAYER=1]   22 12 10.26 N 21 33  6.79 W 269.0   2.0      0
951212 050700.000 "NEL STYLE"   @CB20[LAYER=1]   22 12 10.08 N 21 33 20.34 W 270.5   2.0      0
951212 050800.000 "NEL STYLE"   @DC30[LAYER=1]   22 12 10.18 N 21 33 33.68 W 269.9   2.0      0
951212 050900.000 "NEL STYLE"   @DC30[LAYER=1]   22 12 10.19 N 21 33 47.26 W 268.6   2.0      0
951212 051000.000 "NEL STYLE"   @ED40[LAYER=1]   22 12  9.95 N 21 34  0.87 W 272.1   2.0      0
951212 051100.000 "NEL STYLE"   @ED40[LAYER=1]   22 12 10.30 N 21 34 14.25 W 269.1   2.0      0
951212 051200.000 "NEL STYLE"   @FE50[LAYER=1]   22 12 10.14 N 21 34 27.62 W 245.8   2.0      0
;SENSORARC: NULL NULL "NEL STYLE" @R[LAYER=1] -135 -45 2100 3000 45 135 2100 3000 "Beams null start & finish"
````

**Comment by IanMayo** [comment]
Ok, we've investigated this issue.  

In the above source sample, the track titled "NEL STYLE" is created as a lightweight track, and put into a base layer titled "1".

We then try to add a sensor arc to "NEL STYLE".  But, lightweight tracks can't take dynamic shapes, and it gets ignored.

So, the solution is to put an warning on the error log to indicate that it's not possible to add a `SENSORARC` (or other dynamic shape) to a lightweight track.

**Comment by IanMayo** [comment]
Closed in #4504

**Comment by helenayele** [comment]
Steps to verify:

1. Copy and paste the above data to a newly created plot
2. Open it as Debrief plot  Editor
3. I got an error dialog 
[![Image from Gyazo](https://i.gyazo.com/68fafae45d7f17aed05976ad6b6683ad.gif)](https://gyazo.com/68fafae45d7f17aed05976ad6b6683ad)
4. Tried to remove [Layer 1] and I got the same result.
is this valid?

**Comment by IanMayo** [comment]
That's ok @helenayele 

You've put the text into a file with a `.dpf` suffix, which Debrief expects to be XML files. The above content should go into a file with a `.rep` suffix.

**Comment by helenayele** [comment]
Yes , I can open it without any issues after saving it in rep file
[![Image from Gyazo](https://i.gyazo.com/a9fcec2437f5b9e284b0ebcd14397ffa.gif)](https://gyazo.com/a9fcec2437f5b9e284b0ebcd14397ffa)
Verified
