### ISSUE TITLE
Show an error message to the user when an invalid time is inserted.

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#4497]
In Debrief Lite, when you edit a time property and you add an invalid value, It doesn't show any error message, looking like it was saved after pressing apply.
Steps to reproduce:
1. Open in Debrief Lite the properties editor of a time-related object.
2. Add an invalid value and press "Apply". (No error shown)
3. Open the properties editor again. (Same value it had before)

![image](https://user-images.githubusercontent.com/11049943/64492274-9cc87b80-d272-11e9-943d-59256ab2ee83.png)

**Comment by helenayele** [comment]
We know validates invalid dates like "Saul", "33/09/90" ,"00/09/00" , "12/32/90" , "12-12-90 "etc , but one validation that checks start date is before end  date is missed. Values like 
[![Image from Gyazo](https://i.gyazo.com/dc84093e9fa4844f6aa4bad196bbb89c.png)](https://gyazo.com/dc84093e9fa4844f6aa4bad196bbb89c)
are taken as valid values.

**Comment by IanMayo** [comment]
@helenayele - it would be an extensive change to enforce `start < end` across Debrief.  

But, it's a valid requirement.  Could you create it as an issue?

But, we won't implement it in this PR.

**Comment by helenayele** [comment]
The above comment is tracked on separate bug #4509

**Comment by saulhidalgoaular** [comment]
I will close this Issue, because the part not covered here is now in a different issue.

**Comment by helenayele** [comment]
Verified
