### ISSUE TITLE
Travis ANT build not working

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4507]
I've just performed a release.  But, when I came to test the D-Lite zip file it wouldn't open.

Earlier I'd generated a D-Lite zip file locally from the Ant script, and it worked ok.

I've attached (or tried to attach) the two separate instances. Hopefully we can compare them to determine what's wrong/missing.

**Comment by ayeshare** [comment]
I determined that cmap_legacy.jar was missing in the broken file.  How can I access the travis build file? Cannot replicate this locally, After a build fix, how can I get the travis generated zip file?

**Comment by ayeshare** [comment]
Oh I figured out that the fix for 4419, is missing in the build.xml, will add the fix here

**Comment by IanMayo** [comment]
@ayeshare - this is fixed, isn't it?

**Comment by ayeshare** [comment]
@IanMayo yes it is fixed
