### ISSUE TITLE
While resetting, D-Lite should forget all undo/redo action

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4512]
When user selects New action or resetting, all undo and redo actions should be removed.

But currently when user resets, undo/redo actions are still enabled,(remembers the previous actions before resetting).

### Steps to reproduce :
1. Load BULK_BLUE_TRACKS.rep
2. Remove all tracks in this file 
4. Select New to reset D-Lite
4. See that undo action is still enabled. Here it should forget every action after resetting.
5. Select undo action, it retrieves the deleted tracks.

**Comment by IanMayo** [comment]
Yes, well spotted @helenayele

**Comment by helenayele** [comment]
Verified.

**Comment by helenayele** [comment]
Verified in 4562_upgrade_flamingo as well
