### ISSUE TITLE
[1] Filter to time displays as 12hr clock, without am/pm marker

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4522]
Filter to time displays as 12 hours format without showing am/pm maker, this is confusing for user.

But what I am seeing is 24 hour format in filter to time control
[![Image from Gyazo](https://i.gyazo.com/7212e0c162e5d52b490438b3965f9ee8.gif)](https://gyazo.com/7212e0c162e5d52b490438b3965f9ee8)

**Comment by IanMayo** [comment]
Issue already resolved.
