### ISSUE TITLE
[2] when you drop in multiple narrative entries in separate files they don’t re-sort chronologically

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4523]
when you drop in multiple narrative entries in separate files they don’t re-sort chronologically. no obvious way to force a reset. Have to save and reload to fix.

This is fixed in #4518.

**Comment by saulhidalgoaular** [comment]
https://github.com/debrief/debrief/issues/4520

**Comment by saulhidalgoaular** [comment]
I think we can close it. It has been fixed at: https://github.com/debrief/debrief/pull/4521

**Comment by helenayele** [comment]
Narrative entries now gets sorted correctly. Verified
