### ISSUE TITLE
[9] Svg symbols can be selected but don’t work

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4524]
> Svg symbols can be selected but don’t work 

~~this is replica of #4465, so closing~~

No, I don't think it is.

**Comment by IanMayo** [comment]
@helenayele - this doesn't look like a replicate of #4465. Did you mean another issue number?

**Comment by IanMayo** [comment]
Here is an example of SVG shown as the current point marker, and as the symbol for a label:
![image](https://user-images.githubusercontent.com/1108513/65604058-a9511180-df9e-11e9-8127-85d267fc4d0c.png)

**Comment by IanMayo** [comment]
I've gone back to the user, to ask for more detail on this.

**Comment by helenayele** [comment]
We are able to apply svg: symbols on any shapes like this :
[![Image from Gyazo](https://i.gyazo.com/c40108d40489d8dd928a22c0fe98ada7.png)](https://gyazo.com/c40108d40489d8dd928a22c0fe98ada7)

is there any other issue Ian?

**Comment by helenayele** [comment]
@IanMayo  please provide your feedback

**Comment by IanMayo** [comment]
Sure, it looks ok to me. I'll struggle to get any more detail from the originator.

**Comment by helenayele** [comment]
[![Image from Gyazo](https://i.gyazo.com/63258a07da61859b61237dee60718373.gif)](https://gyazo.com/63258a07da61859b61237dee60718373)
Verified.
