### ISSUE TITLE
[3] No way to collapse all in outline view

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4526]
I think here user wants to collapse all items in outline view. Currently we can't collapse /expand all the elements in one click. 
But here user can hide the whole outline panel by selecting collapse/expand button, better to inform user if possible.

**Comment by IanMayo** [comment]
We discussed this in Slack.  We should just support collapse-all via a button in the Outline toolbar.  We can use the same icon we use in Full Debrief (hopefully)

**Comment by helenayele** [comment]
Verified
