### ISSUE TITLE
Annotations/shapes have default dates of (31/12/69)

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4528]
User reports "Default dates (31/12/69) on annotations is not helpful. ideally the dtg from the time slider as startitng point."

But we fixed this issue at  https://github.com/debrief/debrief/issues/4439 , 
But it seem , regression is happening, and when I add shapes like rectangle or label, I get 31/12/69  as default date.
[![Image from Gyazo](https://i.gyazo.com/821f150cf90bca32cf12a52f3b258606.png)](https://gyazo.com/821f150cf90bca32cf12a52f3b258606)

**Comment by helenayele** [comment]
This issue was fixed at #4439. But the client also suggests that it would be useful if the dtg values are initialized from the track's start/end date.

**Comment by IanMayo** [comment]
We do need the concept of "unset" - for shapes that aren't time dependent.  If we inserted the current time controller time, analysts would have to delete these times if the shape wasn't time dependent.

**Comment by IanMayo** [comment]
Closing, issue resolved:
![image](https://user-images.githubusercontent.com/1108513/65603261-41e69200-df9d-11e9-8030-25618d6f8abb.png)
