### ISSUE TITLE
Extra diagnostics going to Console with Full Debrief

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4530]
In the `develop` branch, we now output about 20 lines of text (see below), listing menu locations (I think).

We don't output this in the `master` branch.

![image](https://user-images.githubusercontent.com/1108513/65604673-c33f2400-df9f-11e9-9004-66167584ca2c.png)

**Comment by helenayele** [comment]
Verified - now it only show the top console messages like :
[![Image from Gyazo](https://i.gyazo.com/3476c02306120c71351336567696e5fc.png)](https://gyazo.com/3476c02306120c71351336567696e5fc)
