### ISSUE TITLE
[13] start / end time for visibility of annotations is inconsistent

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4531]
User comment

> Shape's start/end date is not applied correctly for the visibility of the shape.

### Steps to reproduce:
1. Load shapes.rep file
2. From Annotations layer , edit the Time Start to have a time value of `05:10` of Ellipse:test ellipse shape like this
[![Image from Gyazo](https://i.gyazo.com/c0754a21f91a93175380995c990bff3e.png)](https://gyazo.com/c0754a21f91a93175380995c990bff3e)
3. Start playing the track from time controller
4. See that when it reaches at 05:10, a marker on the ellipse shape is started to be shown and lasts for 3 seconds. See this video:
https://screencast-o-matic.com/watch/cqQTIJuVUI

**Comment by IanMayo** [comment]
Ok, I've checked with some users that have used Debrief for years.  None of them rely on the "Center" value for time.

So, we're free to switch to the more modern way of interpreting time in snail mode:
* if there is a start date, the shape should only appear >= that time
* if there is an end date, the shape should only appear < that time

We can infer from the above that if both are present, the shape is only visible for the specified period.
