### ISSUE TITLE
[7] Impossible to mark a position when a ship calls out a contact at range / bearing

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4534]
Client said that he/she can't copy position by right click, (and there aren’t vectors). this makes it hard to, for example, mark the position when a ship calls out a contact at range / bearing.
mark a position say that when a ship calls out a contact at range / bearing

So we need to find a way to mark a position.

**Comment by IanMayo** [comment]
The conclusion of the conversation with @clenoble was that we should add a right-click menu option to `Add label under cursor`.  

This will add a LabelWrapper at the relevant point, with the name "Label", and the a `ReferenceSym` as the symbol.  The label should go into a "Markers" layer.  (_well, I think it should_. Or, we invite the analyst to choose a layer).

If the analyst is just using this functionality to add a label, then the job's done.   Ian guesses this is 80% of the usage for capturing a location off the map.

But, if it's to set the bounds of a rectangle (for instance), then once the label is there the analyst can select "Drag feature" and drag the corner of an existing rectangle to that point.  On completion the label can be deleted.

**Comment by clenoble** [comment]
@IanMayo This works perfectly. Great idea to add a specific layer for markers. Ideally, the user should be able to move the marker/label to another compatible layer of their choice (using drag and drop).

**Comment by helenayele** [comment]
Now it become possible to mark a position by adding a label. 
[![Image from Gyazo](https://i.gyazo.com/c1e13aa06f83b215baf2ebbb9f434f97.gif)](https://gyazo.com/c1e13aa06f83b215baf2ebbb9f434f97)

And it is possible also to copy a label from the marker layer to any layer by pasting.
Verified.
