### ISSUE TITLE
[10] Unable to change the Rng/Brg measurement unit in D-Lite

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4535]
> rng /bearing off the tool is too small

> i can’t figure out how to change it to miles`

Client said that he/she can't change the Rng Measurement units (yards in the screenshot below). The measured range/bearing is shown at the bottom-left in the image below

Client also said the font size was too small to be legible on small devices.

![Screen Shot 2019-09-30 at 11 26 09](https://user-images.githubusercontent.com/1108513/65870991-66fc4b80-e375-11e9-9242-a016d4760807.png)

### Expected Result:

We need to implement option page that enable the user to configure all measurements units of his interest.

The displayed range and bearing should be in a larger font, to be visible on small screens.

**Comment by IanMayo** [comment]
An alternate strategy _could_ be a properties button provided in the Range/Bearing/Position status bar at the bottom left.  This would open a panel that allows the selection of range/bearing units, and position display format.

**Comment by IanMayo** [comment]
We could do with some UX for this, from @Celine.

**Comment by clenoble** [comment]
@IanMayo 
Are they other units / format the user needs to set? A user is likely to set their preferred units and not changed them for a while. In this case, I recommend a Settings or Preferences button in the Lite ribbon (next to Help and Exit).

If it's something they change often, for example multiple times in the same session, then it makes sense to have a small setting icon immediately next to the Rng/Brg button. 

Currently, the range and bearing measurement replaces the coordinates in the bottom left of the display. I see a number of problem with that: 
1- this location is completely disconnected from the map, there is nothing telling the user to look there when measuring range and bearing, and if the user is looking for a specific bearing number, they have to constantly shift their attention from the mouse to the number and back.
2 - a user can't see both coordinates and range and bearing (when drawing a range bearing, the coordinates of the mouse can still be displayed)

I would place the coordinates within the map (top left corner) and the range and bearing immediately next to the mouse pointer. (See screenshot)

I would also keep the bearing/range with the number in place once the user has finished tracing it. It will disappear as soon as the user clicks on anything else. This will allow the user to note down the number or take a screenshot if they want to capture this measurement. Right now, there is no easy way to do that (except from committing the number to memory).
![Range-Bearing](https://user-images.githubusercontent.com/22282418/66111070-69a2af00-e5c8-11e9-8da7-b5c85c9c41fd.png)

**Comment by IanMayo** [comment]
> If it's something they change often, for example multiple times in the same session, then it makes sense to have a small setting icon immediately next to the Rng/Brg button.

Yes, they do change the measurement often. When looking at the _big picture_ they may use `nautical miles` or `km`, then when zoomed in on an interaction they may use `yards` or `m`.

This would support putting a drop-down near the range/bearing display.

But, if we switch to displaying the range/bearing text alongside the line being drawn (so both are in the field of view for the user, as documented [here](https://github.com/debrief/debrief/issues/4561)) we no longer have text down in the status bar.

Hmm, if we do that, we need to find another place for the drop-down. This _could_ be within a Properties Page.  Or, I guess we _could_ introduce a drop-down in the `View` tab, near the `RngBrg` radio button.   Hmm, _maybe_ that radio button could actually have a drop-down list combined with it, so - once it's selected, a [Split Button](https://docs.microsoft.com/en-us/windows/win32/windowsribbon/windowsribbon-controls-splitbutton) drop-down element of it allows the range units to be selected.

**Comment by clenoble** [comment]
@IanMayo If changing the unit is only based on the scale used, I think it should be done automatically by the system (choose the appropriate unit to the distance measured). The user could set a general preference with either metric or non-metric system. 

If they do change regularly between metric and non-metric, which is something the system can't know in advance, then the dropdown next to the RngBrg button is the best,

**Comment by IanMayo** [comment]
Another current issue also relates to the display of Range/bearing information:  #4561

**Comment by helenayele** [comment]
Now they are impelemented as drop down like this [![Image from Gyazo](https://i.gyazo.com/6f073341c5f27105ca4833561b1c7efe.png)](https://gyazo.com/6f073341c5f27105ca4833561b1c7efe)  and work fine.
Verified

**Comment by helenayele** [comment]
It would be very helpful if we can add icon that looks like drop down though.
