### ISSUE TITLE
Time in Narratives (Inside Narrative Panel) are not getting updated after edition.

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#4540]
Time showed in the Narrative Panel is not getting updated after editing narratives.

![image](https://user-images.githubusercontent.com/11049943/65684376-c863a800-e05f-11e9-8f1e-e80962d54355.png)

Steps to reproduce:
1. Load narratives.
2. Edit one narrative, changing the time.
3. Apply and Save.

**Comment by helenayele** [comment]
It correctly updates the DTG on narrative panel. Verified
