### ISSUE TITLE
Cast Exception when editing Narratives Time in Full Debrief

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#4542]
Steps to reproduce:
1. Open narrative.rep
2. Edit time of any narrative entry.

> !STACK 0
> java.lang.IndexOutOfBoundsException: Cannot get at -1 on list of size 38
> 	at ca.odell.glazedlists.TransformedList.get(TransformedList.java:105)
> 	at org.eclipse.nebula.widgets.nattable.data.ListDataProvider.getRowObject(ListDataProvider.java:62)
> 	at org.mwc.cmap.NarrativeViewer2.NatNarrativeViewer.getSelection(NatNarrativeViewer.java:492)
> 	at org.mwc.cmap.NarrativeViewer2.NatNarrativeViewer.setDTG(NatNarrativeViewer.java:581)
> 	at org.mwc.cmap.NarrativeViewer2.NATViewerView$27.run(NATViewerView.java:1330)
> 	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
> 	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
> 	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5113)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4666)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
> 	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
> 	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)
> 
> !ENTRY org.mwc.cmap.core 4 0 2019-09-26 12:53:47.228
> !MESSAGE Whilst adding new action to history buffer
> !STACK 0
> org.eclipse.core.commands.ExecutionException: While executing the operation, an exception occurred
> 	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:503)
> 	at org.mwc.cmap.core.CorePlugin.run(CorePlugin.java:823)
> 	at org.mwc.cmap.core.property_support.EditableWrapper.setPropertyValue(EditableWrapper.java:772)
> 	at org.eclipse.ui.views.properties.PropertySheetEntry.valueChanged(PropertySheetEntry.java:751)
> 	at org.eclipse.ui.views.properties.PropertySheetEntry.valueChanged(PropertySheetEntry.java:756)
> 	at org.eclipse.ui.views.properties.PropertySheetEntry.setValue(PropertySheetEntry.java:691)
> 	at org.eclipse.ui.views.properties.PropertySheetEntry.applyEditorValue(PropertySheetEntry.java:153)
> 	at org.eclipse.ui.views.properties.PropertySheetEntry$1.applyEditorValue(PropertySheetEntry.java:114)
> 	at org.eclipse.jface.viewers.CellEditor$1.run(CellEditor.java:335)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
> 	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
> 	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:176)
> 	at org.eclipse.jface.viewers.CellEditor.fireApplyEditorValue(CellEditor.java:332)
> 	at org.eclipse.jface.viewers.TextCellEditor.handleDefaultSelection(TextCellEditor.java:286)
> 	at org.eclipse.jface.viewers.TextCellEditor.lambda$0(TextCellEditor.java:146)
> 	at org.eclipse.swt.events.SelectionListener$2.widgetDefaultSelected(SelectionListener.java:102)
> 	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:123)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5874)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1400)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5138)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4663)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
> 	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
> 	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)
> Caused by: java.lang.ClassCastException: MWC.TacticalData.NarrativeEntry cannot be cast to MWC.GUI.Properties.PlainPropertyEditor$PropertyChangeAction
> 	at MWC.TacticalData.NarrativeWrapper$1.propertyChange(NarrativeWrapper.java:431)
> 	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
> 	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:328)
> 	at MWC.GUI.Editable$EditorType.fireChanged(Editable.java:968)
> 	at org.mwc.cmap.core.property_support.EditableWrapper$PropertyChangeAction.execute(EditableWrapper.java:162)
> 	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:495)
> 	... 43 more
> org.eclipse.core.commands.ExecutionException: While executing the operation, an exception occurred
> 	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:503)
> 	at org.mwc.cmap.core.CorePlugin.run(CorePlugin.java:823)
> 	at org.mwc.cmap.core.property_support.EditableWrapper.setPropertyValue(EditableWrapper.java:772)
> 	at org.eclipse.ui.views.properties.PropertySheetEntry.valueChanged(PropertySheetEntry.java:751)
> 	at org.eclipse.ui.views.properties.PropertySheetEntry.valueChanged(PropertySheetEntry.java:756)
> 	at org.eclipse.ui.views.properties.PropertySheetEntry.setValue(PropertySheetEntry.java:691)
> 	at org.eclipse.ui.views.properties.PropertySheetEntry.applyEditorValue(PropertySheetEntry.java:153)
> 	at org.eclipse.ui.views.properties.PropertySheetEntry$1.applyEditorValue(PropertySheetEntry.java:114)
> 	at org.eclipse.jface.viewers.CellEditor$1.run(CellEditor.java:335)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
> 	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
> 	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:176)
> 	at org.eclipse.jface.viewers.CellEditor.fireApplyEditorValue(CellEditor.java:332)
> 	at org.eclipse.jface.viewers.TextCellEditor.handleDefaultSelection(TextCellEditor.java:286)
> 	at org.eclipse.jface.viewers.TextCellEditor.lambda$0(TextCellEditor.java:146)
> 	at org.eclipse.swt.events.SelectionListener$2.widgetDefaultSelected(SelectionListener.java:102)
> 	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:123)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5874)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1400)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5138)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4663)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
> 	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
> 	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)
> Caused by: java.lang.ClassCastException: MWC.TacticalData.NarrativeEntry cannot be cast to MWC.GUI.Properties.PlainPropertyEditor$PropertyChangeAction
> 	at MWC.TacticalData.NarrativeWrapper$1.propertyChange(NarrativeWrapper.java:431)
> 	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
> 	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:328)
> 	at MWC.GUI.Editable$EditorType.fireChanged(Editable.java:968)
> 	at org.mwc.cmap.core.property_support.EditableWrapper$PropertyChangeAction.execute(EditableWrapper.java:162)
> 	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:495)
> 	... 43 more
>

**Comment by helenayele** [comment]
The above exception is no more reproducible hence verified.
