### ISSUE TITLE
Ctrl + V  and Ctrl + X shortcuts are not working 

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4545]
I have been using ctrl+v to paste the copied item from clipboard. But now it doesn't work. The same is true for ctrl +x to cut an item.

But  ctrl +C  is working for  copy purposes.

Did we have shortcut for delete action ? ctrl +d ?

**Comment by saulhidalgoaular** [comment]
Good afternoon @helenayele 
I have checked it, and the shortcuts are alt+key, like alt+x, alt+c, alt+ -, alt+delete, etc.

**Comment by helenayele** [comment]
Okay Saul, thanks , they got working.

**Comment by IanMayo** [comment]
Hmm, wouldn't it be better if the shortcuts used <ctrl> instead of <alt>?

Ctrl is certainly the standard shortcut.  Could you investigate changing it, please @saul=

**Comment by helenayele** [comment]
Ctrl + delete key  - doesn't delete an item, but alt + delete key delete an item. Would you please change this as well

**Comment by helenayele** [comment]
And also when I use ctrl + x to cut an item, as can be seen in the below video, items below the selected layer will become invisible.
https://screencast-o-matic.com/watch/cqXXiZUlCR

### Steps:
1. Launch D-Lite
2. Load shape.rep file
3. From annotation layer, select the first label and cut it using ctrl +x shortcut keys
4. See that all elements below it will be invisible

**Comment by saulhidalgoaular** [comment]
Hi @helenayele 
I have pushed the patch for `https://github.com/debrief/debrief/issues/4545#issuecomment-552322721`
I would rather create another issue for tree rendering.

**Comment by helenayele** [comment]
Okay @saulhidalgoaular  , still ctrl + delete key doesn't delete an item from outline view.

**Comment by saulhidalgoaular** [comment]
Good morning @helenayele 
Are you sure that you have tried the branch `4545_ctrl_del_too`? I have re-checked it and somehow it works in my side.
If it doesn't work there, maybe there is some accessibility or application which is capturing the shortcut.

**Comment by helenayele** [comment]
No , I didn't try it on 4545_ctrl_del_too , because I didn't know you created that branch even.

**Comment by helenayele** [comment]
okay on this branch, I can use ctrl + delete key or only delete key to remove a shape. But When I try to remove a position using these delete key does throw 
"INFO:  Exception caught:Failed trying to remove 0508 from 120500.00 (13 positions) "
And the position is not removed from the outline.
[![Image from Gyazo](https://i.gyazo.com/18d306ff47bfad12099c65d2b4ebea7b.gif)](https://gyazo.com/18d306ff47bfad12099c65d2b4ebea7b)

**Comment by IanMayo** [comment]
@helenayele  - if you create a new issue for the "Delete position" I'll take it on. I've got a fix locally.

**Comment by helenayele** [comment]
Sure thanks , filed it at #4651.

**Comment by helenayele** [comment]
The shortcut keys like Ctrl + X, Ctrl + C and Ctrl + V - works well for both shapes and positions. Only the delete shortcuts are not working and this will be covered at #4651. So closing...
