### ISSUE TITLE
[4] Graph label markers not always take the right track color

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4546]
Problem:  while the sparse track drawn at the top has a range of colors, the graph is all in the default color for the track.  The line should change color to match the position it's plotting.

![image](https://user-images.githubusercontent.com/1108513/65783830-8cf0d880-e148-11e9-8b3d-76d23de566fc.png)

To reproduce:
* load `sparse_track.rep`
* view graph of course

**Comment by IanMayo** [comment]
I just got some clarification on this:

> problem is with a track you have recoloured. the marker / legend keeps the original color

So, the user is changing point colors within D-lite, but the colors on the graph don't change.

That means the graph should take the per-position colors as it is created, and it should listen out for changes to those points/colors.

**Comment by helenayele** [comment]
@IanMayo , would you please attach sparse_track.rep here?

**Comment by IanMayo** [comment]
@helenayele - you'll have to trim off the `.txt` suffix:
[sparse_track.rep.txt](https://github.com/debrief/debrief/files/3670526/sparse_track.rep.txt)

**Comment by saulhidalgoaular** [comment]
Good evening.

At my site, I get the colors of the track in the course Graph.

![2019-11-05-001755_1920x1080_scrot](https://user-images.githubusercontent.com/11049943/68163016-212d3700-ff62-11e9-8023-95ddbbe615b9.png)

And after changing the color points in the track, it also changes.

![2019-11-05-002410_1920x1080_scrot](https://user-images.githubusercontent.com/11049943/68163199-b16b7c00-ff62-11e9-8915-970064b3af3d.png)

Am I missing any detail?

**Comment by saulhidalgoaular** [comment]
and somehow I am also getting a different "Course vs Time" plot.

**Comment by helenayele** [comment]
Verified - able to keep the colors on the graph now.
