### ISSUE TITLE
Improve icon for date-format

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4557]
The icon to change the date format in D-Lite could be better.

I've created a task to get us a new icon:
https://github.com/debrief/debrief-icons/issues/76

_Maybe_ something like this:
![image](https://user-images.githubusercontent.com/1108513/66030718-dc912480-e4f9-11e9-93e2-c454c77d66c2.png)

Once the icon is ready, we'll have to swap it into D-Lite

**Comment by IanMayo** [comment]
Ok. The icon(s) are now ready.

Next steps are:
* create branch from `develop`, called it 4557_date_icon
* copy icon from debrief/debrief-icons repo, and put a copy of 16px version into debrief-lite plugin
* change the Time Ribbon Bar code to show this new icon, rather than existing _cog_ icon
* stage the two changed files, and make a commit
* push the branch

**Comment by helenayele** [comment]
Yes, now the new icon is applied on D-Lite.
[![Image from Gyazo](https://i.gyazo.com/dd95c0ff4fa00165eadaec151eb296d0.png)](https://gyazo.com/dd95c0ff4fa00165eadaec151eb296d0)

**Comment by helenayele** [comment]
Re-opening since in branch 4562_upgrade_flamingo , it holds the old icon : - [![Image from Gyazo](https://i.gyazo.com/2ad004070900bafc5e1180ff2a25618d.png)](https://gyazo.com/2ad004070900bafc5e1180ff2a25618d)

**Comment by helenayele** [comment]
Closing since we now have the current icon for date-time :
[![Image from Gyazo](https://i.gyazo.com/aa248520907f1030a3b9242d87af02d9.png)](https://gyazo.com/aa248520907f1030a3b9242d87af02d9)
