### ISSUE TITLE
Improved UX for Range/Bearing

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4561]
@clenoble [contributed](https://github.com/debrief/debrief/issues/4535#issuecomment-537845082) some thoughts on the UX for measuring range/bearing.

We should make these changes:
* display the measured range/bearing alongside the line that is being dragged
* leave the line on-screen until either the next measurement/drag starts, or the user moves out of measure range/bearing mode

The displayed range/bearing could be rendered alongside the line, or horizontally next to the end of the line:
![image](https://user-images.githubusercontent.com/1108513/66122704-4bdd4600-e5d8-11e9-8866-9add9b27d00a.png)

Do you have a preference, @clenoble?

**Comment by clenoble** [comment]
On a static display, the 1st option would be best. In this case, the user is moving the pointer constantly, it's best if the information they want for is exactly where they are looking at, the pointer. They won't need to shift their gaze constantly between the two. So 2nd option, end of line, is best.

**Comment by clenoble** [comment]
Following the behavior described above, the display should be next to the pointer - end of line as long as the user is moving the mouse. 

After the user releases the mouse button and the display is fixed, the measure can be alongside the line. If it's too complex to have both location depending on movement or not, I still prefer keeping it at the end of the line for ease of use.

**Comment by IanMayo** [comment]
@saulhidalgoaular - here's an example of a "Dropdown Button", which combines a command button with a drop-down menu:
https://docs.telerik.com/devtools/wpf/controls/radribbonview/features/ribbon-controls/ribbon-buttons/dropdown-button

(yes, I know it's not Java)

The drop-down menu will contain the range units choices.

Our challenge will be to integrate it into the mouse-mode radio group. Good luck...
