### ISSUE TITLE
Provide Undo for drag track segment

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4565]
While using Debrief, I thought I was in zoom mode, not drag-track-segment.

When I tried to zoom in on an area, it actually dragged a section of track.

Steps to reproduce:
* Open `midflow2.dpf`
* Switch to drag track segment line
* Drag part of a track segment
* Switch to zoom in mode
* Observer that it's not possible to undo drag-track.

So, it's switching mouse mode that's disabling the Undo.

* [ ] Check we don't start drag operation when clicking no-where near a track
* [ ] Ensure Undo is provided for drag-track operations

**Comment by IanMayo** [comment]
Hmm, can't reproduce.  Have to try to get reproducible sequence on client PC

**Comment by helenayele** [comment]
@IanMayo  , unable to reproduce this on develop branch(before the fix) were you be able to reproduce this issue again?

**Comment by IanMayo** [comment]
@helenayele  - in the `develop` branch (before the fix) you can reproduce the issue by doing a drag, switching to "Pan" mouse mode, then switching back to "Drag track segment" mode.  It's not then possible to undo the drag.

**Comment by helenayele** [comment]
Steps to verify:
1. Open midflow2.dpf
2. Open Drag track segment
3. Move the cursor on the track segment and when the cursor turns to green, drag it
4. Select Pan button
5. Drag the while plot using the pan button
6. Select Drag Track Segment button again. This time undo button will get disabled. 
7. Drag the track segment - This time the undo button will get Enabled.
8. Select Drag Component/Drag Whole feature/Measure Range and Bearing/Pan/ZoomIn buttons again - This time the undo button doesn't get disabled
But I select Drag Track segment here, the undo button gets disabled, is this valid? why this button behaves different from the others?
