### ISSUE TITLE
Keep sensor color on Merge Track Segments

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4566]
An analyst has 4 blocks of sensor data.

Each has a different sensor color.

When the 4 blocks are merged, the sensor cuts all take the color of the first one.

So, in the merge operation, we should check if any successive sensors have a different default color to the first.  If this happens, set the sensor color for cuts for successive sensors.

We should include unit tests that prove the above works for blocks of data with different colors, and with equal colors.

To test:
* load `sample_lots_of_sensors.dpf`
* switch on a couple of (nice & small) sensors in `OSPREY`
* change the ensure the sensors are of different colors
* observe that you can see the blocks of sensor lines in different colors on the plot
* right-click on one of the sensors and select `Merge into [this sensor]`
* ensure the sensor bearing lines don't change color

You could also try changing the color of a few sensor cuts within a sensor, then merging that sensor with another. The color of those cuts should still be their changed color.

**Comment by helenayele** [comment]
Verified -[![Image from Gyazo](https://i.gyazo.com/1d17a572db984b8801c9cbe30a72e7fc.png)](https://gyazo.com/1d17a572db984b8801c9cbe30a72e7fc)
