### ISSUE TITLE
Fails to re-open on `Save-as`

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4578]
An analyst is performing a save-as operation.

Within this operation the file does get successfully saved. But the "new version" doesn't re-open, reporting Null Pointer Errors at `PlotEditor.java:2424` and `CorePlotEditor.java:661`

I'm unable to reproduce on a dev build on MACOS.  

Download 3_0_490 on a MS Windows device and investigate.   This _may_ be due to the Eclipse upgrade to E4.x

Reproducible on windows.

**Comment by IanMayo** [comment]
Here is the issue:
![image](https://user-images.githubusercontent.com/1108513/66923144-31678b80-f020-11e9-85c2-3b07fc91d468.png)

`getSite().getPage()` is returning `null`.

I wonder if this is due to the move to E4?

**Comment by helenayele** [comment]
This was the full stack trace thrown in log while using Save..As action
[NPE_While_SAve_As.txt](https://github.com/debrief/debrief/files/3738209/NPE_While_SAve_As.txt)

**Comment by helenayele** [comment]
Yes, I agree the delay  is just the time taken to re-load the file.

[![Image from Gyazo](https://i.gyazo.com/f4ae0a2e99283c536e6c571d5be8b10f.gif)](https://gyazo.com/f4ae0a2e99283c536e6c571d5be8b10f)
Verified.
