### ISSUE TITLE
Reinstate commented out blocks for Java11

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4597]
To get Java11 to build, these elements are not being built/performed:

* javadoc for ease_scripting (steps in `org.mwc.debrief.help/collate_docbook.xml`)
* `org.mwc.debrief.UI_Test`

**Comment by IanMayo** [comment]
@saulhidalgoaular - you're the best equipped to handle the EASE Scripting JavaDocs.

**Comment by saulhidalgoaular** [comment]
As we talked in Slack, we have sent a message to the Eclipse Ease Developer, and a ticket has been opened about it (by him).

https://bugs.eclipse.org/bugs/show_bug.cgi?id=553769
