### ISSUE TITLE
Default track import mode preference setting is not respected

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4605]
In full debrief, we have got a default track import mode preference setting that enables user to configure the settings of the import mode. But this preference is not respected even if user selects DR, or OTG. It  always asks user to open REP files in either DR or OTG mode.

https://screencast-o-matic.com/watch/cq6vi7u8Iy

But in Debrief  Version: 3.0.494 Build id: 20191025 , this is not reproducible. It only asks user if it is configured as Ask user. If we set it as OTG or DR mode and try to open boat1.rep, it will import it immediately without asking user.
[![Image from Gyazo](https://i.gyazo.com/9c56601c7a6fcb356184bb886aad5305.gif)](https://gyazo.com/9c56601c7a6fcb356184bb886aad5305)

**Comment by IanMayo** [comment]
@helenayele - your video seems to show the intended behaviour.  When the "OTG Track" radio button is selected, the file is loaded using that mode.

**Comment by IanMayo** [comment]
@helenayele  - again, this _may_ be because you're running from inside the IDE . We should re-test it once we have a Java11 release.

**Comment by helenayele** [comment]
I will test this once jdk 11 gets merged

**Comment by IanMayo** [comment]
Helen, a Beta release of Java11 support is here: https://github.com/debrief/debrief/releases/tag/20191106_Java11_Beta

**Comment by helenayele** [comment]
Yes, on this release , it respects the user's default track import mode preference settings. So closing...
