### ISSUE TITLE
Sample_Data is not added on new project creation

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4609]
While creating new Debrief project, Checking Add Sample data option doesn't add the sample_data folder in the new project.
https://screencast-o-matic.com/watch/cq6vlau84l

But this is not happening in the lates Debrief release version : 3.0.494 Build id: 20191025

**Comment by IanMayo** [comment]
This _may_ just happen in our dev environment, since the install folder is different.

I'm making a Java11 release to test against.

**Comment by IanMayo** [comment]
Ok. From a full release the sample data does get copied over:
https://youtu.be/pZGcap1uPxg

**Comment by helenayele** [comment]
Okay great, shall I re-test it on the latest release or close it?

**Comment by IanMayo** [comment]
@helenayele  - it's worth double-checking. it once we've produced a Java11 release.

**Comment by helenayele** [comment]
I have tested this on the new jdk 11 release ,and when I create new project by adding sample data, it correctly adds the sample data folder. And if I uncheck the add sample data folder, it will create empty project . Hence closing..
