### ISSUE TITLE
Change the TMA wizard's Speed and course default value and title page

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4620]
In the TMA wizard, the second page has a title of "This page lets you enter an initial solution ", it would make sense if we change it to "Specify the Course and Speed initial values" ?

And also the default speed and course values doesn't align with the tutorial's default value:
[![Image from Gyazo](https://i.gyazo.com/60d669857cefe56fe0f821b4adb9c145.png)](https://gyazo.com/60d669857cefe56fe0f821b4adb9c145)

**Comment by IanMayo** [comment]
We shouldn't worry about them matching the tutorial values. The dialog remembers the values that user last entered, so for users that have already used Debrief, it will contain different defaults.

**Comment by helenayele** [comment]
Yes, it remembers the last entered value, but for the first time user, it is not using the correct values for default value.  If we see the generated TMA using the system default value it looks like this :
[![Image from Gyazo](https://i.gyazo.com/942da1d25647821106b035062a874abc.png)](https://gyazo.com/942da1d25647821106b035062a874abc)

[![Image from Gyazo](https://i.gyazo.com/c6ced1b6fc8fb0483b8dca451f3bb9ad.gif)](https://gyazo.com/c6ced1b6fc8fb0483b8dca451f3bb9ad)

**Comment by helenayele** [comment]
Verified - the wizard page's little is modified - [![Image from Gyazo](https://i.gyazo.com/4ff531ed43d2ff12492ace6f99ac086a.png)](https://gyazo.com/4ff531ed43d2ff12492ace6f99ac086a)
