### ISSUE TITLE
Stalk in snail mode doesn't have the correct direction.

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#4625]
There seems to be an issue with the direction of the “stalk” in snail mode - it’s not pointing in the same direction as the platform is heading.
There is frequently a 5 degree or so, error, but this seems quite large.

File: sparse_track.rep

![image](https://user-images.githubusercontent.com/11049943/68217572-811bf000-ffeb-11e9-9638-b4095e9dc1a1.png)

**Comment by saulhidalgoaular** [comment]
Good afternoon @IanMayo 

I see that the stalk comes from the course degrees which is read from the .rep file. 

![image](https://user-images.githubusercontent.com/11049943/68222478-bd534e80-fff3-11e9-8688-d86b14eb1420.png)

It can be seen here how the stalk is created.

![image](https://user-images.githubusercontent.com/11049943/68222822-4bc7d000-fff4-11e9-86a6-d40760463394.png)

So, the stalk is "correct" for that file.

We could add a verification process that checks the courses consistency. If you like the idea, we could work on it.

**Comment by IanMayo** [comment]
@saulhidalgoaular  - so, for the period in which I took the screenshot (when the red track is travelling back up from the bottom right), can you verify that the course in the file is around, say, 80 degrees?

**Comment by IanMayo** [comment]
I've got it. The course is interpolated between the course at the last position, and the course at the next position.

That's why, during a leg, the stalk is continuously changing.

This is only an issue with the very, very large jumps in @saulhidalgoaular 's data file.  So, I think we'll be ok in real life.  Closing.
