### ISSUE TITLE
Import Sensor data wizard misses image files

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4634]
While importing sensor, and import sensor data wizard is displayed, but it doesn't load its image, and logs 
- Wizard image file not found for:images/NameSensor.jpg" 
- Wizard image file not found for:images/DopplerEffect.png ...

### Steps to reproduce:
1. Load full debrief from jdk 11 release page
2. From SATC folder open Blue_Track.rep file
3. Import Blue_sensor.dsf file
4. Now see the wizard, it doesn't have any icons.
[![Image from Gyazo](https://i.gyazo.com/9a2d97507c68b721382a447940b13f59.gif)](https://gyazo.com/9a2d97507c68b721382a447940b13f59)

**Comment by helenayele** [comment]
The icons are also not found in  "Generate TMA Segment" wizard
[![Image from Gyazo](https://i.gyazo.com/bb3fdd5971c7e4ff5bd4c5765b524f45.png)](https://gyazo.com/bb3fdd5971c7e4ff5bd4c5765b524f45)

**Comment by helenayele** [comment]
Now the images are restored on the wizard pages so closing...
[![Image from Gyazo](https://i.gyazo.com/671925b12c8976bf6131f21344759ec4.gif)](https://gyazo.com/671925b12c8976bf6131f21344759ec4)

Generate TMA wizard
[![Image from Gyazo](https://i.gyazo.com/79ec8c0cbaadd4563183300f9cc03e0e.gif)](https://gyazo.com/79ec8c0cbaadd4563183300f9cc03e0e)

**Comment by IanMayo** [comment]
Hello @helenayele  - how did this get fixed?

**Comment by helenayele** [comment]
Not sure, how they get fixed , but I can see now the images on the wizard and debrief doesn't complain at all
