### ISSUE TITLE
D-Lite doesn't get launched in Jdk 11 

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4636]
After installing java 11 in my environment when I try to launch D-Lite  which is downloaded from JDK 11 beta release, it doesn't get launched. It tries to load but in the middle it fails to launch.
See the below video:
[![Image from Gyazo](https://i.gyazo.com/4fe81ef2f4d056c7cf1c1461a76e2f16.gif)](https://gyazo.com/4fe81ef2f4d056c7cf1c1461a76e2f16)

**Comment by IanMayo** [comment]
@helenayele - could you try to open it from the command line? You may get a bit more information.

**Comment by helenayele** [comment]
Okay , I get this 
Error: Unable to initialize main class org.mwc.debrief.lite.DebriefLiteApp
Caused by: java.lang.NoClassDefFoundError: org/geotools/swing/JMapPane

**Comment by helenayele** [comment]
D-Lite can be launched successfully on jdk 11 now so closing..
