### ISSUE TITLE
When I use ctrl + x to cut an item, as can be seen in the below video, items below the selected layer will become invisible.

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#4648]
And also when I use ctrl + x to cut an item, as can be seen in the below video, items below the selected layer will become invisible.
https://screencast-o-matic.com/watch/cqXXiZUlCR

### Steps:
1. Launch D-Lite
2. Load shape.rep file
3. From annotation layer, select the first label and cut it using ctrl +x shortcut keys
4. See that all elements below it will be invisible

_Originally posted by @helenayele in https://github.com/debrief/debrief/issues/4545#issuecomment-552325946_

**Comment by IanMayo** [comment]
@helenayele - could you re-test this?

**Comment by saulhidalgoaular** [comment]
I have tried it again and it works properly here, it is not reproducible anymore.

**Comment by IanMayo** [comment]
Great, sorted.

**Comment by helenayele** [comment]
@saulhidalgoaular  I can reproduce it. The steps are 

1. Launch D-Lite - should be fresh launch
2. Load shapes.rep file
3. In Annotation layer , ctrl +x the label shape
4. See that all the shapes under this layers become hidden , if you click on them they will be visible
[![Image from Gyazo](https://i.gyazo.com/9dea3d0a3c8f8b09141c995a3a371692.gif)](https://gyazo.com/9dea3d0a3c8f8b09141c995a3a371692)

**Comment by helenayele** [comment]
Verified - not reproducible now.
