### ISSUE TITLE
D-Lite doesn't cleanly exit

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4667]
After running D-Lite from Eclipse, when I close D-Lite the process remains running, and I have to kill it.

When run from the command line, when I close D-Lite, the app is still running in the command-line, so I have to `<ctrl>-c` kill it.

DebriefLiteApp used to finish with `System.exit()`, but that got commented out in this commit:
https://github.com/debrief/debrief/commit/6d7ad7c4d4c320f9ef1a69baf8ac09d44a49739a#diff-b4831b384a84138346d6c04e6257e6e3R1170

@ayeshare - would you mind casting your mind back to when the `exit()` was commented out, and thinking how we can ensure the application closes?

My guess is that calling `System.exit()` was causing the Unit Test runner to exit, as well as D-Lite.  Maybe D-Lite needs to be able to determine if it's being run by a test-runner, or as a normal app. When being run as a normal app, it should probably still do `System.exit()`.

**Comment by ayeshare** [comment]
This is fixed already. Cant replicate it now

**Comment by helenayele** [comment]
@ayeshare  , after I launch D-Lite from CMD ,when I close D-Lite using Exit button or close button the process is getting killed (checked in the task manager) but it is still running  from the command line . ie, it is just showing me this after exiting 
[![Image from Gyazo](https://i.gyazo.com/925a6e6ec370419206924f68ba8edb53.png)](https://gyazo.com/925a6e6ec370419206924f68ba8edb53)

Video
https://screencast-o-matic.com/watch/cYVUlywfYS

**Comment by helenayele** [comment]
Works fine - Verified
