### ISSUE TITLE
Extended symbology to split track

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4680]
An analyst would like to be able to include some statement in a REP file that triggers the start of a new segment in the subject track.

One way of doing this would be a custom annotation:
```
;TRACKSPLIT DTG NAME
```
Another alternative would be extended symbology for the first position on the new segment:
```
951212 050700.000 NELSON @C[NEW_SEGMENT] 22 11 10.08 N 21 43 20.34 W 270.5   2.0      0
```

**Comment by helenayele** [comment]
@saulhidalgoaular /@IanMayo would you please add steps here to verify this  issue?

**Comment by helenayele** [comment]
Track is split successfully with [NEW_SEGMENT] extended symbology.
[![Image from Gyazo](https://i.gyazo.com/ac9616f93929588a134ddee7b586ce95.png)](https://gyazo.com/ac9616f93929588a134ddee7b586ce95)

Verified
