### ISSUE TITLE
[Update to Flamingo branch] On newly launched D-Lite, Filter to time control shows the start and end icon at the same location

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4698]
On filter to time control, D-Lite shows both start and end icons on the same place. 

###Steps to Reproduce:

1. Launch D-Lite from upgrade to Flamingo branch
2. Load shapes.rep file
3. Open Time  menu and then see the Filter to time control. It shows both start and end time labels but the end time icon found on the same location to the start time icon.
[![Image from Gyazo](https://i.gyazo.com/b527375e7ec1eb00edc74174f23ce932.gif)](https://gyazo.com/b527375e7ec1eb00edc74174f23ce932)

**Comment by ayeshare** [comment]
fixed it on the branch. Please review @helenayele

**Comment by helenayele** [comment]
Thanks @ayeshare  it is working as expected now - 
[![Image from Gyazo](https://i.gyazo.com/79ee74650996418095a325f0d01512ab.png)](https://gyazo.com/79ee74650996418095a325f0d01512ab)

[![Image from Gyazo](https://i.gyazo.com/10f5b785d1caf2f8ad74c88177c992e0.png)](https://gyazo.com/10f5b785d1caf2f8ad74c88177c992e0)

**Comment by helenayele** [comment]
D-Lite shows the start and end time icons on the same place when there is no any tracks in the plot. [![Image from Gyazo](https://i.gyazo.com/92c458de7b26aff982ea7f691c2fd087.png)](https://gyazo.com/92c458de7b26aff982ea7f691c2fd087) 

But when there is track data it shows 2 icons for the start and end time.
[![Image from Gyazo](https://i.gyazo.com/ba113969726a9ffc343fa3b0bd047d95.png)](https://gyazo.com/ba113969726a9ffc343fa3b0bd047d95)

**Comment by IanMayo** [comment]
If there aren't any tracks loaded, then there isn't a time period to choose. Let's accept this behaviour @helenayele , thanks.

**Comment by helenayele** [comment]
Okay then closing it..
