### ISSUE TITLE
Remove the previously created layer after reset

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4704]
After reset the last created layer which a user inserted a shape will be visible. And if user inserts a shape,without changing the selected layer, the first shape will be inserted in misc layer and the second and the others will not be added in outline view at all.

### Steps :
1. Launch D-Lite 
2. Go to Insert menu and add new layer by selecting Add new layer option in the select layers combo
3. Insert Arc , line ,rectangle shapes
4. See that they  will be added both in outline and map panel
5. Rest D-Lite by selecting File > New
6. Go to insert menu and see that the previously created layer is selected by default
7. Insert arc shape, then insert line or rectangle shapes
8. See that only Arc shape is seen in outline panel under misc layer. The others added shapes are not seen at all.
9. Add Label shape or Ellipse shape, this time , all the added shapes will be seen.

Video:
https://screencast-o-matic.com/watch/cqlXjLUSMN

### Expected Result:
After a user reset D-Lite , created layers should be removed and D-Lite should be in default state.

**Comment by ayeshare** [comment]
Fixed it. Please review @helenayele  in the branch 4562_upgrade_flamingo

**Comment by helenayele** [comment]
I get the previous created layer in the layers list after selecting a new layer after reset.
See this video please:
https://screencast-o-matic.com/watch/cYVeidvTuv

### Steps :
1. Insert shapes after creating new layer name it "new layer" 
2. Reset - see that the created layer at step 1 is removed from the list
3. create new layer and insert shape name it "second layer"
4. Select it from the layers list - this time you will see the "new layer" which was created at step 1.

**Comment by helenayele** [comment]
Now the above issue is fixed.

**Comment by helenayele** [comment]
After reset the first created layer "New layer" is shown in the combo list, but the shapes within it are not shown in outline view. 
### Steps are :

1. Insert shapes on new layer called  "new layer"
2. Add shapes to it
3. Reset - see that the created layer at step 1 is removed from the list
4. Create new layer and insert shape name it "second layer"
5. Select it from the layers list - And add 3 new shapes to it
6. See the layers list , if you don't see the old layer , add more shapes 
7. After adding some more shapes you will see the old layer "New Layer" 
8. Select this old layer and try to add new shapes
9. See that the new shapes will not be added to this layer 

[![Image from Gyazo](https://i.gyazo.com/8507deeba5f66e2623a52ab126e86c54.gif)](https://gyazo.com/8507deeba5f66e2623a52ab126e86c54)
### Expected Result 
"New Layer" layer should not be shown at all.

**Comment by ayeshare** [comment]
@helenayele @IanMayo I tried to reproduce this with the same set of steps, I cannot reproduce

**Comment by helenayele** [comment]
Verified.
