### ISSUE TITLE
Rotate/Stretch/Translate modes failing

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4707]
When we're dragging TMA segments, analysts tend to use Shear mode.  The translate mode works, but rotate is particularly screwy and stretch needs some testing.

It's challenging to test these modes. _maybe_ we should try to mock the UI interaction in unit tests.  Or, to apply offsets using mouse movements that should produce predictable results.

**Comment by IanMayo** [comment]
@saulhidalgoaular  - I'd like you to have a look at this issue, please.

These `single sided reconstruction` algorithms are some of the most complex in Debrief.

Steps to reproduce:
* open `midflow2.dpf`
* switch to `drag Track Segment` mode
* drag the leg of track a little from either end - it should work fine.
* now switch to rotate mode (the top-right drop-down in the `Bearing Residuals` view)
* try to drag either end of the track - it will start spinning around. 

My guess is that we're passing the total rotation, rather than the rotation since the last mouse update.  Or, there's a degrees/radians issue.

**Comment by helenayele** [comment]
Verified - [![Image from Gyazo](https://i.gyazo.com/d169c75cf092090706f1a29591d344c2.gif)](https://gyazo.com/d169c75cf092090706f1a29591d344c2)
