### ISSUE TITLE
Arrow on selected Narrative entry sometimes is shown slowly

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4710]
After repetitive and fast selection on each narrative entry in the narrative panel, sometimes the arrow that is shown on the selected narrative entry is shown very slowly. 

### Steps to reproduce the issue :
1. Open sample.dpf file
2. Open time menu and see the time on the player that shows the current selected narrative entry time.
3. Open Narrative entry and select the 4th and 5th narrative entries turn by turn in fast way.
4. Observe that you have selected 5th entry and the selection shows this also but the cursor(Arrow) is still on 4th narrative entry.
https://screencast-o-matic.com/watch/cqlF6LvQHq

**Comment by IanMayo** [comment]
@helenayele - I'm going to merge this PR, but I'll leave this issue open, in case we wish to return to it.
