### ISSUE TITLE
repaint issue on play icon in timecontroller tab

### ISSUE THREAD

**Issue by ayeshare** [debrief/debrief#4712]
This issue is on branch https://github.com/debrief/debrief/pull/4603
there is a repaint issue on the play button.  At the end when the task is done, repaint works only when the whole frame repaints, not on its own. On mouseover or mouse click the image repaints.  I spent some time on this, but couldnt figure out.  I added a propertychangelistener to repaint and even that didnt work.

Steps to reproduce:
* open Debrief-Lite in branch `4562_upgrade_flamingo`
* load `boat1.rep`
* switch to `Time` tab in ribbon
* drag time-slider almost all the way to right (but leave some time remaining)
* press `Play` VCR button
* watch time move forward
* When time runs out, `Play` icon disappears (see video below).  Play button does repaint on mouseover

Expected: The play button image should be updated without the need for mouseover.

![Screencast of issue](https://i.gyazo.com/963c68cf762b077cdfb4bcf74bfa29a8.gif)

The code to update the command button is in DebriefRibbonTimeController.java#1125

**Comment by IanMayo** [comment]
Fixed in Ayesha's branch: 4754990933b2fc9bbf63058b389e9d987bec8267
