### ISSUE TITLE
Don't allow graph panels to grow out of the screen size

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4726]
It shouldn't be possible to make the graph panel larger than the visible window. if we allow this D-Lite will goes to out of screen area and not possible to get its upper toolbar menus.
[![Image from Gyazo](https://i.gyazo.com/8c0ae86bf5868d8486d5899525056003.png)](https://gyazo.com/8c0ae86bf5868d8486d5899525056003)

Video:
 https://screencast-o-matic.com/watch/cYVjIhvwW6

**Comment by IanMayo** [comment]
@helenayele Helen - could you assign it to @ayeshare please, and help her understand the issue?

**Comment by helenayele** [comment]
> @helenayele Helen - could you assign it to @ayeshare please, and help her understand the issue?

Sure

**Comment by helenayele** [comment]
Verified
