### ISSUE TITLE
Layers become hidden when applying property changes

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4728]
After opening property windows of layers and applying changes, some of the layers will become invisible(hidden). And when I select reset, they will re-appear. 
[![Image from Gyazo](https://i.gyazo.com/a1b57343477c4e564fab50f2ba86e24d.gif)](https://gyazo.com/a1b57343477c4e564fab50f2ba86e24d)

**Comment by IanMayo** [comment]
@helenayele - can you re-verify this please?  If it's an issue I'd like to get @saulhidalgoaular  started on it, please.

**Comment by helenayele** [comment]
Yes @Ian it is still reproducible

**Comment by helenayele** [comment]
Verified -not reproducible now.
