### ISSUE TITLE
Performance in the Outline for Large files

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#4731]
There is a slow performance when an item is deleted from the Outline for large files.

Steps to reproduce:
1. Load any of the files attached.
2. Delete 1 node of the tree (a leaf)

[Archive.zip](https://github.com/debrief/debrief/files/4082161/Archive.zip)

**Comment by IanMayo** [comment]
@saulhidalgoaular  - we do have Open Source licences for the YourKit Java profiler. Let me get you a license code.

**Comment by saulhidalgoaular** [comment]
Good morning. Yes. I have found what is happening. You are doing a O(N^2) over the nodes to refresh it. I have implemented a linear update, but somehow the tree has a little detail. It ends collapsed after the refresh. I am finding out what is happening.

**Comment by helenayele** [comment]
To remove a position (leaf) it takes around 16-18 seconds for me.

**Comment by helenayele** [comment]
Now the performance in outline view really improved  and takes less than a second to remove a position. [![Image from Gyazo](https://i.gyazo.com/4678b58175f7a942f1cadb50098adff1.gif)](https://gyazo.com/4678b58175f7a942f1cadb50098adff1)

**Comment by helenayele** [comment]
Verified - it now doesn't take more than a second to remove a position from large file 
[![Image from Gyazo](https://i.gyazo.com/fea35569876c69f4a4ec9c2070234a2f.gif)](https://gyazo.com/fea35569876c69f4a4ec9c2070234a2f)
