### ISSUE TITLE
Display `Import NMEA` dialog on correct monitor

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4743]
An analyst is dragging some NMEA into Full Debrief.  A sample of this file format is in `other_formats\NMEA_TRIAL.log`.

When these files are dragged in, the `Import NMEA Data` dialog opens.

But, on this analyst's multi-monitor setup, the dialog is show in the centre of the first monitor, but Debrief is on monitor 2.    That meant that repeatedly the analyst was unaware of the dialog waiting.

The `Import NMEA Data` dialog should open either at the centre of the monitor currently displaying Debrief, or in the centre of the Debrief application windows.

On my MACOS, the dialog is shown on the Primary monitor.  Sometimes that's right for Debrief, on other occasions it isn't.

**Comment by helenayele** [comment]
Good morning @IanMayo ,
how do I test this issue with a single monitor? The steps please?

**Comment by IanMayo** [comment]
I've just tested on multi-monitor setup, and it works perfectly :-)

**Comment by helenayele** [comment]
Great!
