### ISSUE TITLE
Rendering issue while opening large files

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4749]
When I try to open files from https://github.com/debrief/debrief/files/4082161/Archive.zip , it takes around 4-5 minutes to open the second file. But if the tracks in the files were saved as invisible, the loading does't take more than a second or a couple of seconds.
So we need to improve the performance while rendering those large files.

**Comment by IanMayo** [comment]
This went away with the file loading improvements.

**Comment by helenayele** [comment]
Verified - yes now no slowness is seen while rendering large files.
