### ISSUE TITLE
Performance issue in the Outline for Large files in full debiref

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4750]
To delete a position from large file from the outline view, it takes more than 1 minutes like 1 minutes and 15 sec  in full debrief.
In the mean time, Full debrief goes to not responding state.
See this video that shows when a position gets delete.
https://screencast-o-matic.com/watch/cYV0lYv8xw

### Steps to reproduce:
1. Open one of the  files from Archive folder ([Archive.zip](https://github.com/debrief/debrief/files/4082161/Archive.zip)
2. Right click on the positions and Select All children to see all the positions
3. Right click on one of the positions and delete 
4. See how full debrief gets unresponsive for some seconds and it takes around 1:15 seconds to remove an account.

**Comment by saulhidalgoaular** [comment]
Good afternoon. I consider this performance hard to improve. After debugging I have found a Thread Lock and Unlock inside the `org.eclipse.swt.internal.gtk.GTK` which I consider very slow. It is called for after adding every item. It could be studied, but it is very probably that there is a reason for it.

**Comment by IanMayo** [comment]
I'm sure one day we'll come back to this. But, if we do we've got @saulhidalgoaular 's analysis.

One reason for opening out those huge lists of positions was to get rid of some, because frequently they really slowed down everything.

Now when right-clicking on the positions in a track, analysts are offered `Delete non-visible positions`.  The analyst can then use the time slider to filter the period, and this menu command to delete them. It deletes 10s of thousands in a couple of seconds.

**Comment by helenayele** [comment]
https://screencast-o-matic.com/watch/cYVUXiwf2L, 
I am still experiencing performance issue in the outline view.

**Comment by IanMayo** [comment]
@helenayele  - this performance issue isn't resolvable by us.

Analysts have been using `select all children` to `trick` Debrief into opening up the positions.  Their main reason for doing this was to delete items. They now have a much quicker way of doing it.  When you right-click on `Positions` you'll see an option with `Delete non-visible positions`.  So, if you use the time slider `Filter to period`, and filter down to a one-day period, you can then use this new menu command to delete all those other positions.  It happens in a flash :-)

Have a go...

**Comment by helenayele** [comment]
Okay clear - Able to delete many positions in a second with Delete non-visible position action. So closing ...
