### ISSUE TITLE
Outdated Bounds for LightweightTracker

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#4752]
Steps to reproduce:
1. Open `lightweight_test_tracks.rep`
2. Edit the properties of the first element of the Track "FisherOne_002" (like in the picture)
![image](https://user-images.githubusercontent.com/11049943/73119528-7bd39f00-3f63-11ea-8ad0-bb4e56c2e0d9.png)
3. Change the Degrees of the location from 0 to 10
4. Apply all the changes.
5. Fit to Windows (It should show all the elements)

**Comment by helenayele** [comment]
Verified
