### ISSUE TITLE
Let analyst select what types of narrative to import

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4764]
Analysts import diaries of timed comments from MS Word documents in a specific format. These entries are called "narratives".

The current logic works through the MS Word document (or pdf, actually), and loads each line directly into the plot.

But, sometimes the analyst is only interested in a subset of the entry types.

So, we should load the entries into memory, and let the analyst choose which types to load.

We should _probably_ change the current logic from loading the data immediately, to storing the entries into a hashmap, indexed by what type of entry it is (`narrativeEntry.type`).   Once they're all loaded, popup a custom dialog that shows a list of the types, with checkboxes against each.  There should also be `Select all` and `Select None` buttons.

I guess the above logic could be injected at line 2465 of ImportNarrativeDocument.  Once that import loop is complete we would call a new selectTypesToImport helper (to be created).  This will be initialised similar to the `setNarrativeHelper` processing. We'll have a _dumb_ one for our unit tests, and a GUI version for actual users.

If the user presses `Cancel` the import is cancelled. But, if the user presses `Ok` just those selected types of entries are loaded.

Here's an example of raw narrative content, taken from the `FCS_Narrative.doc` sample data-file:
![image](https://user-images.githubusercontent.com/1108513/73479145-4da0f580-438f-11ea-832b-ccfd21086d9e.png)

Most of the early entries are of type `OOW COMMENT`, but the later ones are `FCS`.

I _expect_ there to be from 5-15 types of entries in a real import document.

**Comment by IanMayo** [comment]
@ayeshare  - I'd like you to work on this Full Debrief feature please, once you're on top of the D-Lite changes, please.

**Comment by ayeshare** [comment]
@IanMayo Since ImportNarrativeDocument is common for all Debrief versions (lite and full), we need to have two dialogs one swing based and the other swt dialog. And we need to bring up the correct dialog depending on the type of gui.  Is this correct assumption?

**Comment by IanMayo** [comment]
I'm ok with just supporting this dialog in Full Debrief.  If `ImportNarrativeDocument` doesn't have a handler for this dialog, we'll just import all entries.
The SWT importer can be assigned to `ImportNarrativeDocument` in `CorePlugin.startup()`.

**Comment by helenayele** [comment]
Able to import different narrative types using the custom narrative importer dialog - [![Image from Gyazo](https://i.gyazo.com/43a9e49db8855ad4cb2e9fb0973db911.png)](https://gyazo.com/43a9e49db8855ad4cb2e9fb0973db911)

-Verified
