### ISSUE TITLE
Narrative Entry's Visibility property is not applied on narrative panel

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4766]
Currently narrative entries are shown on narrative panel whether they are visible or invisible in outline panel in D-Lite.
They should not be shown in narrative panel if they are invisible and also if user applies filter to time, the filtered time should be applied on narrative entries as well and should be shown in narrative panel accordingly.

**Comment by IanMayo** [comment]
(This is actually for D-Lite _and_ full Debrief)

**Comment by helenayele** [comment]
Narrative entries are visible both in D-Lite and Full Debrief based on their visibility properties and also based on the filter to time property. So verified.
