### ISSUE TITLE
Specify turn radius for planning legs

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#477]
_[Migrated from Assembla ticket [479](https://www.assembla.com/spaces/Debrief/tickets/479) - reported by @IanMayo on 2013-05-15 07:07:49]_

Users can build up a plan for a trial using a series of planning legs.

These are all represented by straight lines, and suited for 'high level' planning.

For more detailed planning, users would like to be able to include turning legs.

Propose new leg-type offered that allows turn radius plus demanded course change.

Here are the straight leg calculation types:
http://www.debrief.info/tutorial/ExercisePlanning.html

Since the course angle plus turn radius are specified, we have a known length for the leg.  So, instead of range-time, speed-time, range-speed there will just be a pair of speed/time attributes.  Changing one will result in a calculated value for the other.

Changes  will be required in the UI to allow a turning leg to be generated, the new leg type must be defined, the XML schema plus handlers must be extended, and the user guide should be updated.

**Comment by IanMayo** [comment]
Superceded by #2867
