### ISSUE TITLE
Pan Action doesn't move Scale decoration with the other plot area

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4777]
When I try to move the items on the maps using Pan action, Scale decoration doesn't move at all. See the below video:
[![Image from Gyazo](https://i.gyazo.com/204859325e9f11fb8a8140ef77e3ac34.gif)](https://gyazo.com/204859325e9f11fb8a8140ef77e3ac34)

**Comment by IanMayo** [comment]
No, the scale is meant to stay in the corner that is set in the properties panel.  The numbers on the scale should change if the map zooms in/out though.

**Comment by helenayele** [comment]
okay the numbers on the scale do change while zooming in/out
