### ISSUE TITLE
Reveal All positions action in positions property is not functional

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4783]
In D-Lite, if we load a file with many positions , all the positions will be visible in outline view. But full debrief only show those large number of positions if we use "Reveal All Positions" action.
And D-Lite should behave like this.

**Comment by IanMayo** [comment]
This works for me:

![screencast](https://i.gyazo.com/4fbfa7cf0dec2f40dcd7e6f5d31574dc.gif)

**Comment by helenayele** [comment]
Yes working confirmed.
