### ISSUE TITLE
Delete positions not currently visible action is not working in D-Lite

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4784]
This actions should delete any positions not currently visible in the outline view, But it is not functional yet in D-Lite.

**Comment by IanMayo** [comment]
The points are deleted, but the Outline isn't getting updated.

@helenayele - could you write the steps to reproduce this?

**Comment by helenayele** [comment]
Hmm, I got all the positions deleted from both outline panel and map panel , when I use Delete positions not currently visible action:
1. Load sample.dpf
2. On the Time ribbon, on the Filter to Time , set the start date to 95/12/12  05:59 so that all positions  that start with 05 become invisible both from outline and map panels  from both tracks.
3.  From Nelson layer , double-click on Positions(402  positions) to open its properties.
4. Select 'Delete positions not currently visible' action
5. See that all positions that was invisible are deleted from both outline and map panel.
[![Image from Gyazo](https://i.gyazo.com/ff46539a2b3f9f5b3b472f8d5d9e1c58.gif)](https://gyazo.com/ff46539a2b3f9f5b3b472f8d5d9e1c58)

**Comment by helenayele** [comment]
This is working as expected so closing..Ian if you have any issue I can re-open it.
