### ISSUE TITLE
After undoing action, layers become invisible

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4786]
When I try to undo the invisible action , the layers become invisible in outline panel like this :
[![Image from Gyazo](https://i.gyazo.com/ca09c4e9b976ffc12f66c7cb61165ce7.gif)](https://gyazo.com/ca09c4e9b976ffc12f66c7cb61165ce7)

### Steps to reproduce:
1. Load shapes.rep file
2. Select some of the layers and make them invisible
3. Select Undo action
See that the layers become invisible.

**Comment by IanMayo** [comment]
@helenayele - is this still an issue?

**Comment by helenayele** [comment]
Yes Ian 
[![Image from Gyazo](https://i.gyazo.com/99351f565e3a841efce47c84097b1ded.gif)](https://gyazo.com/99351f565e3a841efce47c84097b1ded)

**Comment by ayeshare** [comment]
May be related to #4795

**Comment by ayeshare** [comment]
Not related to #4795

**Comment by helenayele** [comment]
Working fine - Verified
