### ISSUE TITLE
Adjust time-controller coverage after "Remove not visible:

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4788]
We have a Full Debrief issue where the Outline View rendering slows down the deletion of large numbers of positions (1000s).  So, there is now a method available when right-clicking on the `Positions` child of a track.  If the analyst uses `Filter to time period` to focus on a limited window of data, he/she can use `Delete positions not currently visible` to delete the other data.  This happens effectively instantly.

But, there's an issue:
> In the Time controller I have 6 days of track, I filter the time period to one day,
> then “delete positions not currently visible”, the Time Controller still shows all 
> 6 days. “I click on Filter Plot Data to Selected Time Period” and I still have all 
> six days on the Time Controller.
> 
> All the data before and after has been deleted.

So, after we've run this operation, we have to trigger the operation that updates the bounds of the Time Controller.  The data currently loaded _may_ still cover the original period if several tracks are loaded. But, if there is only one large track, then the Time Controller period should shrink to match the newly trimmed track.

**Comment by ayeshare** [comment]
@IanMayo Please share a sample file on this, or how to create one

**Comment by helenayele** [comment]
[Archive.zip](https://github.com/debrief/debrief/files/4260326/Archive.zip)
Please try with this files.

**Comment by IanMayo** [comment]
@helenayele  - this works for me: ![GIF Recording](https://i.gyazo.com/0f23bfdca6dff80878b56a7f8fb39def.gif)

How about you?

**Comment by helenayele** [comment]
On develop branch it is not working for me :
[![Image from Gyazo](https://i.gyazo.com/3d8cf20af1cf660a7dd0b78eadbe40a0.gif)](https://gyazo.com/3d8cf20af1cf660a7dd0b78eadbe40a0)
let me check on the new fix ..

**Comment by IanMayo** [comment]
Looking at your plot, the points aren't getting hidden.   The track on the plot should get shorter when we Filter to Time Period.

So, the "filter" has to happen before "Delete points not visible" will work.

_Maybe_ click the plot, then the time controller (to re-sync them), then try to filter to time period again?   Aah, or click "Filter to Time Period" toggle button off, then on again?

**Comment by helenayele** [comment]
This feature only  works when 'Filter Plot data to selected time period' is toggled on. So it works when this feature is on and not working when it is off - Verified.
