### ISSUE TITLE
Wizard image file not found for:images/NewEllipse.png

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4790]
While invoking 'Generate TUA  Ellipse for this Track'  context menu on the track, the below warnings are thrown:
"Wizard image file not found for:images/NewEllipse.png"

### Steps to reproduce:
1. Load boat1.rep
2. Right click on the track's line and invoke 'Generate TUA  Ellipse for this Track' ctx menu
3. See that a wizard with 'New Solution' title is shown immediately and the above warning is logged.

[![Image from Gyazo](https://i.gyazo.com/4f2b672d1761759c58d1d7e75cf72d77.gif)](https://gyazo.com/4f2b672d1761759c58d1d7e75cf72d77)

**Comment by IanMayo** [comment]
The image is present in the repo, maybe we're just looking in the wrong place:
![image](https://user-images.githubusercontent.com/1108513/74454365-b00ff080-4e7b-11ea-8792-7cc0b1d7130c.png)

**Comment by helenayele** [comment]
Verified - now the images are added on the wizard.
