### ISSUE TITLE
Early steps towards Database import

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4800]
Tomorrow we're holding a workshop with users to discuss their requirements for pulling database data into Debrief.

The backend database ("Pepys" - pronounced _Peeps_) and it's import library is still under construction right now. But, we can start to take some exploratory steps towards importing the data.

There may be subtle changes to the schema, but it's now fairly stable:
https://docs.google.com/drawings/d/1CXE6pW6lvAKcCP8O1spRNSYBwl6ajJ3HX9dCSRm7nK0/edit?usp=sharing

Eventually the users will be connecting to a PostGres networked database. but for our own testing we're using standalone SQLite database files.  I've attached one that contains 543 positions (states) for 29 platforms (ship), taken from 25 data-files.

Old one (no locations): [test.zip](https://github.com/debrief/debrief/files/4256426/test.zip)
Updated file (with location): 
[test2.db.zip](https://github.com/debrief/debrief/files/4299173/test2.db.zip)

We won't be ready to start implementing the UI until Celine has designed it.  But, we can _hit the ground running_ if we perform some non-UI setup steps:
* create new Debrief plugin:  org.mwc.debref.pepys
* incorporate SQLite JDBC driver jar(s)
* create new Pepys class in the plugin, that can:
    * connect to a SQLite database file
    * list data-files in the database
    * return all of the *State* measurements for a database id, as a series of TrackWrapper objects, containing one FixWrapper for each State record.

**Comment by IanMayo** [comment]
Hello @saulhidalgoaular  - we now have a IU design:
[Debrief-Pepys-importer-UI-20200302.pdf](https://github.com/debrief/debrief/files/4274602/Debrief-Pepys-importer-UI-20200302.pdf)

The database meets this schema:
https://docs.google.com/drawings/d/1CXE6pW6lvAKcCP8O1spRNSYBwl6ajJ3HX9dCSRm7nK0/edit

We may need to make some database changes to allow the necessary querying/filtering we require.  

Aah, we may also need some more testing data in the database - particularly for Tasks.

**Comment by IanMayo** [comment]
@saulhidalgoaular  - for the Time Period filter, we already have some usage of the Nebula Data and Time controls in the `Maintain Contributions` View, screenshot here:
![image](https://user-images.githubusercontent.com/1108513/75871105-f239ab80-5e03-11ea-88cd-026217bd7fc3.png)

**Comment by IanMayo** [comment]
Also, I indicated in the chat channel that the import process should be triggered from clicking on a new `Import from Database` button that will sit to the right of the `Import Natural Earth` button.  Here' the icon to use:
![database](https://user-images.githubusercontent.com/1108513/75882395-fa501600-5e18-11ea-881c-0827962ae8eb.png)

**Comment by IanMayo** [comment]
@saulhidalgoaular - here's another database file, one that contains `Contacts` and `Comments`.
[test6.db.zip](https://github.com/debrief/debrief/files/4330687/test6.db.zip)

**Comment by helenayele** [comment]
Database import is working correctly- Verified
