### ISSUE TITLE
Pepys Database Import - PostGres support

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4814]
The _target_ database for this system will be a networked PostGres database.

We need Debrief to be distributed with the jars to support both PostGres and SQLite.

Ian will provide @saulhidalgoaular  with the connection details for an Internet-hosted PostGres database that contains this data.

We should verify that we can populate the UI from this database.

**Comment by helenayele** [comment]
So Ian this mean that the user should have internet connection to import these data?

**Comment by IanMayo** [comment]
For our development team, yes, it will need an Internet connection.

Once it's deployed to the users, they will just use the details for the database instance installed on their network.

**Comment by saulhidalgoaular** [comment]
Fixed in https://github.com/debrief/debrief/pull/4830

**Comment by helenayele** [comment]
When I try 'Test database connection' from the released full debrief 
Version: 3.1.13
Build id: 20200405
Build date: 2020-04-05
it fails with [![Image from Gyazo](https://i.gyazo.com/8c31ab9a9286b8d508fc7fdf0b993c0d.png)](https://gyazo.com/8c31ab9a9286b8d508fc7fdf0b993c0d).
I tested it with internet connection.

**Comment by IanMayo** [comment]
Yes, @helenayele - there does need to be some setup on the user's machine for the database to connect. You need a config file, and an environment variable pointing to that file: https://pepys-import.readthedocs.io/en/latest/configuration.html

@saulhidalgoaular - could you help @helenayele  configure her PR to load the `.ini` file please?

The "drag/drop" database PR Saul is working on removes the need for the above.

**Comment by IanMayo** [comment]
Re-opening, just so @helenayele  can verify this.

**Comment by helenayele** [comment]
I tried by switching off my internet connection and setting environment variable like this.
[![Image from Gyazo](https://i.gyazo.com/8d3675ae6268efda4ff6dae1ee70697a.png)](https://gyazo.com/8d3675ae6268efda4ff6dae1ee70697a)
And When I try to import the db, it fails with this exception:
[![Image from Gyazo](https://i.gyazo.com/7cdc64243ccf594f221c6eddd6e8be85.gif)](https://gyazo.com/7cdc64243ccf594f221c6eddd6e8be85)

**Comment by helenayele** [comment]
With connection off, and with the above configuration file set, unable to get the connection to the db successful still on the released version of full debrief . Getting this when I select Connection Test button.
[![Image from Gyazo](https://i.gyazo.com/68ca99f16ed9e4e8eb42dd715fa87836.png)](https://gyazo.com/68ca99f16ed9e4e8eb42dd715fa87836)

**Comment by IanMayo** [comment]
Thanks for persevering with these tests @Helen.  But, for @saulhidalgoaular  & I to reproduce the error, we need you to be really clear on how to reproduce it.  So, we need to know:
* the value of the `PEPYS_CONFIG_FILE` environment variable
* the contents of the file that the variable is set to
* if the config file is set to a SQLite database, we need to know if that is present
* or, if the config file is set to PostGres database, whether you have an Internet connection

Thanks :-)

**Comment by helenayele** [comment]
Okay Ian, 
1. regarding the value of PEPYS_CONFIG_File, its value as indicated in the above screenshot , it points to the value of the postgres.ini file , which is saved in the downloads directory as indicated in the environment variable screenshot in the above comment.
2. its content is  this : 
[database]
db_type = postgres
db_username = pepysdb_dev
db_password = dev_P3pys
db_port = 5432
db_name = pepysdb_core
db_host = postgresql-pepysdb.alwaysdata.net

3. it is PostGres db but I test it with no internet connection.

**Comment by IanMayo** [comment]
Ok, in that case I don't quite know what the problem is that you're reporting.  Without an Internet connection it's correct that Debrief can't connect to the database.

**Comment by helenayele** [comment]
@IanMayo  ,So which db is working without internet connection for clients with no internet connection. We have requirement that enables us to use the import db without internet connection right?

**Comment by IanMayo** [comment]
SQLite is the database for offline users to use.

Here is an example of a SQLite config file: https://github.com/debrief/debrief/blob/develop/org.mwc.cmap.combined.feature/root_installs/sample_data/other_formats/sqlite_sample_data.ini

**Comment by saulhidalgoaular** [comment]
When I try with Internet, It works as expected:
![image](https://user-images.githubusercontent.com/11049943/88451525-fff9d700-ce5f-11ea-8333-8f99f16248c6.png)
and without Internet, It shows the error message as expected:
![image](https://user-images.githubusercontent.com/11049943/88451560-48b19000-ce60-11ea-9a37-8c23335ab3a3.png)

It is happening, because the environment variable is forcing to use the Postgres connection. 
When we don't have the environment variable created, we have the following successful connection message:
![image](https://user-images.githubusercontent.com/11049943/88451627-d1303080-ce60-11ea-84d5-765a3f0632a8.png)

Behavior is as specified in Slack.
![image](https://user-images.githubusercontent.com/11049943/88451663-1d7b7080-ce61-11ea-9496-1fdbd9cce84d.png)

**Comment by helenayele** [comment]
1. When there is no env variable and no connection - connection is successful and it uses the default database.
2.  When there is Env variable and no connection - it shows this dialog:
[![Image from Gyazo](https://i.gyazo.com/ec0198caf1e5b1f72fe8829d6f0396ee.png)](https://gyazo.com/ec0198caf1e5b1f72fe8829d6f0396ee)
3. When we have Env variable and connection - it  connects correctly.
[![Image from Gyazo](https://i.gyazo.com/ad2ca7e1a84d2fa55447d17f5ee7b629.png)](https://gyazo.com/ad2ca7e1a84d2fa55447d17f5ee7b629)

Hence Closing...
