### ISSUE TITLE
Pepys Database Import - get config via Env Variable

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4815]
The database connection details will be provided in an `INI` file. The path of the file will be provided in an environmental variable.

At startup, Debrief (or the Pepys viewer plugin, at least) will look for the environmental variable titled `PEPYS_CONFIG_FILE`.

The contents of this file will look like this: https://github.com/debrief/pepys-import/issues/195

Debrief will extract the connection parameters from the `database` section of the file.  The file will (initially) only require SQLite or PostGres connections.

**Comment by saulhidalgoaular** [comment]
Fixed in https://github.com/debrief/debrief/pull/4830
