### ISSUE TITLE
Pepys Database Import - UI improvements

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4816]
Here are some minor UI improvement requests. I've tried to sort them in priority order
* [x] Implement time filter support
* [x] Implement spatial filter support
* [ ] ~~"Mock" the `Use current viewport` by providing this bounding box:
(60N, 6W), (50N, 4W)~~ (no, we no longer need this)
* [x] Introduce column showing the time period covered by that data-file
* [x] Clicking a checkbox clicks all the checkboxes beneath it.  Similar for un-clicking.
* [x] Implement filtering by data-type
* [x] Add "connection test" button - this will use the config file (from env, if provided, to a test-connect, then confirm which database is connected to).  The button will have a label "Test".  A dialog box will open with a confirmation of success/fail.  Both will include connection details, but failure will include an error snippet.
* [ ] Introduce basic handling for typical errors: "database not found", "username not found", "wrong password", "not on this port", "sqlite file not found", ...
* [x] Implement free-text search over the right-hand listing. This will retain the whole _branch_ for matching items. So, it could be used to search for a platform (which will then show all it's children) or a data-file, (which will still display the data-file's parents)
* [x] Switch the "Apply" and "import" buttons to use the 48px icons for "Search" and "Import".  The 48px icons can be found in github.com/debrief/debrief-icons. If they're not already in `org.mwc.debrief.core/icons/48`, then they should probably be copied there, and then referenced from that plugin.
* [x] Introduce icons for `State`, `Contact` and `Comment` entries in the Data-Type search box. From the `debrief-icons` project, these icons can be used (repectively): `fix`, `bearing`, `narrative`.
* [x] Introduce icons in the collapsible-panel tabs:  `control_time`, `map` and `filter` icons, respectively
* [x] Adding busy cursor - https://github.com/debrief/debrief/pull/4809#issuecomment-601236035
* [x] Resizing to a bigger size
* [x] Bring the same Windows when the button `Import Database`  is pressed again.
* [x] Adding icons to the items of the tree.
* [x] Add 'Select All' checkbox to select all the available `State`, `Contact` and `Comment`
* [x] drag/drop .ini file onto database import dialog
* [x] drag/drop .sqlite database file onto database import dialog
* [x] Provide proper error message when user provides wrong db_type
* [x] Increase the size of the title

**Comment by saulhidalgoaular** [comment]
* [ ] Adding busy cursor - https://github.com/debrief/debrief/pull/4809#issuecomment-601236035
* [ ] Resizing to a bigger size

**Comment by saulhidalgoaular** [comment]
* [ ] Bring the same Windows when the button `Import Database`  is pressed again.

**Comment by helenayele** [comment]
After importing all State, Contact and Comments into empty plot, I see no time in time controller, is this expected?
[![Image from Gyazo](https://i.gyazo.com/b16e257e8403714ffd823130d47a3f14.png)](https://gyazo.com/b16e257e8403714ffd823130d47a3f14)

But I don't see any performance issue after importing all the available items in an empty plot

**Comment by helenayele** [comment]
The following functionalities are added now 
- Able to select the entire items by selecting 'Database' Parent item.
- Icons are added to  the items of the tree.
- Able to resize the dialog to the desired value by dragging or using min/maximize buttons.
- Import database dialog become now modal
- connections test actions is added
- Data type filtering is added
- Search functionality is added
- Clicking a checkbox clicks all children checkbox. 
- filtering support by selecting "use current viewport" in the area menu.

**Comment by helenayele** [comment]
Verified but #4859 , #4860 are filed.
