### ISSUE TITLE
Pepys - SQL-error or missing database error while trying to import data

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4826]
After selecting 'Import from Database button', I get a wizard that imports data from db. But after I select my time period and the rest attributes and select Apply, it throws an error dialog that stated that database is missed. But the database is found in pepys project like this :
[![Image from Gyazo](https://i.gyazo.com/5291e16fc5bdddb85b5933b973d99d41.png)](https://gyazo.com/5291e16fc5bdddb85b5933b973d99d41)

[![Image from Gyazo](https://i.gyazo.com/3b4f0629e3680d37f66e2e97e1f25625.gif)](https://gyazo.com/3b4f0629e3680d37f66e2e97e1f25625)
Stack Trace:
Query: SELECT NTP.state_id AS NTQ, NTP.time AS NTR, NTS.sensor_id AS NTT, NTS.name AS NTU, NTV.sensor_type_id AS NTW, NTV.name AS NTX, NTY.platform_id AS NTZ, NTY.name AS NUA, NTS.created_date AS NUB, NTP.heading AS NUC, NTP.course AS NUD, NTP.speed AS NUE, NUF.datafile_id AS NUG, NUF.simulated AS NUH, NUF.privacy_id AS NUI, NUJ.datafile_type_id AS NUK, NUJ.name AS NUL, NUJ.created_date AS NUM, NUF.reference AS NUN, NUF.url AS NUO, NUF.created_date AS NUP, NTP.privacy_id AS NUQ, NTP.created_date AS NUR, X (NTP.location) as NUS_X, Y (NTP.location) as NUS_Y, Z (NTP.location) as NUS_Z FROM States AS NTP INNER  JOIN Sensors AS NTS ON NTS.sensor_id = NTP.sensor_id INNER  JOIN SensorTypes AS NTV ON NTV.sensor_type_id = NTS.sensor_type_id INNER  JOIN Platforms AS NTY ON NTY.platform_id = NTS.host INNER  JOIN Datafiles AS NUF ON NUF.datafile_id = NTP.source_id INNER  JOIN DatafileTypes AS NUJ ON NUJ.datafile_type_id = NUF.datafile_type_id WHERE '2000-03-23 13:25:15.000000' <= NTP.time AND NTP.time <= '2020-03-23 13:25:15.000000'
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (The specified module could not be found.
)
	at org.sqlite.core.DB.newSQLException(DB.java:941)
	at org.sqlite.core.DB.newSQLException(DB.java:953)
	at org.sqlite.core.DB.execute(DB.java:857)

**Comment by helenayele** [comment]
The above error or exception is no more reproducible in windows. Checked in 4816_ui_improvement branch

**Comment by saulhidalgoaular** [comment]
Fixed in https://github.com/debrief/debrief/pull/4830

**Comment by helenayele** [comment]
Database is connected successfully. - Verified
