### ISSUE TITLE
Pepys - Debrief Time Controller can't handle very long periods

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4831]
I've loaded some Pepys data using a spatial query (no time filter).

It has 20 years of tracks loaded, but they're low volume. 4 tracks, all less than 500 points.

But, the time-controller is really, really slow.

We should run it in the profiler - and find/remove the bottleneck.

Note: this isn't Pepys specific. I'll try to produce a plot-file, to reproduce it.

[boat_long_period.rep.zip](https://github.com/debrief/debrief/files/4386281/boat_long_period.rep.zip)

**Comment by IanMayo** [comment]
@ayeshare  - I don't know if you've used Yourkit Java Profiler before.  But, I think it would prove useful in this issue.

I'm hoping to release the "Database import" late next week.  But, you don't need database import to reproduce the problem, the attached REP file is enough to trigger the problem.

@helenayele - I'd appreciate you checking that you experience the performance issue. Then we'll know if//when it has been fixed :-D

**Comment by helenayele** [comment]
After dragging this file in full debrief, full debrief goes to not responding state for long time.  See this video - this happens also in develop branch.
https://screencast-o-matic.com/watch/cYevlC4XPS

**Comment by helenayele** [comment]
This file with long period is playing well now, no performance issue has been seen.  So verifying.
[![Image from Gyazo](https://i.gyazo.com/9aad33f236840e0e07c130258c40ef26.gif)](https://gyazo.com/9aad33f236840e0e07c130258c40ef26)
