### ISSUE TITLE
Pepys - clear Area bounds

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4833]
I filtered to an area (the current viewport).

Then I deleted the value in the area fields.  But, when I filtered, it was still restricted to those bounds.

So, we should not include an area filter if any of the text fields are empty.

**Comment by helenayele** [comment]
@IanMayo  would you please write the steps  to reproduce this issue?

**Comment by IanMayo** [comment]
Open Debrief
Create new empty plot
Zoom to look at Europe
Open Database Import page
On Area Tab, click on "use current viewport"
Click "Apply"
Just about 4-6 platforms shown
Go back to Area Tab. Delete contents of text boxes
Click "Apply"
Still only 4-6 platforms shown - I would expect to see all of them.

**Comment by helenayele** [comment]
It now correctly filters based on the selected area when 'Use current viewport' is selected. 
[![Image from Gyazo](https://i.gyazo.com/8e6e9d2505c35ff8aa57b9cde5aa66d0.png)](https://gyazo.com/8e6e9d2505c35ff8aa57b9cde5aa66d0)

Verified
