### ISSUE TITLE
MSI package generated is corrupted

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#4834]
Currently the MSI package created shows this message when it is getting installed.

Tested on Windows 10.

![image](https://user-images.githubusercontent.com/11049943/78148496-35079700-7435-11ea-9cb1-394426790c2c.png)

**Comment by saulhidalgoaular** [comment]
![image](https://user-images.githubusercontent.com/11049943/82162798-6c2bed80-98a7-11ea-8248-85795d74b14c.png)

I have tested the Release of May 13, 2020 and it works perfectly.

https://github.com/debrief/debrief/releases/tag/20200512_3_1_14

**Comment by IanMayo** [comment]
@saulhidalgoaular  - any idea what the problem was?  We haven't changed anything in the build, as far as I know.
