### ISSUE TITLE
Pepys - text search

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4850]
@saulhidalgoaular - can you confirm that the "free text search" is being run at the server, and not on the client?

That means...  the search string should be used in a SQL query that is run on the server.  We should not collect all the records, then filter them on the client.

**Comment by helenayele** [comment]
Verified - the text search works both from the server side and client side. From the server side we user 'Text' search in the left panel, and for the client search we use Search input field in the top right corner.
