### ISSUE TITLE
Ability to centre XY-Plot on current time

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4870]
It's possible to make an XY Plot "slide" with time, to only show a limited period of data.

1. In XY-Plot properties, set fixed duration toggle, plus duration
2. In XY-Plot toolbar (or drop-down), tick 'Grow Times'
3. Now shows set period running up to current time

But, it shows the window of time "before" the current time.  Analysts would like to the see window of time "around" the current time.

We would support this by adding a "Centre-Window" boolean option to the `Time-related` set of Properties in the XY-Plot properties panel. This will control how the time-axis is scaled/displayed.

![Plot_Properties](https://user-images.githubusercontent.com/1108513/82223574-bb5f3600-991a-11ea-847a-0635108d1b94.png)

**Comment by helenayele** [comment]
Now - Center window property is added, and a stepper is also shown on the graph while playing the track.
[![Image from Gyazo](https://i.gyazo.com/3ec2e399e270ebe5924bf549831eb37b.gif)](https://gyazo.com/3ec2e399e270ebe5924bf549831eb37b)

Verified.
