### ISSUE TITLE
Pepys Import Dialog - blank at initial open

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4872]
I haven't seen this before, which will probably make it difficult to reproduce, but...

When I first open the Pepys Import dialog from Debrief, the dialog is all grey:
![image](https://user-images.githubusercontent.com/1108513/82565480-69185200-9b72-11ea-98bf-121a2f63b9f8.png)

If I expand the dialog, it appears at it should:
![image](https://user-images.githubusercontent.com/1108513/82565570-8f3df200-9b72-11ea-97ee-ef830efdeb4c.png)

I know it won't be easy for @saulhidalgoaular to fix if he can't reproduce it. I guess I'll have to act as `guinea pig`.  Oh, and hopefully Google can offer some assistance.

**Comment by helenayele** [comment]
@IanMayo  please verify this issue at your side, since I can't reproduce the original issue on my computer , can't verify it.

**Comment by IanMayo** [comment]
Yes, the blank panel is fixed:
![image](https://user-images.githubusercontent.com/1108513/82802691-32df1900-9e77-11ea-8b62-445bdc0ae013.png)
