### ISSUE TITLE
Pepys Import Dialog - can't reduce size

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4873]
Once the Pepys Import dialog is open, its size cannot be reduced.

It's bigger than it needs to be.  The minimum size appears to be 1200 * 850

A _realistic_ minimum size is probably more like 600 * 400.

**Comment by helenayele** [comment]
Verified - Now the size of the Pepys import dialog set to the minimum and able to resize its size too.
[![Image from Gyazo](https://i.gyazo.com/48e10dd7a44f14af6ff7cdac3828017f.gif)](https://gyazo.com/48e10dd7a44f14af6ff7cdac3828017f)
