### ISSUE TITLE
Pepys Database connection - better diagnostics

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4874]
I'm playing with connecting to different Pepys databases (SQLite and Postgres).

It would be useful if the dialog shown after "Connection test" showed the value of `PEPYS_CONFIG_FILE` variable. This would make me absolutely sure which config file was being used.

The file path/name would be visible whether the connection was successful for unsuccessful.

**Comment by helenayele** [comment]
1. When we have valid Papys config environment variable we get this dialog while testing connection:
[![Image from Gyazo](https://i.gyazo.com/bdc40bc44b119e7b2b1a500522bfba77.png)](https://gyazo.com/bdc40bc44b119e7b2b1a500522bfba77)

2. When we have a pepys config env. variable which points to an existing invalid file , we get this dialog:
[![Image from Gyazo](https://i.gyazo.com/b7d0a14a60bae43fccb5a779d79d4144.png)](https://gyazo.com/b7d0a14a60bae43fccb5a779d79d4144)

3. When we have a pepys config env. variable which points to unavailable file in the system, we get
[![Image from Gyazo](https://i.gyazo.com/8c4b3b1037a1cdc444d4659bab2a3dba.gif)](https://gyazo.com/8c4b3b1037a1cdc444d4659bab2a3dba)
Note here , it doesn't even open the Pepsy import dialog at all

4. When we don't have a pepys config env. variable at all , it uses the default file:
[![Image from Gyazo](https://i.gyazo.com/61e96a22e287819189141f26bc921ed0.png)](https://gyazo.com/61e96a22e287819189141f26bc921ed0)

- Verified.
