### ISSUE TITLE
TreeViewer in the Database Import Section with update highlighted problems

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#4878]
When we try to search a string that is contained several times in the same Treeİtem, the hıghlıghted ıtem ıs not updated.

https://gyazo.com/e2c862280cdd578ab6180e14cf8700cb

https://gyazo.com/2ec89a3085c4978fc80e71ec3a0a4a92

https://gyazo.com/2ec89a3085c4978fc80e71ec3a0a4a92

**Comment by helenayele** [comment]
Works fine now - Verified
