### ISSUE TITLE
Adding new position from Grid Editor

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4891]
With the grid editor, it's possible to view the positions for a track:
![image](https://user-images.githubusercontent.com/1108513/84792662-0ccb1580-afec-11ea-9af2-037644059275.png)

It's also possible to add new positions.  But, it's very difficult to edit the location on the new positions.

I tried this:
* go to the bottom of the grid editor (that's actually the oldest points, it's in reverse order)
* click on the `row selector` for a row, in the left-hand column
* click on `insert row`.  It will create a duplicate of the current row
* select the new row. (it may have an empty `label` field
* change the time, to put it back 30 seconds.
* now try to edit the location, to move it two minutes up/down, and two minutes to the left/right
* but, as I leave the field the value returns to its previous position

Note: a couple of times this worked ok. But, when I went to record it, it failed :-)

**Comment by saulhidalgoaular** [comment]
Hello @IanMayo .

I was able to replicate it, but I realized it that it happens when the Location is not in the correct format. For example, when It is written "8" in the minutes instead of writing "08", or any error in the format. If you consider it convenient, I could check the Location parser to make it more flexible to those inputs.

Regards.
Saul

**Comment by IanMayo** [comment]
Example of relaxed parser, that allows for spaces rather than leading zeros:
![grid_parse](https://user-images.githubusercontent.com/1108513/85399741-31287400-b54f-11ea-8673-40d3536929d6.gif)

**Comment by helenayele** [comment]
It accepts single digit values like 8, 9. , 1 etc , but if you insert 89, 78, any values greater than 60, it throws exceptions and filed it in separate bug #4898.
