### ISSUE TITLE
Support new file format

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4896]
Our users need to support a new file format.

The file format is detailed here:
https://docs.google.com/document/d/1rotbJ-yeSPKxcNND0v0JVF1LAh9VySVE9pNeC_ozz94/edit

We should create an importer in the `debrief.legacy` module, then support that importer in both Debrief and Debrief-Lite.

We can make the following assumptions about the format:
* there may be unexpected lines before, during, or after the lines of interest
* there may be multiple continuation lines for an entry. But, only the last "remarks" field may be extended.

**Comment by helenayele** [comment]
Able to support  Nisida file type with .txt extension in both full debrief and D-Lite.
## Full Debrief
[![Image from Gyazo](https://i.gyazo.com/1a6eb37fddd22b2192008c97583ff5c4.png)](https://gyazo.com/1a6eb37fddd22b2192008c97583ff5c4)
## D-Lite
[![Image from Gyazo](https://i.gyazo.com/1fa1f26d7165f927ded5f0c4e45b332b.png)](https://gyazo.com/1fa1f26d7165f927ded5f0c4e45b332b)
But in D-Lite the file name `mynisida`is not loaded. Is this expected ?
