### ISSUE TITLE
Color change in Merge Tracks

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4904]
"Do you know that when you Merge Track Segments – into new track (highlight infills) the track it produces is all the same colour."

I tried to reproduce this issue in `midflow2a.dpf` . When I merged the track legs into a new track, I got a plain black track.

![screencast](https://i.gyazo.com/4cc368cb54218aec5b2123ff3065639d.gif)

Note - in the above screencast I had modified the leg colors before doing the merge.

So, it looks like the 'merge' tracks operation needs to be modified to re-use the colors in the original TMA legs.

**Comment by IanMayo** [comment]
Ok. The analyst has found the solution himself.  The merged colors come from these Debrief preferences:
![image](https://user-images.githubusercontent.com/1108513/86221806-491a7c00-bb7d-11ea-9d8d-d77085b8c6ef.png)

After switching to a new PC, both of the colors are black for the user.  But, Debrief "appears" to set sensible defaults for them:
![image](https://user-images.githubusercontent.com/1108513/86222151-c3e39700-bb7d-11ea-917d-d10693e0173e.png)

We should:
* test that for a Debrief installation with cleared preferences, the default colors for these two are set to black
* fix the editors so that they are initialised with the colors provided above

@helenayele - there is an option in the "Run Configurations" to clear the workspace before running. This will force new defaults to be used:
![image](https://user-images.githubusercontent.com/1108513/86222378-0f964080-bb7e-11ea-8aeb-256edd7af07d.png)

**Comment by helenayele** [comment]
Steps to verify this issue are:
1. Launch Debrief by clearing the workspace 
2. Open midflow2a.dpf file
3. Change the colors of the first 3 legs from  Track:TMA..
4. Right click on them and invoke Merge track segments into new Tracks(highlight infills...
5. See that the color of the TMA segment , it uses the default color configured in preference page.
[![Image from Gyazo](https://i.gyazo.com/c0c135177eccd9b4cf4220443c3268b4.gif)](https://gyazo.com/c0c135177eccd9b4cf4220443c3268b4)
