### ISSUE TITLE
Export Narrative to MS Word

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4935]
As an ***analyst***, I wish to ***view a combined set of narratives, outside Debrief, while I am waiting for the track data to arrive & be processed***, in order to ***familiarise myself with what happened, and plan my analysis***

I expect **Apache POI-Word** is the best library to use for this task.

* [x] Add "Export to MS Word" button to Narrative Viewer in Full Debrief.
* [x] Re-use the existing "Export to WMF" icon, in `icons/16/ex_2word.png`
* [x] Create a `.docx` file. The filename will be the date-time of the first narrative entry, formatted as `yyyymmdd_hhmm`.
* [x] Put a single table in the document.  `Time` and `Entry` will always be present. Decide on whether to include `Source` and `Type` depending on if those columns are currently visible
* [x] Export all visible narrative entries (so use can use Outline view to decide what to include)
* [x] Popup file dialog to choose target directory.  The default should be the previous directory, if possible, otherwise the user's home folder.

_Just in case_ we ever want to support this in D-Lite, most functionality should be a in a non-UI class within `cmap.legacy` poss in new `MWC.Utilities.ReaderWriter.Word` package.  Maybe a `NarrativeWriter` class with this API:
```
    public void write(NarrativeWrapper narratives, boolean showSource, boolean showType, File targetDirectory);
```

**Comment by helenayele** [comment]
For narrative.rep file it switches type and entry columns while generating word document. But for narrative_large.rep file and other dpf files with narrative entries , it shows the correct contents. 
Here is narrative.rep file
[narrative.zip](https://github.com/debrief/debrief/files/5143578/narrative.zip)
[![Image from Gyazo](https://i.gyazo.com/60705580a4b2d76b44fe627887a414e3.png)](https://gyazo.com/60705580a4b2d76b44fe627887a414e3)
