### ISSUE TITLE
Outline view does't show shapes after copy and paste actions

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4937]
If we copy a shape and paste it in another folder, the outline view doesn't show it but it is being shown in map panel. 
But it shows the item in outline view if we cut and paste it.

And also we can't paste a shape after we copy it more than once. But we should be allowed to paste it as many times as possible once we copy it.

Here is the video:
[![Image from Gyazo](https://i.gyazo.com/22fc3af369366b9f61f50b33819d0ca4.gif)](https://gyazo.com/22fc3af369366b9f61f50b33819d0ca4)

Cut /paste action:
[![Image from Gyazo](https://i.gyazo.com/0d1f0226b90aeedc7853a8ea2181c19b.gif)](https://gyazo.com/0d1f0226b90aeedc7853a8ea2181c19b)

Copy and paste many times:
[![Image from Gyazo](https://i.gyazo.com/47ba803901647add4a3c927a2ce8aa8d.gif)](https://gyazo.com/47ba803901647add4a3c927a2ce8aa8d)

**Comment by ayeshare** [comment]
After undo and then redo more than one paste operation, the last pasted object is being repasted all the time.

**Comment by helenayele** [comment]
Yes that is correct
Steps:
1. Launch D-Lite
2. Insert rectangle and circle shapes on new layer called `A`
3. Cut and paste both shapes on Chart layer , first cut Rectangle and paste it then continue doing Circle shape
4. Select undo action so that the shapes will be in their original location
5. Select Redo again , see that only the last item which is Circle is pasted on the chart feature layer twice. The rectangle shape just disappears...
[![Image from Gyazo](https://i.gyazo.com/359f5133c3cd72c7e5a7ad9565841fbc.png)](https://gyazo.com/359f5133c3cd72c7e5a7ad9565841fbc)

**Comment by ayeshare** [comment]
@helenayele I have fixed this. On develop I cant replicate this. Please review

**Comment by helenayele** [comment]
Yes , I can't reproduce these issues on develop now also.
So closing...
