### ISSUE TITLE
Support for Antares format

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4940]
As a ***sea-rider*** I want to ***load and view Antares data in Debrief-Lite*** in order to ***view platform tracks from international partners***

We have been provided with this sample:
```
TRACK/DDHHMMZ/LAT-LONG/COURSE/SPEED/DEPTH//
```

The lat-long is constructed like this:
```
2512.0N-03010.5W
```

Note: the above is `25 degrees, 12.0 minutes North, 030 Degrees, 10.5 minutes West`.

The data comes in files with a `.txt` file suffix.  They contain no header lines or specific details in the filename.

To check if a file is an Antares file, we could just check if the file starts with `TRACK/`

The data-format doesn't include month or year.  The sea-rider will _most probably_ be receiving files that have been created on that day.  So, the import process should include a popup dialog to gather the month/year and track name, with the current month-year provided as default.

By default the track should be coloured `RED`, and have symbols shown at 15 minutes and labels at one hour.

**Comment by helenayele** [comment]
The Antares file format is imported and handled in both D-Lite and full debrief without any issues.
## D-Lite
[![Image from Gyazo](https://i.gyazo.com/eb0a18a358e035689424df591040d94d.gif)](https://gyazo.com/eb0a18a358e035689424df591040d94d)
## Full Debrief
[![Image from Gyazo](https://i.gyazo.com/ed4e65961b21feb00b42652cb515df1c.png)](https://gyazo.com/ed4e65961b21feb00b42652cb515df1c)

And when the systems get invalid antares files they show proper error messages.
[![Image from Gyazo](https://i.gyazo.com/19519e626743d3a54e6e2e587d2c2799.gif)](https://gyazo.com/19519e626743d3a54e6e2e587d2c2799)

[![Image from Gyazo](https://i.gyazo.com/50ceca0d0b73ed66448fb69e66ab4175.gif)](https://gyazo.com/50ceca0d0b73ed66448fb69e66ab4175)

Verified.
