### ISSUE TITLE
Export to GeoPDF - Phase 1: Static Tracks

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4949]
As an ***analyst*** I wish to ***provide an interactive track plot to sea-riders*** in order to ***let them do some simple analysis of the tracks***

The analysts want to deliver something more interactive than a PowerPoint slide or PDF analysis report.  (Yes, we did implement dynamic PDFs).  

The GeoPDF standard is a way of doing this. It's a PDF extension that includes the Projection details for the map, plus elements to add layers or lines/shapes to the image.

We're going to give analysts the ability to export the current view to a GeoPDF.  Analysts will typically have a chart image loaded, and some tracks.   We'll allow them to be implemented in 3 phases.  This issue just covers Phase 1:
Phase 1: static tracks plus background image
Phase 2: add ability to move through dynamic tracks with time
Phase 3: support for other annotations

Here is the big picture for the process of producing static tracks:
1. Loop through all tracks
    1. If track is visible, loop through all of its points
    3. Add point to line-array for that track
    4. If symbol is visible, add point to symbol-array for that track
    5. If label is visible, add point to label-array for that track
    6. Output arrays to GeoJSON file(s)
    7. Create GeoJSON file for track name lable
7. Produce list of chart images that are visible in this current view
8. Produce new TIFF copies of images, by stretching them to new projection
9. Collate `XML Composition File` that includes the above images & GeoJSON files
10. Call GDAL command ot process composition file, and produce new PDF file
11. Call system command to open PDF file.

This document includes the GeoJSON structures:
https://docs.google.com/document/d/1Wcj75NjeSYcEW2jzf0s8L-3H2MEVC1zDlyDgjrOMxSc/edit#heading=h.dabx1ro6vekm

Here is an example of an XML Configuration file:
https://github.com/debrief/GeoPDF/blob/master/TestXML_Final.xml

This repo contains examples of Debrief tracks output to GeoJSON to represent the various element types:
https://github.com/debrief/GeoPDF

Note: GeoTools does include two GeoJSON modules, though one is about to be deprecated. But, the GeoTools implementation relies on the data being stored as GeoTools features - which would require us to translate our data first. This GeoJSON library looks like it will be less trouble to adopt: https://github.com/ngageoint/simple-features-geojson-java

**Comment by IanMayo** [comment]
Further tasks:
* [ ] (temporarily) keep `/tmp` files, so they can be checked
* [ ] Add `INFO` statements to record instructions sent to command line (so they can be reproduced)
* [ ] Add `INFO` logging for important steps
* [ ] Include support for _Relative_ file paths (probably after `.exists()` fails)

**Comment by helenayele** [comment]
Able to export a track with background image as follows:
[![Image from Gyazo](https://i.gyazo.com/98ac23e0c11e3813e157d53af3c0b395.png)](https://gyazo.com/98ac23e0c11e3813e157d53af3c0b395)
But the positions' label is not exported.
