### ISSUE TITLE
Icons for Antares and Nisida files formats in D-Lite

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4950]
In Debrief-Lite we have buttons to open the File Dialog for the assorted file types.

Helen has pointed out that we don't have icons for Antares or Nisida.  We should.

I've added icons to Debrief-Lite at 16, 24 and 48 pixels.

**Comment by helenayele** [comment]
Thanks Ian for filing this.

**Comment by helenayele** [comment]
Now we have got Nisida and Antares action to import those file types in D-Lite.
[![Image from Gyazo](https://i.gyazo.com/07dd6606dc0cea73bbbdc91bce07debf.png)](https://gyazo.com/07dd6606dc0cea73bbbdc91bce07debf)
And we are able to import both file tpes:
[![Image from Gyazo](https://i.gyazo.com/58f8b9d64d42b8036e365efbaf5280cf.gif)](https://gyazo.com/58f8b9d64d42b8036e365efbaf5280cf)
[![Image from Gyazo](https://i.gyazo.com/8aa9655c4a695c69ff763c5dbf07b6db.gif)](https://gyazo.com/8aa9655c4a695c69ff763c5dbf07b6db)

Verified
