### ISSUE TITLE
Issues on Show source and show type options while changing the visibility of narrative entries

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4959]
When we change the visibility of the narrative entries from outline view, all the columns of the narrative entries in narrative viewer will be shown. But show source and show type options doesn't get updated or will not have the correct status.

### Steps to reproduce:
1. Open sample.dpf
2. Open narrative viewer
3. See that narrative viewer  is shown with all columns 
4. Uncheck `Show source` and `Show type` so that Source and Type columns will be hidden and it looks like [![Image from Gyazo](https://i.gyazo.com/2edd77af67e0c8c48def17d6e0431368.png)](https://gyazo.com/2edd77af67e0c8c48def17d6e0431368)
5. Go to in outline view and uncheck one of the narrative entries there
6. It shows both `source` and `Type` columns but if you check `show source` and `show type` they remain unchecked
[![Image from Gyazo](https://i.gyazo.com/78cd9a19e502de5633126faabbcb6286.gif)](https://gyazo.com/78cd9a19e502de5633126faabbcb6286)
7. And if you try to export to word doc , it doesn't show the source and type columns.
[![Image from Gyazo](https://i.gyazo.com/bd95c8a92edf338dcc8606c0b3c1a5fc.png)](https://gyazo.com/bd95c8a92edf338dcc8606c0b3c1a5fc). This is because `show source` and `show type` options are unchecked.

**Comment by ayeshare** [comment]
@IanMayo @helenayele I think when we change the visibility of a narrative entry, it should not cause the show source/type to change to default

**Comment by helenayele** [comment]
Okay much issues on this PR are resolved. The only remaining issue is when we change the visibility of narrative entry from outline view , the narrative viewer columns will get reset to the default state. And this is filed in separate bug #4970
So verified.
