### ISSUE TITLE
Export to GeoPDF - Phase 2: Dynamic Tracks

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4965]
Attached is an example of a Dynamic Track Plot.

The dynamic element is provided by storing each track as a series of blocks of data (layers). As the time controls are triggered by the user, Javascript code switches layers on and off.

Support for time is through slicing the track data into layers, each relating to a time period.

This task won't start until the `Tracks to GeoPDF` document has been updated to support this new data structure.

[Example_MovingButtons_v4.pdf](https://github.com/debrief/debrief/files/5187510/Example_MovingButtons_v4.pdf)

**Comment by saulhidalgoaular** [comment]
Covered in https://github.com/debrief/debrief/pull/4978
