### ISSUE TITLE
Export to GeoPDF - Phase 3: Multiple TIFF images

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4966]
It is most likely that the analyst will just be displaying a single TIFF images.

But:
1. Other TIFFs may be visible outside the current viewport
2. The analyst may wish to display the content of multiple TIFFs in the export GeoPDF.

For 1) we can loop through all visible GeoTiffs, and discount any that don't overlap the current viewport.  

But, if multiple are present, then under 2) we should pass them all to the `GDAL_Warp` command.

**Comment by helenayele** [comment]
1 . Able to export multiple tiffs from UKPlotWithGeoTiff.dpf file

2. Able to export tiff files in a current view port  only: tested with /UKPlot again be zooming out the first tiff file and got exported only the visible part of the plot. 

so Verified.
