### ISSUE TITLE
Export to GeoPDF - Phase 5 tracks with multiple colors

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4977]
It is possible to shade a Debrief track in different colors.  

The colors may be used to indicate when one platform is in contact with another, or to separate times when a platform is going above 10 knots.

It would be useful if these colors could be presented in the GeoPDF export

Note: this change may require the change in structure defined in #4973

**Comment by helenayele** [comment]
Now the exported Pdf file has all the colors that the file being exported has.
[![Image from Gyazo](https://i.gyazo.com/8f804fbbc951a945d12df1fd47d6c916.png)](https://gyazo.com/8f804fbbc951a945d12df1fd47d6c916)
Verified
