### ISSUE TITLE
Geo-PDF Warn users about performance issue when the track has more than 100 steps.

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#4986]

**Comment by helenayele** [comment]
@saulhidalgoaular / @IanMayo , any steps to verify this issue please?

**Comment by saulhidalgoaular** [comment]
Hello @helenayele 

Export to GeoPDF a track which has more than 100 steps. When you do it, you will receive a warning message.

To change the amount of steps, you can change the size of the steps in the TimeController, `small step` .

**Comment by helenayele** [comment]
After opening the example file attached in this PR , and change the small step interval to 5 minutes , I didn't get this dialog ,
[![Image from Gyazo](https://i.gyazo.com/9055f9fc2733bf70a499c29608d255d8.png)](https://gyazo.com/9055f9fc2733bf70a499c29608d255d8)
 But can we change the title of this dialog `My info` to other better title like "Too many Time steps" or any other better naming?

**Comment by saulhidalgoaular** [comment]
Hello @helenayele .

Regarding the test you mentioned, after changing the small step interval to 5 minutes, the total amount of steps is 80. That is why you didn't get the dialog. 

To increase the amount of steps, the step interval must be smaller. I mean, to complete all the track doing steps of 5 minutes is 80 steps, but with steps interval of 1 minute is around 400 steps.

**Comment by saulhidalgoaular** [comment]
I have changed the dialog title as indicated.

**Comment by helenayele** [comment]
Here is the title when a track has more than 100 steps:
[![Image from Gyazo](https://i.gyazo.com/852dfbbf5bcdcf61ddc370d3f6fa78be.png)](https://gyazo.com/852dfbbf5bcdcf61ddc370d3f6fa78be)

Verified.
