### ISSUE TITLE
GeoPDF export. Issue with duplicated timestamp

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4988]
I'm playing with exporting to GeoPDF.  I've configured a scenario that breaks the export.

It's a strange scenario, but it gives us an opportunity to make things more robust.

Steps to reproduce:
* open `PlotWithGeoTiff.dpf`
* resample `COLLINGWOOD` to 30 second positions
* Export GeoPDF

I think the export fails because multiple data-files have the same name. This is because of the date format in use.

I _think_ that if the date format is modified to include seconds, the export works.

IMHO the issue could be fixed by using the DTG (long millis) in the filename, rather than the formatted string.

**Comment by IanMayo** [comment]
Note: there's a twin focus here.  It's partly to resolve the file-labelling issue.

But, it's also to understand what problem the original issue caused in the PDF document, and to see if we can make our code more able to handle inconsistent/corrupted input data.

I've attached a corrupted PDF (`14.pdf`) .  The "working" PDF (`15.pdf`) is about 500Kb is much larger, suggesting the issue is in the export process, rather than the pdf rendering.

[14.pdf](https://github.com/debrief/debrief/files/5311797/14.pdf)
[15.pdf](https://github.com/debrief/debrief/files/5311800/15.pdf)

**Comment by helenayele** [comment]
Able to export the pdf after resampling the tracks. 
[![Image from Gyazo](https://i.gyazo.com/6437f1cbee859371a3b93e086ff4cfad.gif)](https://gyazo.com/6437f1cbee859371a3b93e086ff4cfad)

Verified
