### ISSUE TITLE
GeoPDF Export - put all files for one export into single folder

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4991]
Currently in the export we don't delete the files used in the export.

But, they all sit in the top-level of `temp`.

I think it would be better if we started by creating a unique folder in `temp`, then put our working files into there.  That will make it easier for us (or analysts) to package up a set of data-files for subsequent analysis.

**Comment by helenayele** [comment]
Okay now for each export to pdf action  it will create a folder in temp files and put all geojson files and xml files there.
[![Image from Gyazo](https://i.gyazo.com/2955098b1ee47f91f925c9ac7b1aec24.png)](https://gyazo.com/2955098b1ee47f91f925c9ac7b1aec24)

Verified.
