### ISSUE TITLE
GeoPDF Export - failing with time steps under one minute

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4993]
I have `PlotWithGeoTiff.dpf` open, in the `origin/4988_renaming_geojson_temporal_files` branch.

I want to experiment with time steps shorter than one minute.  This track only has positions at one minute, so that probably won't work.  So, I resampled both tracks to 30 second intervals (to give tracks with 47 & 53 positions).

I did export to GeoPDF, all worked fine.

Then I switched small step to 30 seconds, and exported again.  The export completed, but the file wouldn't open.  I didn't see any GDAL errors.

I switched back to small step of one minute, and it worked ok.

This may be easier to explore if we package up the source files into one folder first, as requested in #4991

**Comment by helenayele** [comment]
@IanMayo /@saulhidalgoaular  would you please attach PlotWithGeoTiff.dpf , the track with positions at one minute?

**Comment by IanMayo** [comment]
@helenayele - I'm pretty sure it's the one in `sample_data`.

**Comment by helenayele** [comment]
Okay thanks

**Comment by helenayele** [comment]
We can generate a pdf and open and play a track with 15 seconds, 30 seconds small step values.
[![Image from Gyazo](https://i.gyazo.com/498a834539f3076194a62c49ce4f5637.gif)](https://gyazo.com/498a834539f3076194a62c49ce4f5637)
But when with 1 sec small step value the generated pdf takes longer time while opening it and after opening it, when I try to play the track, the pdf will goes to not responding state.
[![Image from Gyazo](https://i.gyazo.com/42e3eedee08ea0731bb13f963095ff56.png)](https://gyazo.com/42e3eedee08ea0731bb13f963095ff56)
Verified.
