### ISSUE TITLE
Pepys Import - Contacts import bug

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#5009]
In the import of contacts, destination track is incorrectly calculated.
It must be Contact, go to Sensor then Platform.

**Comment by saulhidalgoaular** [comment]
I am not sure if it is really a bug or a feature specified previously, but before importing, It is checking that there is a BaseLayer with the name of the reference id in the Datafile.

![image](https://user-images.githubusercontent.com/11049943/97485211-1da47400-195a-11eb-88b7-4725fa2e69f7.png)

It looks too specific to be a bug...

Is it correct @IanMayo ?

**Comment by IanMayo** [comment]
Ok, I see what it's doing.

It's putting all of the contents of this DataFile into one Folder.  So there contact goes onto a track, which goes into a folder for that datafile.

It seems sensible enough.

Note: in the other PR, we're moving to having `Name + Identifier` as the name for Pepys platforms in Debrief.  The code above should probably be modified to construct the platform name to search for using name and identifier (line 90 above).

It would be _neat_ if we encapsulated the creation of Track names in the import process in a single helper function.  So we pass `getPlatform()` to a method, and inside that method it generates the Debrief name for that platform, using name+id (or some other pattern in the future).

**Comment by IanMayo** [comment]
Close - I think this is now sorted.
