### ISSUE TITLE
Update to new GDAL

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#5013]
Our `gdal_create` command is included in the new (3.2.0) release of GDAL.

We should use it in our Debrief release.

**Comment by saulhidalgoaular** [comment]
Good afternoon.

Currently the binaries that Debrief includes for Windows are from GISInternals https://www.gisinternals.com/release.php, nightly development build. 

However, they have for now only the version 3.1.3 as stable. I will update it as soon as it is available.

Regarding the unit tests for Linux (Travis-Ci) , Gdal is getting compiled from sources directly from github.
