### ISSUE TITLE
Build failing, since EASE repo moved

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#5019]
The Travis build is failing:
![image](https://user-images.githubusercontent.com/1108513/98802022-94397b00-240a-11eb-9613-fd0dda5652f6.png)

This is because the EASE repo has moved:
https://www.eclipse.org/lists/ease-dev/msg00840.html

We should update our build to use the new repo.

**Comment by saulhidalgoaular** [comment]
Fixed at #5020
