### ISSUE TITLE
Adding unit tests for Debrief

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#5022]
Adding unit tests for Eclipse Ease integration with Debrief.

**Comment by IanMayo** [comment]
@saulhidalgoaular - could you give a bit more detail on what's happening here?

Is this the change to ensure we deliver EASE Unit-Test framework in Debrief installs?

**Comment by saulhidalgoaular** [comment]
Good morning Ian.

I conclude yes. I have added the libraries mentioned by Christian. I didn't add them the first time because they were moved to a different and I thought they were not the same, but after the email I realized they were the same.

I had to upgrade osgi.ee from Java 8 to Java 11, because it was giving compilation error.

The other change in the manifest for Debrief lite was suggested by Eclipse
