### ISSUE TITLE
Pepys Database Import crashing on `Apply`

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#5025]
Users are connecting to a PostGIS database.

They apply a time filter, and press `Apply`.  Debrief hangs.  Nothing gets written to the Error Log.

We should put some (more) error trapping around the `Apply` button operation.

1. The problem _could_ be the volume of data. 
2. Or, the problem _could_ be something specific to the currently loaded data.

The database contains around 150 datafiles.  To help with option 1) we should create/load - say, 200 datafiles to PostGIS, and then connect to it. (Ian can do that).

For option 2) we should inspect the code,  include some discrete logging statements, and check we have exception handling.

**Comment by helenayele** [comment]
With the new fix, to load the `pepys_Test.sqlite` db , after selecting apply button, it took me around 3 seconds.
[![Image from Gyazo](https://i.gyazo.com/808e8e121f8a87425ebf8b608f26f367.gif)](https://gyazo.com/808e8e121f8a87425ebf8b608f26f367)
And I can see the query log in the eclipse console.
Query: SELECT NTP.comment_id AS NTQ, .....

**Comment by IanMayo** [comment]
@saulhidalgoaular - the last line that gets produced is `Starting to create text filter`:
![Capture_Error Log 2](https://user-images.githubusercontent.com/1108513/100446165-3a8dad80-30a6-11eb-948c-f1101632b1c2.png)

**Comment by IanMayo** [comment]
Inspecting the code suggests the error is occurring here:
![image](https://user-images.githubusercontent.com/1108513/100450373-6f513300-30ad-11eb-962c-5bea6465d71f.png)

**Comment by IanMayo** [comment]
Ok. In December we gained an understanding of the issue here.  The "Search" operation was downloading all matching data into Debrief, from which the search results were displayed.  Once the backend database got to 1.5 million rows, this was too much for Debrief to store - resulting in out of memory issues.
So, we need to refactor the Pepys import as follows:
1. for search operation, request list of matching datafiles from database (not measurements)
2. once user selects datafiles of interest, and pressed "Apply", pull matching measurements into Debrief, and create as Debrief objects.

Here is the first query. It includes examples of time/space filters at the start.
[Measurements-v0.5.txt](https://github.com/debrief/debrief/files/5795902/Measurements-v0.5.txt)

Here are examples of the `Measurements` queries used in the second phase.
[States_DemoScript_v0.3f.txt](https://github.com/debrief/debrief/files/5795908/States_DemoScript_v0.3f.txt)
[Contacts_DemoScript_v0.3f.txt](https://github.com/debrief/debrief/files/5795910/Contacts_DemoScript_v0.3f.txt)
[Comments_DemoScript_v0.3f.txt](https://github.com/debrief/debrief/files/5795911/Comments_DemoScript_v0.3f.txt)

**Comment by IanMayo** [comment]
Updated versions of scripts.

[Measurements-v0.6.txt](https://github.com/debrief/debrief/files/5831826/Measurements-v0.6.txt)
[States_DemoScript_v0.5.txt](https://github.com/debrief/debrief/files/5831829/States_DemoScript_v0.5.txt)
[Comments_DemoScript_v0.5.txt](https://github.com/debrief/debrief/files/5831827/Comments_DemoScript_v0.5.txt)
[Contacts_DemoScript_v0.5.txt](https://github.com/debrief/debrief/files/5831828/Contacts_DemoScript_v0.5.txt)

**Comment by arunlal-v** [comment]
Hey Ian, just wanted to check if we were able to integrate those queries.
