### ISSUE TITLE
Need to be able to clear spatial filter in `Pepys Import` dialog

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#5026]
We can populate the spatial filter by typing in values, or by using the current viewport.

But, it's cumbersome to clear the filter.

![image](https://user-images.githubusercontent.com/1108513/100357262-57fe4100-2fec-11eb-848d-7f1cc7dcfe46.png)

We should add a "Clear" button at the bottom left of the `Area` panel.

**Comment by helenayele** [comment]
Now clear button is added and working fine.

[![Image from Gyazo](https://i.gyazo.com/5f628afb5f886e5e3f6b977423edc601.gif)](https://gyazo.com/5f628afb5f886e5e3f6b977423edc601)
Verified
