### ISSUE TITLE
Change pepys variables in the view layer to final

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#5034]
Change pepys variables in the view layer to final

https://github.com/debrief/debrief/pull/5033#discussion_r531493683

**Comment by helenayele** [comment]
Pepys import dialog works fine
[![Image from Gyazo](https://i.gyazo.com/b4cfc780a9af5315967ae17d6b784030.png)](https://gyazo.com/b4cfc780a9af5315967ae17d6b784030)

[![Image from Gyazo](https://i.gyazo.com/8e0cb2da63700b3f2b04f398f441ac49.png)](https://gyazo.com/8e0cb2da63700b3f2b04f398f441ac49)

Verified
