### ISSUE TITLE
Include Pepys database URL in "Test connection" dialog

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#5037]
It would be useful to have confirmation of which database Debrief is connected to.

The contents of `db_name` would be enough to double-check where Debrief is connecting to.

**Comment by helenayele** [comment]
Now db_name , Database Type and  Database host are added on Test Connection dialog.
[![Image from Gyazo](https://i.gyazo.com/5ab29d3d4ed0d4fbc70262643b112fa2.png)](https://gyazo.com/5ab29d3d4ed0d4fbc70262643b112fa2)
Verified
