### ISSUE TITLE
SWTBot UI tests

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#505]
_[Migrated from Assembla ticket [507](https://www.assembla.com/spaces/Debrief/tickets/507) - reported by @IanMayo on 2013-10-18 18:27:00]_

"SWTBot integrates with Eclipse PDE, Eclipse headless testing framework, Ant and Tycho, so it's easy to use in your IDE and Headless Builds (as part of a CI job for example)."

"Starting from version 2.1.0, SWTBot also provide a Test Recorder and Generator that you can use to generate your test case simply by recording the UI actions as an end-user would perform them. This is really helpful to get quickly a first sketch of your SWTBot scenario and reduce costs of writing tests."

this appears to be an easy/cheap way to produce a set of tests that verify Debrief high level functionality.  In my experience, it's rarely the "maths" elements that break. More often it's the plugin integration & comms.

This ticket is to investigate integration of UI tests into Debrief's tycho build.

**Comment by IanMayo** [comment]
Close. This issue is also covered in #4083
