### ISSUE TITLE
Create deployable instance in PR builds

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#5050]
In another project I maintain, a deployable instances gets created as an artefact:
![image](https://user-images.githubusercontent.com/1108513/109300849-fe95f000-782e-11eb-8477-ca03988f27a6.png)

I believe this is performed by this code:
![image](https://user-images.githubusercontent.com/1108513/109300965-25542680-782f-11eb-95f4-22bd9bfb12b4.png)

So, if a build fails to pass the test for "Release", it would be good if we could create it as an artefact.  Well, ideally we would make all of the files we normally release into these artefacts.

**Comment by ayeshare** [comment]
@IanMayo I was looking at upload-artifact action.  Thanks.

**Comment by IanMayo** [comment]
There's an outstanding of this issue here: https://github.com/debrief/debrief/pull/5052#issuecomment-796665142

**Comment by ayeshare** [comment]
@IanMayo  Fixed now
