### ISSUE TITLE
Pepys import performance

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#5051]
I'm importing a datafile with 4 points:
![image](https://user-images.githubusercontent.com/1108513/109310254-3192b080-783c-11eb-9415-0c342a8fd3ef.png)

The data takes 9 seconds to load:
![screencast](https://i.gyazo.com/34270ee84c4313edc04ba8eb5659b7eb.gif)
It would be useful to understand what is happening in this time, and to see if any bottlenecks can be resolved.

We do have our licences for Yourkit Java Profiler, if you think that will help.

This larger file (10k) points takes 14 seconds to load:
![image](https://user-images.githubusercontent.com/1108513/109311448-c1852a00-783d-11eb-81e3-8431318c77ba.png)

**Comment by saulhidalgoaular** [comment]
Hello @IanMayo .

I have debugged the performance issue manually (without Yourkit profiler, because my license is expired), and around 80 or 90% of the time is consumed by the query.

I am copying here the query that runs with that import using stored procedures.
`
select state_id, state_time as time, sensor_name, platform_name, platformtype_name as platform_type, nationality_name, state_location as location, elevation, heading, course, speed, reference from pepys.states_for ('2001-05-13 13:21:37.000000', '2021-05-13 13:21:37.000000', null, array['4aabc7a7-3f7d-49d4-ab2f-b011307d7e3d'], array['bf8cb58d-78e3-4539-9fc0-6d276b57fa91'], array['a85858c8-6e7c-4af8-be4a-b237ebac0d1e'])`

If you want me to take a deeper look into it, I would be happy to do it.

**Comment by IanMayo** [comment]
Thanks @saulhidalgoaular  - I've passed the issue to Arunlal, to consider here: https://github.com/debrief/pepys-import/issues/913

**Comment by IanMayo** [comment]
Hello @saulhidalgoaular - Arunlal thinks he has reduced the time taken for the query from 6 seconds down to 0.6 seconds, which is great.  
I've tried a larger query, with 10k records:
![image](https://user-images.githubusercontent.com/1108513/118245964-4e34a100-b499-11eb-95d2-2e7478a57bec.png)

This takes much longer. No surprise there :-)

But, I'm keen to double-check that the time is spent in PostGres, and not in Debrief.  There have been occasions over the years when we have code that takes O(n ^ 2) - getting slower and slower for larger files.

Would you mind investigating this please?

**Comment by arunlal-v** [comment]
Hey @saulhidalgoaular, need another info to proceed with issue analysis for debrief/pepys-import#913.

Can you share the query (along with actual parameters) that will be generated if a user ticks BUTE2_UK(58037) and SENSOR-1 (46084) with respect to the following image, and then clicks on import?

![image](https://user-images.githubusercontent.com/77854924/118271097-7bf00900-b4de-11eb-89c0-5e4041064e95.png)

**Comment by IanMayo** [comment]
Here you go @arunlal-v :
```
about to list all:select state_id, state_time as time, sensor_name, platform_name, platformtype_name as platform_type, nationality_name, state_location as location, elevation, heading, course, speed, reference from pepys.states_for (?, ?, ?, ?, ?, ?)
[2001-05-14 12:30:17.000000, 2021-05-14 12:30:17.000000, null, [86eca7cb-0e69-4ee5-bb24-c655b17039ca, 86eca7cb-0e69-4ee5-bb24-c655b17039ca, 86eca7cb-0e69-4ee5-bb24-c655b17039ca, 86eca7cb-0e69-4ee5-bb24-c655b17039ca, 99249268-72cf-4e9f-bc1a-512a481760ed, 99249268-72cf-4e9f-bc1a-512a481760ed, 99249268-72cf-4e9f-bc1a-512a481760ed, 99249268-72cf-4e9f-bc1a-512a481760ed, 99249268-72cf-4e9f-bc1a-512a481760ed], [42c00877-7193-4cd8-bd44-f7c94b6cbfb3, e4545cfb-7a87-492d-b1ea-9960ac92f74a, d156c867-d6e8-4efb-9e21-646e1e8ac0c6, 18938505-682a-4c9b-b25f-8a0c160637aa, 6f4b1d18-f0dd-4a83-880b-fae4ab315c5d, f8ad3e18-4cff-449e-930f-b4e2b888c505, 3c762272-b993-4ee6-b367-f681122eaf58, b2d0a55b-49ff-449e-bcb8-da3432e31e9e, 48658028-e570-458f-b670-f81ea11c07ef], [063a47d8-9b51-408a-af7e-27c5cded2bd8, 063a47d8-9b51-408a-af7e-27c5cded2bd8, 063a47d8-9b51-408a-af7e-27c5cded2bd8, 063a47d8-9b51-408a-af7e-27c5cded2bd8, 58aeb5dc-3d7d-450a-bd55-4d09925bd4bb, 58aeb5dc-3d7d-450a-bd55-4d09925bd4bb, 58aeb5dc-3d7d-450a-bd55-4d09925bd4bb, 58aeb5dc-3d7d-450a-bd55-4d09925bd4bb, 58aeb5dc-3d7d-450a-bd55-4d09925bd4bb]]
select state_id, state_time as time, sensor_name, platform_name, platformtype_name as platform_type, nationality_name, state_location as location, elevation, heading, course, speed, reference from pepys.states_for (?, ?, ?, ?, ?, ?)


```

**Comment by IanMayo** [comment]
Aah, @saulhidalgoaular, @arunlal-v has a theory.  Python can retrieve 11k records in 4 seconds.

But, our ORM conversion takes 3.5 minutes.  Are you able to drill down into the code to determine how long it takes to get the query results, vs how long it takes for the ORM to run?

If the ORM is very expensive, maybe we need to consider one/more of these:
* don't use ORM. Manually parse the fields of interest (at least for `State` queries)
* for manually parsed data, only parse the minimum fields at load (time, location). Use lazy loading of course/speed/other fields.
* page the SQL `state_for` calls, so we can display genuine %age progress to the analyst - though it would still be good to make great reduction in processing time.

**Comment by arunlal-v** [comment]
>Aah, @saulhidalgoaular, @arunlal-v has a theory. ~~Python~~ can retrieve 11k records in 4 seconds.

Making a minor correction here. The retrieval was from **DBeaver SQL client - 7.3.0**. The total payload received was of 3.4 MB size, and had 11.5 K records.

![dbeaver](https://user-images.githubusercontent.com/77854924/118282133-9381be80-b4eb-11eb-98f0-ba7c28e6760a.png)

**Comment by arunlal-v** [comment]
> Here you go @arunlal-v:

@IanMayo, This is the formatted input.

**Start_Time**: 2001-05-14 12:30:17.000000
**End_Time**: 2021-05-14 12:30:17.000000
**Location**: null
**Sensor Ids**: [
86eca7cb-0e69-4ee5-bb24-c655b17039ca, 
86eca7cb-0e69-4ee5-bb24-c655b17039ca, 
86eca7cb-0e69-4ee5-bb24-c655b17039ca, 
86eca7cb-0e69-4ee5-bb24-c655b17039ca, 
99249268-72cf-4e9f-bc1a-512a481760ed, 
99249268-72cf-4e9f-bc1a-512a481760ed, 
99249268-72cf-4e9f-bc1a-512a481760ed, 
99249268-72cf-4e9f-bc1a-512a481760ed, 
99249268-72cf-4e9f-bc1a-512a481760ed
]
**Source Ids**: [
42c00877-7193-4cd8-bd44-f7c94b6cbfb3, 
e4545cfb-7a87-492d-b1ea-9960ac92f74a, 
d156c867-d6e8-4efb-9e21-646e1e8ac0c6, 
18938505-682a-4c9b-b25f-8a0c160637aa, 
6f4b1d18-f0dd-4a83-880b-fae4ab315c5d, 
f8ad3e18-4cff-449e-930f-b4e2b888c505, 
3c762272-b993-4ee6-b367-f681122eaf58, 
b2d0a55b-49ff-449e-bcb8-da3432e31e9e, 
48658028-e570-458f-b670-f81ea11c07ef
]
**Platform Ids**: [
063a47d8-9b51-408a-af7e-27c5cded2bd8
063a47d8-9b51-408a-af7e-27c5cded2bd8
063a47d8-9b51-408a-af7e-27c5cded2bd8
063a47d8-9b51-408a-af7e-27c5cded2bd8
58aeb5dc-3d7d-450a-bd55-4d09925bd4bb
58aeb5dc-3d7d-450a-bd55-4d09925bd4bb
58aeb5dc-3d7d-450a-bd55-4d09925bd4bb
58aeb5dc-3d7d-450a-bd55-4d09925bd4bb
58aeb5dc-3d7d-450a-bd55-4d09925bd4bb
]

This looks good. Have following items to clarify.

1) Did you happen to tick any **Source Ids**?
2) We should be avoiding duplicate parameter values. (like in Sensors and Platforms)

**Comment by arunlal-v** [comment]
Please ignore point 1 in my previous comment. **Source Ids** would always be selected.

**Comment by arunlal-v** [comment]
@saulhidalgoaular, please hold off on item 2 in https://github.com/debrief/debrief/issues/5051#issuecomment-841292545. This might require a change in how input is passed to the function. I'll inform in sometime.

**Comment by arunlal-v** [comment]
> @saulhidalgoaular, please hold off on item 2 in [#5051 (comment)](https://github.com/debrief/debrief/issues/5051#issuecomment-841292545). This might require a change in how input is passed to the function. I'll inform in sometime.

Task https://github.com/debrief/debrief/issues/5107 is raised to track this.

**Comment by arunlal-v** [comment]
@saulhidalgoaular, Are the sensor_ids, platform_ids, and source_ids mentioned https://github.com/debrief/debrief/issues/5051#issuecomment-841292545 in the same order and combination as selected in the UI filters?

In other terms,  can these three arrays be arranged to form the exact tree representation that was selected in the UI if we stack them side by side?

**Comment by saulhidalgoaular** [comment]
Good afternoon @arunlal-v 

Yes, I think yes. I am adding the sensors_ids, platforms_ids and source_ids according to the UI tree filter. I can check it deeper thou.

If you think adding duplicated values is wrong, I can remove them. It is a small change.

**Comment by arunlal-v** [comment]
Thanks @saulhidalgoaular. I'm confirming with @IanMayo on the behaviour of the query as this function might be used outside Debrief as well. I'll let you know once the input format is finalised.
