### ISSUE TITLE
Unable to run maven locally

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#5055]
I run this command to update POM versions for each new release:
```
mvn org.eclipse.tycho:tycho-versions-plugin:update-pom
```

I've recently rebuilt my PC, and now it doesn't work (log below). I think it has an unnecessary JDK8 dependency.  My PC is currently running AdoptOpenJDK 11.

I tried to fix it, but failed. However, I think it's down to an entry in the target-platform definition.  I think we need to update the entries.  Or, find where the Java8 dependency comes from.

```
./update_pom.sh 
[INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: org.mwc.debrief:org.freehep:1.0.10 @ /Users/ian/git/debrief/org.freehep/pom.xml
[INFO] Fetching p2.index from https://download.eclipse.org/releases/2019-06/ (122B)
[INFO] Adding repository https://download.eclipse.org/releases/2019-06
[INFO] Fetching p2.index from https://download.eclipse.org/technology/epp/packages/2019-06/ (142B)
[INFO] Fetching p2.index from https://download.eclipse.org/technology/epp/packages/2019-06/ (142B)
[INFO] Fetching p2.index from https://download.eclipse.org/releases/2019-06/201906191000/ (142B)
[INFO] Fetching p2.index from https://download.eclipse.org/releases/2019-06/201906191000/ (142B)
Mar 19, 2021 3:54:35 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://download.eclipse.org:443: The target server failed to respond
Mar 19, 2021 3:54:35 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://download.eclipse.org:443
[INFO] Adding repository https://download.eclipse.org/ease/release/latest
[INFO] Fetching p2.index from http://download.eclipse.org/nebula/releases/2.2.0/ (172B)
[INFO] Fetching p2.index from http://download.eclipse.org/nebula/releases/2.2.0/ (172B)
[INFO] Adding repository http://download.eclipse.org/nebula/releases/2.2.0
[INFO] Fetching p2.index from http://download.eclipse.org/webtools/repository/2019-06/ (130B)
[INFO] Fetching p2.index from http://download.eclipse.org/webtools/repository/2019-06/ (130B)
[INFO] Adding repository http://download.eclipse.org/webtools/repository/2019-06
[INFO] Fetching p2.index from https://download.eclipse.org/webtools/downloads/drops/R3.14.0/R-3.14.0-20190612230649/repository/ (172B)
[INFO] Fetching p2.index from https://download.eclipse.org/webtools/downloads/drops/R3.14.0/R-3.14.0-20190612230649/repository/ (172B)
[INFO] Resolving dependencies of MavenProject: org.mwc.debrief:org.freehep:1.0.10 @ /Users/ian/git/debrief/org.freehep/pom.xml
[ERROR] Cannot resolve target definition:
[ERROR]   Software being installed: org.eclipse.wst.xml_ui.feature.feature.group 3.14.0.v201905291408
[ERROR]   Missing requirement: org.eclipse.core.jobs 3.10.400.v20190506-1457 requires 'osgi.ee; (&(osgi.ee=JavaSE)(version=1.8))' but it could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.core.runtime 3.15.300.v20190508-0543 depends on: osgi.bundle; org.eclipse.core.jobs [3.10.0,4.0.0)
[ERROR]   Cannot satisfy dependency: org.eclipse.jem.util 2.1.201.v201903222010 depends on: osgi.bundle; org.eclipse.core.runtime [3.4.0,4.0.0)
[ERROR]   Cannot satisfy dependency: org.eclipse.wst.common.emfworkbench.integration 1.2.101.v201903222010 depends on: osgi.bundle; org.eclipse.jem.util [2.1.0,3.0.0)
[ERROR]   Cannot satisfy dependency: org.eclipse.wst.common_core.feature.feature.group 3.10.100.v201904082145 depends on: org.eclipse.equinox.p2.iu; org.eclipse.wst.common.emfworkbench.integration [1.2.101.v201903222010,1.2.101.v201903222010]
[ERROR]   Cannot satisfy dependency: org.eclipse.wst.common_ui.feature.feature.group 3.11.0.v201905071717 depends on: org.eclipse.equinox.p2.iu; org.eclipse.wst.common_core.feature.feature.group 0.0.0
[ERROR]   Cannot satisfy dependency: org.eclipse.wst.xml_ui.feature.feature.group 3.14.0.v201905291408 depends on: org.eclipse.equinox.p2.iu; org.eclipse.wst.common_ui.feature.feature.group 0.0.0
[ERROR] 
[ERROR] Failed to resolve target definition /Users/ian/git/debrief/org.mwc.debrief.targetplatforms/eclipse-latest.target: See log for details -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

**Comment by ayeshare** [comment]
@IanMayo from the logs it appears the problem is with the org.eclipse.core.jobs

org.eclipse.core.jobs 3.10.400.v20190506-1457 requires 'osgi.ee; (&(osgi.ee=JavaSE)(version=1.8))'

I will take a deeper look into it soon.

**Comment by ayeshare** [comment]
@IanMayo Here is the manifest of org.eclipse.core.jobs.  The execution environment for this is 1.8.

Manifest-Version: 1.0
Automatic-Module-Name: org.eclipse.core.jobs
Bundle-SymbolicName: org.eclipse.core.jobs; singleton:=true
Built-By: genie.releng
Require-Bundle: org.eclipse.equinox.common;bundle-version="[3.8.0,4.0.
 0)"
Bundle-ManifestVersion: 2
Bundle-RequiredExecutionEnvironment: **JavaSE-1.8**
Bundle-ActivationPolicy: lazy
Eclipse-SourceReferences: scm:git:git://git.eclipse.org/gitroot/platfo
 rm/eclipse.platform.runtime.git;path="bundles/org.eclipse.core.jobs";
 tag="I20190508-0150";commitId=ad3f044ea5848ba96e91ccdf022790980f71487
 b

**Comment by IanMayo** [comment]
So, do we update the version of that plugin?

**Comment by ayeshare** [comment]
@IanMayo I tried downloading and installing the latest version of eclipse, it comes with a jre.  See attached image.  Upgrading to the newer version of eclipse could solve the problem

![image](https://user-images.githubusercontent.com/38917949/112500758-ab23ad00-8dae-11eb-97dc-684cbff5a052.png)

**Comment by IanMayo** [comment]
Hmm, won't `target-platforms` still try to pull in the old lib, with the old dependency?

**Comment by IanMayo** [comment]
Note: I am running 2020-12 version of Eclipse (I had to rebuild my PC a couple of weeks ago)

**Comment by ayeshare** [comment]
@IanMayo the problem is in org.eclipse.core.jobs which has a dependency of javase1.8 for execution environment.  Since the new version comes with jdk12, this dependency might not be there.  Target Platforms we are setting in debrief.product file which is all pointing to jdk11 itself.  I dont see a reference to jdk1.8 in our codebase

**Comment by IanMayo** [comment]
Thanks for that @ayeshare .

Are you able to run `mvn clean verify` on your machine?   If it works for you then I'm happy for us to try to identify what is preventing mine from building.

But, if it's broken for you in the same way mine is, then I think we may have to update our build requirements to jdk12.

**Comment by ayeshare** [comment]
ok i will try that after removing all other versions of jdk

**Comment by IanMayo** [comment]
Fixed, thanks to @theanuradha
