### ISSUE TITLE
Error in path validation for the pptx master template.

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#5099]
In the preference section, there is a bug that after changing any property, it doesn't recognize the original pptx master template path like a valid path. 

More information about it here:
https://github.com/debrief/debrief/pull/5085#issuecomment-840558806

**Comment by IanMayo** [comment]
This is a high priority one, please @saulhidalgoaular  - since it affects the usage of the `Stored functions` toggle preference.
