### ISSUE TITLE
Investigate scripting support

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#511]
_[Migrated from Assembla ticket [513](https://www.assembla.com/spaces/Debrief/tickets/513) - reported by @IanMayo on 2013-10-26 12:53:05]_

We've got an existing (but still new) ticket for geospatial operations.

An alternate strategy for providing ad-hoc extensibility in Debrief could be to introduce support for scripting. Potentially using an emerging Eclipse scripting environment: http://codeandme.blogspot.co.uk/2013/10/eclipse-scripting-on-steroids.html

Use Cases:
- apply some custom change to the selected objects
- apply some change to the objects in a particular region
- generate a range of points at some set frequency
- perform some "standard plotting" to one or more tracks

Challenges:
- get at the current plot
- get at the current selection
- retrieve the current time / time period
- UI recording would be good

This should be investigated once the eScript project matures.    I expect that @ed.butcher would be most interested...

Oct 2014 update: The EASE project appears to have some momentum:
http://codeandme.blogspot.co.uk/2014/10/writing-modules-for-ease.html
## UI thoughts

I guess we have two possible modes of use. 
1. The script is a standalone entity, which sits in it's own editor at the centre of the editor pane
2. The script is a child of a plot file, so we would interact with it via a view

I guess there's a 1/2 way house.  A "script browser" view shows the following:
- scripts at a network location
- scripts installed in this current IDE (in user prefs folder)
- scripts within the current plot

We then have a "Script editor" view that shows the contents of the "Script browser".

Hopefully one or both of these UI components could come from the EASE project.

**Comment by IanMayo** [comment]
I've just been to an Eclipse EASE presentation.  It makes sense, and could certainly be included, providing we can hide it from "normal" users.

It's worth talking through some use cases with @ed-butcher , so it's clear which Debrief objects/models should be made visible.

**Comment by IanMayo** [comment]
Done, in #2888
