### ISSUE TITLE
Update measurement queries

### ISSUE THREAD

**Issue by arunlal-v** [debrief/debrief#5111]
@saulhidalgoaular, please update measurement queries by applying the below patch.

[ApplyDiff.txt](https://github.com/debrief/debrief/files/6502636/ApplyDiff.txt)

**Comment by IanMayo** [comment]
Thanks @arunlal-v 
1.  Just as "belt and braces", could you attach the 3 text files in a zip-file?
2. To keep the Debrief audit history, could you give a link/URL/description to what triggered these changes?

**Comment by arunlal-v** [comment]
1) Attached
[scripts.tar.gz](https://github.com/debrief/debrief/files/6502694/scripts.tar.gz)
2) These changes were required as 
        a) the measurement functions were changed for performance (pepys-import#914)
        b) debrief still uses the older version of the query for it's approach 2, where the long form query is used (approach 1 being measurements function)
