### ISSUE TITLE
Introduce semi-transparent WMF for export plot to clipboard

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#540]
*[Migrated from Assembla ticket [542](https://www.assembla.com/spaces/Debrief/tickets/542) - reported by @IanMayo on 2013-12-11 11:26:52]*

The SWTCanvasAdapter implements ExtendedCanvasType - which provides semi-transparent plotting of shapes.

It would be great if WMF could render these semi-transparent shapes, it currently only exports them with a solid fill.

I suspect our WMF libs don't currently support semi-transparency, so this may require some research.

But, this will give a great quality plot in the MS Word reports.

**Comment by IanMayo** [comment]
WMF doesn't support semi-transparent objects:
http://stackoverflow.com/questions/22813312/does-emf-enhanced-metafile-support-opacity
