### ISSUE TITLE
BULK AIS DATA - Simplified tracks, inside parent object

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#552]
_[Migrated from Assembla ticket [554](https://www.assembla.com/spaces/Debrief/tickets/554) - reported by @IanMayo on 2014-01-20 14:48:10]_

An analyst has many 10s of AIS tracks shown.

They are slow in performance, and difficult to manage inside the layer manager.

I believe these problems can be overcome using this method:
1. Introduce new REP annotation type BULK:    The fields for this will be the same as the "normal" Debrief position format, but they will be handled as bulk tracks, and put into a LightTrack object
2. Introduce new LightTrack object. The LightTrack object should enjoy quicker rendering, at reduced memory consumption.  This is just a Plottables that implements WatchableList with these extra fields:
   1.  Name
   2.  Color
   3.  On/Off
   4.  FilterListTo
   5.  Resample data at/
   6.  TrimTrackTo Time Controller period
   7.  Convert to normal track
3. Introduce new BulkTracks object. This will contain the bulk tracks, and will have these fields:
   1.  Name
   2.  On/off
   3.  FilterListTo
   4.  ResampleDataAt
   5.  TrimTrackTo Time Controller period
   6.  Apply rainbow-shades to tracks
4. The bulk AIS/NMEA datasets would also be stored in this format.

Follow on suggestion:
On load, the LightTrack would run a simplify algorithm over its contents, to reduce the data volume as much as possible. We'd then rely on interpolation to show discrete positions.

**Comment by IanMayo** [comment]
this could be of value in the new AIS data support

**Comment by IanMayo** [comment]
Closed. AIS tracks now loaded into lightweight track wrapper objects.
