### ISSUE TITLE
Add Measure Range (Path) tool

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#556]
*[Migrated from Assembla ticket [558](https://www.assembla.com/spaces/Debrief/tickets/558) - reported by @IanMayo on 2014-01-28 15:58:28]*

It's currently possible to measure range/bearing using mouse drag.

Google Earth includes the capability to measure a path - a connected series of points.  If we implement it, it would make sense to closely copy the Google Earth way of working.

Such a path is similar to a polyline. Maybe there's an overlap.

Maybe there should be an improved polyline element, one that has a "What is my range" capability.   Other objects could support such a capability:  "IKnowMyLength".  Right-clicking on one will add the "Display my length" menu option.

But, if the "entity" isn't already in Debrief, we need to let a user enter it.

**Comment by IanMayo** [comment]
This requirement has re-arisen. Drop.
