### ISSUE TITLE
Configurable snail trail lengths

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#558]
_[Migrated from Assembla ticket [560](https://www.assembla.com/spaces/Debrief/tickets/560) - reported by @IanMayo on 2014-03-18 12:13:41]_

Ed uses snail trails to show the dynamic changes in a dense plot.

But, some tracks require much smaller trail lengths than others.  A slow moving track should show a trail for a longer period, and faster tracks would have a much shorter time period.

The solution to this would seem to be an optional element on tracks.  This element would specify the snail length to use for that track.

The snail trail plotting code would then use a track-specific length, if present, else use the scenario-wide setting.

**Comment by IanMayo** [comment]
Have had a fresh request regarding this capability:

    The default trail length in the snail mode is 15 minutes. Analyst is doing a
    piece of work where he would like one target to have a 2 minute snail trail 
    and the rest of the targets a longer snail tail, is it possible?

Have discussed potential solutions with users. Seemed acceptable to introduce an optional *Snail length* property for tracks. By default this will be empty (in which case the default snail length is used).  But, if over-ridden a different snail length is used.

Requires changes to:
* track save/restore
* schema for Debrief tracks
* track properties
* snail trail rendering `SnailDrawSWTFix`
* *maybe* user guidance
