### ISSUE TITLE
Don't merge colors on merge tracks

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#559]
*[Migrated from Assembla ticket [561](https://www.assembla.com/spaces/Debrief/tickets/561) - reported by @IanMayo on 2014-03-19 15:22:42]*

Ian H has a frustration.

He colors track segments to make them easier to manage.  But, on a merge operation Debrief sets them all to the same color.

He'd like them to remain in their original color.

Good suggestion.

Hey, if a user wants the points to be the same color then he can set that color in the layer manager, or right-click on the track and select "Reset Color".

**Comment by IanMayo** [comment]
Close - not reported in a long time.
