### ISSUE TITLE
Try to produce manoeuvre detection algorithm (again)

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#578]
*[Migrated from Assembla ticket [580](https://www.assembla.com/spaces/Debrief/tickets/580) - reported by @IanMayo on 2014-04-28 14:38:31]*

The maths is working really well, producing good solutions with little effort.

But, the analyst retains the chore of deciding the straight legs.

He does this partially through pattern analysis.  The PC "should" be able to do a good job of this, but we failed to find a suitable pattern/algorithm last otime, falling over because of the poor fidelity in bearing (typically 1 decimal point).

Have another go, it would be brilliant if it worked.

Note: we really need either to use some analysts bearing data, or to look at the patterns in the data so that it can be simulated.

#### Ray of hope

Maybe non-traditional/unusual methods may offer a solution.  Modern data science offers Machine Learning. So, how about providing a system with many, many datasets that include target zig information.  The datasets could be produced fairly easy with a simulation tool, though the accuracy/fidelity would have to be degraded to match the realistic data.  Once the system has learnt to spot target zigs (verified by testing against further simulation datasets), it can be tried on real data.

**Comment by IanMayo** [comment]
The ArcTan algorithm proved an effective way of doing this
