### ISSUE TITLE
Problem in GA mutation algorithm

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#599]
_[Migrated from Assembla ticket [601](https://www.assembla.com/spaces/Debrief/tickets/601) - reported by @IanMayo on 2014-05-16 09:54:29]_

We're currently getting an exception, where GA is trying to use track points that go off the planet (>180 degs West).

Running Generate Scenario for the attached scenario throws the error.

None of the location bounds extends as far West as 180 degs.  Investigate how this is occurring.  Debrief is wasting its effort in considering this kind of solution.

**Comment by IanMayo** [comment]
Close. No longer relevant.
