### ISSUE TITLE
Value doesn't appear after switching the axes

### ISSUE THREAD

**Issue by nimeshp27** [debrief/debrief#729]
Steps:
1. Load sample.xml file
2. Select two tracks together
3. RIght click on select "XY" plot
4. Select the attribute as Range and select any Primary track and click on "OK" button
5. XY Plot should appear at the bottom
6. Observe that one value appears on top left
7. Now switch axes
8. Observe the same value in the Plot

Issue: It doesn't appear anywhere in the plot

See the video here:
https://www.dropbox.com/s/djr5z2n40702thg/value%20disappears%20after%20switching%20the%20axes.avi?dl=0

**Comment by IanMayo** [comment]
Fixed as part of windows xy-plotting fix
