### ISSUE TITLE
Expanding/collapsing "Bearing Residuals" section, charts do not load instantly

### ISSUE THREAD

**Issue by nimeshp27** [debrief/debrief#771]
Cheat seat: Single Sided Reconstruction -> Working with target tracks -> Generating a segment of target track.

Issue: Expanding/collapsing "Bearing Residuals" section, charts do not load instantly

See the video here:
https://www.dropbox.com/s/wbeg83cz6mqro2m/Bearing%20Residuals.avi?dl=0

**Comment by IanMayo** [comment]
Fixed with adoption of SWT charts.
