### ISSUE TITLE
Reduce build size to overcome build problem

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#996]
Our Travis build is currently failing, Peco suspects this is because we're running out of disk space.

We have two strategies:
1. [ ] reduce the size of the build
2. [ ] see if we can increase the Travis build allocation. Note, it Travis docs do indicate the space [is limited](http://docs.travis-ci.com/user/ci-environment/#The-Build-Machine)

@pecko  - I'd appreciate you looking into the second one, please (Travis build allocation).

**Comment by pecko** [comment]
I think that we can close this issue.
