### ISSUE TITLE
De-cluttering Natural Earth Labels / Symbols

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#999]
We paint the Natural Earth data in 3 phases:
1. filled polygons
2. lines
3. points & text labels

For the last item we should use a "de-cluttering" algorithm - which allows us to avoid a dense "block" of text labels. Natural Earth contains a **SCALERANK** which shows the importance of each label (with *0* being the most important).

Examples of such an algorithm may be available on the Internet, but I suggest something like this:

* work through list of labels, for each label:
    * determine the on-screen rectangle it will occupy
    * see if this area overlaps with previously stored cached areas. If there is a clash:
        * keep the most important text label

* once all labels are processed, plot labels

**Comment by pecko** [comment]
Do you have some example with such labels?

IMO, the geotools api already supports it, but maybe we will have to use some sld styles.

**Comment by IanMayo** [comment]
Hopefully our GeoTools rendering can handle this. We'll see once we've got some more complex data items displayed.  

I saw the rankings get used in QGis. I'll have to remember which data I used.

**Comment by IanMayo** [comment]
Yes, I've seen GeoTools doing this in our Debrief code.
